### PR TITLE
fixup! ASoC: SOF: sof-audio: Fix broken early bclk feature for SSP

### LINKED ISSUE #4039: [BUG][stable-v2.2] ipc tx error for 0x80010000| GLB_DAI_MSG: CONFIG when testing audio on ADLP_BRYA_SDW
**Describe the bug**
IPC tx error when checking audio. This issue only happens with sof-dev + sof/stable-v2.2 and this is a kernel regression and caused by:
https://github.com/thesofproject/linux/commit/b2ff7a64ce02b35823afc1db49e919b6151477a8
```

commit b2ff7a64ce02b35823afc1db49e919b6151477a8
Author: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
Date:   Sun Nov 13 19:16:53 2022 -0800

    ASoC: SOF: sof-audio: Fix broken early bclk feature for SSP

    With the removal of widget setup during BE hw_params, the DAI config IPC
    is never sent with the SOF_DAI_CONFIG_FLAGS_HW_PARAMS. This means that
    the early bit clock feature required for certain codecs will be broken.

    Fix this by saving the config flags sent during BE DAI hw_params and
    reusing it when the DAI_CONFIG IPC is sent after the DAI widget is set
    up. Also, free the DAI config before the widget is freed.

    Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

 sound/soc/sof/ipc3-topology.c | 28 +++++++++++++++++++++++++++-
 sound/soc/sof/sof-audio.c     | 28 +++++++++++++++++++++++++---
```

**dmesg**
```
[   36.438198] snd_sof:sof_widget_setup: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.4.ALH515.IN setup complete
[   36.438199] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[   36.438438] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   36.438609] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx error for 0x80010000 (msg/reply size: 216/12): -19
[   36.438615] sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to set dai config for SDW2-Capture
[   36.438623] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30020000: GLB_TPLG_MSG: COMP_FREE
[   36.438791] snd_sof:sof_widget_free: sof-audio-pci-intel-tgl 0000:00:1f.3: widget ALH515.IN freed
[   36.438793] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30110000: GLB_TPLG_MSG: PIPE_FREE
[   36.439639] snd_sof:sof_widget_free: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.4.ALH515.IN freed
[   36.439649] sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to restore pipeline after resume -19
[   36.439676] soundwire_intel soundwire_intel.link.2: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.2: -16
[   36.439680]  SDW2-Playback: ASoC: error at __soc_pcm_open on SDW2-Playback: -16
[   36.439683]  Speaker: ASoC: error at dpcm_be_dai_startup on Speaker: -16
[   36.439685]  Speaker: ASoC: error at dpcm_fe_dai_startup on Speaker: -16
[   36.764990] sof-audio-pci-intel-tgl 0000:00:1f.3: Copying cached debugfs data
[   36.765025] sof-audio-pci-intel-tgl 0000:00:1f.3: Copying cached debugfs data
[   36.765246] sof-audio-pci-intel-tgl 0000:00:1f.3: Copying cached debugfs data
[   36.765248] sof-audio-pci-intel-tgl 0000:00:1f.3: Copying cached debugfs data
[   38.033531] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device failed: -22
[   38.033574] sof-audio-pci-intel-tgl 0000:00:1f.3: Filter update failed: -22
[   38.047301] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device failed: -22
[   38.047306] sof-audio-pci-intel-tgl 0000:00:1f.3: Filter update failed: -22

```

**slogger**
```
[       64921.091170] (          17.968750) c0 memory                      src/lib/alloc.c:569  INFO  heap: 0x9e19e000 size 5376 blocks 0 caps 0x45
[       64939.164086] (          18.072916) c0 memory                      src/lib/alloc.c:571  INFO   (In Bytes) used 3904 free 1472
[       65292.705739] (         353.541656) c0 dma-trace                 src/trace/trace.c:141  INFO Suppressed 19 similar messages:  %d Bytes blocks ID:%d base 0x%x
[       65305.257822] (          12.552083) c0 dma-trace                 src/trace/trace.c:141  INFO Suppressed 22 similar messages:    Number of Blocks: total % used %d free %d
[       65318.955738] (          13.697916) c0 ipc                  src/ipc/ipc3/handler.c:1605 INFO ipc: new cmd 0x30010000
[       65360.414069] (          41.458332) c0 component             src/ipc/ipc3/helper.c:306  INFO comp new dai <c2b00d27-ffbc-4150-a51a-245c79c5e54b> type 2 id 4.23
[       65403.018234] (          42.604164) c0 alh-dai      4.515  src/drivers/intel/alh.c:113  INFO alh_probe()
[       65428.174483] (          25.156248) c0 dai                           src/lib/dai.c:166  INFO dai_get type 4 index 515 new sref 1
[       65451.664066] (          23.489582) c0 dma                           src/lib/dma.c:123  INFO dma_get() ID 0 sref = 3 busy channels 0
[       65781.195303] (         329.531250) c0 ipc                  src/ipc/ipc3/handler.c:1605 INFO ipc: new cmd 0x80010000
[       65807.705718] (          26.510416) c0 ipc                  src/ipc/ipc3/handler.c:595  INFO ipc: dai 4.0 -> config
[       65827.080718] (          19.375000) c0 dai                           src/lib/dai.c:166  INFO dai_get type 4 index 0 new sref 0
[       65850.830717] (          23.750000) c0 ipc                  src/ipc/ipc3/handler.c:559  ERROR ipc: dai 4,0 not found
[       66088.434874] (         237.604156) c0 ipc                  src/ipc/ipc3/handler.c:1605 INFO ipc: new cmd 0x30020000
[       66109.059873] (          20.625000) c0 ipc                  src/ipc/ipc3/handler.c:1386 INFO ipc: comp 23 -> free
[       66145.049455] (          35.989582) c0 dma                           src/lib/dma.c:143  INFO dma_put(), dma = 0x9e076cc0, sref = 2
[       66165.414037] (          20.364582) c0 alh-dai      4.515  src/drivers/intel/alh.c:130  INFO alh_remove()
[       66192.861953] (          27.447916) c0 dai                           src/lib/dai.c:190  INFO dai_put type 4 index 515 new sref 0
[       66403.122361] (         210.260406) c0 ipc                  src/ipc/ipc3/handler.c:1605 INFO ipc: new cmd 0x30110000

```
**To Reproduce**
~/sof-test/test-case/check-playback.sh -d 3 -l 1 -r 1 -F

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: sof-dev
    * SOF: tip stable-v2.2
2) Name of the topology file
    * Topology: sof-adl-sdw-max98373-rt5682.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform:ADLP_BRYA_SDW

### PR DESCRIPTION
**Pull request by ranj063**
The DAI_CONFIG IPC sent during the sof_widget_free() does not have the DAI index information. So, save the dai_index in the config during hw_params and reuse it during hw_free.

Fixes https://github.com/thesofproject/linux/issues/4039

### CODE REVIEW

File: sound/soc/sof/ipc3-topology.c [hunk 1]
```diff
@@ -2081,7 +2081,9 @@ static int sof_ipc3_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
 		break;
 	case SOF_DAI_INTEL_ALH:
 		if (data) {
-			config->dai_index = data->dai_index;
+			/* save the dai_index during hw_params and reuse it for hw_free */
+			if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS)
+				config->dai_index = data->dai_index;
```
Comment (plbossart) [inline sound/soc/sof/ipc3-topology.c:2086]: rather unclear to me. We never used the different config stages for ALH, what makes it a requirement now?

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: @plbossart the fact that we never used is what didn't expose the problem. With the new change, we actually send the dai_config ipc properly during hw_params and hw_free. So we need to preserve the dai_index for use during hw_frew

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: sorry, not following @ranj063 

````c
static int sdw_params_stream(struct device *dev,
			     struct sdw_intel_stream_params_data *params_data)
{
	struct snd_soc_dai *d = params_data->dai;
	struct snd_sof_dai_config_data data;
	struct snd_soc_dapm_widget *w;

	w = snd_soc_dai_get_widget(d, params_data->stream);
	data.dai_index = (params_data->link_id << 8) | d->id;
	data.dai_data = params_data->alh_stream_id;

	return hda_ctrl_dai_widget_setup(w, SOF_DAI_CONFIG_FLAGS_NONE, &data);
}

static int sdw_free_stream(struct device *dev,
			   struct sdw_intel_stream_free_data *free_data)
{
	struct snd_soc_dai *d = free_data->dai;
	struct snd_sof_dai_config_data data;
	struct snd_soc_dapm_widget *w;

	w = snd_soc_dai_get_widget(d, free_data->stream);
	data.dai_index = (free_data->link_id << 8) | d->id;

	/* send invalid stream_id */
	data.dai_data = 0xFFFF;

	return hda_ctrl_dai_widget_free(w, SOF_DAI_CONFIG_FLAGS_NONE, &data);
}
````

Where do you see that we will see this SOF_DAI_CONFIG_FLAGS_HW_PARAMS set?

edit: and data->dai_index is set for both hw_params and hw_free, so what is the issue?

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: @plbossart the dai_config ipc in sdw_free_stream() would never get sent because the dai widget would already have been freed during the FE DAI hw_free in sof_widget_free(). And if you look at that function, we only set the channel not the DAI index because we just don't have that info

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: sorry, I am following even less.

a) if we are already sending the dai_config IPC somewhere else than sdw_free_stream(), then why on earth do we still have this function. we would need a larger change.

b) if we are not sending the dai_config IPC, ever, then the flow is broken.

Which is it?

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: It is a). We should just remove sdw_free_stream()

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: ok, then let's do a real cleanup, it's really confusing to have dead code that remains present.

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: actually wait, where would we send the invalid stream id, if it's not done in sdw_free_stream?

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: Sof_widget_free()

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: it's a nightmare to follow....

we call tplg_ops->dai_config from sdw_hw_params, sof_widget_setup, hda_ipc3_post_trigger, sof_widget_free and sdw_hw_free.

For SoundWire/ALH, this seems completely overkill or redundant. It's quite likely that we were sending the same IPC multiple times for no good reason.

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: I've cleaned up the dai config calls during BE DAI hw_free now. The others will have to stay though.

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: I am still in the dark on the sequences.

For HDaudio, we would still have ipc3_post_trigger and sof_widget_free sending the same dai config (same DMA_CHAN_INVALID, same FLAGS_HW_FREE)

For ALH, we still have a dai config IPC in sdw_hw_params and sof_widget_setup.

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: For AlH, the ipc will only be sent during sof_widget_setup. Sdw_hw_params() will only update the stream ID.

The post_trigger ipc is also needed because we perform the  cleanup during the stop trigger for the HDA DAIs. I'm not sure it is really required. I'll need to experiment to see if I can remove it

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: in that case, why do we set the HW_PARAMS flag in sdw_hw_params()? It's a no-op or rather it'll be done again in sof_widget_setup.

I also don't get what happens in ipc3_post_trigger, the use_count is only decreased in sof_widget_free, so there's no IPC, and I am not sure what cleanup you are referring to.

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: @plbossart for the start/stop test that we have where we do the stop without hw_free, I think we need to keep the post_trigger op to clear the channel ID in the DSP.

As for sdw_hw_params(), its not a no-op. We get the alh_stream_id during BE hw_params and send it during FE hw_params

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: > I also don't get what happens in ipc3_post_trigger, the use_count is only decreased in sof_widget_free, so there's no IPC, and I am not sure what cleanup you are referring to.

@plbossart post_trigger() is called during the BE DAI STOP/SUSPEND trigger. We call hda_link_dma_cleanup() during thse triggers, so we have to clear the channel ID in the DSP as well.

Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: I can't follow this sorry. We have 5 stages (hw_params, widget_setup, trigger_stop, widget_free, hw_free) multiplied by two (BE/FE). We don't need this complexity for ALH, and I'll personally forget all the explanations after each long week-end.

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: BTU ALH doesnt have this complexity at all. So i'm not getting your point. For ALH, we have BE hw_params, where we get the stream ID and save it in the config. And send it to the DSP after the DAI widget is setup.

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2086]: maybe what will help make a bit easier to follow is if I moved the dai_config op from being a topology op to being a DAI widget op. But that will take a bit of work. For now, can we please consider mergin this to fix the Brya issue?

**Review by plbossart — DISMISSED** [review]
I'll approve but I have really no idea of what our flows look like, there's just too many stages and confusing parts IMHO.

**Review by RanderWang — DISMISSED** [review]

**Comment by bardliao** [comment]
@plbossart @ranj063 The patch looks good to me. But I have a question. Do we need to set invalid stream id at all? IIRC, we set invalid stream id is to inform firmware to stop the ALH stream. Am I correct? But, it seems we don't need to set invalid stream id to stop the stream now.
And if we need to set invalid stream id, can we do it in ipc_unprepare callback instead of sof_widget_free?
When will we need to send the IPC with invalid stream id?
I asked that because I meet an issue when I played with sdw aggregated speakers. 
We free alh_group_ida in [sof_ipc4_unprepare_copier_module](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/ipc4-topology.c#L1067). But we get group_id from `ipc4_copier->data.gtw_cfg.node_id` which is already set to invalid id at that moment. As a result, we will always free a wrong ida.

File: sound/soc/sof/ipc3-topology.c (hunk 1 above)
Comment (ujfalusi) [reply sound/soc/sof/ipc3-topology.c:2086]: Commit subject: `fixup! ASoC: SOF: sof-audio: Fix broken early bclk feature for SSP`, emphasis on **SSP**
and the patch modifies `case SOF_DAI_INTEL_ALH:` ?

**Review by bardliao — DISMISSED** [review]

File: sound/soc/sof/intel/hda-dai.c [hunk 2]
```diff
@@ -318,25 +318,9 @@ static int hda_dai_trigger(struct snd_pcm_substream *substream, int cmd, struct
...
-
-	data.dai_data = DMA_CHAN_INVALID;
-
-	return hda_dai_config(w, SOF_DAI_CONFIG_FLAGS_HW_FREE, &data);
-}
-
 static const struct snd_soc_dai_ops hda_dai_ops = {
 	.hw_params = hda_dai_hw_params,
-	.hw_free = hda_dai_hw_free,
+	.hw_free = hda_link_dma_hw_free,
```
Comment (ujfalusi) [inline sound/soc/sof/intel/hda-dai.c]: Can we rename the `hda_link_dma_hw_free` to `hda_dai_hw_free` as well?
It looks completely out of place in this struct with the other callbacks are sans `_link_`.

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: done. thanks!

File: sound/soc/sof/ipc3-topology.c (hunk 1 above)
Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2086]: I think the fixup convention is that we use the initial commit title that's being fixed. In this case, we fixed SSP in the initial commit but broke ALH with a side effect. It's still a fixup for the same issue.

**Comment by plbossart** [comment]
> @plbossart @ranj063 The patch looks good to me. But I have a question. Do we need to set invalid stream id at all? IIRC, we set invalid stream id is to inform firmware to stop the ALH stream. Am I correct? But, it seems we don't need to set invalid stream id to stop the stream now. And if we need to set invalid stream id, can we do it in ipc_unprepare callback instead of sof_widget_free? When will we need to send the IPC with invalid stream id? I asked that because I meet an issue when I played with sdw aggregated speakers. We free alh_group_ida in [sof_ipc4_unprepare_copier_module](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/ipc4-topology.c#L1067). But we get group_id from `ipc4_copier->data.gtw_cfg.node_id` which is already set to invalid id at that moment. As a result, we will always free a wrong ida.

@ranj063 can you address @bardliao 's questions?

**Comment by ranj063** [comment]
> We free alh_group_ida in [sof_ipc4_unprepare_copier_module](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/ipc4-topology.c#L1067). But we get group_id from `ipc4_copier->data.gtw_cfg.node_id` which is already set to invalid id at that moment. As a result, we will always free a wrong ida.

@bardliao we cannot free thhe stream ID in unprepare. What you need to do for IPC4 is free the IDA for the aggregated case in dai_config() if the flag is SOF_DAI_CONFIG_FLAGS_HW_FREE

**Comment by ranj063** [comment]
> > We free alh_group_ida in [sof_ipc4_unprepare_copier_module](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/ipc4-topology.c#L1067). But we get group_id from `ipc4_copier->data.gtw_cfg.node_id` which is already set to invalid id at that moment. As a result, we will always free a wrong ida.
> 
> @bardliao we cannot free thhe stream ID in unprepare. What you need to do for IPC4 is free the IDA for the aggregated case in dai_config() if the flag is SOF_DAI_CONFIG_FLAGS_HW_FREE

Or alternatively if you want to keep prepare/unprepare() balanced, only handle the SOF_DAI_CONFIG_FLAGS_HW_PARAMS case for ALH DAIs in sof_ipc4_dai_config()

**Review by bardliao — DISMISSED** [review]

File: sound/soc/sof/ipc4-topology.c [hunk 3]
```diff
@@ -2147,8 +2151,14 @@ static int sof_ipc4_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
 		pipeline->skip_during_fe_trigger = true;
 		fallthrough;
 	case SOF_DAI_INTEL_ALH:
-		copier_data->gtw_cfg.node_id &= ~SOF_IPC4_NODE_INDEX_MASK;
-		copier_data->gtw_cfg.node_id |= SOF_IPC4_NODE_INDEX(data->dai_data);
+		/*
+		 * Do not clear the node ID during hw_free. It is needed to free the group_ida
```
Comment (plbossart) [inline sound/soc/sof/ipc4-topology.c]: is this really during hw_free? Or did you mean widget_free? I don't see how hw_free and widget_unprepare are related?

Comment (ranj063) [reply sound/soc/sof/ipc4-topology.c]: Widget free happens during hw_free or during suspend. Unprepare also happens during hw_free but it's just the for the AlH dais we free the group_ida is freed during unprepare and we should not clear the node ID until then

Comment (ranj063) [reply sound/soc/sof/ipc4-topology.c]: ive changed the comment now.

**Review by bardliao — APPROVED** [review]

**Review by RanderWang — APPROVED** [review]

**Review by plbossart — APPROVED** [review]
