### PR TITLE
ASoC: SOF: ipc4: Ensure DSP is in D0I0 during sof_ipc4_set_get_data()

### LINKED ISSUE #4246: [BUG] MOD_SET_DX times out on MTL platform
**Describe the bug**
This issue happened on MTL when testing suspend/resume related cases. From the demsg, it failed with MOD_SET_DX timeout.
```
[  142.743284] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x44000000|0x3060004c: MOD_LARGE_CONFIG_SET [data size: 76]
[  142.743892] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x64000000|0x3060004c: MOD_LARGE_CONFIG_SET
[  142.743966] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x44000000|0x3060004c: MOD_LARGE_CONFIG_SET [data size: 76]
[  142.744060] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[  143.247354] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x47000000|0x0
[  143.247443] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: preventing DSP entering D3 state to preserve context
[  143.247454] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[  143.247552] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x47000000|0x0|0x0, target: 0x64000000|0x3060004c|0x0, ctl: 0x3
[  143.247634] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[  143.247689] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  143.247744] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[  143.247785] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
[  143.247864] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0x5, ROM error: 0x0
[  143.247932] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x50000005, ROM debug error: 0x0
[  143.247997] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit enabled
[  143.248043] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[  143.248101] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: -110 failed to prepare DSP for device removal
```
Before the reproduction rate is about 50%, but after https://github.com/thesofproject/sof/commit/0664718a5896abe1e50191218cb80abb7171ad2d, this issue can be reproduced on MTL 100% at the first round of suspend/resume.

**To Reproduce**
rtcwake -m mem -s 5 

**Reproduction Rate**
<del>100% after https://github.com/thesofproject/sof/commit/0664718a5896abe1e50191218cb80abb7171ad2d, before the repro rate is about 50%.</del>
[UPDATE]: the reproduction rate has been extremely low since Dec 23 on tip sof/main.

**Expected behavior**

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: tip sof-dev/eebcfac2c69e
    * SOF: main/99a65fc7d72f
2) Name of the platform(s) on which the bug is observed.
    * Platform: MTL

[dmesg.txt](https://github.com/thesofproject/sof/files/10233416/dmesg.txt)

### PR DESCRIPTION
**Pull request by ranj063**
The set_data_data() IPC op bypasses the check for the no_pm flag as done with the regular IPC tx_msg op. Since set_get_data should be performed when the DSP is in D0I0, set the DSP power state before sending the IPC's in sof_ipc4_set_get_data().

Fixes https://github.com/thesofproject/linux/issues/4246

### CODE REVIEW

**Review by ujfalusi — DISMISSED** [review]
@ranj063, good catch.

**Comment by ranj063** [comment]
SOFCI TEST

File: sound/soc/sof/ipc4.c [hunk 1]
```diff
@@ -435,6 +438,11 @@ static int sof_ipc4_set_get_data(struct snd_sof_dev *sdev, void *data,
 
 	tx.extension |= SOF_IPC4_MOD_EXT_MSG_FIRST_BLOCK(1);
 
+	/* ensure the DSP is in D0i0 before sending IPC */
+	ret = snd_sof_dsp_set_power_state(sdev, &target_state);
+	if (ret < 0)
+		return ret;
+
```
Comment (plbossart) [inline sound/soc/sof/ipc4.c:445]: humm, didn't we have something in the past where we wouldn't access the data and wake-up the DSP if it was in D3?

Not sure what would happen if userspace plays with a kcontrol, is this really needed to wake-up the DSP?

Clearly not following this PR.

Comment (plbossart) [inline sound/soc/sof/ipc4.c:445]: also your commit message mentions set_data_data()

Comment (ranj063) [reply sound/soc/sof/ipc4.c:445]: @plbossart there's no waking up here. With deep buffer pipeline active, we could be in d0i3 and if we invoke set_get_data, we have to make sure we're in d0i0 first.

Comment (plbossart) [reply sound/soc/sof/ipc4.c:445]: well, exactly, wasn't it agreed that the IPC would trigger a move back to D0i0, so why would we need to do this again?

Comment (ranj063) [reply sound/soc/sof/ipc4.c:445]: Because this ops sends ipc without going through the check for that which is only done in sof_ipc4_tx_msg() and set_get_data() doesn't use that function. So we need to make sure we do it here as well.

Comment (ranj063) [reply sound/soc/sof/ipc4.c:445]: fixed

Comment (bardliao) [reply sound/soc/sof/ipc4.c:445]: > Because this ops sends ipc without going through the check for that which is only done in sof_ipc4_tx_msg() and set_get_data() doesn't use that function. So we need to make sure we do it here as well.

I was wondering why only sof_ipc4_set_get_data need to be in D0i0 but not all IPC message. This comment answered my question.

**Review by bardliao — APPROVED** [review]

**Comment by ranj063** [comment]
SOFCI TEST

File: sound/soc/sof/ipc4.c (hunk 1 above)
Comment (ujfalusi) [reply sound/soc/sof/ipc4.c:445]: Fwiw, the IPC3 implementation is identical: `sof_ipc3_set_get_data()` uses `ipc3_tx_msg_unlocked()` and the set power state is in `sof_ipc3_tx_msg()`, which is not in that execution path.
There it is good, here it is not?

The set_get_data implementation for ipc4 was 'inspired' by the existing ipc3 one...

**Review by ujfalusi — APPROVED** [review]

File: sound/soc/sof/ipc4.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/ipc4.c:445]: @ujfalusi in IPC3, we do not send the set-get_data() IPC just before suspend. It should be fixed there too but we just dont see the problem

**Comment by ranj063** [comment]
SOFCI TEST

**Review by plbossart — APPROVED** [review]

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
known issues with alsabat failures on TGL/ADL nocodec with IPC4

File: sound/soc/sof/ipc4.c (hunk 1 above)
Comment (marc-hb) [reply sound/soc/sof/ipc4.c:445]: > @ujfalusi in IPC3, we do not send the set-get_data() IPC just before suspend. It should be fixed there too but we just dont see the problem

We had relatively frequent suspend/resume issues all across the board since forever. They just became much more frequent recently.

Granted, some happen even without audio; suspend/resume is always broken by the weakest link in the chain.

@ranj063 will you submit the IPC3 fix?

Comment (ranj063) [reply sound/soc/sof/ipc4.c:445]: @marc-hb no I wont be fixing this for IPC3. It is not a sequence that is used with IPC3 i.e set_get_data() while the DSP is in D0i3. So there would be no way for me to test it.

Comment (marc-hb) [reply sound/soc/sof/ipc4.c:445]: Sorry I misunderstood "It should be fixed there too but we just dont see the problem"
