### PR TITLE
ASoC: SOF: Intel: Split the set_power_op for IPC3 and IPC4

### LINKED ISSUE #4246: [BUG] MOD_SET_DX times out on MTL platform
**Describe the bug**
This issue happened on MTL when testing suspend/resume related cases. From the demsg, it failed with MOD_SET_DX timeout.
```
[  142.743284] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x44000000|0x3060004c: MOD_LARGE_CONFIG_SET [data size: 76]
[  142.743892] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x64000000|0x3060004c: MOD_LARGE_CONFIG_SET
[  142.743966] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x44000000|0x3060004c: MOD_LARGE_CONFIG_SET [data size: 76]
[  142.744060] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x47000000|0x0: MOD_SET_DX [data size: 8]
[  143.247354] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x47000000|0x0
[  143.247443] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: preventing DSP entering D3 state to preserve context
[  143.247454] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[  143.247552] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x47000000|0x0|0x0, target: 0x64000000|0x3060004c|0x0, ctl: 0x3
[  143.247634] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[  143.247689] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  143.247744] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[  143.247785] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
[  143.247864] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0x5, ROM error: 0x0
[  143.247932] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x50000005, ROM debug error: 0x0
[  143.247997] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit enabled
[  143.248043] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[  143.248101] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: -110 failed to prepare DSP for device removal
```
Before the reproduction rate is about 50%, but after https://github.com/thesofproject/sof/commit/0664718a5896abe1e50191218cb80abb7171ad2d, this issue can be reproduced on MTL 100% at the first round of suspend/resume.

**To Reproduce**
rtcwake -m mem -s 5 

**Reproduction Rate**
<del>100% after https://github.com/thesofproject/sof/commit/0664718a5896abe1e50191218cb80abb7171ad2d, before the repro rate is about 50%.</del>
[UPDATE]: the reproduction rate has been extremely low since Dec 23 on tip sof/main.

**Expected behavior**

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: tip sof-dev/eebcfac2c69e
    * SOF: main/99a65fc7d72f
2) Name of the platform(s) on which the bug is observed.
    * Platform: MTL

[dmesg.txt](https://github.com/thesofproject/sof/files/10233416/dmesg.txt)

### PR DESCRIPTION
**Pull request by ranj063**
Suspending to S0iX with IPC3 requires the PM_GATE IPC to be sent again to stop the DMA trace. But with IPC4, this is not needed as the trace is stopped with the LARGE_CONFIG_SET IPC. Also, sending the MOD_D0IX IPC to set the D0I3 state again when the DSP is in D0I3 already results in an imbalance in PM runtime states in the firmware. So split the set_power_state ops for IPC3 and IPC4 to avoid sending the MOD_D0IX IPC when the DSP is already in D0I3 with IPC4.

Fixes https://github.com/thesofproject/linux/issues/4246

### CODE REVIEW

**Review by RanderWang — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

File: sound/soc/sof/intel/hda-dsp.c [hunk 1]
```diff
@@ -574,31 +574,11 @@ static void hda_dsp_state_log(struct snd_sof_dev *sdev)
...
-	/*
-	 * When the DSP is already in D0I3 and the target state is D0I3,
-	 * it could be the case that the DSP is in D0I3 during S0
-	 * and the system is suspending to S0Ix. Therefore,
-	 * hda_dsp_set_D0_state() must be called to disable trace DMA
-	 * by sending the PM_GATE IPC to the FW.
-	 */
-	if (target_state->substate == SOF_HDA_DSP_PM_D0I3 &&
-	    sdev->system_suspend_target == SOF_SUSPEND_S0IX)
-		goto set_state;
```
Comment (ujfalusi) [inline sound/soc/sof/intel/hda-dsp.c:591]: @ranj063, I'm really not sure what this is fixing, what is the sequence, I have spent few hours to figure out how it is possible that we set the DSP to D0I3 and then we again set it to D0I3?
It is not with the DeepBuffer + suspend since with that we will stop pipeplines, etc. It is not a suspend while inactive either as in that case the DSP is already off (runtime suspended).

This patch does not make any difference in behavior on TGL with IPC4 as far as I can tell.

Comment (ranj063) [reply sound/soc/sof/intel/hda-dsp.c:591]: @ujfalusi if the system suspends to S0ix while a deep buffer pcm is active, it will not be suspended. So the DSP will continue to be D0i3 and then hda_dsp_suspend() will try to set the DSP to d0i3 again.

Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dsp.c:591]: @ranj063, like `aplay -iv -Dplughw:0,31 -fdat /dev/zero` ?
If I do that then the audio stopped prior and the DSP is in D0I0 (tested on TGL), I need WoV or something like that to reproduce or test this?

File: sound/soc/sof/intel/hda-dsp.c [hunk 2]
```diff
@@ -574,31 +574,11 @@ static void hda_dsp_state_log(struct snd_sof_dev *sdev)
...
 
-	/*
-	 * When the DSP is already in D0I3 and the target state is D0I3,
-	 * it could be the case that the DSP is in D0I3 during S0
-	 * and the system is suspending to S0Ix. Therefore,
-	 * hda_dsp_set_D0_state() must be called to disable trace DMA
-	 * by sending the PM_GATE IPC to the FW.
-	 */
-	if (target_state->substate == SOF_HDA_DSP_PM_D0I3 &&
-	    sdev->system_suspend_target == SOF_SUSPEND_S0IX)
```
Comment (ujfalusi) [inline sound/soc/sof/intel/hda-dsp.c:590]: Can we get away without new function and just do:
```c
if (sdev->pdata->ipc_type == SOF_IPC &&
    target_state->substate == SOF_HDA_DSP_PM_D0I3 &&
    sdev->system_suspend_target == SOF_SUSPEND_S0IX)
```

Comment (ranj063) [reply sound/soc/sof/intel/hda-dsp.c:590]: That was my first thought too @ujfalusi . But I avoid it consciously considering that we dont want the IPC version check scattered around the code and keep it isolated to ops_init() to make it easier to follow

**Review by ujfalusi — APPROVED** [review]

**Comment by fredoh9** [comment]
I was able to run overnight test with this pr, suspend/resume tests were all passed.

**Review by plbossart — APPROVED** [review]
