### PR TITLE
[TEST] soundwire: bus: clear bus clash interrupt after attached

### LINKED ISSUE #2578: [SDW] Bus clash detected
Bus clash detected error can be seen on many SoundWire devices on check-suspend-resume-with-playback-25.sh and check-suspend-resume-with-capture-25.sh test  (SOF v1.6.1 release test report ID 828)

Ideally, HW will be recovered from bus clash. But it could also be a sign.  So create a issue to track it.

Recipe:
Kernel: topic/sof-dev 38e180a4
SOF : master 90955de93e8f
 
Note that ``Bus clash detected`` doesn't contain any error key words, so CI didn't fail with the ``Bus clash detected`` log before.
It means that the issue could already exist for a while. 

@RanderWang @plbossart FYI

### PR DESCRIPTION
**Pull request by bardliao**
We may get bus clash during the attach process, and the SDW_SCP_INT1_
BUS_CLASH bit will be set once we set the corresponding bit on the
SDW_SCP_INTMASK1 register. But it is harmless after codec is attached.
Clear it right after seting SDW_SCP_INTMASK1 register can reduce the
noise of harmless error.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

Fixes #2578

### CODE REVIEW

**Comment by bardliao** [comment]
CI test 849 shows positive result.

**Review by RanderWang — DISMISSED** [review]
LGTM

**Review by RanderWang — DISMISSED** [review]

File: drivers/soundwire/bus.c [hunk 1]
```diff
@@ -1280,6 +1280,12 @@ static int sdw_initialize_slave(struct sdw_slave *slave)
 			"SDW_SCP_INTMASK1 write failed:%d\n", ret);
 		return ret;
 	}
+	/* Clear bus clash interrupt */
+	ret = sdw_update_no_pm(slave, SDW_SCP_INT1,
+			       SDW_SCP_INT1_BUS_CLASH, SDW_SCP_INT1_BUS_CLASH);
+	if (ret < 0)
+		dev_err(&slave->dev,
+			"Clear SDW_SCP_INT1_BUS_CLASH failed:%d\n", ret);
```
Comment (plbossart) [inline drivers/soundwire/bus.c]: How about doing the opposite, first clear the status and then enable the interrupt?

That would remove any memory of the initial bus clash, but allow for programming errors or persistent electrical errors to be detected.

I also think this should be an optional bus behavior, e.g. for Intel devices this behavior would be the default but we don't force all implementations to behave the same.

The commit message is also questionable, a bus clash is not a harmless error!

**Review by plbossart — COMMENTED** [review]
Not sure about this @bardliao, see comments below.

Also not sure if this improves anything?

File: drivers/soundwire/bus.c (hunk 1 above)
Comment (bardliao) [reply drivers/soundwire/bus.c]: > How about doing the opposite, first clear the status and then enable the interrupt?
> 
> That would remove any memory of the initial bus clash, but allow for programming errors or persistent electrical errors to be detected.

I tested it, but clearing before enabling doesn't help. I can still see bus clash on my side. On the other hand, clearing right after enabling fixes the clash issue on my side.

> 
> I also think this should be an optional bus behavior, e.g. for Intel devices this behavior would be the default but we don't force all implementations to behave the same.
> 
> The commit message is also questionable, a bus clash is not a harmless error!

Agree.
I will make it optional and revise the commit message.

File: drivers/soundwire/bus.c [hunk 2]
```diff
@@ -1257,13 +1257,21 @@ static int sdw_slave_set_frequency(struct sdw_slave *slave)
...
 
 	ret = sdw_slave_set_frequency(slave);
 	if (ret < 0)
 		return ret;
 
+	/* Clear bus clash interrupt before enabling interrupt mask */
+	status = sdw_read_no_pm(slave, SDW_SCP_INT1);
+	if (status & SDW_SCP_INT1_BUS_CLASH) {
+		dev_warn(&slave->dev, "Bus clash detected before enabling\n");
+		sdw_write_no_pm(slave, SDW_SCP_INT1, SDW_SCP_INT1_BUS_CLASH);
```
Comment (RanderWang) [inline drivers/soundwire/bus.c]: sdw_update_no_pm ?

Comment (RanderWang) [reply drivers/soundwire/bus.c]: > sdw_update_no_pm ?

I got it . update can't work for it will compare clash bit. But how about other bits in SCP_INT1?

File: drivers/soundwire/bus.c (hunk 1 above)
Comment (bardliao) [reply drivers/soundwire/bus.c]: > > How about doing the opposite, first clear the status and then enable the interrupt?
> > That would remove any memory of the initial bus clash, but allow for programming errors or persistent electrical errors to be detected.
> 
> I tested it, but clearing before enabling doesn't help. I can still see bus clash on my side. On the other hand, clearing right after enabling fixes the clash issue on my side.
> 

Sorry, I tested it with a wrong way. I tested it with ``sdw_write_no_pm``. i.e. without reading operation. That's why ``bus clash`` wasn't cleared. The test result is good if I tested it with the updated version.

Comment (RanderWang) [reply drivers/soundwire/bus.c]: clear register is not the key step, read register is. It is very trick. @bardliao do you plan to disclose this idea ?

File: drivers/soundwire/bus.c (hunk 2 above)
Comment (bardliao) [reply drivers/soundwire/bus.c]: > > sdw_update_no_pm ?
> 
> I got it . update can't work for it will compare clash bit. But how about other bits in SCP_INT1?

We only want to clear the bus clash bit, so set 0 to all other bits.

File: drivers/soundwire/bus.c (hunk 1 above)
Comment (bardliao) [reply drivers/soundwire/bus.c]: > clear register is not the key step, read register is. It is very trick. @bardliao do you plan to disclose this idea ?

mipi_SoundWire_specification_v1-2 session 11.1.2 "Interrupt Model" says successful read from DPN_IntStat register is a necessary process of clearing an interrupt.

File: drivers/soundwire/intel.c [hunk 3]
```diff
@@ -1286,6 +1286,8 @@ static int sdw_master_read_intel_prop(struct sdw_bus *bus)
 	if (quirk_mask & SDW_INTEL_QUIRK_MASK_BUS_DISABLE)
 		prop->hw_disabled = true;
 
+	prop->quirks = SDW_SLAVE_QUIRKS_CLEAR_INITIAL_CLASH;
```
Comment (plbossart) [inline drivers/soundwire/intel.c]: that should be SDW_MASTER_...

File: include/linux/soundwire/sdw.h [hunk 4]
```diff
@@ -405,6 +406,7 @@ struct sdw_slave_prop {
  * command
  * @mclk_freq: clock reference passed to SoundWire Master, in Hz.
  * @hw_disabled: if true, the Master is not functional, typically due to pin-mux
+ * @quirks: bitmask identifying deltas from the MIPI specification
```
Comment (plbossart) [inline include/linux/soundwire/sdw.h]: it's more 'bitmask identifying optional behavior beyond the scope of the MIPI specification'

File: include/linux/soundwire/sdw.h [hunk 5]
```diff
@@ -387,6 +387,7 @@ struct sdw_slave_prop {
 };
 
 #define SDW_SLAVE_QUIRKS_INVALID_INITIAL_PARITY	BIT(0)
+#define SDW_SLAVE_QUIRKS_CLEAR_INITIAL_CLASH	BIT(1)
```
Comment (plbossart) [inline include/linux/soundwire/sdw.h]: it's s new set for SDW_MASTER_QUIRKS_CLEAR_INITIAL_CLASH

File: drivers/soundwire/bus.c [hunk 6]
```diff
@@ -1257,13 +1257,23 @@ static int sdw_slave_set_frequency(struct sdw_slave *slave)
 static int sdw_initialize_slave(struct sdw_slave *slave)
 {
 	struct sdw_slave_prop *prop = &slave->prop;
+	int status;
```
Comment (plbossart) [inline drivers/soundwire/bus.c:1260]: Commit message:

The SoundWire specification allows a Slave device to report a bus clash with the in-band interrupt mechanism when it detects a conflict while driving a bitSlot it owns. This can be a symptom of an electrical conflict or a programming error, and it's vital to detect reliably.

Unfortunately, on some platforms, bus clashes are randomly reported by Slave devices after a bus reset, with an interrupt status set even before the bus clash interrupt is enabled. These initial spurious interrupts are not relevant and should optionally be filtered out, while leaving the interrupt mechanism enabled to detect 'true' issues.

This patch suggests the addition of a Master level quirk to discard such interrupts. The quirk should in theory have been added at the Slave level, but since the problem was detected with different generations of Slave devices it's hard to point to a specific IP. The problem might also be board-dependent and hence dealing with a Master quirk is simpler.

**Review by plbossart — CHANGES_REQUESTED** [review]
that's what I had in mind @bardliao, but it's a master quirk, not a slave one. see comments below.

**Comment by xiulipan** [comment]
SOFCI TEST

**Review by RanderWang — APPROVED** [review]

**Review by plbossart — APPROVED** [review]
LGTM, thanks @bardliao
