### PR TITLE
ASoC: SOF: fix DSP oops definitions in FW ABI

### LINKED ISSUE #871: [regression][APL] DSP panic dump to kernel log is not correct
While working on the host side FW watchdog patches, I noticed the DSP panic dump printed to Linux kernel log (dmesg) is not sensible. 

Platform: APL / UP2
Linux: latest sofdev (f7e9d4a170ff0942bfab7d48f476dba5f8387c71)
FW: latest tip (81887c9f3add154a11df554bc67d6b09e6050cca

DSP panic dump looks like this now:
```
Apr 25 19:37:42 ubilinux4 kernel: [   44.558242] sof-audio-pci 0000:00:0e.0: error : DSP panic!
Apr 25 19:37:42 ubilinux4 kernel: [   44.558607] sof-audio-pci 0000:00:0e.0: panic: dsp_oops_offset 788480 offset 788480
Apr 25 19:37:42 ubilinux4 kernel: [   44.558616] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
Apr 25 19:37:42 ubilinux4 kernel: [   44.559163] sof-audio-pci 0000:00:0e.0: error: can't enter idle
Apr 25 19:37:42 ubilinux4 kernel: [   44.559564] sof-audio-pci 0000:00:0e.0: error: trace point 00004000
Apr 25 19:37:42 ubilinux4 kernel: [   44.559991] sof-audio-pci 0000:00:0e.0: error: panic at :0
Apr 25 19:37:42 ubilinux4 kernel: [   44.560347] sof-audio-pci 0000:00:0e.0: error: DSP Firmware Oops
Apr 25 19:37:42 ubilinux4 kernel: [   44.560750] sof-audio-pci 0000:00:0e.0: error: Exception Cause: IllegalInstructionCause, Illegal instruction
Apr 25 19:37:42 ubilinux4 kernel: [   44.561372] sof-audio-pci 0000:00:0e.0: EXCCAUSE 0x00000000 EXCVADDR 0x00000000 PS       0x00000000 SAR     0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.562048] sof-audio-pci 0000:00:0e.0: EPC1     0x00000000 EPC2     0x00000000 EPC3     0x00000000 EPC4    0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.562724] sof-audio-pci 0000:00:0e.0: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.563412] sof-audio-pci 0000:00:0e.0: EPS2     0x00000000 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.564093] sof-audio-pci 0000:00:0e.0: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.564775] sof-audio-pci 0000:00:0e.0: stack dump from 0x00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.565178] sof-audio-pci 0000:00:0e.0: 0x00000000: 00000000 00000000 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.565695] sof-audio-pci 0000:00:0e.0: 0x00000004: 00000000 00000000 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.566207] sof-audio-pci 0000:00:0e.0: 0x00000008: efd96700 76bf3185 f7143028 ffff8abd
Apr 25 19:37:42 ubilinux4 kernel: [   44.566723] sof-audio-pci 0000:00:0e.0: 0x0000000c: f852b600 ffff8abd f6a77600 ffff8abd
Apr 25 19:37:42 ubilinux4 kernel: [   44.567256] sof-audio-pci 0000:00:0e.0: 0x00000010: f6a77600 ffff8abd aeab5452 ffffffff
Apr 25 19:37:42 ubilinux4 kernel: [   44.567775] sof-audio-pci 0000:00:0e.0: 0x00000014: 408cfbf0 ffffac14 f6c40d00 ffff8abd
Apr 25 19:37:42 ubilinux4 kernel: [   44.568300] sof-audio-pci 0000:00:0e.0: 0x00000018: f75b2f40 ffff8abd 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.568814] sof-audio-pci 0000:00:0e.0: 0x0000001c: 00000000 00000000 00000000 00000000
Apr 25 19:37:42 ubilinux4 kernel: [   44.569319] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
Apr 25 19:37:42 ubilinux4 kernel: [   44.569910] sof-audio-pci 0000:00:0e.0: error: trace IO error
```

The register values and stack pointer look completely wrong.

When I revert this FW patch, the register dump starts to look sane again (not yet sure about the stack part):
25cd7795 debugability: extend core dumps to provide AR registers

### PR DESCRIPTION
**Pull request by kv2019i**
Fixes https://github.com/thesofproject/sof/issues/1374 and needs to be merged at the same time with thesofproject/sof#1420 

Targetted for ABI 6 (3.6.0)

The definitions for DSP oops structures were not aligned
correctly to current FW ABI version 3.6.0, leading to
invalid data being printed out to debug logs. Fix the structs
and update related platform code accordingly.

Also fixes #871

### CODE REVIEW

File: sound/soc/sof/intel/byt.c [hunk 1]
```diff
@@ -265,17 +265,18 @@ static void byt_get_registers(struct snd_sof_dev *sdev,
 			      struct sof_ipc_panic_info *panic_info,
 			      u32 *stack, size_t stack_words)
 {
+	u32 offset = sdev->dsp_oops_offset;
+
 	/* first read regsisters */
-	sof_mailbox_read(sdev, sdev->dsp_oops_offset, xoops, sizeof(*xoops));
+	sof_mailbox_read(sdev, offset, xoops, sizeof(*xoops));
```
Comment (plbossart) [inline sound/soc/sof/intel/byt.c:271]: this doesn't look right, you can't use sizeof on a structure with a variable-length array. Was is xoops->arch_hdr.totalsize as for bdw?

File: sound/soc/sof/intel/hda.c [hunk 2]
```diff
@@ -108,17 +108,20 @@ static void hda_dsp_get_registers(struct snd_sof_dev *sdev,
 				  struct sof_ipc_panic_info *panic_info,
 				  u32 *stack, size_t stack_words)
 {
+	u32 offset = sdev->dsp_oops_offset;
+
 	/* first read registers */
-	sof_block_read(sdev, sdev->mmio_bar, sdev->dsp_oops_offset, xoops,
+	sof_block_read(sdev, sdev->mmio_bar, offset, xoops,
```
Comment (plbossart) [inline sound/soc/sof/intel/hda.c]: same here this can't be right, the sizeof below is likely wrong?

File: sound/soc/sof/intel/byt.c (hunk 1 above)
Comment (jajanusz) [reply sound/soc/sof/intel/byt.c:271]: @kv2019i in C `sizeof(struct with vararray)` is basiacally sizeof of struct with vararray of size 0. Real size of oops will be oops size + (before apl 32, later 64) * 4, probably there will be more different things in the future, that's why we have `totalsize` field in the oops header, it's the real size of whole struct (including headers and vararray).

Comment (kv2019i) [reply sound/soc/sof/intel/byt.c:271]: @plbossart  D'oh, copy'n'paste error. The one in bdw is actually wrong. We can't use arch_hdr.totalsize as this field is not yet filled at this point. We don't support reading out the AR registers in current implementation. Do you think I should add that here as well...?

File: sound/soc/sof/intel/hda.c (hunk 2 above)
Comment (kv2019i) [reply sound/soc/sof/intel/hda.c]: See above.

File: sound/soc/sof/intel/byt.c (hunk 1 above)
Comment (kv2019i) [reply sound/soc/sof/intel/byt.c:271]: @plbossart sizeof will ignore "ar[]", so using sizeof() is ok here. 

To really dump the AR variables, that is a more complex change as then we'd need to change how the oops area is allocated (now users of this code allocate with sizeof so there's no space for AR register list).

We haven't support AR register dumping before, so I'd rather do this separately if needed.

Comment (plbossart) [reply sound/soc/sof/intel/byt.c:271]: ok, then you should add a comment that this is intentional.

Comment (kv2019i) [reply sound/soc/sof/intel/byt.c:271]: @plbossart Ack, now uploaded a new patch that has an explicit comment (plus alignment to Janus'es newer patch).

File: sound/soc/sof/xtensa/core.c [hunk 3]
```diff
@@ -110,7 +110,7 @@ static void xtensa_stack(struct snd_sof_dev *sdev, void *oops, u32 *stack,
 			 u32 stack_words)
 {
 	struct sof_ipc_dsp_oops_xtensa *xoops = oops;
-	u32 stack_ptr = xoops->stack;
+	u32 stack_ptr = xoops->plat_hdr.stackptr;
```
Comment (jajanusz) [inline sound/soc/sof/xtensa/core.c:113]: Does it work? It looks like `stackptr` is in dsp address space (stack top position in the moment of panic). Stack values copied to the memory window are located at `stackoffset`. Sorry for naming, idk why they are named so poorly (and why these names are alllowercaselikeinluaapi?).

Comment (plbossart) [reply sound/soc/sof/xtensa/core.c:113]: @kv2019i let me know if an update is needed to address @jajanusz ' question, will wait until tomorrow before merging

Comment (kv2019i) [reply sound/soc/sof/xtensa/core.c:113]: @jajanusz @plbossart This is intentional. This value is only used to pretty print the results. Considering all the register contents is reflecting values from DSP address space, it would seem more useful to use DSP addresses in the stack print out. Address where the stack is copied in kernel space does not seem very useful information. 

So I think this is good. In any case for deeper debug, you will want to look at full "exception" file and parse it with core-dumper. Chime in @lgirdwood and @xiulipan but I think this is good to go. We can improve the stack dump later.

Comment (jajanusz) [reply sound/soc/sof/xtensa/core.c:113]: @kv2019i Thanks. Then it's ok.

**Comment by jajanusz** [comment]
@kv2019i @plbossart Be careful with fix/resolve keywords in PR and commits description because you closed fw issue too early. More info here: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by kv2019i** [comment]
@jajanusz wrote:
> @kv2019i @plbossart Be careful with fix/resolve keywords in PR and commits description because you 

Ack, my bad. I put the fixes in there on purpose, but did not realize it was filed to fw.

**Comment by plbossart** [comment]
I didn't know either that you could close an issue on a separate repo. That doesn't sound like a good idea really...
