### PR TITLE
ASoC: SOF: Intel: hda: Initialize HDA controller after i915 init

### LINKED ISSUE #1027: [Bug][APL][DPMST] No soundcards found while power on after plugout hdmi and headphone on UP2-PCM512X platform.
***Summary:***
No soundcards found while power on after plugout hdmi and headphone on UP2-PCM512X platform.
However,can not reproduce it when plugin one hdmi device.

***To reproduce***
aplay -l

***Actual result***
```
aplay: device_list:270: no soundcards found...
```

***Test recipe***
sof master: 347ee08c
kernel sof-dev: 24d854a5
tplg: sof-apl-pcm512x.tplg

***dmesg***
```
[    4.603633] sof-audio-pci 0000:00:0e.0: PCI DSP detected
[    4.603898] sof-audio-pci 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    4.603997] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0xc00
[    4.603998] sof-audio-pci 0000:00:0e.0: found ML capability at 0xc00
[    4.604001] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x800
[    4.604003] sof-audio-pci 0000:00:0e.0: found DSP capability at 0x800
[    4.604005] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x500
[    4.604007] sof-audio-pci 0000:00:0e.0: found GTS capability at 0x500
[    4.604009] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x1f00
[    4.604011] sof-audio-pci 0000:00:0e.0: found DRSM capability at 0x1f00
[    4.604013] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x700
[    4.604014] sof-audio-pci 0000:00:0e.0: found SPIB capability at 0x700
[    4.604026] sof-audio-pci 0000:00:0e.0: DMA mask is 64 bit
[    4.604030] sof-audio-pci 0000:00:0e.0: hda global caps = 0x1006701
[    4.604032] sof-audio-pci 0000:00:0e.0: detected 6 playback and 7 capture streams
[    4.604118] sof-audio-pci 0000:00:0e.0: use msi interrupt mode
[    4.604120] sof-audio-pci 0000:00:0e.0: using HDA IRQ 134
[    4.605008] sof-audio-pci 0000:00:0e.0: using IPC IRQ 134
[    4.605072] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000044
[    4.605074] sof-audio-pci 0000:00:0e.0: PP capability, will probe DSP later.
[    4.605077] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000040 at  00000048
[    4.605081] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000000 at  00000048
[    4.611020] sof-audio-pci 0000:00:0e.0: codec_mask = 0x0
[    4.611034] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000048
[    4.611037] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000040 at  00000048
[    5.650725] Console: switching to colour frame buffer device 240x75
[    5.650892] sof-audio-pci 0000:00:0e.0: bound 0000:00:02.0 (ops vgt_balloon_space [i915])
[    5.650903] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power on
[    5.655848] sof-audio-pci 0000:00:0e.0: no hda codecs found!
[    5.655855] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power off
[    5.655996] sof-audio-pci 0000:00:0e.0: loading firmware
[    5.792840] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000002 at  00000048
[    5.792849] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000000 at  00000048
[    5.792856] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000044
[    5.792862] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000004 at  00000044
[    5.792865] sof-audio-pci 0000:00:0e.0: booting DSP firmware
[    5.792944] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[    5.792962] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[    5.792968] sof-audio-pci 0000:00:0e.0: period_bytes:0x0
[    5.792972] sof-audio-pci 0000:00:0e.0: periods:1
[    5.793335] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x3030303 successful
[    5.793351] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x3030302 successful
[    5.793357] sof-audio-pci 0000:00:0e.0: unstall/run core: core_mask = 1
[    5.793363] sof-audio-pci 0000:00:0e.0: DSP core(s) enabled? 1 : core_mask 1
[    5.793927] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000000 successful
[    5.793935] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x1010202 successful
[    5.810821] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x5000001 successful
[    5.826035] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x5 successful
[    5.826045] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x140000 successful
[    5.826049] sof-audio-pci 0000:00:0e.0: Firmware download successful, booting...
[    5.829452] sof-audio-pci 0000:00:0e.0: ipc rx: 0x70000000: FW_READY
[    5.829459] sof-audio-pci 0000:00:0e.0: ipc: DSP is ready 0x70000000 offset 0x81000
[    5.829480] sof-audio-pci 0000:00:0e.0: Firmware info: version 1:1:0-347ee
[    5.829484] sof-audio-pci 0000:00:0e.0: Firmware: ABI 3:7:0 Kernel ABI 3:7:0
[    5.829489] sof-audio-pci 0000:00:0e.0: Firmware debug build 1 on Jun 11 2019-21:23:01 - options:
                GDB: disabled
                lock debug: disabled
                lock vdebug: disabled
[    5.829534] sof-audio-pci 0000:00:0e.0: found ext header type 1 size 0xb8
[    5.829605] sof-audio-pci 0000:00:0e.0:  mailbox upstream 0x81000 - size 0x1000
[    5.829607] sof-audio-pci 0000:00:0e.0:  mailbox downstream 0xa0000 - size 0x2000
[    5.829609] sof-audio-pci 0000:00:0e.0:  stream region 0xc1000 - size 0x1000
[    5.829615] sof-audio-pci 0000:00:0e.0: ipc rx done: 0x70000000: FW_READY
[    5.829713] sof-audio-pci 0000:00:0e.0: firmware boot complete
[    5.829725] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000048
[    5.829729] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000002 at  00000048
[    5.829734] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000004 at  00000044
[    5.829738] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000000 at  00000044
[    5.829781] sof-audio-pci 0000:00:0e.0: generating page table for 00000000ef43f746 size 0x10000 pages 16
[    5.829784] sof-audio-pci 0000:00:0e.0: dma_trace_pages: 16
[    5.829816] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[    5.829831] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x40000 successful
[    5.829835] sof-audio-pci 0000:00:0e.0: period_bytes:0x0
[    5.829837] sof-audio-pci 0000:00:0e.0: periods:1
[    5.829844] sof-audio-pci 0000:00:0e.0: stream_tag: 1
[    5.829851] sof-audio-pci 0000:00:0e.0: ipc tx: 0x90030000: GLB_TRACE_MSG
[    5.830501] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x90030000: GLB_TRACE_MSG
[    5.831045] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x2014001e successful
[    5.831390] sof-audio-pci 0000:00:0e.0: created machine bxt-pcm512x
[    5.831393] sof-audio-pci 0000:00:0e.0: Completing SOF PCI probe
[    5.837930] bxt-pcm512x bxt-pcm512x: info: override FE DAI link SSP5-Codec
[    5.837933] bxt-pcm512x bxt-pcm512x: info: override FE DAI link iDisp1
[    5.837934] bxt-pcm512x bxt-pcm512x: info: override FE DAI link iDisp2
[    5.837936] bxt-pcm512x bxt-pcm512x: info: override FE DAI link iDisp3
[    5.837945] bxt-pcm512x bxt-pcm512x: ASoC: CODEC DAI intel-hdmi-hifi1 not registered
[    6.372503] random: crng init done
[    6.372508] random: 7 urandom warning(s) missed due to ratelimiting
[    6.414751] i915 0000:00:02.0: fb0: i915drmfb frame buffer device
[    6.831180] sof-audio-pci 0000:00:0e.0: ipc rx: 0x90020000: GLB_TRACE_MSG
[    6.831191] sof-audio-pci 0000:00:0e.0: ipc rx done: 0x90020000: GLB_TRACE_MSG
[    9.308305] systemd-journald[253]: Received request to flush runtime journal from PID 1
[   11.597075] Generic Realtek PHY r8169-200:00: attached PHY driver [Generic Realtek PHY] (mii_bus:phy_addr=r8169-200:00, irq=IGNORE)
[   11.697164] r8169 0000:02:00.0 enp2s0: Link is Down
[   11.705892] Generic Realtek PHY r8169-300:00: attached PHY driver [Generic Realtek PHY] (mii_bus:phy_addr=r8169-300:00, irq=IGNORE)
[   11.805236] r8169 0000:03:00.0 enp3s0: Link is Down
[   13.479265] r8169 0000:03:00.0 enp3s0: Link is Up - 100Mbps/Full - flow control off
[   13.479280] IPv6: ADDRCONF(NETDEV_CHANGE): enp3s0: link becomes ready
```

***lsmod***
```
Module                  Size  Used by
snd_soc_sst_bxt_pcm512x    16384  1
snd_soc_hdac_hdmi      32768  1 snd_soc_sst_bxt_pcm512x
snd_soc_dmic           16384  0
sof_pci_dev            20480  0
snd_sof_intel_hda_common    65536  1 sof_pci_dev
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
snd_sof_intel_byt      28672  1 sof_pci_dev
snd_soc_acpi_intel_match    28672  2 snd_sof_intel_hda_common,sof_pci_dev
snd_sof_intel_ipc      20480  1 snd_sof_intel_byt
snd_sof               102400  4 snd_sof_intel_hda_common,snd_sof_intel_byt,snd_sof_intel_ipc,sof_pci_dev
snd_sof_xtensa_dsp     16384  1 sof_pci_dev
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,sof_pci_dev
snd_hda_ext_core       24576  3 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_sof_intel_hda
snd_soc_pcm512x_i2c    16384  0
snd_soc_wm8804_i2c     16384  0
snd_soc_wm8804         20480  1 snd_soc_wm8804_i2c
snd_soc_pcm512x        36864  1 snd_soc_pcm512x_i2c
snd_hda_core           81920  4 snd_hda_ext_core,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_sof_intel_hda
snd_soc_core          204800  7 snd_soc_pcm512x,snd_soc_sst_bxt_pcm512x,snd_soc_wm8804,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_dmic
snd_pcm               126976  8 snd_soc_pcm512x,snd_soc_wm8804,snd_hda_ext_core,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_core,snd_hda_core
x86_pkg_temp_thermal    20480  0
snd_seq                81920  0
snd_seq_device         16384  1 snd_seq
snd_timer              36864  2 snd_seq,snd_pcm
snd                    73728  6 snd_seq,snd_soc_pcm512x,snd_seq_device,snd_timer,snd_soc_core,snd_pcm
mei_me                 40960  0
mei                   102400  1 mei_me
soundcore              16384  1 snd
intel_lpss_pci         20480  0
intel_lpss             16384  1 intel_lpss_pci
mfd_core               16384  1 intel_lpss
efivarfs               16384  1
mmc_block              45056  3
i915                 1765376  12
sdhci_pci              45056  0
cqhci                  32768  1 sdhci_pci
sdhci                  49152  1 sdhci_pci
i2c_algo_bit           16384  1 i915
drm_kms_helper        172032  1 i915
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
xhci_pci               20480  0
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
xhci_hcd              245760  1 xhci_pci
drm                   385024  13 drm_kms_helper,i915
```

***log files***
[lsmod.log](https://github.com/thesofproject/linux/files/3279821/lsmod.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3279822/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3279823/logger.log)

### PR DESCRIPTION
**Pull request by ranj063**
On some platforms, sound card registration fails when a HDMI
monitor is not connected. This is caused by a recent commit
that switched the order in which the HDA controller and the
i915 are initialized. Initializing the i915 before initializing
the HDA controller fixes the problem.

Fixes #1027 #1074

### CODE REVIEW

**Comment by zhuyingjiang** [comment]
Good catch!
But more needs to be added then:

```
	ret = hda_dsp_ctrl_init_chip(sdev, true);
	if (ret < 0) {
		dev_err(bus->dev, "error: init chip failed with ret: %d\n",
			ret);
+#if IS_ENABLED(CONFIG_SND_SOC_SOF_HDA)
+              hda_codec_i915_exit(sdev);
+#endif
		return ret;
	}
```

hda_codec_i915_put is need from hda_codec_i915_exit.

**Comment by RanderWang** [comment]
This patch is consistent with legacy hda driver. Good Finding!

File: sound/soc/sof/intel/hda.c [hunk 1]
```diff
@@ -346,7 +339,17 @@ static int hda_init_caps(struct snd_sof_dev *sdev)
...
 	}
+#endif
+
+	/* Init HDA controller after i915 init */
+	ret = hda_dsp_ctrl_init_chip(sdev, true);
+	if (ret < 0) {
+		dev_err(bus->dev, "error: init chip failed with ret: %d\n",
+			ret);
+		return ret;
+	}
```
Comment (libinyang) [inline sound/soc/sof/intel/hda.c:357]: @ranj063 Good catch. 

Just a tiny comments:
My understanding is "snd_hdac_ext_bus_get_ml_capabilities(bus);" should be called after hda_dsp_ctrl_init_chip(sdev, true).

**Comment by ranj063** [comment]
Thanks for the review @zhuyingjiang @libinyang . Updated now

**Comment by ranj063** [comment]
Sorry @zhuyingjiang @libinyang could you pleas approve again. I had to rebase after merging 1058

File: sound/soc/sof/intel/hda.c [hunk 2]
```diff
@@ -335,24 +335,30 @@ static int hda_init_caps(struct snd_sof_dev *sdev)
 	if (bus->ppcap)
 		dev_dbg(sdev->dev, "PP capability, will probe DSP later.\n");
 
+#if IS_ENABLED(CONFIG_SND_SOC_SOF_HDA)
+	/* init i915 and HDMI codecs */
+	ret = hda_codec_i915_init(sdev);
+	if (ret < 0) {
+		dev_err(sdev->dev, "error: no HDMI audio devices found\n");
```
Comment (xiulipan) [inline sound/soc/sof/intel/hda.c]: The error message here looks wired?
```suggestion
		dev_err(sdev->dev, "error: init i915 and HDMI codec failed\n");
```

Comment (ranj063) [reply sound/soc/sof/intel/hda.c]: done!

**Comment by ranj063** [comment]
@xiulipan fixed now

**Comment by ranj063** [comment]
> But we still not know why the HDMI connection will help to workaround this situation, right?

@xiulipan that is still a mystery. Although it only helps in the case of Up2. on the chromebook it doesnt seem to the case

**Comment by xiulipan** [comment]
@ranj063 
And I see some difference with i915 as built-in or module from @zhuyingjiang kconfig.
So let keep some notes on this.
