### PR TITLE
ALSA: hda/realtek - Check headset type by unplug and resume

### LINKED ISSUE #908: [BUG] About 2s delay to switch status in sound setting when plug in/out headset in idle.
**Describe the bug**
Plug in/out headset in idle, check the speaker and headset switch from sound setting. Delay about 2s to switch status.

**To Reproduce**
1.  Stop music 
2. Open sound setting of laptop
3. Plug in  headset, then plug out, check.

**Expected behavior**
About 2s delay to switch status in sound setting when plug in/out headset in idle.

**Environment**
platform: CML laptop with ALC3204 codec
Test Recipe | '+Rander UCM https://github.com/RanderWang/intel-UCM |  
-- | -- | --
Kernel repo | https://github.com/thesofproject/linux/tree/release/sof-v5.0 |  
  | d698c4f | kernel topic/sof-dev branch
  | PR #853 | ASoC: sof: hda: fix fw loading failure
  | PR #868 | ASoC: soc-pcm: BE dai needs prepare when pause release after resume
  |   |  
Firmware repo | https://github.com/thesofproject/sof/commits/master |  
  | 47fcac2  [thesofproject/sof: master] | top of master branch
  |   |  
Topology: | https://github.com/thesofproject/sof/commits/master | Same as above SOF repo
  | file:  tools/topology/sof-hda-generic.m4,  sof-hda-generic-2ch.tplg |  

[jackWithoutPlay_dmesg.log](https://github.com/thesofproject/linux/files/3151034/jackWithoutPlay_dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3151035/logger.log)

### PR DESCRIPTION
**Pull request by bardliao**
When system enable HDA power save mode.
This issue will happen on new platform which DMIC connect to PCH.
In Dell headset mode, it will recheck during runtime resume when
headset was plugged.
This patch will move check headset type on unplug and system resume.

[ A few minor code cleanups by tiwai ]

Signed-off-by: Kailang Yang <kailang@realtek.com>
Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit aeac1a0dadb4ab699a61136a5729d048abe6ee5f)

This patch fix #908

### CODE REVIEW

**Comment by keyonjie** [comment]
Hi @bardliao what issue the commit really fixed for us?

**Comment by bardliao** [comment]
> Hi @bardliao what issue the commit really fixed for us?

@keyonjie Headset type won't be detected on runtime resume with this patch. It will significantly reduce the runtime resume latency time when a headset is plugged in.

**Comment by libinyang** [comment]
@bardliao I saw this patch is signed-off by Takashi. Does this mean the patch has been merged?
I'm wondering whether this patch is ok if the HS is hotplugged when S3 or S4?

And please see my comments inline.

File: sound/pci/hda/patch_realtek.c [hunk 1]
```diff
@@ -4981,7 +4983,10 @@ static void alc_fixup_headset_mode(struct hda_codec *codec,
 		alc_probe_headset_mode(codec);
 		break;
 	case HDA_FIXUP_ACT_INIT:
-		spec->current_headset_mode = 0;
+		if (is_s3_resume(codec) || is_s4_resume(codec)) {
```
Comment (libinyang) [inline sound/pci/hda/patch_realtek.c:4986]: Why do we need this judgement?

File: sound/pci/hda/patch_realtek.c [hunk 2]
```diff
@@ -4901,6 +4903,8 @@ static void alc_update_headset_mode(struct hda_codec *codec)
 	switch (new_headset_mode) {
 	case ALC_HEADSET_MODE_UNPLUGGED:
 		alc_headset_mode_unplugged(codec);
+		spec->current_headset_mode = ALC_HEADSET_MODE_UNKNOWN;
```
Comment (libinyang) [inline sound/pci/hda/patch_realtek.c:4906]: spec->current_headset_mode will be set to new_headset_mode later in this function. So it seems not necessary to set spec->current_headset_mode = ALC_HEADSET_MODE_UNKNOWN. But the code should be harmless here. So this is fine to me.

**Comment by bardliao** [comment]
> @bardliao I saw this patch is signed-off by Takashi. Does this mean the patch has been merged?

@libinyang Yes, it is cherry picked from commit aeac1a0. I am not the author. So I am afraid I can't answer your questions.

**Comment by RanderWang** [comment]
> > Hi @bardliao what issue the commit really fixed for us?
> 
> @keyonjie Headset type won't be detected on runtime resume with this patch. It will significantly reduce the runtime resume latency time when a headset is plugged in.

If the runtime resume is caused by headset plugged event, could headset be detected with this PR?

**Comment by bardliao** [comment]
> > @keyonjie Headset type won't be detected on runtime resume with this patch. It will significantly reduce the runtime resume latency time when a headset is plugged in.
> 
> If the runtime resume is caused by headset plugged event, could headset be detected with this PR?

@RanderWang The patch is about headset type detection, not headset plug detection. So it won't impact the result of headset detection. Basically, the issue was the headset type detection will take about 1 sec, and the patch will remove the headset type detection from runtime resume. And the patch is merged into release/sof-v5.0 branch since May 16.
