### PR TITLE
 ASoC: SOF: implement polling mode on snd_hdac_bus_get_response and force polling mode on CFL/CNL 

### LINKED ISSUE #953: [BUG][CML]Audio output via internal speaker will have 1-2s latency
**Summary**:
Audio output via internal speaker will have 1-2s latency

**To reproduce**
Make sure not plug in headphone or headset 
Play music via command "aplay -Dhw:0,0 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav"

**Expect result**
Streaming output normally without latency

**Impact**
Streaming output will have 1-2 latency between press the enter and show the music playing status.

**Reproduce rate: 4/10**

**Test recipe**
Rander UCM https://github.com/RanderWang/intel-UCM/commits/hdmi
Kernel repo：c536f9f https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout	
Topology: https://github.com/thesofproject/sof/commits/debug-ipc-timeout	Same as above SOF repo	
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

Upload 4 dmesg log to compare.
[failDmesg2.txt](https://github.com/thesofproject/linux/files/3186440/failDmesg2.txt)
[passDmesg1.txt](https://github.com/thesofproject/linux/files/3186441/passDmesg1.txt)
[passDmesg2.txt](https://github.com/thesofproject/linux/files/3186442/passDmesg2.txt)
[failDmesg1.txt](https://github.com/thesofproject/linux/files/3186443/failDmesg1.txt)

### PR DESCRIPTION
**Pull request by bardliao**
@kailangyang found that sometimes we will get a long latency response on WHL and we can set
polling_mode as a workaround on legacy HDA driver.
https://github.com/thesofproject/linux/issues/900#issuecomment-493056368
The workaround is already used on CFL. [if (IS_CFL(pci))](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/pci/hda/hda_intel.c#L1704)

However, there is no polling_mode on [snd_hdac_bus_get_response](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/hda/hdac_controller.c#L233).
We can move polling_mode flag from struct azx to struct hdac_bus and implement polling_mode on ```snd_hdac_bus_get_response()```. Then force polling mode on CFL and CNL. 

Fix #953

### CODE REVIEW

**Comment by plbossart** [comment]
@bardliao can't we add this polling to the snd_hdac_bus_get_response() and use the chip = bus_to_azx(bus) accessor?
Also that function seems to lag behind the legacy driver big time, so likely additional updates if we want to support all cases

**Comment by libinyang** [comment]
The patch is OK to me. And I have the same suggestion as Pierre that it is better to change the generic function. My suggestion is to add polling_mode flag in hdac_bus. and code like:
```
if (bus->polling_mode || do_poll) //we don't need to poll at the first time
xxxx
```

**Comment by bardliao** [comment]
> @bardliao can't we add this polling to the snd_hdac_bus_get_response() and use the chip = bus_to_azx(bus) accessor?
@plbossart Yes, I also prefer to use snd_hdac_bus_get_response(). Currently ``struct azx`` is only for legacy HDA driver, and we have ``struct sof_intel_hda_dev`` in sof. So it may not be a good idea to use ``struct azx`` here. I think what we can do is
1. create a similar struct with polling_mode and replace ``struct hda_bus hbus`` in the ``struct sof_intel_hda_dev {}`` by the new struct. So we can get polling_mode in ''snd_hdac_bus_get_response()''.
or
2. Add polling_mode in ``struct hdac_bus`` so we can get polling_mode directly from bus->polling_mode in ``snd_hdac_bus_get_response()``.
Option 2 is simpler than 1. We can even move polling_mode from ``struct azx`` to ``struct hdac_bus``.
What do you think?

> Also that function seems to lag behind the legacy driver big time, so likely additional updates if we want to support all cases

Yes, it is also my concern. Actually I am thinking if we should implement the full function of polling_mode, i.e. switch to polling mode if it is timed out, or just add a workaround for some platforms.

**Comment by bardliao** [comment]
> The patch is OK to me. And I have the same suggestion as Pierre that it is better to change the generic function. My suggestion is to add polling_mode flag in hdac_bus. and code like:
> 
> ```
> if (bus->polling_mode || do_poll) //we don't need to poll at the first time
> xxxx
> ```

Thanks @libinyang it should be a easier way to implement polling mode in snd_hdac_bus_get_response()

**Comment by plbossart** [comment]
> > The patch is OK to me. And I have the same suggestion as Pierre that it is better to change the generic function. My suggestion is to add polling_mode flag in hdac_bus. and code like:
> > ```
> > if (bus->polling_mode || do_poll) //we don't need to poll at the first time
> > xxxx
> > ```
> 
> Thanks @libinyang it should be a easier way to implement polling mode in snd_hdac_bus_get_response()

Except that it's not conceptually clean. The polling is a controller capability, not something related to the bus. The bus has no concept of polling.

**Comment by libinyang** [comment]
@plbossart Actually it is not controller capability, I think. Every hardware can do the polling. No special HW support is needed. And polling is the behavior of controller to poll codec. So it's more like bus related feature. I'm not sure why the community will put the flag in the controller. From my viewpoint, it should be put in bus.

> 
> Except that it's not conceptually clean. The polling is a controller capability, not something related to the bus. The bus has no concept of polling.

**Comment by mengdonglin** [comment]
@libinyang @bardliao @plbossart  According to Realtek, this latency issues was observed on SKL at first many years ago, so the legacy-HDA driver introduced this fix.  

And this fix also helps SOF, verified by 
QA: https://github.com/thesofproject/linux/issues/953#issuecomment-494327465

**Comment by ranj063** [comment]
> @plbossart Actually it is not controller capability, I think. Every hardware can do the polling. No special HW support is needed. And polling is the behavior of controller to poll codec. So it's more like bus related feature. I'm not sure why the community will put the flag in the controller. From my viewpoint, it should be put in bus.
> 
> >

@libinyang please dont top post when you reply to comments. Always post under(like this one).

**Comment by libinyang** [comment]
> @libinyang please dont top post when you reply to comments. Always post under(like this one).

@ranj063 Good tips. Thanks. I never realize it.

**Comment by keyonjie** [comment]
Hi @bardliao so are we missing RIRB interrupts here? I am wondering if the same issue existed with SST driver or SOF specific, and if there is anything wrong in our suspend/resume routines.

**Comment by bardliao** [comment]
> Hi @bardliao so are we missing RIRB interrupts here? 

@keyonjie Yes, I think so.

> I am wondering if the same issue existed with SST driver or SOF specific, and if there is anything wrong in our suspend/resume routines.

I think it is a HW related issue. Please see https://github.com/thesofproject/linux/pull/963#issuecomment-494617407

**Comment by bardliao** [comment]
> Except that it's not conceptually clean. The polling is a controller capability, not something related to the bus. The bus has no concept of polling.

@plbossart I think the polling_mode here is polling the rirb status by SW. So it's not about HW capability. However, the intent of this PR is to add a workaround for some specific platforms. In the point of view, it seems make more sense to add the polling_mode in a chip struct. That's the concept of option 1. 

> @plbossart Actually it is not controller capability, I think. Every hardware can do the polling. No special HW support is needed. And polling is the behavior of controller to poll codec. So it's more like bus related feature. I'm not sure why the community will put the flag in the controller. From my viewpoint, it should be put in bus.

@libinyang As you said, the polling mode is not a capability of bus either. Can we say it is a behavior of bus? I doubt it very much.

**Comment by plbossart** [comment]
The definition of polling is an active loop to access a register/mmio.
This doesn't exist at the bus level, you don't poll a bus. It's only defined for entities that expose a register map, and for HDaudio this means a controller only. The codecs are accessed with commands/verbs.

**Comment by libinyang** [comment]
@plbossart @bardliao 

Bus is not a HW device here in the driver. The bus means the connection of controller and chip. If you look into the struct hdac_bus, you will find it defines void __iomem *ppcap, *spbcap, *mlcap and other registers. And what's more, you will find in struct hdac_bus, it defines: struct hdac_rb corb, struct hdac_rb rirb. So if we are polling the corb and rirb, it is reasonable to put the flag in struct hdac_bus. 

However, it will not impact on the feature implementation to put the flag in bus or chip. @bardliao when you submit the patch to community, please kindly cc me.

**Comment by bardliao** [comment]
Since the change will not only inside SOF, so ask for comment from alsa-dev first
https://www.spinics.net/lists/alsa-devel/msg91235.html.
Now the PR has updated and I will send it to upstream. But before that, can someone give me some comments?
@plbossart @libinyang @keyonjie @ranj063

**Comment by bardliao** [comment]
@libinyang 
> 1. chip->poll_count++ seems to be good as bus->poll_count++

Sounds good

> 2. not sure if we can merge the 2 get_response functions into 1?

I don't know if it's worth doing that. And we still use struct azx in the function. eg.
[if (chip->msi) {](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/pci/hda/hda_controller.c#L851)

File: sound/pci/hda/hda_intel.c [hunk 1]
```diff
@@ -375,6 +375,7 @@ enum {
```
Comment (plbossart) [inline sound/pci/hda/hda_intel.c:375]: fix typos/grammar in commit message.

We observed the same issue as reported by commit....

File: sound/pci/hda/hda_intel.c [hunk 2]
```diff
@@ -1700,8 +1701,8 @@ static int azx_create(struct snd_card *card, struct pci_dev *pci,
 	else
 		chip->bdl_pos_adj = bdl_pos_adj[dev];
 
-	/* Workaround for a communication error on CFL (bko#199007) */
-	if (IS_CFL(pci))
+	/* Workaround for a communication error on CFL and CNL (bko#199007) */
```
Comment (plbossart) [inline sound/pci/hda/hda_intel.c]: Workaround for a communication error on CFL (bko#199007) and CNL

File: sound/pci/hda/hda_intel.c [hunk 3]
```diff
@@ -1701,17 +1701,17 @@ static int azx_create(struct snd_card *card, struct pci_dev *pci,
 	else
 		chip->bdl_pos_adj = bdl_pos_adj[dev];
 
-	/* Workaround for a communication error on CFL and CNL (bko#199007) */
-	if (IS_CFL(pci) || IS_CNL(pci))
-		chip->polling_mode = 1;
-
```
Comment (plbossart) [inline sound/pci/hda/hda_intel.c:1706]: you should move this first in a separate patch to allow for bisects.

File: sound/hda/hdac_controller.c [hunk 4]
```diff
@@ -240,6 +240,8 @@ int snd_hdac_bus_get_response(struct hdac_bus *bus, unsigned int addr,
 
 	for (loopcounter = 0;; loopcounter++) {
 		spin_lock_irq(&bus->reg_lock);
+		if (bus->polling_mode)
+			snd_hdac_bus_update_rirb(bus);
```
Comment (plbossart) [inline sound/hda/hdac_controller.c:243]: should be separate patch to mirror the functionality in the legacy code.

File: sound/soc/sof/intel/hda.c [hunk 5]
```diff
@@ -217,6 +220,11 @@ static int hda_init(struct snd_sof_dev *sdev)
 	ext_ops = snd_soc_hdac_hda_get_ops();
 #endif
 	sof_hda_bus_init(bus, &pci->dev, ext_ops);
+
+	/* Workaround for a communication error on CFL and CNL (bko#199007) */
```
Comment (plbossart) [inline sound/soc/sof/intel/hda.c]: Workaround for a communication error on CFL (bko#199007) and CNL

**Comment by libinyang** [comment]
Use separate get_response is OK to me. So the PR is OK to me now.
