### PR TITLE
ASoC: SOF: keep prepare/unprepare widgets in sink path

### LINKED ISSUE #4021: [BUG] PCM IO error with multi stream capture topology on pause-resume test
**Describe the bug**
PCM IO error happen when I run the "~/sof-test/test-case/multiple-pause-resume.sh -r 50" test.

**To Reproduce**
1. export TPLG=/lib/firmware/intel/avs-tplg/sof-tgl-nocodec.tplg
2. ~/sof-test/test-case/multiple-pause-resume.sh -r 50

**Reproduction Rate**
100%. But I can't reproduce this issue if I start two PCMs and pause-resume them manually.

**Expected behavior**
PASS "~/sof-test/test-case/multiple-pause-resume.sh -r 50" test

**Impact**
This is a blocker to add multi capture stream on topology.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: topic/sof-dev: https://github.com/thesofproject/linux/commit/ec7f15280902c4599ad97d0a93226b2fa5f62993
    * SOF: main: https://github.com/thesofproject/sof/commit/1e3a4cfe9b26176e28287b913b35bcbe12bbef79  + https://github.com/thesofproject/sof/pull/6601
2) Name of the topology file
    * Topology: cavs-tgl-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: {TGL}

**Screenshots or console output**
I can't find useful information from kernel or firmware log. Below is the console output.
```
2022-11-15 08:31:45 UTC [INFO] ssp-capture to command: arecord -D hw:0,12 -r 48000 -c 2 -f S16_LE -vv -i /dev/null -q
2022-11-15 08:31:45 UTC [INFO] Port1 to command: aplay -D hw:0,1 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
spawn arecord -D hw:0,12 -r 48000 -c 2 -f S16_LE -vv -i /dev/null -q
2022-11-15 08:31:45 UTC [INFO] wait for expect process finished
spawn aplay -D hw:0,1 -r 48000 -c 2 -f S16_LE -vv -i /dev/zero -q
Hardware PCM card 0 'sof-nocodec' device 12 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16384
  period_size  : 4096
  period_time  : 85333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4096
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 16384
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
Hardware PCM card 0 'sof-nocodec' device 1 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 16384
  period_size  : 4096
  period_time  : 85333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 4096
  period_event : 0
  start_threshold  : 16384
  stop_threshold   : 16384
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
...
arecord: pcm_read:2178: read error: Input/output error
...
2022-11-15 08:31:50 UTC [INFO] pipeline: ssp-capture with arecord
2022-11-15 08:31:50 UTC [INFO] pipeline: Port1 with aplay
2022-11-15 08:31:50 UTC [INFO] Check expect exit status
declare -- cmd="journalctl_cmd --since=@1668501030"
2022-11-15 08:31:50 UTC [ERROR] pause resume PID 2222 had non-zero exit status
2022-11-15 08:31:50 UTC [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2022-11-15 08:31:51 UTC [ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2022-11-15 08:31:51 UTC [ERROR]  main()  @  /home/ubuntu/sof-test/test-case/multiple-pause-resume.sh:191
2022-11-15 08:31:51 UTC [INFO] pkill -TERM -f mtrace-reader.py
2022-11-15 08:31:51 UTC [INFO] ktime=258 sof-test PID=1575: ending
2022-11-15 08:31:51 UTC [INFO] Test Result: FAIL!
```
Full console output, kernel and firmware log are attached.
[console.txt](https://github.com/thesofproject/sof/files/10010780/console.txt)
[out.txt](https://github.com/thesofproject/sof/files/10010759/out.txt)
[dmesg.txt](https://github.com/thesofproject/sof/files/10010760/dmesg.txt)

### PR DESCRIPTION
**Pull request by bardliao**
The existing code return when a widget doesn't need to prepare/unprepare. This will prevent widgets in the sink path from being prepared/unprepared.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

Fixes: #4021

### CODE REVIEW

**Comment by bardliao** [comment]
Thanks @ranj063 for finding this issue.

File: sound/soc/sof/sof-audio.c [hunk 1]
```diff
@@ -311,7 +311,7 @@ sof_unprepare_widgets_in_path(struct snd_sof_dev *sdev, struct snd_soc_dapm_widg
 
 	/* return if the widget is in use or if it is already unprepared */
 	if (!swidget->prepared || swidget->use_count > 1)
-		return;
+		goto sink_unprepare;
```
Comment (plbossart) [inline sound/soc/sof/sof-audio.c:314]: commit message, should we add a 

````
Link: https://github.com/thesofproject/linux/issues/4021
````

**Review by plbossart — DISMISSED** [review]

**Review by ranj063 — DISMISSED** [review]

File: sound/soc/sof/sof-audio.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/sof-audio.c:314]: just thinking a bit aloud @bardliao. Im not sure why I used swidget->use_count > 1, IF a widget is in use, its use_count will be > 0 right?

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:314]: makes sense to me, you only want to unprepare if there is exactly one user of the widget. If there is more than one you skip it.

Comment (ranj063) [reply sound/soc/sof/sof-audio.c:314]: right, so we can even get rid of the prepared flag and just use use_count to decide whether we need to prepare or not.

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:314]: are you sure about the change @bardliao ? This will never unprepare.

Comment (bardliao) [reply sound/soc/sof/sof-audio.c:314]: @ranj063 @plbossart It sounds reasonable. Let me do more test.

**Comment by bardliao** [comment]
PR test result: https://sof-ci.01.org/linuxpr/PR4022/build2014/devicetest/index.html

File: sound/soc/sof/sof-audio.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/sof/sof-audio.c:314]: > are you sure about the change @bardliao ? This will never unprepare.

@plbossart I rechecked the code, and I think it should be correct. It will not unprepare and visit the next widget in the path when `swidget->use_count > 0`. So, it will unprepare when swidget->use_count = 0. This is correct, right?

File: sound/soc/sof/sof-audio.c [hunk 2]
```diff
@@ -310,7 +310,7 @@ sof_unprepare_widgets_in_path(struct snd_sof_dev *sdev, struct snd_soc_dapm_widg
 	struct snd_soc_dapm_path *p;
 
 	/* return if the widget is in use or if it is already unprepared */
-	if (!swidget->prepared || swidget->use_count > 1)
+	if (!swidget->prepared || swidget->use_count > 0)
```
Comment (plbossart) [inline sound/soc/sof/sof-audio.c:313]: sorry this makes no sense to me @bardliao @ranj063 

You want to return here if the widget has two users. If there is a single user you still want to unprepare.
This was added in c02c3b653c7342fe0e21c7cd918a7905a92486d6 by @RanderWang for mixing usages.

In addition, in the sof_prepare_widgets_path we only use swidget->prepared, that's unbalanced and makes no sense either.  If we use the use count on unprepare we should also use it on prepare, no?

**Review by plbossart — CHANGES_REQUESTED** [review]

File: sound/soc/sof/sof-audio.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/sof/sof-audio.c:313]: oh it was @RanderWang and not me. I was wondering why I added this and couldnt remember the reason. I should have checked git blame. But let's think about when unprepare is called. Its called after all the widgets in the DAPM widget list are freed. So a widget should be unprepared only if there are no users, right? So use_count > 0 makes sense.

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:313]: @bardliao my understanding is that we follow the ALSA logic of open/prepare/unprepare/free. I don't see how we could unprepare AFTER the free.

Comment (ranj063) [reply sound/soc/sof/sof-audio.c:313]: but this unprepare() isnt related to the ALSA ioctls at all @plbossart. We do a prepare followed by setup() for all widgets during hw_params and then a free followed by unprepare during hw_free. Have a look at https://github.com/thesofproject/linux/blob/929cd48102671d515a484c6da284d14bd793dff9/sound/soc/sof/sof-audio.c#L636

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:313]: A free followed by unprepare? how is this even possible. Wow, we have all the naming backwards I am afraid.

Comment (ranj063) [reply sound/soc/sof/sof-audio.c:313]: yes, I think we do have the naming inverted. The problem was setup() came first and for lack of a better name, I went with prepare(). But ideally, the prepare should be called setup and the setup() should be called init(). Then we'd have setup() followed by init() and then free() followed by reset() maybe?

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:313]: we need to rename all this:
sof_widget_list_setup -> sof_widget_list_prepare_setup
sof_widget_list_free -> sof_widget_list_free_unprepare

Comment (ranj063) [reply sound/soc/sof/sof-audio.c:313]: yes but going back to the original question. I think the logic is correct with use_count > 0 right?

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:313]: Yes indeed, the unprepare is when there are no users left with your definition.

File: sound/soc/sof/sof-audio.c [hunk 3]
```diff
@@ -310,16 +310,14 @@ sof_unprepare_widgets_in_path(struct snd_sof_dev *sdev, struct snd_soc_dapm_widg
 	struct snd_soc_dapm_path *p;
 
 	/* skip if the widget is in use or if it is already unprepared */
-	if (!swidget->prepared || swidget->use_count > 0)
+	if (swidget->use_count > 0)
```
Comment (plbossart) [inline sound/soc/sof/sof-audio.c]: commit title should be ASoC: SOF: sof-audio: remove swidget->prepared flag

File: sound/soc/sof/sof-audio.c [hunk 4]
```diff
@@ -350,7 +348,7 @@ sof_prepare_widgets_in_path(struct snd_sof_dev *sdev, struct snd_soc_dapm_widget
 	if (!widget_ops)
 		goto sink_prepare;
 
-	if (!widget_ops[widget->id].ipc_prepare || swidget->prepared)
+	if (!widget_ops[widget->id].ipc_prepare && !swidget->use_count)
```
Comment (plbossart) [inline sound/soc/sof/sof-audio.c]: This works as long as we have always prepare followed by setup (where the reference count is increased).

If this is not the case and we can have multiple calls to prepare, then this would not work.

In the first case, there should be a deeper explanation in the commit message as to why this is ok.

Comment (bardliao) [reply sound/soc/sof/sof-audio.c]: @plbossart @ranj063 On the second thought, I think it is better to keep the prepared flag. Think about if a widget is prepared, but fail to setup. The use_count will be 0, but it is prepared. It will likely be a problem.

Comment (ranj063) [reply sound/soc/sof/sof-audio.c]: But @bardliao don't we call unprepare if widget setup fails?

File: sound/soc/sof/sof-audio.c (hunk 2 above)
Comment (ujfalusi) [inline sound/soc/sof/sof-audio.c:313]: Can the use_count go negative?
```c
if (!swidget->prepared || swidget->use_count)
```

File: sound/soc/sof/sof-audio.c (hunk 4 above)
Comment (bardliao) [reply sound/soc/sof/sof-audio.c]: > But @bardliao don't we call unprepare if widget setup fails?

Yes, we call sof_walk_widgets_in_order SOF_WIDGET_UNPREPARE if sof_walk_widgets_in_order SOF_WIDGET_SETUP failed. But what if one of the widget is failed and others are success? Those widgets that have already set up will not be unprepared since their use_count is 1. My point is that prepare and setup are handled in different helper functions, someone can easily break it even if it works well now.

File: sound/soc/sof/sof-audio.c (hunk 2 above)
Comment (bardliao) [reply sound/soc/sof/sof-audio.c:313]: > Can the use_count go negative?
> 
> ```c
> if (!swidget->prepared || swidget->use_count)
> ```

Ideally, no. But I do see it is negative when I meet IPC errors. And sof_widget_free() will never work at that time.

File: sound/soc/sof/sof-audio.c (hunk 4 above)
Comment (ranj063) [reply sound/soc/sof/sof-audio.c]: @bardliao when widget setup fails, we unroll and free all widgets that were previously set up in sof_set_up_widgets_in_path(). I am fairly certain the prepare flag is redundant

Comment (ranj063) [reply sound/soc/sof/sof-audio.c]: But this PR is good enough for what it was intended for. We should follow up with another PR to remove the prepared flag

**Review by ranj063 — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Comment by ranj063** [comment]
@bardliao can you please take a look at the IPC4 device test failures

**Comment by bardliao** [comment]
SOFCI TEST

File: sound/soc/sof/sof-audio.c (hunk 2 above)
Comment (RanderWang) [reply sound/soc/sof/sof-audio.c:313]: In original code, swidget->use_count = 2 when the widget was unprepared. Now swidget->use_count = 1 in this function with many changes in kernel.

**Comment by bardliao** [comment]
PR test looks good now.
https://sof-ci.01.org/linuxpr/PR4022/build2160/devicetest/index.html
https://sof-ci.01.org/linuxpr/PR4022/build2159/devicetest/index.html

**Review by RanderWang — APPROVED** [review]
LGTM
