### PR TITLE
ASoC: SOF: topology2: add core token in each module token list

### LINKED ISSUE #4181: [Bug][IPC4] core id token not handled properly
In sof_widget_ready() in topology.c, we will parse and copy token tuples to swidget->tuples, and also in this function, we have below code to enable/disable multicore with debug flag.
```
	if (sof_debug_check_flag(SOF_DBG_DISABLE_MULTICORE)) {
		swidget->core = SOF_DSP_PRIMARY_CORE;
	} else {
		int core = sof_get_token_value(SOF_TKN_COMP_CORE_ID, swidget->tuples,
					       swidget->num_tuples);
		pr_info("Chao %d\n", core);
		if (core >= 0)
			swidget->core = core;
	}
```

However, in the ipc4 case, the token SOF_TKN_COMP_CORE_ID is not in any token list, so it probabily will not be copied to swidge->tuples, we will never get the value for core id, and lead to `swidget->core === -EINVAL` for IPC4.

For IPC3 case, there is SOF_CORE_TOKENS in all the token list, so it is fine.

We could add SOF_CORE_TOKENS for IPC4, but I think IPC4 uses pipeline level SCHED token for multicore scheduling.

Issue originally found by @RanderWang that the swdget->core is wrong, and I help to root cause the issue.

@ujfalusi  @ranj063

### PR DESCRIPTION
**Pull request by RanderWang**
Add core token in extended token list for each module to support multi-core feature.

Validated with tigerlake up board
fix https://github.com/thesofproject/linux/issues/4181

### CODE REVIEW

File: sound/soc/sof/ipc4-topology.c [hunk 1]
```diff
@@ -128,6 +128,12 @@ static const struct sof_topology_token src_tokens[] = {
 		offsetof(struct sof_ipc4_src, sink_rate)},
 };
 
+/* Core tokens */
+static const struct sof_topology_token core_tokens[] = {
+	{SOF_TKN_COMP_CORE_ID, SND_SOC_TPLG_TUPLE_TYPE_WORD, get_token_u32,
+		offsetof(struct snd_sof_widget, core)},
```
Comment (ranj063) [inline sound/soc/sof/ipc4-topology.c]: can we club this with comp_ext_tokens? I mean the name comp_ext_tokens had a different meaning in IPC3. For IPC4, it could be anything no?

Comment (RanderWang) [reply sound/soc/sof/ipc4-topology.c]: yes, good idea.  updated

**Review by ranj063 — APPROVED** [review]

**Comment by aiChaoSONG** [comment]
I don't think this is going to work, because  https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/topology.c#L1251-L1264, we use continue for SOF_COMP_EXT_TOKENS, so tokens under this set will not be copied to swidget->tuples.

I think we do the correct think for IPC3 to add core id token, so we can do the same for IPC4.

File: sound/soc/sof/ipc4-topology.c (hunk 1 above)
Comment (aiChaoSONG) [reply sound/soc/sof/ipc4-topology.c]: @ranj063  I don't think this is going to work, because  https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/topology.c#L1251-L1264, we use continue for SOF_COMP_EXT_TOKENS, so tokens under this set will not be copied to swidget->tuples. Below code in topology.c probably can not work
```
	if (sof_debug_check_flag(SOF_DBG_DISABLE_MULTICORE)) {
		swidget->core = SOF_DSP_PRIMARY_CORE;
	} else {
		int core = sof_get_token_value(SOF_TKN_COMP_CORE_ID, swidget->tuples,
					       swidget->num_tuples);
		pr_info("Chao %d\n", core);
		if (core >= 0)
			swidget->core = core;
	}
```

Comment (ranj063) [reply sound/soc/sof/ipc4-topology.c]: why wont it work @aiChaoSONG. Yes, we use continue but we have already parsed the core and uuid into swidget on line https://github.com/thesofproject/linux/blob/cfd8c7d5c3e38c0684263bcf9f2580486e5662f6/sound/soc/sof/topology.c#L1253

Comment (RanderWang) [reply sound/soc/sof/ipc4-topology.c]: I validated it

Comment (aiChaoSONG) [reply sound/soc/sof/ipc4-topology.c]: > why wont it work @aiChaoSONG. Yes, we use continue but we have already parsed the core and uuid into swidget on line
> 
> https://github.com/thesofproject/linux/blob/cfd8c7d5c3e38c0684263bcf9f2580486e5662f6/sound/soc/sof/topology.c#L1253

@ranj063  Yes, it will work, but it also makes the else block in the above code I pasted redundant for IPC4 (because the token never copied to swidget->tuples), but still valid for IPC3, that's what makes me uncomfortable.

**Review by plbossart — APPROVED** [review]

File: sound/soc/sof/ipc4-topology.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/ipc4-topology.c]: yes that wont "work" for IPC4 but it doesnt need to. All we care about is whether swidget->core is what is set in topology or not.

**Review by aiChaoSONG — APPROVED** [review]
