### PR TITLE
ASoC: SOF: update gain ipc msg definition to align with fw

### LINKED ISSUE #4026: [BUG] IPC4 volume windows ramp was broken with latest sof-dev kernel and sof firmware
**Describe the bug**
When volume change, volume ramp should take effect, however, from debug, never see ramp is happening, from sof side, finally find the cdata from kernel driver have random value, no the ramp time.

**To Reproduce**
1. build sof with ipc4 with logs inserted in volume ramp.
2. run it on test machine.
3. aplay a wav file.
4. enable mtrace and adjust volume with alsamixer, inserted log never come out.

**Reproduction Rate**
100%

**Expected behavior**
volume ramp should happen, and cdata should be right.

**Impact**
volume ramp missed, pop noise come when volume change.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: latest
    * SOF: latest
2) Name of the topology file
    * Topology: cavs_sdw.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: dell adlp test machine.

**Screenshots or console output**
n/a

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

### PR DESCRIPTION
**Pull request by RanderWang**
Fw uses latest 64 bits curve_duration in gain ipc msg definition so update kernel driver side. Curve_duration is in number of hundreds nanoseconds, and only 32 bits int can support up to 400s volume ramp, which is enough for ramp feature, so we don't need to support 64 bits read by topology. Now divide 64 bits curve_duration to two parts: low part set by topology and high part zeroed in driver.

fix https://github.com/thesofproject/linux/issues/4026 (IPC4 volume windows ramp was broken with latest sof-dev kernel and sof firmware)

### CODE REVIEW

**Comment by RanderWang** [comment]
The discussion is in https://github.com/thesofproject/linux/issues/4026 .  The gain ipc msg was first supported based on closed source TGL branch in 2020. At that time it was 32 bits. It was updated to 64bits later but kernel side is not updated

File: sound/soc/sof/ipc4-topology.h [hunk 1]
```diff
@@ -279,14 +279,16 @@ struct sof_ipc4_control_data {
...
+ * @curve_duration_h: Curve duration high part
  */
 struct sof_ipc4_gain_data {
 	uint32_t channels;
 	uint32_t init_val;
 	uint32_t curve_type;
 	uint32_t reserved;
-	uint32_t curve_duration;
+	uint32_t curve_duration_l;
+	uint32_t curve_duration_h;
```
Comment (bardliao) [inline sound/soc/sof/ipc4-topology.h:291]: Does it mean we didn't align with FW side?

Comment (RanderWang) [reply sound/soc/sof/ipc4-topology.h:291]: yes, we didn't

**Review by bardliao — DISMISSED** [review]

File: sound/soc/sof/ipc4-control.c [hunk 2]
```diff
@@ -84,7 +84,8 @@ sof_ipc4_set_volume_data(struct snd_sof_dev *sdev, struct snd_sof_widget *swidge
 		}
 
 		/* set curve type and duration from topology */
-		data.curve_duration = gain->data.curve_duration;
+		data.curve_duration_l = gain->data.curve_duration_l;
+		data.curve_duration_h = gain->data.curve_duration_h;
```
Comment (plbossart) [inline sound/soc/sof/ipc4-control.c:88]: commit message: you've got to explain better what this change is needed and what it solves.

ASoC: SOF: IPC4: update gain ipc msg definition to align with fw

Recent firmware changes modified the curve duration from 32 to 64 bits, which breaks volume ramps.
A simple solution would be to change the definition, but unfortunately the ASoC topology framework only supports up to 32 bit tokens.
This patch suggests breaking the 64 bit value in low and high parts, with only the low-part extracted from topology and high-part only zeroes. Since the curve duration is represented in hundred of nanoseconds, we can still represent a 400s ramp, which is just fine. 
The defacto ABI change has no effect on existing users since the IPC4 firmware has not been released just yet.



Link: https://github.com/thesofproject/linux/issues/4026

**Review by plbossart — CHANGES_REQUESTED** [review]

**Comment by ranj063** [comment]
> The discussion is in #4026 . The gain ipc msg was first supported based on closed source TGL branch in 2020. At that time it was 32 bits. It was updated to 64bits later but kernel side is not updated

@RanderWang will this break TGL with the tester?

**Comment by RanderWang** [comment]
> > The discussion is in #4026 . The gain ipc msg was first supported based on closed source TGL branch in 2020. At that time it was 32 bits. It was updated to 64bits later but kernel side is not updated
> 
> @RanderWang will this break TGL with the tester?

I validated on TGL with Closed source FW.  Please check the original definition, a u32 sized memory is padded by compiler to align 8. Why FW is crashed ? because we don't zeroed "struct sof_ipc4_gain_data" in volume update, so the padded u32 is full of garbage, so FW get a 64bit data with high part of unexpected data. Now we change the padded u32 to explicitly defined high part and zero it.
````c
struct sof_ipc4_gain_data {
	uint32_t channels;
	uint32_t init_val;
	uint32_t curve_type;
	uint32_t reserved;
	uint32_t curve_duration;
        // compiler will allocate more u32 memory to aligned(8)
} __aligned(8);
````

File: sound/soc/sof/ipc4-control.c (hunk 2 above)
Comment (RanderWang) [reply sound/soc/sof/ipc4-control.c:88]: Thanks! updated

**Review by ranj063 — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Review by bardliao — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]
