### PR TITLE
ASoC: SOF: intel: set stream decouple false in stream_free

### LINKED ISSUE #299: SOF_HDA: need to clean-up exit sequences
we are missing a lot of hdac library calls, such as 	snd_hdac_ext_bus_device_remove(bus), both in the .remove calls as well as in error handling.

The goal is to release ALL the resources allocated, no exceptions. This will be mandatory for upstream.

### PR DESCRIPTION
**Pull request by bardliao**
snd_hdac_ext_stream_decouple(bus, stream, true) will be called
on boot up and hw_params. So add snd_hdac_ext_stream_decouple(bus,
stream, false) in hda_dsp_stream_free().

Signed-off-by: Bard liao <yung-chuan.liao@linux.intel.com>

Fix #299

### CODE REVIEW

File: sound/soc/sof/intel/hda-stream.c [hunk 1]
```diff
@@ -659,13 +659,15 @@ void hda_dsp_stream_free(struct snd_sof_dev *sdev)
 #endif
 
 	list_for_each_entry_safe(s, _s, &bus->stream_list, list) {
+		stream = stream_to_hdac_ext_stream(s);
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-stream.c]: should stream be defined conditionally? We don't want to use hdac_ext_stream in all cases

**Comment by bardliao** [comment]
@plbossart decouple is required from hardware. All streams will be configured as decoupled in init, that's done by hdac_ext_link_stream_assign(). I don't feel comfortable with current  code. It is set in hw_params and pcm_trigger which is not symmetry. How about we move snd_hdac_ext_stream_decouple(false) to hw_free? So it will be configured to couple when the stream is not active and we don't need to configure it when the device is removed.

**Comment by plbossart** [comment]
@bardliao can you remind me how it's done in the existing SST driver?

**Comment by bardliao** [comment]
@plbossart Below is what I found, but I don't know if there is anything missed since I didn't test sst driver.

snd_hdac_ext_stream_decouple(true):
```
skl_tplg_mixer_event() SND_SOC_DAPM_PRE_PMU case -> ... -> snd_hdac_ext_stream_decouple()
skl_pcm_prepare() -> skl_pcm_host_dma_prepare() -> snd_hdac_ext_stream_decouple()
skl_pcm_open() -> snd_hdac_ext_stream_assign() -> ... -> snd_hdac_ext_stream_decouple()
skl_link_hw_params() -> snd_hdac_ext_stream_assign() -> ... -> snd_hdac_ext_stream_decouple()
skl_dsp_prepare() -> snd_hdac_ext_stream_assign() -> ... -> snd_hdac_ext_stream_decouple()
```
snd_hdac_ext_stream_decouple(false):
```
skl_shutdown() -> snd_hdac_ext_stream_decouple()
skl_pcm_trigger() SNDRV_PCM_TRIGGER_SUSPEND case -> snd_hdac_ext_stream_decouple(). 
skl_link_pcm_trigger() SNDRV_PCM_TRIGGER_SUSPEND case -> snd_hdac_ext_stream_decouple(). 
skl_remove() -> skl_free() -> snd_hdac_stream_free_all() -> snd_hdac_ext_stream_decouple(). 
skl_dsp_cleanup() -> snd_hdac_ext_stream_release() -> snd_hdac_ext_stream_decouple()
skl_pcm_close() -> snd_hdac_ext_stream_release() -> snd_hdac_ext_stream_decouple() (if the stream type is not _COUPLED)
skl_link_hw_free() -> snd_hdac_ext_stream_release() -> snd_hdac_ext_stream_decouple()
```

**Comment by plbossart** [comment]
@ranj063 we could use your help here.
The Skylake driver sets the "decouple_stream" to 
- true on .prepare
- false on .trigger(suspend) and .shutdown

@bardliao showed we currently set it to 
- true on .hw_params
- false on .trigger(suspend)

I agree his patch seems more logical to use hw_params/free but I am concerned about the suspend part. What is the flow on resume, would .prepare or .hw_params be reissued?

**Comment by ranj063** [comment]
@plbossart let me look into the code and get back on this.

**Comment by ranj063** [comment]
@plbossart yes, hw_params will definitely be called upon resume. I am not sure about prepare as we dont have that callback set in our hda dai link ops. But this change looks good to me. 

Also, the suspend trigger was something I never saw only the stop trigger before suspend.

**Comment by plbossart** [comment]
@ranj063 you probably only saw the stop trigger because that's how CRAS operates (streams stopped). We'd still figure out if we can suspend a running stream, that's a valid ALSA use case.
Will apply this for now, let's see if this breaks anything...
