### PR TITLE
ASoC: SOF: ipc3-topology: subtract ALH dai_index by 2

### LINKED ISSUE #9571: [BUG] [IPC3] ALH Pin5 ipc tx error for 0x30010000.
**Describe the bug**
When creating a ALH Pin5 on SoundWire link 0,  relevant pipeline, widget, buf and pcm ipc tx errors : 

[    5.060518] snd_sof:sof_widget_setup_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.5.ALH5.IN setup complete
[    5.060520] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30010000
[    5.060725] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx error for 0x30010000 (msg/reply size: 96/0): -22
[    5.060750] sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to setup widget ALH5.IN
[    5.060765] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x30110000
[    5.061391] snd_sof:sof_widget_free_unlocked: sof-audio-pci-intel-tgl 0000:00:1f.3: widget PIPELINE.5.ALH5.IN freed
[    5.061525] sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
[    5.061545] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
[    5.061560] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[    5.061597] sof_sdw sof_sdw: ASoC: failed to instantiate card -22

**To Reproduce**
Steps to reproduce the behavior: (e.g. list commands or actions used to reproduce the bug)
When create a ALH Pin5 on SoundWire link 0

#ALH Pin5 (ID: 4) 
DAI_CONFIG(ALH, 5, 4, `Capture-SmartMic',
        ALH_CONFIG(ALH_CONFIG_DATA(ALH, 5, 48000, 2)))

**Reproduction Rate**
100%

**Expected behavior**
ALH Pin5 is successfully to create the relevant pipeline, widget, buf and pcm.

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)
The Soundwire device not available to support on board.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel:  upstream
    * SOF: all IPC3 firmware/topology
2) Name of the topology file
    * Topology: new topology which requires ALH5 support will impact.
3) Name of the platform(s) on which the bug is observed.
    * Platform: IPC3 with Soundwire support

### PR DESCRIPTION
**Pull request by bardliao**
We use SDW pin 2 as for ALH dai 0. However, IPC3 ALH dai index should start from 0.

Fixes: https://github.com/thesofproject/sof/issues/9571

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@bardliao do we need to state this is a fix in our commit message as some users SDW wont work without this patch ?

File: sound/soc/sof/ipc3-topology.c [hunk 1]
```diff
@@ -2167,8 +2178,19 @@ static int sof_ipc3_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
 	case SOF_DAI_INTEL_ALH:
 		if (data) {
 			/* save the dai_index during hw_params and reuse it for hw_free */
-			if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS)
-				config->dai_index = data->dai_index;
+			if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS) {
+				/*
+				 * DAI 2 is used as the first DAI for SDW in topology, normalize
+				 * it to 0
```
Comment (kv2019i) [inline sound/soc/sof/ipc3-topology.c]: Maybe refer to sof_sdw.c (something like "see SOC_SDW_INTEL_BIDIR_PDI_BASE in sof_sdw.c") defitinion to explain where the value "2" comes from?

File: sound/soc/sof/ipc3-topology.c [hunk 2]
```diff
@@ -1594,6 +1594,17 @@ static int sof_ipc3_widget_setup_comp_dai(struct snd_sof_widget *swidget)
 	if (ret < 0)
```
Comment (kv2019i) [inline sound/soc/sof/ipc3-topology.c:1597]: Can you explain in commit this is needed to support 3rd and 4th pins of SDW with IPC3 and Intel platforms. Older topology files have not used these pins, so this has not been an issue before (people will want to understand why this was not needed before and why this is needed now).

**Review by kv2019i — COMMENTED** [review]
I think this is way to go. A few comments on the commit message and inline commets. I wonder if we could somehow also highlight that we have to support existing topology files, so renumbering (in Linux code) is not an option.

File: sound/soc/sof/ipc3-topology.c [hunk 3]
```diff
@@ -1594,6 +1594,17 @@ static int sof_ipc3_widget_setup_comp_dai(struct snd_sof_widget *swidget)
...
 		goto free;
 
+	/* DAI 2 is used as the first DAI for SDW in topology, normalize it to 0 */
+	if (comp_dai->type == SOF_DAI_INTEL_ALH) {
+		comp_dai->dai_index -= 2;
+		if (comp_dai->dai_index < 0) {
+			dev_err(sdev->dev,
+				"Invalid ALH dai index %d, Please use SDW Pin 2 and above\n",
```
Comment (ranj063) [inline sound/soc/sof/ipc3-topology.c]: maybe we can say that only Pin numbers > 1 are supported instead of saying please use Pin 2

File: sound/soc/sof/ipc3-topology.c (hunk 2 above)
Comment (bardliao) [reply sound/soc/sof/ipc3-topology.c:1597]: Commit message updated.

File: sound/soc/sof/ipc3-topology.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/sof/ipc3-topology.c]: > Maybe refer to sof_sdw.c (something like "see SOC_SDW_INTEL_BIDIR_PDI_BASE in sof_sdw.c") defitinion to explain where the value "2" comes from?

Added. But on the second thought, this is Intel specific. Should we do it here?

File: sound/soc/sof/ipc3-topology.c (hunk 3 above)
Comment (bardliao) [reply sound/soc/sof/ipc3-topology.c]: > maybe we can say that only Pin numbers > 1 are supported instead of saying please use Pin 2

Updated

**Comment by bardliao** [comment]
> @bardliao do we need to state this is a fix in our commit message as some users SDW wont work without this patch ?

Yes, Fixes tag added.

File: sound/soc/sof/ipc3-topology.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/sof/ipc3-topology.c]: Added sdw_bidir_base in sof_dev_desc struct. But I am not sure if it is the best place to add the base.

**Review by lgirdwood — DISMISSED** [review]

**Review by kv2019i — COMMENTED** [review]
Thanks @bardliao . All my concerns covered. I'll let other kernel folks comment on the sdw_bidir_base added -- not sure whether this is ok or not (it's always 2 now). It does make the logic more explicit, which I do like.

**Comment by ranj063** [comment]
@bardliao I think we should squash both patches or at least split out the addition of the base field and setting the base into a seaprate patch first following by the next patch using it

**Comment by bardliao** [comment]
> @bardliao I think we should squash both patches or at least split out the addition of the base field and setting the base into a seaprate patch first following by the next patch using it

Done

**Comment by lgirdwood** [comment]
@ujfalusi pls review. Thanks

File: sound/soc/sof/ipc3-topology.c [hunk 4]
```diff
@@ -1594,6 +1595,17 @@ static int sof_ipc3_widget_setup_comp_dai(struct snd_sof_widget *swidget)
 	if (ret < 0)
 		goto free;
 
+	/* Subtract the base to match the IPC3 FW dai index. */
+	if (comp_dai->type == SOF_DAI_INTEL_ALH) {
+		comp_dai->dai_index -= desc->sdw_bidir_base;
+		if (comp_dai->dai_index < 0) {
```
Comment (ujfalusi) [inline sound/soc/sof/ipc3-topology.c]: dai_index is uint32_t ...

File: sound/soc/sof/intel/pci-icl.c [hunk 5]
```diff
@@ -27,6 +27,7 @@ static const struct sof_dev_desc icl_desc = {
 	.resindex_pcicfg_base   = -1,
 	.resindex_imr_base      = -1,
 	.irqindex_host_ipc      = -1,
+	.sdw_bidir_base		= 2,
```
Comment (ujfalusi) [inline sound/soc/sof/intel/pci-icl.c]: This is not really platform related, does it? It is IPC3 related, IPC4's bidir base is 0, right?

**Review by ranj063 — DISMISSED** [review]

File: sound/soc/sof/ipc3-topology.c (hunk 4 above)
Comment (bardliao) [reply sound/soc/sof/ipc3-topology.c]: > dai_index is uint32_t ...

Thanks, move the check before subtracting.

File: sound/soc/sof/intel/pci-icl.c (hunk 5 above)
Comment (bardliao) [reply sound/soc/sof/intel/pci-icl.c]: > This is not really platform related, does it? It is IPC3 related, IPC4's bidir base is 0, right?

That is platform related. SDW bidirectional pins are the same on IPC3 and IPC4. But, IPC4 FW supports all SDW pins. So, we don't need to shift the dai index in IPC4.

Comment (ujfalusi) [reply sound/soc/sof/intel/pci-icl.c]: Right, so, if you boot cAVS2.5 (TGL/ADL/etc) the sdw_bidir_base is applicable, but it is applicable only if you boot to use IPC3. Same platform, different IPC version.
sdw_bidir_base is not platform related option, it is IPC version specific, no?

Comment (ujfalusi) [reply sound/soc/sof/intel/pci-icl.c]: or you are saying that with both IPC3/4 the topology's sdw bidir index starts at 2 and we don't need to normalize this in case of IPC4?

Or to put this the other way: On MTL+ the bidir_base is 0 in (IPC4) topology and it is 2 in (IPC4) cAVS2.5?

Comment (bardliao) [reply sound/soc/sof/intel/pci-icl.c]: sdw_bidir_base will be applied to IPC3 only because dai_index 4, and 5 are acceptable by IPC4. As far as I know we always use 2+ SDW Pins even on MTL+ platforms.

Comment (ujfalusi) [reply sound/soc/sof/intel/pci-icl.c]: you are not touching pci-mtl, pci-lnl, for those platforms the sdw_bidir_base is 0.

Why do you even need this in the `struct sof_dev_desc` when the subtraction is only applicable for INTEL_ALH with IPC3 and it is always applicable in this case?

If you are saying that this is somehow a platform variable and applicable to all Intel platforms, then you should set the correct value for all platforms that this applies.

Comment (bardliao) [reply sound/soc/sof/intel/pci-icl.c]: > you are not touching pci-mtl, pci-lnl, for those platforms the sdw_bidir_base is 0.
> 
> Why do you even need this in the `struct sof_dev_desc` when the subtraction is only applicable for INTEL_ALH with IPC3 and it is always applicable in this case?

Because AMD or other vendors may not need the offset.

> 
> If you are saying that this is somehow a platform variable and applicable to all Intel platforms, then you should set the correct value for all platforms that this applies.

Sure I will add sdw_bidir_base to all Intel platforms. We define SOC_SDW_INTEL_BIDIR_PDI_BASE 2 and apply it to all Intel platforms. But, that doesn't match to the HW capabilities. I am not sure about older platforms, but I checked TGL, MTL, and LNL, all SDW pins are bidirectional. You can check the HW capabilities by the dmesg log below.
```
soundwire_intel:intel_pdi_init: soundwire_intel soundwire_intel.link.0: PCM cap bd:12 in:0 out:0
```

Comment (ujfalusi) [reply sound/soc/sof/intel/pci-icl.c]: AMD and other vendors don't use dai type `SOF_DAI_INTEL_ALH`?

Comment (bardliao) [reply sound/soc/sof/intel/pci-icl.c]: Added sdw_bidir_base to all Intel platforms.

Comment (bardliao) [reply sound/soc/sof/intel/pci-icl.c]: > AMD and other vendors don't use dai type `SOF_DAI_INTEL_ALH`?

Oh, yes, that is a valid point. Then I think we don't need sdw_bidir_base.

Comment (bardliao) [reply sound/soc/sof/intel/pci-icl.c]: updated

File: sound/soc/sof/ipc3-topology.c [hunk 6]
```diff
@@ -2167,8 +2181,16 @@ static int sof_ipc3_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
 	case SOF_DAI_INTEL_ALH:
 		if (data) {
 			/* save the dai_index during hw_params and reuse it for hw_free */
-			if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS)
-				config->dai_index = data->dai_index;
+			if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS) {
+				/* Subtract the base to match the IPC3 FW dai index. */
```
Comment (ujfalusi) [inline sound/soc/sof/ipc3-topology.c]: The `IPC3` is not needed, we are in `ipc3-topology.c` file anyways.

I think the comment should be somehow different, probably 'Convert the topology pin index to ALH dai index, the mapping is using 2-off indexing, iow, pin #2 is ALH dai #0' or around these lines?

This looks much cleaner already, imho.

**Review by ujfalusi — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]
@kv2019i good for you ?

**Review by kv2019i — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]
