### PR TITLE
ASoC: Intel: sof_sdw: Always register the HDMI dai links

### LINKED ISSUE #4594: No soundcard detected with nomodeset kernel option Dell XPS 17 9720 SKU 0AFE
If I boot without nomodeset kernel option then audio works properly but if I boot with nomodeset kernel option then no soundcard is detected.
Maybe firmware is waiting for HDMI from dGPU and fail if no HDMI is detected.
I'm using Debian unstable with latest kernel 6.5.0-rc6+ from https://github.com/thesofproject/linux and firmware-sof-signed 2.2.6-1.
[dmesg-with-nomodeset.txt](https://github.com/thesofproject/linux/files/12618639/dmesg-with-nomodeset.txt)
[dmesg-without-nomodeset.txt](https://github.com/thesofproject/linux/files/12618640/dmesg-without-nomodeset.txt)

### LINKED ISSUE #4648: [MTL] TPLG failed to load on MTLP_SKU0C87_SDCA
**Describe the bug**
This is a kernel regression and caused by https://github.com/thesofproject/linux/commit/b785e242c835409d3eeb8aa3c765cfbe2d77913a.

kernel log:
```
[    4.078374] snd_sof:sof_widget_ready: sof-audio-pci-intel-mtl 0000:00:1f.3: tplg: widget 23 (dai-copier.HDA.iDisp1.playback) is ready [type: 27, pipe: 51, pins: 1 / 0, stream: iDisp1]
[    4.078379] sof-audio-pci-intel-mtl 0000:00:1f.3: error: can't connect DAI dai-copier.HDA.iDisp1.playback stream iDisp1
[    4.078392] sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to add widget id 0 type 27 name : dai-copier.HDA.iDisp1.playback stream iDisp1
[    4.078409] sof_sdw sof_sdw: ASoC: failed to load widget dai-copier.HDA.iDisp1.playback
[    4.078417] sof_sdw sof_sdw: ASoC: topology: could not load header: -22
[    4.078478] sof-audio-pci-intel-mtl 0000:00:1f.3: error: tplg component load failed -22
[    4.078493] sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to load DSP topology -22
[    4.078505] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[    4.078541] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[    4.079015] sof_sdw sof_sdw: snd_soc_register_card failed -22
[    4.079024] sof_sdw: probe of sof_sdw failed with error -22

```

**To Reproduce**
check the kernel log after booting.

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[SHA](https://github.com/thesofproject/linux/commit/b785e242c835409d3eeb8aa3c765cfbe2d77913a.)}
2) Name of the topology file
    * Topology: {sof-ace-tplg/sof-mtl-rt1318-l12-rt714-l0.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {MTLP_SKU0C87_SDCA}

### PR DESCRIPTION
**Pull request by ujfalusi**
The topology files for SDW devices require HDMI dai links to be present and
this is granted under normal conditions but in case of special use cases
the display (i915) driver might not be enabled due to deny-listing,
booting with nomodeset or just not compiled at all.

This should not block the non HDMI audio to be usable so register the dai
links unconditionally. The code has been prepared for this and in case of
no HDMI audio the link is created with dummy codec.

Closes: https://github.com/thesofproject/linux/issues/4594
Closes: https://github.com/thesofproject/linux/issues/4648

### CODE REVIEW

**Comment by ujfalusi** [comment]
Fixes: https://github.com/thesofproject/linux/issues/4594

**Review by bardliao — DISMISSED** [review]

File: sound/soc/intel/boards/sof_sdw.c [hunk 1]
```diff
@@ -1572,8 +1572,8 @@ static int sof_card_dai_links_create(struct snd_soc_card *card)
 	int num_links, link_index = 0;
 	char *name, *cpu_dai_name;
 	char *codec_name, *codec_dai_name;
+	int codec_index, hdmi_num;
```
Comment (plbossart) [inline sound/soc/intel/boards/sof_sdw.c]: i really don't like two variables without any correlation on the same line. It's legal in C but it looks weird. Why would we group codec_index and hdmi_num?

File: sound/soc/intel/boards/sof_sdw.c [hunk 2]
```diff
@@ -1611,7 +1610,8 @@ static int sof_card_dai_links_create(struct snd_soc_card *card)
 		bt_num = 1;
 
 	dev_dbg(dev, "sdw %d, ssp %d, dmic %d, hdmi %d, bt: %d\n",
-		sdw_be_num, ssp_num, dmic_num, hdmi_num, bt_num);
+		sdw_be_num, ssp_num, dmic_num,
+		ctx->hdmi.idisp_codec ? hdmi_num : 0, bt_num);
```
Comment (plbossart) [inline sound/soc/intel/boards/sof_sdw.c:1615]: commit message needs a 

Closes: https://github.com/thesofproject/linux/issues/4594

File: sound/soc/intel/boards/sof_sdw.c (hunk 1 above)
Comment (ujfalusi) [reply sound/soc/intel/boards/sof_sdw.c]: OK

**Comment by ujfalusi** [comment]
Changes since v1:
- move the declaration of hdmi_num as separate line
- add Closes tag to commit message

**Review by kv2019i — APPROVED** [review]
Thanks @ujfalusi !

**Comment by ujfalusi** [comment]
Changes since v2:
- rebased on topic/sof-dev

**Comment by ujfalusi** [comment]
Changes since v3:
- added closes tag for https://github.com/thesofproject/linux/issues/4648

**Comment by ujfalusi** [comment]
@plbossart, @keqiaozhang, internal test runs: 33544 and 33550.
33550 fails with HDMI playback with
```
sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on iDisp1 Pin: -22
```
So the card forms with this patch but the non existent HDMI is not working. Let me see if I can figure out something for this.

**Comment by ujfalusi** [comment]
This is the exact behavior with HDA machines also. If the HDMI is disabled (nomodeset or denylisted/not compiled display driver) then attempt to play to HDMI PCM results:
```
sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on iDisp1 Pin: -22
```
I'm not sure how this can be fixed, dummy dai almost works (iow does not). I can get it probe with that with a hack in sound/soc/sof/topology.c :
```diff
diff --git a/sound/soc/sof/topology.c b/sound/soc/sof/topology.c
index a3a3af252259..b123f4ee9b48 100644
--- a/sound/soc/sof/topology.c
+++ b/sound/soc/sof/topology.c
@@ -1089,6 +1091,8 @@ static int sof_connect_dai_widget(struct snd_soc_component *scomp,
 			if (!snd_soc_dai_get_widget(cpu_dai, stream)) {
 				snd_soc_dai_set_widget(cpu_dai, stream, w);
 				break;
+			} else if (!strcmp(cpu_dai->name, "snd-soc-dummy-dai")) {
+				break;
 			}
 		}
 		if (i == rtd->dai_link->num_cpus) {
```
But then the DAPM route is messed up badly and the playback attempt will fail with different error.

I'm not sure if we want or need to fix that and to how...

FWIW, before https://github.com/thesofproject/linux/commit/b785e242c835409d3eeb8aa3c765cfbe2d77913a the codec for HDMI did showed up and that's why the playback did not failed:
```
sof-audio-pci-intel-mtl 0000:00:1f.3: hda codecs found, mask 4
```
vs after the patch:
```
sof-audio-pci-intel-mtl 0000:00:1f.3: no hda codecs found!
```

**Review by plbossart — APPROVED** [review]
