### PR TITLE
ASoC: SOF: Intel: hda-ctrl: add missing WAKE_STS clear

### LINKED ISSUE #4889: LNL/SDW AOIC: major regression with PIO commands
from Intel daily tests #/result/planresultdetail/39251?model=LNLM_SDW_AIOC&testcase=check-sof-logger

````
[ 4685.789060] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[ 4685.789067] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to reset controller during suspend
[ 4685.789070] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to power down DSP during suspend -5
[ 4685.789076] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -5)
[ 4688.184905] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[ 4688.184915] kernel: soundwire_intel soundwire_intel.link.0: intel_resume_runtime: power_up failed after bus reset: -5
[ 4688.184919] kernel: soundwire_intel soundwire_intel.link.0: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.0: -5
[ 4688.184923] kernel:  SDW0-Playback: ASoC: error at __soc_pcm_open on SDW0-Playback: -5
[ 4688.184926] kernel:  Jack Out: ASoC: error at dpcm_be_dai_startup on Jack Out: -5
[ 4688.184928] kernel:  Jack Out: ASoC: error at dpcm_fe_dai_startup on Jack Out: -5
[ 4688.186628] kernel: soundwire_intel soundwire_intel.link.0: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.0: -22
[ 4688.191686] kernel: soundwire_intel soundwire_intel.link.2: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[ 4688.191701] kernel: soundwire_intel soundwire_intel.link.2: intel_resume_runtime: power_up failed after bus reset: -5
[ 4688.191707] kernel: soundwire_intel soundwire_intel.link.2: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.2: -5
[ 4688.191713] kernel:  SDW2-Playback: ASoC: error at __soc_pcm_open on SDW2-Playback: -5
[ 4688.191717] kernel:  Speaker: ASoC: error at dpcm_be_dai_startup on Speaker: -5
[ 4688.191721] kernel:  Speaker: ASoC: error at dpcm_fe_dai_startup on Speaker: -5
[ 4688.193344] kernel: soundwire_intel soundwire_intel.link.0: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.0: -22
[ 4688.195635] kernel: soundwire_intel soundwire_intel.link.2: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.2: -22
[ 4688.200113] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[ 4688.200116] kernel: soundwire_intel soundwire_intel.link.1: intel_resume_runtime: power_up failed after bus reset: -5
[ 4688.200119] kernel: soundwire_intel soundwire_intel.link.1: ASoC: error at snd_soc_pcm_component_pm_runtime_get on soundwire_intel.link.1: -5
[ 4688.200121] kernel:  SDW1-Capture: ASoC: error at __soc_pcm_open on SDW1-Capture: -5
[ 4688.200123] kernel:  Microphone: ASoC: error at dpcm_be_dai_startup on Microphone: -5
[ 4688.200124] kernel:  Microphone: ASoC: error at dpcm_fe_dai_startup on Microphone: -5
````

That's super bad...

manual tests run on a different device jf-lnlm-rvp-sdw-1 show this

````
[  363.370649] kernel: hdaudio ehdaudio0D7: no AFG or MFG node found
[  363.370671] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: device init failed for hdac device
[  367.530144] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to reset HDA controller gctl 0x1
[  367.530180] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to reset controller during suspend
[  367.530196] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed to power down DSP during suspend -5
[  367.530228] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: can't suspend (snd_sof_runtime_suspend [snd_sof] returned -5)
[  373.581625] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x44000000|0x31400008 failed: -19
[  373.581627] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: sof_ipc4_set_get_data: large config set failed at offset 0: -19
[  373.671146] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[  373.671168] kernel: soundwire_intel soundwire_intel.link.0: intel_resume failed: -5
[  373.671178] kernel: soundwire_intel soundwire_intel.link.0: PM: dpm_run_callback(): pm_generic_resume+0x0/0x30 returns -5
[  373.671215] kernel: soundwire_intel soundwire_intel.link.0: PM: failed to resume: error -5
[  373.674568] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[  373.674570] kernel: soundwire_intel soundwire_intel.link.1: intel_resume failed: -5
[  373.674571] kernel: soundwire_intel soundwire_intel.link.1: PM: dpm_run_callback(): pm_generic_resume+0x0/0x30 returns -5
[  373.674575] kernel: soundwire_intel soundwire_intel.link.1: PM: failed to resume: error -5
[  373.677853] kernel: soundwire_intel soundwire_intel.link.2: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[  373.677855] kernel: soundwire_intel soundwire_intel.link.2: intel_resume failed: -5
[  373.677856] kernel: soundwire_intel soundwire_intel.link.2: PM: dpm_run_callback(): pm_generic_resume+0x0/0x30 returns -5
[  373.677858] kernel: soundwire_intel soundwire_intel.link.2: PM: failed to resume: error -5
[  373.681192] kernel: soundwire_intel soundwire_intel.link.3: intel_link_power_up: hdac_bus_eml_sdw_power_up failed: -5
[  373.681193] kernel: soundwire_intel soundwire_intel.link.3: intel_resume failed: -5
[  373.681194] kernel: soundwire_intel soundwire_intel.link.3: PM: dpm_run_callback(): pm_generic_resume+0x0/0x30 returns -5
[  373.681196] kernel: soundwire_intel soundwire_intel.link.3: PM: failed to resume: error -5
[  373.787757] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: IP_MCP_CONTROL_SW_RST is not cleared
[  373.789266] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: MCP_CONTROL_CMD_RST is not cleared
[  373.789363] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: MCP_CONTROL_SOFT_RST is not cleared
[  373.790132] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: MCP_CONTROL_CLK_STOP_CLR is not cleared
[  373.790136] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: MCP_CONFIG_UPDATE_BIT is not cleared
[  373.790138] kernel: soundwire_intel soundwire_intel.link.3: sdw_cdns_clock_stop failed: MCP_CONTROL_HW_RST is not cleared
[  373.790155] kernel: soundwire_intel soundwire_intel.link.2: sdw_cdns_clock_stop failed: IP_MCP_CONTROL_SW_RST is not cleared
[  373.790159] kernel: soundwire_intel soundwire_intel.link.2: sdw_cdns_clock_stop failed: MCP_CONTROL_CMD_RST is not cleared
[  373.790160] kernel: soundwire_intel soundwire_intel.link.2: sdw_cdns_clock_stop failed: MCP_CONTROL_SOFT_RST is not cleared
[  373.790162] kernel: soundwire_intel soundwire_intel.link.2: sdw_cdns_clock_stop failed: MCP_CONTROL_CLK_STOP_CLR is not cleared
[  373.790175] kernel: soundwire_intel soundwire_intel.link.2: sdw_cdns_clock_stop failed: MCP_CONFIG_UPDATE_BIT is not cleared
[  373.790177] kernel: soundwire_intel soundwire_intel.link.2: sdw_cdns_clock_stop failed: MCP_CONTROL_HW_RST is not cleared
[  373.790189] kernel: soundwire_intel soundwire_intel.link.1: sdw_cdns_clock_stop failed: IP_MCP_CONTROL_SW_RST is not cleared
[  373.790192] kernel: soundwire_intel soundwire_intel.link.1: sdw_cdns_clock_stop failed: MCP_CONTROL_CMD_RST is not cleared
[  373.790194] kernel: soundwire_intel soundwire_intel.link.1: sdw_cdns_clock_stop failed: MCP_CONTROL_SOFT_RST is not cleared
[  373.790195] kernel: soundwire_intel soundwire_intel.link.1: sdw_cdns_clock_stop failed: MCP_CONTROL_CLK_STOP_CLR is not cleared
[  373.790198] kernel: soundwire_intel soundwire_intel.link.1: sdw_cdns_clock_stop failed: MCP_CONFIG_UPDATE_BIT is not cleared
[  373.790209] kernel: soundwire_intel soundwire_intel.link.1: sdw_cdns_clock_stop failed: MCP_CONTROL_HW_RST is not cleared
[  373.790220] kernel: soundwire_intel soundwire_intel.link.0: sdw_cdns_clock_stop failed: IP_MCP_CONTROL_SW_RST is not cleared
[  373.790245] kernel: soundwire_intel soundwire_intel.link.0: sdw_cdns_clock_stop failed: MCP_CONTROL_CMD_RST is not cleared
[  373.790247] kernel: soundwire_intel soundwire_intel.link.0: sdw_cdns_clock_stop failed: MCP_CONTROL_SOFT_RST is not cleared
[  373.790249] kernel: soundwire_intel soundwire_intel.link.0: sdw_cdns_clock_stop failed: MCP_CONTROL_CLK_STOP_CLR is not cleared
[  373.790251] kernel: soundwire_intel soundwire_intel.link.0: sdw_cdns_clock_stop failed: MCP_CONFIG_UPDATE_BIT is not cleared
[  373.790253] kernel: soundwire_intel soundwire_intel.link.0: sdw_cdns_clock_stop failed: MCP_CONTROL_HW_RST is not cleared
````

which is even worse - something is clearly not quite right.

We'll need to bisect this one further, I don't recall seeing all this before. @fredoh9 @marc-hb @bardliao @kv2019i @ujfalusi FYI

### PR DESCRIPTION
**Pull request by plbossart**
For some reason, the programming sequences in the SOF driver do not include a clear of the WAKE_STS bits before resetting the controller.

This clear is not formally required by the HDaudio specification, but was added to harden the snd-hda-reset back in 2007. Adding this sequence back avoids an issue reported by the Intel CI.

Closes: https://github.com/thesofproject/linux/issues/4889

### CODE REVIEW

**Comment by marc-hb** [comment]
In a comment in #4894 you posted more information and SHA1s which really seem to belong to this commit message:
https://github.com/thesofproject/linux/pull/4894#issuecomment-2030474135

> FWIW the 3rd commit partially reverts https://github.com/thesofproject/linux/commit/6ec3295826d8c11141c970cf3fd68d77d3452adb ("ASoC: SOF: Intel: hda: remove duplicated clear WAKESTS")
>
> I have no idea why this was removed.
>
> It could also be that there's an interference from https://github.com/thesofproject/linux/commit/ae5ff22a884d2aac0908cfd0113d3db633d79ae6 ("ASoC: SOF: Intel: hda-ctrl: only clear WAKESTS for HDaudio codecs"), where in the end we didn't clear all the WAKE_STS fields.
>
> Wow, my brain is officially fried haha.

OK: maybe the last line about your brain is not necessary.

**Comment by marc-hb** [comment]
> I have no idea why this was removed.

This was discussed in
- #1020

**Comment by plbossart** [comment]
I don't want to add more details on this patch. 
We don't really know what the correlation/causation is on LNL, adding more details would likely mislead reviewers.

**Comment by marc-hb** [comment]
I wonder why even the purely factual, past SHA1s could confuse reviewers but I imagine they can be found with some well placed `git blame` commands so I hope omitting them only adds a bit overhead.

File: sound/soc/sof/intel/hda-ctrl.c [hunk 1]
```diff
@@ -196,6 +197,12 @@ int hda_dsp_ctrl_init_chip(struct snd_sof_dev *sdev)
 
 	hda_dsp_ctrl_misc_clock_gating(sdev, false);
 
+	/* clear WAKE_STS if not in reset */
+	gctl = snd_sof_dsp_read(sdev, HDA_DSP_HDA_BAR, SOF_HDA_GCTL);
+	if (gctl & SOF_HDA_GCTL_RESET)
```
Comment (bardliao) [inline sound/soc/sof/intel/hda-ctrl.c:202]: Do we need to test gctl? Can we clear WAKE_STS unconditionally?

Comment (plbossart) [reply sound/soc/sof/intel/hda-ctrl.c:202]: sorry @bardliao I don't understand the questions. This is similar to the code in https://github.com/thesofproject/linux/commit/b37a15188eae9d4c49c5bb035e0c8d4058e4d9b3

**Review by ujfalusi — APPROVED** [review]

File: sound/soc/sof/intel/hda-ctrl.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/sof/intel/hda-ctrl.c:202]: Thanks @plbossart , I got the reason why `if (gctl & SOF_HDA_GCTL_RESET)` is needed after reading https://github.com/thesofproject/linux/commit/b37a15188eae9d4c49c5bb035e0c8d4058e4d9b3.

**Review by bardliao — APPROVED** [review]
