### PR TITLE
ASoC: SOF: ipc4-topology: Fix ChainDMA DMA Link ID handling during xrun

### LINKED ISSUE #5116: MTL: DSP panic with firmware 2.10.1
Reported by @ImDevinC and forked from https://github.com/thesofproject/linux/issues/4880#issuecomment-2241332797

Just confirmed I'm on 6.10 and while the audio device shows up now, I do not get any audio. Here's what I'm seeing in journalctl for "sof-". My dmesg buffer is too large to go back to the beginning because there is a bunch of spam messages about the audio card (I'll put those below)
Also, since this issue is already closed, let me know if it would be better to create a new one with this info

````
Jul 21 09:51:06.879342 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: enabling device (0000 -> 0002)
Jul 21 09:51:06.886182 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
Jul 21 09:51:06.886285 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
Jul 21 09:51:06.889348 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: use msi interrupt mode
Jul 21 09:51:06.899343 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: DMICs detected in NHLT tables: 2
Jul 21 09:51:06.899515 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: hda codecs found, mask 4
Jul 21 09:51:06.902678 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Firmware paths/files for ipc type 1:
Jul 21 09:51:06.902832 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3:  Firmware file:     intel/sof-ipc4/mtl/sof-mtl.ri
Jul 21 09:51:06.902956 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3:  Firmware lib path: intel/sof-ipc4-lib/mtl
Jul 21 09:51:06.903065 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3:  Topology file:     intel/sof-ace-tplg/sof-mtl-rt711-l0-rt1316-l3-2ch.tplg
Jul 21 09:51:06.903176 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Loaded firmware library: ADSPFW, version: 2.10.0.1
Jul 21 09:51:07.026011 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Booted firmware version: 2.10.0.1
Jul 21 09:51:07.036010 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Topology: ABI 3:29:0 Kernel ABI 3:23:0
Jul 21 09:51:07.070351 bean kernel: input: sof-soundwire Headset Jack as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card1/input23
Jul 21 09:51:07.070376 bean kernel: input: sof-soundwire HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card1/input24
Jul 21 09:51:07.070389 bean kernel: input: sof-soundwire HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card1/input25
Jul 21 09:51:07.070402 bean kernel: input: sof-soundwire HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card1/input26
Jul 21 09:52:50.079336 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
Jul 21 09:52:50.079656 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: DSP panic!
Jul 21 09:52:50.079800 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
Jul 21 09:52:50.079926 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: 0x50000005: module: ROM_EXT, state: FW_ENTERED, running
Jul 21 09:52:50.080043 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Firmware state: 0x5, status/error code: 0x0
Jul 21 09:52:50.080154 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Unknown toolchain is used
Jul 21 09:52:50.080266 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: DSP Firmware Oops
Jul 21 09:52:50.080396 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: Exception Cause: AllocaCause, MOVSP instruction, if caller’s registers are not in the register file
Jul 21 09:52:50.080514 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: EXCCAUSE 0x00000005 EXCVADDR 0x00000000 PS       0x00060e20 SAR     0x0000000c
Jul 21 09:52:50.080625 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: EPC1     0xa00727e5 EPC2     0x00000000 EPC3     0x00000000 EPC4    0x00000000
Jul 21 09:52:50.080738 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
Jul 21 09:52:50.080847 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: EPS2     0x00000000 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
Jul 21 09:52:50.080952 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000000
Jul 21 09:52:50.081057 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: stack dump from 0x00000000
Jul 21 09:52:50.081168 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: AR registers:
Jul 21 09:52:50.081278 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: 0x0: a004b5d5 a0102f00 00000000 4011b440
Jul 21 09:52:50.081390 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: 0x10: a011b4c0 00000018 40107730 a0102f00
Jul 21 09:52:50.081498 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: 0x20: a005bf99 a0102ec0 40107730 a00613d8
Jul 21 09:52:50.081605 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: 0x30: a005bf99 a0102ec0 40107730 a00613d8
Jul 21 09:52:50.081711 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
Jul 21 09:52:50.586371 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0xe030003|0xc00
Jul 21 09:52:50.586696 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
Jul 21 09:52:50.586875 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x8e030003|0xc00|0x0, target: 0x1b0a0000|0x0|0x0, ctl: 0x3
Jul 21 09:52:50.587031 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
Jul 21 09:52:50.587179 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
Jul 21 09:52:50.587333 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -110
Jul 21 09:52:50.587503 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0xe010003|0x0 failed: -19
Jul 21 09:52:50.587652 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -19
Jul 21 09:52:50.587835 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x13000003|0x1 failed: -19
Jul 21 09:52:50.587985 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to pause all pipelines
Jul 21 09:52:50.588129 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -19
Jul 21 09:52:50.588295 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x46000002|0x3 failed: -19
Jul 21 09:52:50.588442 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to unbind modules mixin.0.1:0 -> mixout.1.1:0
Jul 21 09:52:50.588598 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x12000000|0x0 failed: -19
Jul 21 09:52:50.588742 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to free pipeline widget pipeline.0
Jul 21 09:52:50.588884 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x12010000|0x0 failed: -19
Jul 21 09:52:50.589032 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to free pipeline widget pipeline.1
Jul 21 09:52:50.589176 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to free connected widgets
Jul 21 09:52:50.589346 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: sof_pcm_stream_free: sof_widget_list_free failed -19
Jul 21 09:52:50.589496 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
Jul 21 09:52:50.589899 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x13000003|0x1 failed: -19
Jul 21 09:52:50.590047 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to pause all pipelines
Jul 21 09:52:50.590190 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -19
Jul 21 09:52:50.590351 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x46010002|0x10003 failed: -19
Jul 21 09:52:50.590499 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to unbind modules mixin.20.1:0 -> mixout.21.1:0
Jul 21 09:52:50.590639 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x12020000|0x0 failed: -19
Jul 21 09:52:50.590778 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to free pipeline widget pipeline.20
Jul 21 09:52:50.590919 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x12030000|0x0 failed: -19
Jul 21 09:52:50.591069 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to free pipeline widget pipeline.21
Jul 21 09:52:50.591208 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to free connected widgets
Jul 21 09:52:50.591344 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: sof_pcm_stream_free: sof_widget_list_free failed -19
Jul 21 09:52:50.591481 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
Jul 21 09:52:50.591663 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0xe010002|0x0 failed: -19
Jul 21 09:52:50.591804 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -19
Jul 21 09:52:50.591965 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: sof_pcm_stream_free: pcm_ops hw_free failed -19
Jul 21 09:52:50.592127 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
Jul 21 09:52:50.592397 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to create module pipeline.0
Jul 21 09:52:50.592628 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to set up connected widgets
Jul 21 09:52:50.592779 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed widget list set up for pcm 0 dir 0
Jul 21 09:52:50.593003 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: set pcm hw_params after resume
Jul 21 09:52:50.593209 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
Jul 21 09:52:50.593352 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to create module pipeline.20
Jul 21 09:52:50.593461 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to set up connected widgets
Jul 21 09:52:50.593565 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed widget list set up for pcm 2 dir 0
Jul 21 09:52:50.593668 bean kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: error: set pcm hw_params after resume
....
````

Repeated messages in dmesg

````
[  510.927461]  Speaker: ASoC: error at __soc_pcm_prepare on Speaker: -19
[  510.927464]  Speaker: ASoC: error at dpcm_fe_dai_prepare on Speaker: -19
[  510.932642] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to create module pipeline.0
[  510.932645] sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to set up connected widgets
[  510.932647] sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed widget list set up for pcm 0 dir 0
[  510.932649] sof-audio-pci-intel-mtl 0000:00:1f.3: error: set pcm hw_params after resume
[  510.932650] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
[  510.932652]  Jack Out: ASoC: error at __soc_pcm_prepare on Jack Out: -19
[  510.932654]  Jack Out: ASoC: error at dpcm_fe_dai_prepare on Jack Out: -19
````

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

Recent fixes for xrun (pending_stop) caused a regression on xrun handling of ChainDMA by uncovering two bugs related to how the DMA Link ID is handled and causing firmware crash under special circumstances.
The bugs will result loosing the DMA Link ID for the stream which experienced an xrun.

The first patch is a fix for a code move, but the actual bug was introduced by the same commit as the second patch is fixing, we need to create a new patch out from the first one for kernel versions prior to 6.9.

Fixes: https://github.com/thesofproject/linux/issues/5116

### CODE REVIEW

**Comment by ujfalusi** [comment]
The patch which actually triggers the issue is new for 6.10:
`ebd3b3014eeb ("ASoC: SOF: pcm: reset all PCM sources in case of xruns")`

**Comment by ujfalusi** [comment]
to reproduce the issue (on soundwire device):
```
aplay -Dhw:0,0 -c2 -r48000 -fS16_LE /dev/zero -d 120 &
sleep 0.5; aplay -Dhw:0,2 -c2 -r48000 -fS16_LE /dev/zero -d 120 &
sleep 1; aplay -Dhw:0,5 -c8 -r48000 -fS32_LE /dev/zero -d 120 &
sleep 1.5; aplay -Dhw:0,6 -c8 -r48000 -fS32_LE /dev/zero -d 120 &
sleep 2; aplay -Dhw:0,7 -c8 -r48000 -fS32_LE /dev/zero -d 120 &
sleep 2.5; aplay -Dhw:0,31 -c2 -r48000 -fS16_LE /dev/zero -d 120 &
```
Kill the second HDMI playback:
```
pgrep -f "aplay -Dhw:0,6" | xargs kill -9
```
Start it again:
```
aplay -Dhw:0,6 -c8 -r48000 -fS32_LE /dev/zero -d 120
```
Press <`CTRL+z`> to freeze aplay, then type `fg` to bring it back. This will trigger an xrun.

Note: Likely only two aplay to HDMI is adequate.

File: sound/soc/sof/ipc4-topology.c [hunk 1]
```diff
@@ -1348,7 +1348,13 @@ static void sof_ipc4_unprepare_copier_module(struct snd_sof_widget *swidget)
...
 	if (WIDGET_IS_AIF(swidget->id) || swidget->id == snd_soc_dapm_buffer) {
 		if (pipeline->use_chain_dma) {
-			pipeline->msg.primary = 0;
+			/*
+			 * Preserve the DMA Link ID and clear other bits since
+			 * the DMA Link ID is only configured once during
+			 * dai_config, other fields are expected to be 0 for
+			 * re-configuration
+			 */
+			pipeline->msg.primary &= SOF_IPC4_GLB_CHAIN_DMA_LINK_ID_MASK;
```
Comment (plbossart) [inline sound/soc/sof/ipc4-topology.c]: is this one correct? It's the host-facing part, in theory this has nothing to do with the link DMA.

File: sound/soc/sof/ipc4-topology.c [hunk 2]
```diff
@@ -1358,7 +1364,13 @@ static void sof_ipc4_unprepare_copier_module(struct snd_sof_widget *swidget)
...
 
 		if (pipeline->use_chain_dma) {
-			pipeline->msg.primary = 0;
+			/*
+			 * Preserve the DMA Link ID and clear other bits since
+			 * the DMA Link ID is only configured once during
+			 * dai_config, other fields are expected to be 0 for
+			 * re-configuration
+			 */
+			pipeline->msg.primary &= SOF_IPC4_GLB_CHAIN_DMA_LINK_ID_MASK;
```
Comment (plbossart) [inline sound/soc/sof/ipc4-topology.c:1367]: this one looks correct.

**Review by plbossart — COMMENTED** [review]
Impressive fixes @ujfalusi 

I can't believe we've had this forever...

But one of the changes looks weird, can you take a look?

File: sound/soc/sof/ipc4-topology.c (hunk 1 above)
Comment (ujfalusi) [reply sound/soc/sof/ipc4-topology.c]: right, true, I'll drop this change

**Comment by ujfalusi** [comment]
Changes since v1:
- Drop the masking of DMA link ID on host side in patch 2

File: sound/soc/sof/ipc4-topology.c (hunk 1 above)
Comment (ujfalusi) [reply sound/soc/sof/ipc4-topology.c]: done

Comment (plbossart) [reply sound/soc/sof/ipc4-topology.c]: hmm, is this really dropping or should we used the dual macro SOF_IPC4_GLB_CHAIN_DMA_HOST_ID?

Comment (ujfalusi) [reply sound/soc/sof/ipc4-topology.c]: The HOST ID is reprogrammed in `sof_ipc4_prepare_copier_module()`
We need to preserve the LinkID, all others must be cleared.

**Review by bardliao — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

File: sound/soc/sof/ipc4-topology.c (hunk 1 above)
Comment (plbossart) [reply sound/soc/sof/ipc4-topology.c]: ok

**Review by plbossart — APPROVED** [review]
