### PR TITLE
ASoC: SOF: ipc3-topology: Fix pipeline tear down logic

### LINKED ISSUE #4807: [BUG] refactoring breaks sof-rt5682 audio on chromebook; successfully bisected
As described in the [kernel mailing list](https://lore.kernel.org/regressions/6013930.lOV4Wx5bFT@ayana/), commit [31ed8da](https://github.com/torvalds/linux/commit/31ed8da1c8e5e504710bb36863700e3389f8fc81) (ASoC: SOF: sof-audio:
Modify logic for enabling/disabling topology cores) seems to break audio on tigerlake chromebooks with soundcard sof-rt5682.

`alsa-info` and `dmesg` log pasted below (w/ dynamic debugging enabled), for both the working version and the broken version:
### revert 31ed8da, working
[alsa-info](http://alsa-project.org/db/?f=d570a71a13919eefb96e38f578c21adeaf75f442)
[full dmesg](https://github.com/thesofproject/linux/files/14176762/revert-31ed8da-dmesg.txt)

### vanilla linux-git kernel, no sound
[alsa-info](http://alsa-project.org/db/?f=d670ee203fcfb628469ba0e3f7f0d92abf3dd50c)
[full-dmesg](https://github.com/thesofproject/linux/files/14176758/vanilla-mainline-dmesg.txt)

### changes suggested in the email, still no sound
```
diff --git a/sound/soc/sof/sof-audio.c b/sound/soc/sof/sof-audio.c
index e693dcb475e4..a16dee8ee704 100644
--- a/sound/soc/sof/sof-audio.c
+++ b/sound/soc/sof/sof-audio.c
@@ -221,7 +221,7 @@ static int sof_widget_setup_unlocked(struct
snd_sof_dev *sdev,
 pipe_widget_free:
        if (swidget->id != snd_soc_dapm_scheduler) {
                sof_widget_free_unlocked(sdev, swidget->spipe->pipe_widget);
-       } else {
+       } else if (!use_count_decremented) {
                int j;

                /* decrement ref count for all cores that were updated previously */
```
[alsa-info](http://alsa-project.org/db/?f=98137efc49dc5f0bded8174dca39952719aa8653)
[full-dmesg](https://github.com/thesofproject/linux/files/14176744/patch-2-dmesg.txt)

---
Guess I'll also leave a link to the original issue here, maybe the ucm confs wasn't configured correctly either:
> https://github.com/WeirdTreeThing/chromebook-linux-audio/issues/70
https://github.com/WeirdTreeThing/chromebook-ucm-conf/tree/main/sof-rt5682

---
I don't really know much about the ALSA nor the linux sound subsystem, so apologize in advance if I did something wrong or if there're things can help further debugging, please let me know.

### PR DESCRIPTION
**Pull request by ranj063**
With the change in the widget free logic to power down the cores only when the scheduler widgets are freed, we need to ensure that the scheduler widget is freed only after all the widgets associated with the scheduler are freed. This is to ensure that the secondary core that the scheduler is scheduled to run on is kept powered on until all widgets that need them are in use. While this works well for dynamic pipelines, in the case of static pipelines the current logic does not take this into account and frees all widgets in the order they occur in the widget_list. So, modify this to ensure that the scheduler widgets are freed only after all other types of widgets in the widget_list are freed.

Fixes: 31ed8da1c8e5 ("ASoC: SOF: sof-audio: Modify logic for enabling/disabling topology cores")

Fixes https://github.com/thesofproject/linux/issues/4807

### CODE REVIEW

File: sound/soc/sof/ipc3-topology.c [hunk 1]
```diff
@@ -2435,11 +2424,49 @@ static int sof_ipc3_tear_down_all_pipelines(struct snd_sof_dev *sdev, bool verif
...
+	 * topology loading the sound card unavailable to open PCMs. Do not free the scheduler
+	 * widgets yet so that the secondary cores do not get powered down before all the widgets
+	 * associated with the widgets are freed.
+	 */
+	ret = sof_ipc3_free_widgets_in_list(sdev, false, &dyn_widgets, verify);
+	if (ret < 0)
+		return ret;
+
+	/* free all the scheduler widgets now */
+	ret = sof_ipc3_free_widgets_in_list(sdev, true, &dyn_widgets, verify);
```
Comment (plbossart) [inline sound/soc/sof/ipc3-topology.c:2466]: dyn_widgets is passed twice as a reference, can this lead to invalid configurations where the second call nukes the results of the first?

Or is this harmless and the result is the same for each call to sof_ipc3_free_widgets_in_list() ?

File: sound/soc/sof/ipc3-topology.c [hunk 2]
```diff
@@ -2435,11 +2424,49 @@ static int sof_ipc3_tear_down_all_pipelines(struct snd_sof_dev *sdev, bool verif
...
+	bool dyn_widgets = false;
+	int ret;
+
+	/*
+	 * This function is called during suspend and for one-time topology verification during
+	 * first boot. In both cases, there is no need to protect swidget->use_count and
+	 * sroute->setup because during suspend all running streams are suspended and during
+	 * topology loading the sound card unavailable to open PCMs. Do not free the scheduler
+	 * widgets yet so that the secondary cores do not get powered down before all the widgets
+	 * associated with the widgets are freed.
```
Comment (plbossart) [inline sound/soc/sof/ipc3-topology.c]: "the widgets associated with the widgets" ? There's probably a confusion here, no?

File: sound/soc/sof/ipc3-topology.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2466]: Yes, It is harmless. We only set it when it is true.

**Review by plbossart — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]
