### PR TITLE
ALSA: hda: intel-nhlt: Ignore vbps when looking for DMIC 32 bps format

### LINKED ISSUE #4689: [BUG][MTL] 24bit pch-dmic capture fails due to missing config in NHLT
With generic HDA topology and MTl platform, following is hit:

[   64.951286] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
[   64.951346] sof-audio-pci-intel-mtl 0000:00:1f.3: no matching blob for sample rate: 48000 sample width: 32 channels: 2
[   64.951348] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to prepare widget dai-copier.DMIC.dmic01.capture
[   64.951349] sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to prepare connected widgets

The NHLT table shows configurations for:
[  690.593197] sof-audio-pci-intel-mtl 0000:00:1f.3: Endpoint format: ch=2 fmt=16/16 rate=48000
[  690.593199] sof-audio-pci-intel-mtl 0000:00:1f.3: Endpoint format: ch=2 fmt=24/32 rate=48000

But kernel uses 32/32bit config in the NHLT query and does not find a matching config. The NHLT blob seems valid and 24/32 is a correct configuration, so SOF kernel driver should correctly handle this scenario (a limitation that follow deriving NHLT search params from FE PCM parameters).

### PR DESCRIPTION
**Pull request by ujfalusi**
When looking up DMIC blob from the NHLT table and the format is 32 bits,
ignore the vbps matching for 32 bps for DMIC since some NHLT table have
the vbps as 24, some have it as 32.
The DMIC hardware supports only one type of 32 bit sample size, which is
24 bit sampling on the MSB side and bits[1:0] is used for indicating the
channel number.

### CODE REVIEW

File: sound/hda/intel-nhlt.c [hunk 1]
```diff
@@ -310,6 +310,16 @@ intel_nhlt_get_endpoint_blob(struct device *dev, struct nhlt_acpi_table *nhlt,
 			cfg = nhlt_get_specific_cfg(dev, fmt, num_ch, rate, vbps, bps);
 			if (cfg)
 				return cfg;
+
+			/*
+			 * The DMIC bps=32 configuration is described in some
+			 * table with vbps=32 (the DMIC hardware is vbps=24)
+			 */
```
Comment (ranj063) [inline sound/hda/intel-nhlt.c]: @ujfalusi this patch feels a bit odd. May I suggest a different approach in the SOF driver by looking up both 32/32 and 24/32 when the bit-depth is 32 instead?

Comment (ujfalusi) [reply sound/hda/intel-nhlt.c]: @ranj063, I had that implementation first, but it felt out of place and hackish. The reason why I have moved it here is that it is the NHLT table itself which is incorrect and it is better to handle this in the NHLT code rather then in upper layer.

Comment (plbossart) [reply sound/hda/intel-nhlt.c]: no, the NHLT is not incorrect. It's really that vbs is irrelevant and should be ignored.

Comment (ujfalusi) [reply sound/hda/intel-nhlt.c]: OK, so rewording the comments and the commit message would suffice?
But then if the user asks for 32/32 then we need to look for 32/24 also, right? For DMIC, that is.
The NHLT core can do this:
if DMIC and bps == 32, set the vbps to 24 first, try to find the blob, if not found, look for it using vbps = 32.
Or pass  vbps = 0 to `nhlt_get_specific_cfg()` and if vbps is 0, do not try to match it, only look for bps match.

Comment (plbossart) [reply sound/hda/intel-nhlt.c]: > pass vbps = 0 to `nhlt_get_specific_cfg()` and if vbps is 0, do not try to match it, only look for bps match.

that would be my preference. vbps is a wildcard - ignored.

Comment (ranj063) [reply sound/hda/intel-nhlt.c]: me too!

Comment (kv2019i) [reply sound/hda/intel-nhlt.c]: I'm ok with this as long as we can limit this to DMIC in the caller (i.e. pass 0 to use a wildcard).

**Comment by ujfalusi** [comment]
Changes since v1:
- Drop the SOF patch
- Ignore vbps when looking for DMIC blob with 32bps

File: sound/hda/intel-nhlt.c [hunk 2]
```diff
@@ -298,7 +302,21 @@ intel_nhlt_get_endpoint_blob(struct device *dev, struct nhlt_acpi_table *nhlt,
...
+		 * size, which is 24 bit sampling on the MSB side and bits[1:0]
+		 * is used for indicating the channel number.
+		 */
+		dev_dbg(dev,
+			"  ch=%d fmt=%d rate=%d (vbps is ignored for DMIC 32bit format)\n",
+			num_ch, bps, rate);
+		vbps = 0;
+	} else {
+		dev_dbg(dev, "  ch=%d fmt=%d/%d rate=%d\n", num_ch, vbps, bps, rate);
+	}
```
Comment (plbossart) [inline sound/hda/intel-nhlt.c:325]: I would move this to the SOF driver.

Comment (ujfalusi) [reply sound/hda/intel-nhlt.c:325]: But this is a generic NHLT table issue, no? The exact same configuration might have 24/32 or 32/32 in the BIOS embedded table which cannot be guessed from upper layers.

**Review by kv2019i — DISMISSED** [review]
Code-wise ok. I have no favorites whether this should be on SOF or in intel-nhlt.c. I guess depends on wheter AVS et al assume this to be handled by intel-nhlt.c or not.

File: sound/hda/intel-nhlt.c (hunk 2 above)
Comment (plbossart) [reply sound/hda/intel-nhlt.c:325]: not following @ujfalusi, the caller can set vbs to zero and ask the intel-nhlt layer to give the first blob that matches bps.

Comment (ujfalusi) [reply sound/hda/intel-nhlt.c:325]: @plbossart, right, I have overlooked that. Do we really want that? I'm not sure.

**Comment by ujfalusi** [comment]
Changes since v2:
- Only ignore vbps in case of DMIC with bps==32, use a local flag to not change the handling of vbps from caller in other cases.

**Review by kv2019i — DISMISSED** [review]

File: sound/hda/intel-nhlt.c [hunk 3]
```diff
@@ -298,7 +303,21 @@ intel_nhlt_get_endpoint_blob(struct device *dev, struct nhlt_acpi_table *nhlt,
...
 	dev_dbg(dev, "  vbus_id=%d link_type=%d dir=%d, dev_type=%d\n",
 		bus_id, link_type, dir, dev_type);
-	dev_dbg(dev, "  ch=%d fmt=%d/%d rate=%d\n", num_ch, vbps, bps, rate);
+	if (link_type == NHLT_LINK_DMIC && bps == 32) {
+		/*
+		 * Ignore the vbps matching for 32 bps for DMIC since some NHLT
+		 * table have the vbps as 24, some have it as 32.
+		 * The DMIC hardware supports only one type of 32 bit sample
+		 * size, which is 24 bit sampling on the MSB side and bits[1:0]
+		 * is used for indicating the channel number.
```
Comment (ranj063) [inline sound/hda/intel-nhlt.c]: a couple of typos: some NHLT tables .... bits[1:0] are used....

**Review by ranj063 — DISMISSED** [review]
a couple of typos to fix before upstreaming

File: sound/hda/intel-nhlt.c (hunk 3 above)
Comment (plbossart) [reply sound/hda/intel-nhlt.c]: we should also say that the 32 bit case is harmless, otherwise the whole point of ignoring vbs could be seen as a regression or a miss.

Comment (ujfalusi) [reply sound/hda/intel-nhlt.c]: done, both

**Comment by ujfalusi** [comment]
Changes since v2:
- Reword the comment
- Make the ignoring vbps more strict and only do it when vbps is either 32 or 24

File: sound/hda/intel-nhlt.c [hunk 4]
```diff
@@ -255,8 +255,12 @@ nhlt_get_specific_cfg(struct device *dev, struct nhlt_fmt *fmt, u8 num_ch,
 		dev_dbg(dev, "Endpoint format: ch=%d fmt=%d/%d rate=%d\n",
 			wfmt->channels, _vbps, _bps, wfmt->samples_per_sec);
 
+		/*
+		 * When looking for exact match of configuration ignore the vbps
+		 * from NHTL table when vbps == 0 passed to the function
```
Comment (plbossart) [inline sound/hda/intel-nhlt.c]: the comment is no longer valid, 'vbs' is ignored when 'ignore_vbs' is set

Comment (ujfalusi) [reply sound/hda/intel-nhlt.c]: gash, just a sec.

**Comment by ujfalusi** [comment]
Changes since v3:
- Fix the stale comment in nhlt_get_specific_cfg()

**Review by plbossart — DISMISSED** [review]

File: sound/hda/intel-nhlt.c [hunk 5]
```diff
@@ -255,8 +255,12 @@ nhlt_get_specific_cfg(struct device *dev, struct nhlt_fmt *fmt, u8 num_ch,
 		dev_dbg(dev, "Endpoint format: ch=%d fmt=%d/%d rate=%d\n",
 			wfmt->channels, _vbps, _bps, wfmt->samples_per_sec);
 
+		/*
+		 * When looking for exact match of configuration ignore the vbps
+		 * from NHTL table when ignore_vbps is true
```
Comment (ranj063) [inline sound/hda/intel-nhlt.c]: Typo NHTL  🙂

**Review by ranj063 — DISMISSED** [review]

**Comment by ujfalusi** [comment]
Changers since v4:
- Fixed another typo in a comment (NHTL -> NHLT)

**Review by kv2019i — APPROVED** [review]

**Review by plbossart — APPROVED** [review]

**Review by ranj063 — APPROVED** [review]

**Comment by ujfalusi** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
SOFCI TEST

**Comment by ujfalusi** [comment]
Sorry, force pushed to kick a new CI run. The recent failures cannot be caused by this PR - they were not present in earlier versions and there were no change in functionality...
