### PR TITLE
PM resume fixes - Based on Takashi Iwai's feedback

### LINKED ISSUE #764: up2: pulseaudio playback fails after suspend/resume
PCM playback to headset fails to recover after suspend/resume on UP2 board. 

Commands:
sh1> /usr/bin/pulseaudio -vv
sh2> aplay -D default test.wav
sh3> sudo rtcwake -m mem -s 2

Notes:
- without pulseaudio, recovery from suspend/resume works
- @plbossart it seems at least the rewinds fails, this is probably what you referred to in a mail recently

Log:
I: [pulseaudio] protocol-native.c: Final latency 624.99 ms = 250.02 ms + 2*124.99 ms + 124.99 ms
D: [alsa-sink-Port5 (*)] alsa-sink.c: Latency set to 124.99ms
D: [alsa-sink-Port5 (*)] alsa-sink.c: hwbuf_unused=41284
D: [alsa-sink-Port5 (*)] alsa-sink.c: setting avail_min=15439
D: [alsa-sink-Port5 (*)] alsa-sink.c: Requesting rewind due to latency change.
D: [alsa-sink-Port5 (*)] alsa-sink.c: Requested to rewind 65280 bytes.
D: [alsa-sink-Port5 (*)] alsa-sink.c: Limited to 44864 bytes.
D: [alsa-sink-Port5 (*)] alsa-sink.c: before: 11216
D: [alsa-sink-Port5 (*)] alsa-sink.c: after: 11216
D: [alsa-sink-Port5 (*)] alsa-sink.c: Rewound 44864 bytes.
D: [alsa-sink-Port5 (*)] sink.c: Processing rewind...
D: [alsa-sink-Port5 (*)] sink-input.c: Have to rewind 44864 bytes on render memblockq.
D: [alsa-sink-Port5 (*)] source.c: Processing rewind...
D: [alsa-sink-Port5 (*)] protocol-native.c: Requesting rewind due to end of underrun.
D: [alsa-sink-Port5 (*)] alsa-sink.c: Requested to rewind 65280 bytes.
D: [alsa-sink-Port5 (*)] alsa-sink.c: Limited to 23548 bytes.
D: [alsa-sink-Port5 (*)] alsa-sink.c: before: 5887
D: [alsa-sink-Port5 (*)] alsa-sink.c: after: 5887
D: [alsa-sink-Port5 (*)] alsa-sink.c: Rewound 23548 bytes.
D: [alsa-sink-Port5 (*)] sink.c: Processing rewind...
D: [alsa-sink-Port5 (*)] sink-input.c: Have to rewind 23548 bytes on render memblockq.
D: [alsa-sink-Port5 (*)] source.c: Processing rewind...
I: [alsa-sink-Port5 (*)] alsa-sink.c: Scheduling delay of 464.48 ms > 18.38 ms, you might want to investigate this to improve latency...
D: [alsa-sink-Port5 (*)] alsa-util.c: Got POLLERR from ALSA
D: [alsa-sink-Port5 (*)] alsa-util.c: Got POLLOUT from ALSA
D: [alsa-sink-Port5 (*)] alsa-util.c: PCM state is SUSPENDED
I: [alsa-sink-Port5 (*)] alsa-sink.c: Starting playback.
I: [alsa-sink-Port5 (*)] (alsa-lib)pcm_hw.c: SNDRV_PCM_IOCTL_START failed (-77)
D: [alsa-sink-Port5 (*)] alsa-util.c: Got POLLERR from ALSA
D: [alsa-sink-Port5 (*)] alsa-util.c: Got POLLOUT from ALSA
D: [alsa-sink-Port5 (*)] alsa-util.c: PCM state is RUNNING
I: [alsa-sink-Port5 (*)] alsa-sink.c: Starting playback.
D: [alsa-sink-Port5 (*)] ratelimit.c: 215 events suppressed
D: [alsa-sink-Port5 (*)] alsa-sink.c: Cutting sleep time for the initial iterations by half.
D: [alsa-sink-Port5 (*)] alsa-util.c: Got POLLERR from ALSA
D: [alsa-sink-Port5 (*)] alsa-util.c: Got POLLOUT from ALSA
D: [alsa-sink-Port5 (*)] alsa-util.c: PCM state is RUNNING

### PR DESCRIPTION
**Pull request by ranj063**
This PR does the following:
1. dont advertise INFO_RESUME in the SOF driver
2. add pm prepare op for FE and BE dai links
3. clean up previous code for hw_params during pcm resume.
4. Fixes #764 

With above changes, link DMA resumes without errors but there is no sound. We need these 2 on top of this PR to fix the problem: 
1. https://github.com/thesofproject/linux/pull/783
2. https://github.com/thesofproject/linux/pull/725/commits/c3a5b119788b8a2739fa9d9d561f75e1206b0e0b

### CODE REVIEW

File: sound/soc/sof/intel/hda-dai.c [hunk 1]
```diff
@@ -165,6 +165,30 @@ static int hda_link_hw_params(struct snd_pcm_substream *substream,
...
+	int stream = substream->stream;
+
+	spcm = snd_sof_find_spcm_dai(sdev, rtd);
+	if (!spcm)
+		return -EINVAL;
+
+	/* do hw_params only if resuming from system suspend */
+	if (!spcm->hw_params_upon_resume[stream])
+		return 0;
+
```
Comment (libinyang) [inline sound/soc/sof/intel/hda-dai.c:184]: prepare should handle both resume and non-resume operation. This is what I talked with you last time I want to move some operations into prepare. Prepare is only for resume seems not be very good.

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c:184]: @libinyang im not sure what non-resume ops you're talking about. EVen if that is the case, its beyond the scope of this PR. Please propose you changes on top of this in a separate PR.

**Comment by plbossart** [comment]
I am uncomfortable with this, we've advertised support for RESUME for nearly 10 years, and I don't understand if we made a mistake all along, if we missed a key requirement and what userspace does when this flag is not set. Not sure what both tinyalsa and alsa-lib work the same way for example. Clearly both resume and HDMI/HDA fixes are not going to make the cut for v6.

**Comment by ranj063** [comment]
> I am uncomfortable with this, we've advertised support for RESUME for nearly 10 years, and I don't understand if we made a mistake all along, if we missed a key requirement and what userspace does when this flag is not set. Not sure what both tinyalsa and alsa-lib work the same way for example. Clearly both resume and HDMI/HDA fixes are not going to make the cut for v6.

@plbossart as Takashi explained in his comment. when this flag is not set, it forces the app to restart the stream from the last position which comes with the added benefit of calling the prepare op. I think you should reconsider your decision to not include this in v6. Without this change, we will never be able to fix the link DMA resume problem. It will require us to jump through a number of hoops requiring topology ABI changes.

**Comment by ranj063** [comment]
@plbossart I did a quick check with tinyplay on the up2 and regardless of whether I set the INFO_RESUME flag or not, the audio fails to resume with this error: "error playing sample".
Is there anything else I can check to convince you about this PR? I am quite convinced that this is the right option for SOF. But I'm willing to cover my bases if it makes you uncomfortable. So would appreciate some pointers in this regard.

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (libinyang) [reply sound/soc/sof/intel/hda-dai.c:184]: @ranj063 Prepare is not used only for resume. Actually we do some operations in other callbacks which should be in prepare. As prepare callback is added, we should make the prepare be more general. Otherwise, it's more like a workaround for resume.

**Comment by libinyang** [comment]
@ranj063 How did you test on tiny-alsa? I would like to test my patches on tiny-alsa too. I think tiny-alsa should work. Otherwise, do you think if there may be something wrong in our patches?

File: sound/soc/sof/pcm.c [hunk 2]
```diff
@@ -270,62 +272,18 @@ static int sof_pcm_trigger(struct snd_pcm_substream *substream, int cmd)
...
-			/* unset restore_stream */
-			spcm->restore_stream[substream->stream] = 0;
-		}
-
-		/* trigger stream */
 		stream.hdr.cmd |= SOF_IPC_STREAM_TRIG_START;
-
 		break;
 	case SNDRV_PCM_TRIGGER_SUSPEND:
-		/* fallthrough */
```
Comment (lyakh) [inline sound/soc/sof/pcm.c:314]: Is this intended? I personally don't mind, I'm not advocating for such comments, but some maintainers / reviewers want them...

File: sound/soc/sof/pcm.c [hunk 3]
```diff
@@ -394,6 +352,9 @@ static int sof_pcm_open(struct snd_pcm_substream *substream)
 	dev_dbg(sdev->dev, "pcm: open stream %d dir %d\n", spcm->pcm.pcm_id,
 		substream->stream);
 
+	/* Clear hw_params_upon_stream flag */
```
Comment (lyakh) [inline sound/soc/sof/pcm.c]: did you mean "upon_resume?"

**Comment by plbossart** [comment]
> @plbossart as Takashi explained in his comment. when this flag is not set, it forces the app to restart the stream from the last position which comes with the added benefit of calling the prepare op. I think you should reconsider your decision to not include this in v6. Without this change, we will never be able to fix the link DMA resume problem. It will require us to jump through a number of hoops requiring topology ABI changes.

Well, the first application I look at, PulseAudio, does not call snd_pcm_hw_params_can_resume(). Same for aplay, so I challenge the fact that the application is actually forced to do anything when the driver does not support INFO_RESUME. 
I will need to see code that actually mandates application to restart from a known position. I am probably missing something but it's certainly not obvious.

**Comment by plbossart** [comment]
> > @plbossart as Takashi explained in his comment. when this flag is not set, it forces the app to restart the stream from the last position which comes with the added benefit of calling the prepare op. I think you should reconsider your decision to not include this in v6. Without this change, we will never be able to fix the link DMA resume problem. It will require us to jump through a number of hoops requiring topology ABI changes.
> 
> Well, the first application I look at, PulseAudio, does not call snd_pcm_hw_params_can_resume(). Same for aplay, so I challenge the fact that the application is actually forced to do anything when the driver does not support INFO_RESUME.
> I will need to see code that actually mandates application to restart from a known position. I am probably missing something but it's certainly not obvious.

And at the kernel level the only thing I see is this:

````c
static int snd_pcm_pre_resume(struct snd_pcm_substream *substream, int state)
{
	struct snd_pcm_runtime *runtime = substream->runtime;
	if (!(runtime->info & SNDRV_PCM_INFO_RESUME))
		return -ENOSYS;
	runtime->trigger_master = substream;
	return 0;
}
````
And returning an error doesn't seem like the best way to handle application compatibility.

**Comment by ranj063** [comment]
> > @plbossart as Takashi explained in his comment. when this flag is not set, it forces the app to restart the stream from the last position which comes with the added benefit of calling the prepare op. I think you should reconsider your decision to not include this in v6. Without this change, we will never be able to fix the link DMA resume problem. It will require us to jump through a number of hoops requiring topology ABI changes.
> 
> Well, the first application I look at, PulseAudio, does not call snd_pcm_hw_params_can_resume(). Same for aplay, so I challenge the fact that the application is actually forced to do anything when the driver does not support INFO_RESUME.
> I will need to see code that actually mandates application to restart from a known position. I am probably missing something but it's certainly not obvious.

@plbossart I can certainly look into pulseaudio and get back with some info later today. But without INFO_RESUME, I did notice that pulseaudio is forced to restart the stream just like with aplay.

**Comment by kv2019i** [comment]
@plbossart  wrote:
> Well, the first application I look at, PulseAudio, does not call snd_pcm_hw_params_can_resume(). 
> Same for aplay, so I challenge the fact that the application is actually forced to do anything when the 
> driver does not support INFO_RESUME.

I took a survey of various common apps and couldn't find any that would use INFO_RESUME. 
But there are code paths in alsa-lib that do take note, e.g. snd_pcm_direct_resume() -> affects dmix/dsnoop and friends -> not widely used anymore I believe.

So the main mechanism is the one you quote above in ALSA core, which will force and error and for the application to restart from start. 

But definitely dropping INFO now seems to risk regressions as this will force many apps to take another code path in this case. Further it's problematic if old SST drivers behave differently from SOF. I'm not sure if all apps will recover gracefully (although they of course should but alas if it's not tested it's not tested). In the alsa-devel thread, Takashi indicated INFO flag is ok to keep if the general framework allows for it (even if not all platforms support it yet).

**Comment by plbossart** [comment]
> > > @plbossart as Takashi explained in his comment. when this flag is not set, it forces the app to restart the stream from the last position which comes with the added benefit of calling the prepare op. I think you should reconsider your decision to not include this in v6. Without this change, we will never be able to fix the link DMA resume problem. It will require us to jump through a number of hoops requiring topology ABI changes.
> > 
> > 
> > Well, the first application I look at, PulseAudio, does not call snd_pcm_hw_params_can_resume(). Same for aplay, so I challenge the fact that the application is actually forced to do anything when the driver does not support INFO_RESUME.
> > I will need to see code that actually mandates application to restart from a known position. I am probably missing something but it's certainly not obvious.
> 
> @plbossart I can certainly look into pulseaudio and get back with some info later today. But without INFO_RESUME, I did notice that pulseaudio is forced to restart the stream just like with aplay.

I have a nasty feeling that by returning an error on resume the application is forced to enter the same flow as e.g. for underflows. That's hardly what I call working-by-design.

File: sound/soc/sof/pcm.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/sof/pcm.c:314]: @lyakh yes I intentionally removed it as there was comment saying that this might be superfluous.

File: sound/soc/sof/pcm.c (hunk 3 above)
Comment (ranj063) [reply sound/soc/sof/pcm.c]: yes, thanks!

**Comment by ranj063** [comment]
@plbossart i made a small change to this PR. While going through the documentation, it was recommended that even if the driver doesnt support INFO_RESUME, it is better to implement the RESUME trigger for compatibility. So, with this change, the behaviour in the SOF driver would remain the same as before if the app does not restart as expected. 
That said, this will not fix our problem with link DMA resume though. If we choose to keep INFO_RESUME, we will have to change our trigger order.

**Comment by ranj063** [comment]
@plbossart @libinyang I just a brilliant realization that we can set the trigger order for our FE dai links in sof_link_load(). There is no need to change this in the topology at all. With this, I'm able to resume link DMA properly if INFO_RESUME is set.

So @plbossart we have 2 options now: 
1. not set INFO_RESUME in SOF: in this case we utilize prepare() op to set hw_params and both FE and BE params will be done before trigger.

2. set INFO_RESUME in SOF: in this case w need to change the trigger order in sof_link_load() to SND_SOC_DPCM_TRIGGER_POST. Then the BE hw_params will happen before FE hw_params and all will be good. 

Could you please let me know which one you prefer and I will change this PR accordingly.

**Comment by plbossart** [comment]
@ranj063 let's see Takashi's feedback, I want to check this point "While going through the documentation, it was recommended that even if the driver doesnt support INFO_RESUME, it is better to implement the RESUME trigger for compatibility.". If this is correct then we keep INFO_RESUME and use whatever fix you came up with.

**Comment by plbossart** [comment]
> @plbossart @libinyang I just a brilliant realization that we can set the trigger order for our FE dai links in sof_link_load(). There is no need to change this in the topology at all. With this, I'm able to resume link DMA properly if INFO_RESUME is set.
> 
> So @plbossart we have 2 options now:
> 
> 1. set INFO_RESUME in SOF: in this case we utilize prepare() op to set hw_params and both FE and BE params will be done before trigger.
> 2. not set INFO_RESUME in SOF: in this case w need to change the trigger order in sof_link_load() to SND_SOC_DPCM_TRIGGER_POST. Then the BE hw_params will happen before FE hw_params and all weill be good.

I can't figure out if there is a typo or a logical issue here. Did you invert set and not set by any chance?

**Comment by ranj063** [comment]
> I can't figure out if there is a typo or a logical issue here. Did you invert set and not set by any chance?

@plbossart yes, sorry about that. I've edited it now.

**Comment by ranj063** [comment]
> @ranj063 let's see Takashi's feedback, I want to check this point "While going through the documentation, it was recommended that even if the driver doesnt support INFO_RESUME, it is better to implement the RESUME trigger for compatibility.". If this is correct then we keep INFO_RESUME and use whatever fix you came up with.

@plbossart Here's the relevant text: 
"Even if the driver doesn’t support PM fully but partial suspend/resume is still possible, it’s still worthy to implement suspend/resume callbacks. In such a case, applications would reset the status by calling snd_pcm_prepare() and restart the stream appropriately. Hence, you can define suspend/resume callbacks below but don’t set SNDRV_PCM_INFO_RESUME info flag to the PCM.

Note that the trigger with SUSPEND can always be called when snd_pcm_suspend_all() is called, regardless of the SNDRV_PCM_INFO_RESUME flag. The RESUME flag affects only the behavior of snd_pcm_resume(). (Thus, in theory, SNDRV_PCM_TRIGGER_RESUME isn’t needed to be handled in the trigger callback when no SNDRV_PCM_INFO_RESUME flag is set. But, it’s better to keep it for compatibility reasons.)"

**Comment by plbossart** [comment]
> Thus, in theory, SNDRV_PCM_TRIGGER_RESUME isn’t needed to be handled in the trigger callback when no SNDRV_PCM_INFO_RESUME flag is set. But, it’s better to keep it for compatibility reasons.)"

I don't get the last part, what sort of compatibility are we talking about here: the trigger_resume() would never be used 
 ````c
res = ops->pre_action(substream, state);
	if (res < 0)
		return res;
	res = ops->do_action(substream, state);
````
````c
static const struct action_ops snd_pcm_action_resume = {
	.pre_action = snd_pcm_pre_resume,
	.do_action = snd_pcm_do_resume,
````
````c
static int snd_pcm_pre_resume(struct snd_pcm_substream *substream, int state)
{
	struct snd_pcm_runtime *runtime = substream->runtime;
	if (!(runtime->info & SNDRV_PCM_INFO_RESUME))
		return -ENOSYS;
````

**Comment by libinyang** [comment]
@kv2019i It seems there are some audio drivers drop INFO and they are working well. If we can follow the alsa requirement, I think SOF and cAVS should work. If it doesn't work, maybe it means our driver is something wrong?

I think the solution of dropping INFO flag may be a good solution. In this way, we can handle it in prepare(). But we do need to polish this patch to make it be more general, not only just for resume. Otherwise, it seems to be a workaround just for resume.

> But definitely dropping INFO now seems to risk regressions as this will force many apps to take another code path in this case. Further it's problematic if old SST drivers behave differently from SOF. I'm not sure if all apps will recover gracefully (although they of course should but alas if it's not tested it's not tested). In the alsa-devel thread, Takashi indicated INFO flag is ok to keep if the general framework allows for it (even if not all platforms support it yet).

**Comment by ranj063** [comment]
> I don't get the last part, what sort of compatibility are we talking about here: the trigger_resume() would never be used

@plbossart this would be a question for Takashi as this text is from his documentation. I agree that an app would never get to do_resume() in case of an error in pre_resume.

**Comment by plbossart** [comment]
Takashi has spoken, so the direction is:

not set INFO_RESUME in SOF: in this case w need to change the trigger order in sof_link_load() to SND_SOC_DPCM_TRIGGER_POST. Then the BE hw_params will happen before FE hw_params and all we'll be good.

**Comment by ranj063** [comment]
> Takashi has spoken, so the direction is:
> 
> not set INFO_RESUME in SOF: in this case w need to change the trigger order in sof_link_load() to SND_SOC_DPCM_TRIGGER_POST. Then the BE hw_params will happen before FE hw_params and all we'll be good.

@plbossart sorry I think you copied my text before I edited it for the mistake. The direction should be:

**do not set INFO_RESUME in SOF:** in this case we utilize prepare() op to set hw_params and both FE and BE params will be done before trigger.

**Comment by ranj063** [comment]
@plbossart this PR is updated now. The description is still accurate.

**Comment by plbossart** [comment]
@xiulipan same issue here. More than one hour to get a build result?

File: sound/soc/sof/pcm.c [hunk 4]
```diff
@@ -394,6 +359,9 @@ static int sof_pcm_open(struct snd_pcm_substream *substream)
 	dev_dbg(sdev->dev, "pcm: open stream %d dir %d\n", spcm->pcm.pcm_id,
 		substream->stream);
 
+	/* Clear hw_params_upon_resume flag */
+	spcm->hw_params_upon_resume[substream->stream] = 0;
```
Comment (plbossart) [inline sound/soc/sof/pcm.c:380]: the moral equivalent of .hw_params is .hw_free, wondering if we can have a case where the PCM is not closed but new parameters are passed?

File: sound/soc/sof/pcm.c [hunk 5]
```diff
@@ -168,9 +168,6 @@ static int sof_pcm_hw_params(struct snd_pcm_substream *substream,
 	/* save pcm hw_params */
 	memcpy(&spcm->params[substream->stream], params, sizeof(*params));
 
-	/* unset restore_stream */
-	spcm->restore_stream[substream->stream] = 0;
-
```
Comment (plbossart) [inline sound/soc/sof/pcm.c:173]: why not leave this here?

Comment (ranj063) [reply sound/soc/sof/pcm.c:173]: @plbossart I cant clear it here because I also use the same flag for setting the hw_params for the BE dai link which happens later. Clearing it here will prevent the BE hw_params from being setup after resuming.

The reason I reset the flag in open is because we can be sure that when the stream is opened, it will be followed by hw_params and prepare(). And, we do not want to repeat it in both these calls.

Comment (plbossart) [reply sound/soc/sof/pcm.c:173]: ok, I will have to trust you on this one.

File: sound/soc/sof/pcm.c (hunk 4 above)
Comment (ranj063) [reply sound/soc/sof/pcm.c:380]: @plbossart I could reset it in hw_free. let me run some tests with it before I make the change.

**Comment by plbossart** [comment]
same here, I'll merge after checking that the code compiles on my machine. I didn't know maintaining the code would be that painful :-1:
