### PR TITLE
Fix capture regression - Take 2

### LINKED ISSUE #4261: [BUG] I/O error with headset capture stop/start on MTL
**Describe the bug**
This is a driver regression on all MTL platforms. It's caused by https://github.com/thesofproject/linux/commit/658d0f0a1d4e
```
ASoC: SOF: pcm: Make hw_params reset conditional for IPC3
In the case of IPC4, since there is no PCM_PARAMS IPC to send the new
stream tag when restarting a stream without a hw_free, the original
stream tag needs to be preserved. So, add new a flag as part of struct
sof_ipc_pcm_ops, reset_hw_params_during_stop and set it only for IPC3.
This will ensure that the host DMA stream tag will not be given up during
the STOP trigger for IPC4.

```
I/O error occurs when testing signal stop/start on headset capture pipeline at the first round. 

**console log**
```
2023-03-16 11:08:12 UTC [REMOTE_INFO] ktime=1665 sof-test PID=11448: starting
2023-03-16 11:08:15 UTC [REMOTE_INFO] Starting /usr/local/bin/mtrace-reader.py
2023-03-16 11:08:15 UTC [REMOTE_INFO] /home/ubuntu/sof-test/test-case/check-signal-stop-start.sh will use topology /usr/lib/firmware/intel/sof-ace-tplg/sof-mtl-rt711-4ch.tplg to run the test case
2023-03-16 11:08:15 UTC [REMOTE_INFO] Pipeline list to ignore is specified, will ignore 'pcm=HDA Digital' in test case
2023-03-16 11:08:15 UTC [REMOTE_INFO] Run command to get pipeline parameters
2023-03-16 11:08:15 UTC [REMOTE_COMMAND] sof-tplgreader.py /usr/lib/firmware/intel/sof-ace-tplg/sof-mtl-rt711-4ch.tplg -f 'type:capture & ~pcm:HDMI' -b ' pcm:HDA Digital' -s 0 -e
2023-03-16 11:08:15 UTC [REMOTE_INFO] Testing: run stop/start test on PCM:Jack in,capture. Interval time: 0.5
2023-03-16 11:08:15 UTC [REMOTE_COMMAND] arecord -Dhw:0,1 -r 48000 -c 2 -f S16_LE /dev/null -q &
2023-03-16 11:08:16 UTC [REMOTE_INFO] Stop/start count: 1
overrun!!! (at least 125.449 ms long)
arecord: pcm_read:2221: read error: Input/output error
process: 11545, status: not found
2023-03-16 11:08:17 UTC [REMOTE_ERROR] arecord(11545) process is in an abnormal status
```

**mtrace**
```
[00:00:00.379,535] <inf> ipc: ipc_cmd: rx	: 0x13000004|0x1
[00:00:00.379,601] <inf> pipe: pipeline_trigger: pipe:1 0x0 pipe trigger cmd 7
[00:00:00.379,620] <inf> ll_schedule: zephyr_ll_task_schedule_common: task add 0xa0112ec0 0x201b0U priority 0 flags 0x0
[00:00:00.379,668] <inf> ll_schedule: zephyr_domain_register: zephyr_domain_register domain->type 1 domain->clk 3 domain->ticks_per_ms 38400 period 1000
[00:00:00.379,781] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.379,833] <inf> dai_comp: dai_capture_params: comp:0 0x40000 dai_capture_params() src_dev = 23 stream_id = 8 src_width = 4 dest_width = 4
[00:00:00.379,885] <inf> eq_iir: eq_iir_prepare: comp:0 0x100000 eq_iir_prepare(), source_format=2, sink_format=2
[00:00:00.379,903] <inf> eq_iir: eq_iir_init_coef: comp:0 0x100000 eq_iir_init_coef(): 1 responses, 2 channels, stream 2 channels
[00:00:00.379,918] <inf> eq_iir: eq_iir_init_coef: comp:0 0x100000 eq_iir_init_coef(), ch 0 is set to response 0
[00:00:00.379,933] <inf> eq_iir: eq_iir_init_coef: comp:0 0x100000 eq_iir_init_coef(), ch 1 is set to response 0
[00:00:00.379,988] <inf> pipe: pipeline_trigger: pipe:0 0x0 pipe trigger cmd 7
[00:00:00.380,006] <inf> ll_schedule: zephyr_ll_task_schedule_common: task add 0xa0113940 0x201b0U priority 0 flags 0x0
[00:00:00.380,766] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.380,826] <wrn> dai_comp: comp:0 0x40000 dai_copy(): nothing to copy
[00:00:00.381,760] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.381,778] <wrn> dai_comp: comp:0 0x40000 dai_copy(): nothing to copy
[00:00:00.382,796] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.382,816] <wrn> dai_comp: comp:0 0x40000 dai_copy(): nothing to copy
[00:00:00.383,810] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.383,830] <wrn> dai_comp: comp:0 0x40000 dai_copy(): nothing to copy
[00:00:00.384,751] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.384,776] <wrn> dai_comp: comp:0 0x40000 dai_copy(): nothing to copy
[00:00:00.385,751] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.385,771] <wrn> dai_comp: comp:0 0x40000 dai_copy(): nothing to copy
[00:00:00.386,751] <inf> host_comp: host_get_copy_bytes_normal: comp:1 0x40001 no bytes to copy, available bytes: 0, free_bytes: 768
[00:00:00.901,970] <inf> ipc: ipc_cmd: rx	: 0x13000003|0x1
```

**To Reproduce**
~/sof-test/test-case/check-signal-stop-start.sh -m capture -c 50

**Reproduction Rate**
100%

### PR DESCRIPTION
**Pull request by ranj063**
Fixes https://github.com/thesofproject/linux/issues/4261

### CODE REVIEW

File: sound/soc/sof/pcm.c [hunk 1]
```diff
@@ -211,16 +211,22 @@ static int sof_pcm_hw_free(struct snd_soc_component *component,
...
+			ret = pcm_ops->hw_free(component, substream);
+			if (ret < 0)
+				err = ret;
+		}
 
 		spcm->prepared[substream->stream] = false;
 	}
 
-	/* stop DMA */
+	/* reset DMA */
```
Comment (ujfalusi) [inline sound/soc/sof/pcm.c:229]: why the change in term?

**Review by ujfalusi — DISMISSED** [review]

File: sound/soc/sof/pcm.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/pcm.c:229]: because it was wrong in the first place. I have a stop DMA just a few lines about with my change where we actually stop the DMA

File: sound/soc/sof/ipc4-pcm.c [hunk 2]
```diff
@@ -836,5 +836,6 @@ const struct sof_ipc_pcm_ops ipc4_pcm_ops = {
 	.pcm_setup = sof_ipc4_pcm_setup,
 	.pcm_free = sof_ipc4_pcm_free,
 	.delay = sof_ipc4_pcm_delay,
-	.ipc_first_on_start = true
+	.ipc_first_on_start = true,
+	.delayed_platform_trigger = true,
```
Comment (plbossart) [inline sound/soc/sof/ipc4-pcm.c:840]: I find the commit message confusing:

````
In the case of IPC4, a pipeline is only paused during STOP/PAUSE/RELEASE
triggers and the FW keeps the host DMA running when a pipeline is
paused.
````
that's the start, so far so good.

````
With start/stop tests that do not involve a hw_free, the
pipeline switches between pause and release triggers.
````

You lost me already here. We're mixing start/stop and pause/release in the same sentence. I don't have enough understanding of what the tests do to figure out what you are trying to say.

````
 Therefore, the
host DMA must not be stopped and restarted during these tests.
````
which tests? Stop or pause/release? Both? There are too many unclear parts in the description.

````
Introduce a new flag in struct sof_ipc_pcm_ops, delayed_platform_trigger,
that will be used to ensure that the host DMA will not be stopped during
the STOP/PAUSE/RELEASE triggers.
````
I think you should clarify what states the DMA can have, I think it's pause/stop/reset, but it's not fully clear to me. @ujfalusi had a similar comment.

File: sound/soc/sof/pcm.c [hunk 3]
```diff
@@ -211,16 +211,22 @@ static int sof_pcm_hw_free(struct snd_soc_component *component,
...
 		spcm->pcm.pcm_id, substream->stream);
 
-	/* free PCM in the DSP */
-	if (pcm_ops && pcm_ops->hw_free && spcm->prepared[substream->stream]) {
-		ret = pcm_ops->hw_free(component, substream);
-		if (ret < 0)
-			err = ret;
+	if (spcm->prepared[substream->stream]) {
+		/* stop DMA first if needed */
+		if (pcm_ops && pcm_ops->delayed_platform_trigger)
```
Comment (plbossart) [inline sound/soc/sof/pcm.c:216]: remind me if it's possible NOT to have a pcm_ops?

File: sound/soc/sof/sof-audio.c [hunk 4]
```diff
@@ -805,6 +805,10 @@ int sof_pcm_stream_free(struct snd_sof_dev *sdev, struct snd_pcm_substream *subs
 	const struct sof_ipc_pcm_ops *pcm_ops = sof_ipc_get_ops(sdev, pcm);
 	int ret;
 
+	/* stop DMA first if needed */
+	if (pcm_ops && pcm_ops->delayed_platform_trigger)
+		snd_sof_pcm_platform_trigger(sdev, substream, SNDRV_PCM_TRIGGER_STOP);
```
Comment (plbossart) [inline sound/soc/sof/sof-audio.c]: I don't get this one, this looks exactly the same as in https://github.com/thesofproject/linux/pull/4268/commits/7c22b4fd5d467a1a75aace712a1e5f77eacadc89#diff-e9b5e07876285874ebc72f3a79a32cc92bb8f84a405c8819157d5c954fd0b97aR217, but this time this is not conditional on anything being prepared.

Is this intentional? If yes, a comment to understand the difference would help. This looks like a duplicate or redundant call for now.

**Review by plbossart — COMMENTED** [review]
No sustained objections, this makes sense, just a couple of comments on commit message and a  possible duplicate stop?

File: sound/soc/sof/pcm.c (hunk 3 above)
Comment (ranj063) [reply sound/soc/sof/pcm.c:216]: only for the DSP-less mode. I did not not use sdev->dsplessmod because those patches are not upstream and would block upstreaming this patch

File: sound/soc/sof/ipc4-pcm.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/sof/ipc4-pcm.c:840]: updated the commit message now @plbossart . Let me know what you think of it now

File: sound/soc/sof/sof-audio.c (hunk 4 above)
Comment (ranj063) [reply sound/soc/sof/sof-audio.c]: I've added the same check just to be consistent

File: sound/soc/sof/pcm.c (hunk 3 above)
Comment (plbossart) [reply sound/soc/sof/pcm.c:216]: oh I see, so !pcm_ops is equivalent to sdev->dspmode_selected then?

File: sound/soc/sof/ipc4-pcm.c (hunk 2 above)
Comment (plbossart) [reply sound/soc/sof/ipc4-pcm.c:840]: much better indeed, clear and concise. thanks @ranj063

**Review by plbossart — APPROVED** [review]
LGTM thanks @ranj063, I'll let you and @ujfalusi haggle now.

File: sound/soc/sof/pcm.c (hunk 3 above)
Comment (ranj063) [reply sound/soc/sof/pcm.c:216]: right exactly

Comment (plbossart) [reply sound/soc/sof/pcm.c:216]: so just to be clear, there's no case where the STOP will be triggered twice, right?

Comment (ranj063) [reply sound/soc/sof/pcm.c:216]: correct. There will be no case where we have duplicate stop triggers. We stop only once either during suspend or during hw_free

**Comment by ranj063** [comment]
SOFCI TEST

File: sound/soc/sof/sof-audio.h [hunk 5]
```diff
@@ -123,6 +127,7 @@ struct sof_ipc_pcm_ops {
 				   struct snd_pcm_substream *substream);
 	bool reset_hw_params_during_stop;
 	bool ipc_first_on_start;
+	bool delayed_platform_trigger;
```
Comment (ujfalusi) [inline sound/soc/sof/sof-audio.h:130]: I'm not too happy about the `delayed_platform_trigger` name as it should describe that if it is set we are not going to stop/trigger the platform at trigger time, we are only going to do a STOP on hw_free().

**Review by ujfalusi — APPROVED** [review]
Looks good, my only problem is with the flag name, but that can be a fixup when we figure out a better one.

**Comment by ujfalusi** [comment]
@ranj063, @plbossart, I'm going to merge this to be included in the next daily, we should have a fixup for the flag name, imho.

File: sound/soc/sof/sof-audio.h (hunk 5 above)
Comment (plbossart) [reply sound/soc/sof/sof-audio.h:130]: @ujfalusi @ranj063 yes the term 'delayed' is tainted in Linux. it hints at a delayed workqueue or something scheduled later, but that's not what is done at all.

stop_during_hwfree would be a more accurate description, no?
