### PR TITLE
remove hda checking from hda_dsp_remove and add it to hda_dsp_trace_init

### LINKED ISSUE #492: Upstream: fix smatch warnings for hdev usages
reported by Dan Carpenter/Smatch. Adding both @bardliao and @keyonjie since this may impact both in-flight fixes.

````
smatch warnings:
sound/soc/sof/intel/hda.c:579 hda_dsp_remove() error: we previously assumed 'hda' could be null (see line 559)
sound/soc/sof/intel/hda-trace.c:49 hda_dsp_trace_init() warn: variable dereferenced before check 'hda' (see line 46)
sound/soc/sof/intel/hda-trace.c:55 hda_dsp_trace_init() error: we previously assumed 'hda->dtrace_stream' could be null (see line 49)

# https://github.com/plbossart/sound/commit/f395dd273254cd66d28ae0b24e54ec0871d435ff
git remote add plbossart-sound https://github.com/plbossart/sound
git remote update plbossart-sound
git checkout f395dd273254cd66d28ae0b24e54ec0871d435ff
vim +/hda +579 sound/soc/sof/intel/hda.c

fa06c6de Bard liao            2018-11-23  558  
f395dd27 Bard liao            2018-12-19 @559  	if (hda && (!IS_ERR_OR_NULL(hda->dmic_dev)))
                                                    ^^^
Is this check required?

f395dd27 Bard liao            2018-12-19  560  		platform_device_unregister(hda->dmic_dev);
5d7f0748 Pierre-Louis Bossart 2018-10-31  561  
def495eb Liam Girdwood        2018-01-08  562  	/* disable DSP IRQ */
def495eb Liam Girdwood        2018-01-08  563  	snd_sof_dsp_update_bits(sdev, HDA_DSP_PP_BAR, SOF_HDA_REG_PP_PPCTL,
def495eb Liam Girdwood        2018-01-08  564  				SOF_HDA_PPCTL_PIE, 0);
def495eb Liam Girdwood        2018-01-08  565  
def495eb Liam Girdwood        2018-01-08  566  	/* disable CIE and GIE interrupts */
def495eb Liam Girdwood        2018-01-08  567  	snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR, SOF_HDA_INTCTL,
def495eb Liam Girdwood        2018-01-08  568  				SOF_HDA_INT_CTRL_EN | SOF_HDA_INT_GLOBAL_EN, 0);
def495eb Liam Girdwood        2018-01-08  569  
def495eb Liam Girdwood        2018-01-08  570  	/* disable cores */
def495eb Liam Girdwood        2018-01-08  571  	if (chip)
def495eb Liam Girdwood        2018-01-08  572  		hda_dsp_core_reset_power_down(sdev, chip->cores_mask);
def495eb Liam Girdwood        2018-01-08  573  
def495eb Liam Girdwood        2018-01-08  574  	/* disable DSP */
def495eb Liam Girdwood        2018-01-08  575  	snd_sof_dsp_update_bits(sdev, HDA_DSP_PP_BAR, SOF_HDA_REG_PP_PPCTL,
def495eb Liam Girdwood        2018-01-08  576  				SOF_HDA_PPCTL_GPROCEN, 0);
def495eb Liam Girdwood        2018-01-08  577  
def495eb Liam Girdwood        2018-01-08  578  	free_irq(sdev->ipc_irq, sdev);
f395dd27 Bard liao            2018-12-19 @579  	free_irq(hda->irq, bus);
                                                         ^^^^^^^^
Not checked here.

7032cf60 Libin Yang           2018-11-28  580  	if (sdev->msi_enabled)
def495eb Liam Girdwood        2018-01-08  581  		pci_free_irq_vectors(pci);
def495eb Liam Girdwood        2018-01-08  582  
def495eb Liam Girdwood        2018-01-08  583  	hda_dsp_stream_free(sdev);
fa06c6de Bard liao            2018-11-23  584  #if IS_ENABLED(CONFIG_SND_SOC_SOF_HDA)
fa06c6de Bard liao            2018-11-23  585  	snd_hdac_link_free_all(bus);
fa06c6de Bard liao            2018-11-23  586  #endif
893e7e85 Pierre-Louis Bossart 2018-11-12  587  
893e7e85 Pierre-Louis Bossart 2018-11-12  588  	iounmap(sdev->bar[HDA_DSP_BAR]);
893e7e85 Pierre-Louis Bossart 2018-11-12  589  	iounmap(bus->remap_addr);
893e7e85 Pierre-Louis Bossart 2018-11-12  590  
````

### PR DESCRIPTION
**Pull request by bardliao**
sdev->pdata->hw_pdata is assigned in hda_dsp_probe() so sdev->pdata->hw_pdata won't be null in hda_dsp_remove(). But hda could be null if hda_dsp_trace_init() is using in a wrong place.

Fix #492

### CODE REVIEW

File: sound/soc/sof/intel/hda-trace.c [hunk 1]
```diff
@@ -44,6 +44,11 @@ int hda_dsp_trace_init(struct snd_sof_dev *sdev, u32 *tag)
 		(struct sof_intel_hda_dev *)sdev->pdata->hw_pdata;
 	int ret;
 
+	if (!hda) {
+		dev_err(sdev->dev, "error: forget to assign hw_pdata?\n");
+		return -ENODEV;
+	}
+
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-trace.c]: I don't get why this is needed? the trace_init can only happen if the probe is successful, no?

Comment (bardliao) [reply sound/soc/sof/intel/hda-trace.c]: @plbossart Yes. But if we set ```.trace_init = hda_dsp_trace_init,``` in a specific ```struct snd_sof_dsp_ops``` with a .probe other than ```hda_dsp_probe```, it will cause problem. The situation should not happen, but it may happen by mistake.

Comment (ranj063) [reply sound/soc/sof/intel/hda-trace.c]: @bardliao can we not argue the same for the first commit?

Comment (bardliao) [reply sound/soc/sof/intel/hda-trace.c]: @ranj063 Sorry, I didn't get your question. I didn't argue with anything. I was trying to explain the second patch. But I don't insist on it. It's fine for me if the second patch is not applied. :)

Comment (ranj063) [reply sound/soc/sof/intel/hda-trace.c]: @bardliao sorry please dont take it personally. All i was trying to say was that the situation that you described with .probe being somthing other than hda_dsp_probe() could lead to the same problem in hda_dsp_remove() just like in hda_dsp_trace_init().

Comment (bardliao) [reply sound/soc/sof/intel/hda-trace.c]: @ranj063 Oh yes, indeed, there is also the same risk in the first patch.  However, in my opinion, the .probe and .remove ops are a pair. That's why I didn't think set .probe = hda_dsp_probe() but not .remove = hda_dsp_remove()  will happen in real world. But I agree with you, we should use the same criterion for both patches. Lets revert the second patch.
