### PR TITLE
ASoC: Intel: sof_sdw_rt_sdca_jack_common: ctx->headset_codec_dev = NULL

### LINKED ISSUE #4715: refcount_t: underflow when rmmod snd_sof_pci_intel_mtl with rt713 codec
**Describe the bug**
`refcount_t: underflow; use-after-free.` error will happen when we remove snd_sof_pci_intel_mtl.
It happens when `sdw_delete_slave` calls `device_unregister(dev);` to unregister the **rt713** device.

**To Reproduce**
sudo rmmod snd_sof_pci_intel_mtl

**Reproduction Rate**
100%

**Environment**

Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
Kernel: {[09138cb33833](https://github.com/thesofproject/linux/commit/09138cb33833a7dd08e8323e3d589eac5e03a65d)}
SOF: {[a6d65ee6dcad](https://github.com/thesofproject/sof/commit/a6d65ee6dcada94b77e8b40ded12fdf596001196)}
Name of the topology file
Topology: {sof-ace-tplg/sof-mtl-rt713-l0-rt1316-l12-rt1713-l3.tplg}
Name of the platform(s) on which the bug is observed.
Platform: {MTL SDW + rt713}

```
[ 1563.853429] ------------[ cut here ]------------
[ 1563.853432] refcount_t: underflow; use-after-free.
[ 1563.853453] WARNING: CPU: 10 PID: 2404 at lib/refcount.c:28 refcount_warn_saturate+0xbe/0x110
[ 1563.853464] Modules linked in: snd_soc_sof_sdw snd_soc_intel_hda_dsp_common snd_soc_intel_sof_maxim_common snd_sof_ipc_msg_injector snd_sof_probes snd_soc_rt712_sdca snd_soc_rt712_sdca_dmic snd_soc_rt1316_sdw regmap_sdw_mbq regmap_sdw snd_soc_dmic snd_sof_pci_intel_mtl(-) snd_sof_intel_hda_common soundwire_intel i915 soundwire_generic_allocation snd_sof_intel_hda_mlink soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp snd_sof snd_sof_utils snd_soc_hdac_hda snd_hda_ext_core snd_hda_codec_hdmi snd_soc_acpi_intel_match snd_soc_acpi snd_soc_core snd_compress soundwire_bus snd_hda_intel snd_intel_dspcfg snd_intel_sdw_acpi snd_hda_codec snd_hwdep snd_hda_core snd_pcm snd_seq_midi snd_seq_midi_event i2c_algo_bit iwlwifi drm_buddy snd_rawmidi snd_seq ttm drm_display_helper snd_seq_device processor_thermal_device_pci processor_thermal_device snd_timer drm_kms_helper mei_me snd processor_thermal_rfim processor_thermal_mbox processor_thermal_rapl wmi_bmof mei soundcore video intel_rapl_common intel_pmc_core
[ 1563.853547]  int3403_thermal x86_pkg_temp_thermal int3400_thermal int340x_thermal_zone intel_powerclamp acpi_thermal_rel wmi squashfs drm fuse efivarfs cdc_ether usbnet r8152 intel_ishtp_hid intel_lpss_pci xhci_pci intel_lpss psmouse idma64 intel_ish_ipc mfd_core xhci_hcd vmd intel_ishtp
[ 1563.853581] CPU: 10 PID: 2404 Comm: modprobe Tainted: G     U             6.6.0-rc1+ #1060
[ 1563.853585] Hardware name: Dell Inc. Precision 5690/, BIOS 0.3.15 11/16/2023
[ 1563.853587] RIP: 0010:refcount_warn_saturate+0xbe/0x110
[ 1563.853592] Code: 01 01 e8 e5 f7 8b ff 0f 0b c3 cc cc cc cc 80 3d fe 49 76 01 00 75 85 48 c7 c7 48 e0 5e 8b c6 05 ee 49 76 01 01 e8 c2 f7 8b ff <0f> 0b c3 cc cc cc cc 80 3d d9 49 76 01 00 0f 85 5e ff ff ff 48 c7
[ 1563.853596] RSP: 0018:ffffc90006217c38 EFLAGS: 00010282
[ 1563.853600] RAX: 0000000000000000 RBX: ffff888104453040 RCX: 0000000000000027
[ 1563.853602] RDX: ffff88847ebdc748 RSI: 0000000000000001 RDI: ffff88847ebdc740
[ 1563.853605] RBP: ffffc90006217c70 R08: ffffffff8b963328 R09: 00000000ffffdfff
[ 1563.853607] R10: ffffffff8b883340 R11: ffffffff8b933340 R12: ffff888104452868
[ 1563.853609] R13: 0000000000000246 R14: ffffffff8a5f48b0 R15: 0000000000000000
[ 1563.853611] FS:  00007efe48937c40(0000) GS:ffff88847ea00000(0000) knlGS:0000000000000000
[ 1563.853614] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1563.853616] CR2: 000000c00013b000 CR3: 000000015e0f2005 CR4: 0000000000f70ee0
[ 1563.853630] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 1563.853633] DR3: 0000000000000000 DR6: 00000000ffff07f0 DR7: 0000000000000400
[ 1563.853636] PKRU: 55555554
[ 1563.853638] Call Trace:
[ 1563.853642]  <TASK>
[ 1563.853647]  ? __warn+0x84/0x160
[ 1563.853653]  ? refcount_warn_saturate+0xbe/0x110
[ 1563.853660]  ? report_bug+0x199/0x1b0
[ 1563.853667]  ? handle_bug+0x3c/0x70
[ 1563.853672]  ? exc_invalid_op+0x18/0x70
[ 1563.853676]  ? asm_exc_invalid_op+0x1a/0x20
[ 1563.853681]  ? __pfx_klist_children_put+0x10/0x10
[ 1563.853692]  ? refcount_warn_saturate+0xbe/0x110
[ 1563.853698]  ? refcount_warn_saturate+0xbe/0x110
[ 1563.853703]  klist_next+0xbf/0x170
[ 1563.853710]  ? __pfx_sdw_delete_slave+0x10/0x10 [soundwire_bus]
[ 1563.853724]  device_for_each_child+0x43/0xa0
[ 1563.853732]  sdw_bus_master_delete+0x1e/0x70 [soundwire_bus]
[ 1563.853743]  auxiliary_bus_remove+0x1c/0x30
[ 1563.853749]  device_release_driver_internal+0x1a1/0x210
[ 1563.853756]  bus_remove_device+0xd4/0x140
[ 1563.853762]  device_del+0x158/0x3e0
[ 1563.853770]  sdw_intel_exit+0x28/0xb0 [soundwire_intel]
[ 1563.853783]  hda_dsp_remove+0x7c/0x180 [snd_sof_intel_hda_common]
[ 1563.853805]  snd_sof_device_remove+0x10c/0x140 [snd_sof]
[ 1563.853829]  sof_pci_remove+0x1e/0x50 [snd_sof_pci]
[ 1563.853837]  pci_device_remove+0x37/0xa0
[ 1563.853844]  device_release_driver_internal+0x1a1/0x210
[ 1563.853851]  driver_detach+0x4b/0x90
[ 1563.853855]  bus_remove_driver+0x70/0xf0
[ 1563.853860]  pci_unregister_driver+0x3f/0x90
[ 1563.853868]  __do_sys_delete_module+0x1a6/0x2a0
[ 1563.853878]  ? exit_to_user_mode_prepare+0x2f/0x110
[ 1563.853883]  do_syscall_64+0x3c/0x90
[ 1563.853888]  entry_SYSCALL_64_after_hwframe+0x6e/0xd8
[ 1563.853892] RIP: 0033:0x7efe48a5fcdb
[ 1563.853897] Code: 73 01 c3 48 8b 0d 55 21 0f 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa b8 b0 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 25 21 0f 00 f7 d8 64 89 01 48
[ 1563.853899] RSP: 002b:00007fffe9fa1df8 EFLAGS: 00000206 ORIG_RAX: 00000000000000b0
[ 1563.853904] RAX: ffffffffffffffda RBX: 000055f6ea489190 RCX: 00007efe48a5fcdb
[ 1563.853906] RDX: 0000000000000000 RSI: 0000000000000800 RDI: 000055f6ea4891f8
[ 1563.853908] RBP: 000055f6ea489190 R08: 0000000000000000 R09: 0000000000000000
[ 1563.853910] R10: 00007efe48af7ac0 R11: 0000000000000206 R12: 000055f6ea4891f8
[ 1563.853912] R13: 0000000000000000 R14: 000055f6ea4891f8 R15: 00007fffe9fa4128
[ 1563.853923]  </TASK>
[ 1563.853925] ---[ end trace 0000000000000000 ]---
```

Thanks @ujfalusi for reporting this issue.

### PR DESCRIPTION
**Pull request by bardliao**
sof_sdw_rt_sdca_jack_exit() are used by different codecs, and some of them use the same dai name.
For example, rt712 and rt713 both use "rt712-sdca-aif1" and sof_sdw_rt_sdca_jack_exit().
As a result, sof_sdw_rt_sdca_jack_exit() will be called twice by mc_dailink_exit_loop(). Set ctx->headset_codec_dev = NULL; after put_device(ctx->headset_codec_dev); to avoid ctx->headset_codec_dev being put twice.

Fixes: #4715

### CODE REVIEW

**Review by plbossart — DISMISSED** [review]
thanks @bardliao and @ujfalusi

**Comment by plbossart** [comment]
@bardliao do we need a Fixes tag?

**Comment by bardliao** [comment]
> @bardliao do we need a Fixes tag?

Yes, added.

**Comment by plbossart** [comment]
SOFCI TEST

File: sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c [hunk 1]
```diff
@@ -176,6 +176,7 @@ int sof_sdw_rt_sdca_jack_exit(struct snd_soc_card *card, struct snd_soc_dai_link
 
 	device_remove_software_node(ctx->headset_codec_dev);
 	put_device(ctx->headset_codec_dev);
+	ctx->headset_codec_dev = NULL;
```
Comment (ujfalusi) [inline sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c:179]: The reasoning described by the commit message does not sound encouraging,
The sof_sdw_rt_sdca_jack_init() is also called twice? The sdw_dev is the same or different for the calls?
If we have multiple jacks then we should not use a single pointer to store the two headset's information, no?

Comment (ujfalusi) [reply sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c:179]: You also need to check above:
```c
if (!ctx || !ctx->headset_codec_dev)
```
I have seen a NULL dereference crash.

Comment (bardliao) [reply sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c:179]: > The reasoning described by the commit message does not sound encouraging, The sof_sdw_rt_sdca_jack_init() is also called twice? The sdw_dev is the same or different for the calls? If we have multiple jacks then we should not use a single pointer to store the two headset's information, no?

No, `sof_sdw_rt_sdca_jack_init()` will not be called twice. `sof_sdw_rt_sdca_jack_init()` is called when a dai_link is created. [set_codec_init_func](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw.c#L1574). But we call `.exit` in [mc_dailink_exit_loop](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/sof_sdw.c#L1889), and check all .init in codec_info_list[].



> You also need to check above:
> 
> ```c
> if (!ctx || !ctx->headset_codec_dev)
> ```
> 
> I have seen a NULL dereference crash.

No, `ctx->headset_codec_dev` has been checked at the beginning of `sof_sdw_rt_sdca_jack_exit`().

Comment (ujfalusi) [reply sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c:179]: I see, the jack detection is only supported for playback?
If we have a line-in jack then we prevent the detection?
```c
diff --git a/sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c b/sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c
index e430be7681d2..d9c283829fc7 100644
--- a/sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c
+++ b/sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c
@@ -176,6 +176,7 @@ int sof_sdw_rt_sdca_jack_exit(struct snd_soc_card *card, struct snd_soc_dai_link
 
 	device_remove_software_node(ctx->headset_codec_dev);
 	put_device(ctx->headset_codec_dev);
+	ctx->headset_codec_dev = NULL;
 
 	return 0;
 }
@@ -191,10 +192,10 @@ int sof_sdw_rt_sdca_jack_init(struct snd_soc_card *card,
 	int ret;
 
 	/*
-	 * headset should be initialized once.
-	 * Do it with dai link for playback.
+	 * Jack detection should be only initialized once for headsets since
+	 * the playback/capture is sharing the same jack
 	 */
-	if (!playback)
+	if (ctx->headset_codec_dev)
 		return 0;
 
 	sdw_dev = bus_find_device_by_name(&sdw_bus_type, NULL, dai_links->codecs[0].name);

```

Comment (bardliao) [reply sound/soc/intel/boards/sof_sdw_rt_sdca_jack_common.c:179]: @ujfalusi Good suggestion. Updated now.

**Review by plbossart — APPROVED** [review]

**Review by ujfalusi — APPROVED** [review]
