### PR TITLE
ASoC: SOF: sof-client: fix build when only IPC4 is selected

### LINKED ISSUE #4581: Linux 6.5.2 does not compile snd-sof kernel module
I tried to compile linix 6.5.2 on my Thinkpad L460 and it failed with:

  MODPOST Module.symvers
ERROR: modpost: "sof_ipc3_do_rx_work" [sound/soc/sof/snd-sof.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:144: Module.symvers] Fehler 1
make[1]: *** [/usr/src/linux-6.5.2/Makefile:1984: modpost] Fehler 2
make: *** [Makefile:234: __sub-make] Fehler 2

The mentioned function has been added to sof-client.c with commit https://github.com/thesofproject/linux/commit/91774c9b5d56ab30c3b79773a34504354b440b5f / https://github.com/torvalds/linux/commit/70dad53ddff0778c4920a1ee9eb1cfea539d4e91

I don't see this compile error on my newer Intel NUC systems. As I'm having individual .configs related to the system hardware, I have seen that SND_SOC_SOF_IPC3 is not selected when SND_SOC_SOF_SKYLAKE is set, which itself selects SND_SOC_SOF_INTEL_SKL which itself selects only SND_SOC_SOF_INTEL_IPC4 with regardto IPC. 

The other two systems with CONFIG_SND_SOC_SOF_COFFEELAKE=m or CONFIG_SND_SOC_SOF_COMETLAKE=m select SND_SOC_SOF_INTEL_CNL which tiself selects SND_SOC_SOF_IPC3.

Manually adding select SND_SOC_SOF_IPC3 in sound/soc/intel/Kconfig in SND_SOC_SOF_INTEL_SKL fixes the compile error for me.

Maybe selecting SND_SOC_SOF_IPC3 was just missed for SND_SOC_SOF_INTEL_SKL in commits  https://github.com/thesofproject/linux/commit/b50c58edbe751e877e59792cc9665906738a53ef / https://github.com/torvalds/linux/commit/7ed1f83bb4f05fe460984ae49e98d1c1be38fb5f

Let me know if you need further information. I have attached my non working kernel .config. 

[config-6.5-HAUIHAU.txt](https://github.com/thesofproject/linux/files/12565871/config-6.5-HAUIHAU.txt)

### PR DESCRIPTION
**Pull request by plbossart**
When IPC3 is not selected, sof-client.c still makes a hard-coded reference to an IPC3-specific function:

ERROR: modpost: "sof_ipc3_do_rx_work" [sound/soc/sof/snd-sof.ko] undefined!

Fix by making the code conditional.

Closes: https://github.com/thesofproject/linux/issues/4581

### CODE REVIEW

**Comment by plbossart** [comment]
@ujfalusi @cujomalainey you guys are probably the most relevant reviewers for this

File: sound/soc/sof/sof-client.c [hunk 1]
```diff
@@ -305,7 +305,8 @@ EXPORT_SYMBOL_NS_GPL(sof_client_ipc_tx_message, SND_SOC_SOF_CLIENT);
 
 int sof_client_ipc_rx_message(struct sof_client_dev *cdev, void *ipc_msg, void *msg_buf)
 {
-	if (cdev->sdev->pdata->ipc_type == SOF_IPC_TYPE_3) {
+	if (IS_ENABLED(CONFIG_SND_SOC_SOF_IPC3) &&
```
Comment (ranj063) [inline sound/soc/sof/sof-client.c:308]: @plbossart does it make sense to allow the IPC3 type when the config is not selected in the first place?

**Review by cujomalainey — APPROVED** [review]

File: sound/soc/sof/sof-client.c (hunk 1 above)
Comment (plbossart) [reply sound/soc/sof/sof-client.c:308]: I am not sure I understand what you mean by "allow the IPC3 type" @ranj063. Maybe you are referring to another layer of errror control at a higher level, but for this PR the only goal is to fix the build. The IPC type is only known at run-time, different problem IMHO.

Comment (ujfalusi) [reply sound/soc/sof/sof-client.c:308]: Fixes: 70dad53ddff0 ("ASoC: SOF: Add IPC3 Kernel Injector")

I would use `#ifdef CONFIG_SND_SOC_SOF_IPC3` around this instead.

Comment (ujfalusi) [reply sound/soc/sof/sof-client.c:308]: Hrm, simple backport will not  work due to the IPC generic naming change, but I would do this for the rebase branch and re-arrange t he patches and fix them up

Comment (plbossart) [reply sound/soc/sof/sof-client.c:308]: Takashi and Mark have suggested multiple times to use IS_ENABLED since it makes the code look 'better', I only use the macros when the compiler is too stupid.

Comment (plbossart) [reply sound/soc/sof/sof-client.c:308]: > Hrm, simple backport will not work due to the IPC generic naming change, but I would do this for the rebase branch and re-arrange t he patches and fix them up

we can do this after merging and making sure that topic/sof-dev and topic/sof-dev-rebase are the same after the patch reshuffling.

Comment (ujfalusi) [reply sound/soc/sof/sof-client.c:308]: > Takashi and Mark have suggested multiple times to use IS_ENABLED since it makes the code look 'better', I only use the macros when the compiler is too stupid.

IS_ENABLED is good in case when a config option is three state, for bool it does not really matter.

But my question was more about the
```c
	if (IS_ENABLED(CONFIG_SND_SOC_SOF_IPC3) &&
	    cdev->sdev->pdata->ipc_type == SOF_IPC_TYPE_3) {
		struct sof_ipc_cmd_hdr *hdr = ipc_msg;

		if (hdr->size < sizeof(hdr)) {
			dev_err(cdev->sdev->dev, "The received message size is invalid\n");
			return -EINVAL;
		}

		sof_ipc3_do_rx_work(cdev->sdev, ipc_msg, msg_buf);
		return 0;
	}
```
vs
```c
#if IS_ENABLED(CONFIG_SND_SOC_SOF_IPC3)
	if (cdev->sdev->pdata->ipc_type == SOF_IPC_TYPE_3) {
		struct sof_ipc_cmd_hdr *hdr = ipc_msg;

		if (hdr->size < sizeof(hdr)) {
			dev_err(cdev->sdev->dev, "The received message size is invalid\n");
			return -EINVAL;
		}

		sof_ipc3_do_rx_work(cdev->sdev, ipc_msg, msg_buf);
		return 0;
	}
#endif
```

Probably the compiler will just drop the whole if statement if IPC3 is not enabled so the linker will not see the `sof_ipc3_do_rx_work()`?
fwiw, this will fail to compile:
```c
	if (0) {
		this will fail to compile
	}
```

**Review by ujfalusi — APPROVED** [review]
@plbossart, the patch works, no question about that, I just prefer the `#if` `#endif` way to align with the rest of the file.
If you prefer the current patch I will not block it, so approving it

**Review by ranj063 — APPROVED** [review]
