### PR TITLE
Fix SSP early bclk feature

### LINKED ISSUE #4009: Early bclk feature for SSP is broken
With the removal of widget setup in hda_ctrl_dai_widget_setup(), the DAI_CONFIG is never sent with the SOF_DAI_CONFIG_FLAGS_HW_PARAMS(). This means that the early bit clock feature will not be enabled by the firmware if it is requested in topology.

### PR DESCRIPTION
**Pull request by ranj063**
Fixes https://github.com/thesofproject/linux/issues/4009

### CODE REVIEW

File: sound/soc/sof/intel/hda-dai.c [hunk 1]
```diff
@@ -605,126 +605,13 @@ static const struct snd_soc_dai_ops ipc4_hda_dai_ops = {
...
-}
-
-static int ipc3_ssp_dai_trigger(struct snd_pcm_substream *substream,
-				int cmd, struct snd_soc_dai *dai)
-{
-	if (cmd != SNDRV_PCM_TRIGGER_SUSPEND)
-		return 0;
-
-	return ssp_dai_setup(substream, dai, false);
-}
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-dai.c:686]: how do we handle this TRIGGER_SUSPEND now? The introduction of setup/free at the FE level would not handle this case, would it? Additional explanations would be useful.

File: sound/soc/sof/intel/hda-dai.c [hunk 2]
```diff
@@ -605,126 +605,13 @@ static const struct snd_soc_dai_ops ipc4_hda_dai_ops = {
...
 {
 	int i;
 
 	switch (sdev->pdata->ipc_type) {
 	case SOF_IPC:
 		for (i = 0; i < ops->num_drv; i++) {
-			if (strstr(ops->drv[i].name, "SSP")) {
-				ops->drv[i].ops = &ipc3_ssp_dai_ops;
-				continue;
-			}
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-dai.c:727]: the commit message talks about IPC4, this is about IPC3. It's not that straightforward for the reviewer to figure out what the impact of the PR really is.

File: sound/soc/sof/intel/hda-dai.c [hunk 3]
```diff
@@ -605,126 +605,13 @@ static const struct snd_soc_dai_ops ipc4_hda_dai_ops = {
...
-				 bool setup)
-{
-	struct snd_soc_dapm_widget *w;
-
-	w = snd_soc_dai_get_widget(dai, substream->stream);
-
-	if (setup)
-		return hda_ctrl_dai_widget_setup(w, SOF_DAI_CONFIG_FLAGS_NONE, NULL);
-
-	return hda_ctrl_dai_widget_free(w, SOF_DAI_CONFIG_FLAGS_NONE, NULL);
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-dai.c:623]: what about SoundWire? We still have the callbacks that make use of hda_ctrl_dai_widget_setup/free

````c
static int sdw_params_stream(struct device *dev,
			     struct sdw_intel_stream_params_data *params_data)
{
	struct snd_soc_dai *d = params_data->dai;
	struct snd_sof_dai_config_data data;
	struct snd_soc_dapm_widget *w;

	w = snd_soc_dai_get_widget(d, params_data->stream);
	data.dai_index = (params_data->link_id << 8) | d->id;
	data.dai_data = params_data->alh_stream_id;

	return hda_ctrl_dai_widget_setup(w, SOF_DAI_CONFIG_FLAGS_NONE, &data);
}

static int sdw_free_stream(struct device *dev,
			   struct sdw_intel_stream_free_data *free_data)
{
	struct snd_soc_dai *d = free_data->dai;
	struct snd_sof_dai_config_data data;
	struct snd_soc_dapm_widget *w;

	w = snd_soc_dai_get_widget(d, free_data->stream);
	data.dai_index = (free_data->link_id << 8) | d->id;

	/* send invalid stream_id */
	data.dai_data = 0xFFFF;

	return hda_ctrl_dai_widget_free(w, SOF_DAI_CONFIG_FLAGS_NONE, &data);
}
````

How could this possibly be part of the FE configuration?

**Review by plbossart — COMMENTED** [review]
clearly lost in space on this one @ranj063  :-)

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c:686]: @plbossart all we do in the BE hw_params/free is set/unset the DAI CONFIG for the DAI widgets. We never set up or free the widgets themselves

File: sound/soc/sof/intel/hda-dai.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c:727]: the problem is when there was only IPC3, we used to set up the BE DAI widgets during BE hw_params and free them during BE hw_free. But with IPC4, we moved everything to the FE DAI hw_params/hw_free.

File: sound/soc/sof/intel/hda-dai.c (hunk 3 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c:623]: Soundwire is not different. We only set the DAI config . never set up/free anything. So the hda_ctrl_dai_widget_setup/free is a misnomer.

**Review by ranj063 — COMMENTED** [review]
@plbossart this change is going to be needed and probably a few more cleanups. But I want to get #3972 merged before I proceed with this PR

File: sound/soc/sof/intel/hda-dai.c (hunk 3 above)
Comment (plbossart) [reply sound/soc/sof/intel/hda-dai.c:623]: sure we do, we tell the firmware to use a DMA channel  in hw_params, release it in hw_free and have the trigger.

This is beyond confusing.

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c:623]: @plbossart thats the DAI config IPC. Its not widget setup/free

Comment (plbossart) [reply sound/soc/sof/intel/hda-dai.c:623]: I need a 'lost in space' emoji!

File: sound/soc/sof/intel/hda-dai.c (hunk 2 above)
Comment (plbossart) [reply sound/soc/sof/intel/hda-dai.c:727]: I tried to look at the code and couldn't figure out where in IPC4 we configure the BE DAI widgets when an FE DAI is configured, and I have a conceptual block on how this might work with mixers/copiers for multi-stream support. Can you point me to what changed @ranj063 ? Thanks!

**Review by bardliao — DISMISSED** [review]
The code change looks good to me. However, it would be easier for reviewer to understand the code if you say SOF_DAI_CONFIG_FLAGS_HW_PARAMS and SOF_DAI_CONFIG_FLAGS_HW_FREE were set in hda_ctrl_dai_widget_setup() and hda_ctrl_dai_widget_free() in commit message. Because it is not intuitive

**Comment by RanderWang** [comment]
> The code change looks good to me. However, it would be easier for reviewer to understand the code if you say SOF_DAI_CONFIG_FLAGS_HW_PARAMS and SOF_DAI_CONFIG_FLAGS_HW_FREE were set in hda_ctrl_dai_widget_setup() and hda_ctrl_dai_widget_free() in commit message. Because it is not intuitive

@ranj063 I see the HW_PARAM flag is used by widget_setup. Does it used by hda_ctrl_dai_widget_setup ?

**Comment by ranj063** [comment]
> > The code change looks good to me. However, it would be easier for reviewer to understand the code if you say SOF_DAI_CONFIG_FLAGS_HW_PARAMS and SOF_DAI_CONFIG_FLAGS_HW_FREE were set in hda_ctrl_dai_widget_setup() and hda_ctrl_dai_widget_free() in commit message. Because it is not intuitive
> 
> @ranj063 I see the HW_PARAM flag is used by widget_setup. Does it used by hda_ctrl_dai_widget_setup ?

@RanderWang yes, the HW_PARAMS flags is set in hda_ctrl_dai_widget_setup(). So the HW_PARAMS flag in sof_widget_setup() is only needed for widgets that do not have a BE DAI drv op for example SSP DAI widgets now with this PR

File: sound/soc/sof/ipc3-topology.c [hunk 4]
```diff
@@ -2089,7 +2089,11 @@ static int sof_ipc3_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
 		break;
 	}
 
-	config->flags = flags;
+	/* For DAI_CONFIG during hw_params, save the flags from the BE DAI hw_params */
+	if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS)
+		config->flags |= flags;
+	else
+		config->flags = flags;
```
Comment (plbossart) [inline sound/soc/sof/ipc3-topology.c:2115]: I don't understand what this is doing. This is mixing bit-wise operations in one case and not in the other, this is hard to review.

File: sound/soc/sof/sof-audio.c [hunk 5]
```diff
@@ -49,9 +49,27 @@ int sof_widget_free(struct snd_sof_dev *sdev, struct snd_sof_widget *swidget)
...
+	}
+
 	/* continue to disable core even if IPC fails */
-	if (tplg_ops && tplg_ops->widget_free)
-		err = tplg_ops->widget_free(sdev, swidget);
+	if (tplg_ops && tplg_ops->widget_free) {
+		ret = tplg_ops->widget_free(sdev, swidget);
+		if (ret < 0 && !err)
+			err = ret;
+	}
```
Comment (plbossart) [inline sound/soc/sof/sof-audio.c:72]: that seems to belong to a separate patch that fixes the error flow, I don't see how this is logically connected to the CONFIG_FLAGS?

**Review by plbossart — CHANGES_REQUESTED** [review]
looks mostly good @ranj063 , just two simple things that can be improved, see below.

File: sound/soc/sof/sof-audio.c (hunk 5 above)
Comment (ranj063) [reply sound/soc/sof/sof-audio.c:72]: @plbossart no. this change is because of the DAI_CONFIG IPC above. WIthout that widget_free was the first step. Now its the second step

Comment (plbossart) [reply sound/soc/sof/sof-audio.c:72]: ah yes, thanks for the explanations

File: sound/soc/sof/ipc3-topology.c (hunk 4 above)
Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2115]: @plbossart I've added some explanation in the comment above now. Please let me know if it makes better sense.

**Comment by ranj063** [comment]
> The code change looks good to me. However, it would be easier for reviewer to understand the code if you say SOF_DAI_CONFIG_FLAGS_HW_PARAMS and SOF_DAI_CONFIG_FLAGS_HW_FREE were set in hda_ctrl_dai_widget_setup() and hda_ctrl_dai_widget_free() in commit message. Because it is not intuitive

@bardliao I've added more comments in the dai_config for IPC3. Hopefully that makes the change more intuitive.

File: sound/soc/sof/ipc3-topology.c (hunk 4 above)
Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2115]: yes it's very useful. I didn't even remember we had quirks!

**Review by plbossart — APPROVED** [review]
Thanks for this PR @ranj063

**Review by RanderWang — APPROVED** [review]
LGTM

**Review by bardliao — APPROVED** [review]

File: sound/soc/sof/ipc3-topology.c [hunk 6]
```diff
@@ -2089,14 +2089,40 @@ static int sof_ipc3_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
...
+	 * SOF_DAI_CONFIG_FLAGS_PAUSE and contains no quirks
+	 * BE DAI hw_free: When invoked during the BE DAI hw_free, flags is set to
+	 * SOF_DAI_CONFIG_FLAGS_HW_FREE and contains no quirks
+	 * FE DAI hw_free: When invoked during the FE DAI hw_free, flags is set to
+	 * SOF_DAI_CONFIG_FLAGS_HW_FREE and contains no quirks
+	 *
+	 * The DAI_CONFIG IPC is sent to the DSP, only after the widget is set up during the FE
+	 * DAI hw_params. But since the BE DAI hw_params precedes the FE DAI hw_params, the quirks
+	 * need to be preserved when assigning the flags before sending the IPC.
+	 * For the case of PAUSE/HW_FREE, since there are no quirks, flags can be used as is.
```
Comment (ujfalusi) [inline sound/soc/sof/ipc3-topology.c:2109]: In other words: collect the quirk flags for hw_params to be sent as a single message during GFE's hw_params?

**Review by ujfalusi — APPROVED** [review]

File: sound/soc/sof/ipc3-topology.c (hunk 6 above)
Comment (plbossart) [reply sound/soc/sof/ipc3-topology.c:2109]: was this a question or a request for a change @ujfalusi ? Not getting the point at all.

Comment (ranj063) [reply sound/soc/sof/ipc3-topology.c:2109]: I think he's just trying to understand whats going on @plbossart and yes thats right @ujfalusi

**Comment by marc-hb** [comment]
This apparently caused kernel regression:
- #4039
