### PR TITLE
ASoC: SOF: pcm: Do not invoke sof_pcm_stream_free() during stop trigger

### LINKED ISSUE #6723: [BUG] I/O error with DMIC capture pause/release on MTL
**Describe the bug**
CI observed an Input/output error when check-pause-resume-capture-100  or check-signal-stop-start.sh on MTL platforms.

**To Reproduce**
```
TPLG=/lib/firmware/intel/sof-ace-tplg/sof-mtl-rt711-4ch.tplg MODEL=MTLP_RVP_SDW ~/sof-test/test-case/check-pause-resume.sh -c 100 -m capture
```

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: https://github.com/thesofproject/linux/commit/321028577de9
    * SOF: https://github.com/thesofproject/sof/commit/4a9a99aeb24a
2) Name of the topology file
    * Topology: sof-ace-tplg/sof-mtl-rt711-4ch.tplg, sof-ace-tplg/sof-hda-generic-4ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTLP_RVP_SDW, MTLP_RVP_HDA

**Screenshots or console output**

**console output**
```
=== PAUSE ===                                                            
(100/100) Wait for 121 ms before pause

(100/100) Wait for 181 ms before resume

declare -- cmd="journalctl_cmd --since=@1670281836"
2022-12-05 23:11:08 UTC [REMOTE_INFO] Entering expect script with:
      arecord   -D hw:0,10 -r 48000 -c 4 -f S32_LE -vv -i /dev/null -q
spawn arecord -D hw:0,10 -r 48000 -c 4 -f S32_LE -vv -i /dev/null -q
Hardware PCM card 0 'sof-soundwire' device 10 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 4
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 32
  buffer_size  : 4096
  period_size  : 1024
  period_time  : 21333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1024
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 4096
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0

#+                                                 | 00%
(1/100) Wait for 142 ms before pause
 
#+                                                 | 00%
=== PAUSE ===                                                            
(1/100) Wait for 107 ms before pause

(1/100) Wait for 104 ms before resume
                                                                           
 
#+                                                 | 00%
=== PAUSE ===                                                            
(2/100) Wait for 189 ms before pause

(2/100) Wait for 181 ms before resume
                                                                           
 arecord: pcm_read:2221: read error: Input/output error
2022-12-05 23:11:10 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2022-12-05 23:11:10 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-pause-resume.sh
```

[full console_log.txt](https://github.com/thesofproject/sof/files/10161836/console_log.txt)
[mtrace.txt](https://github.com/thesofproject/sof/files/10161834/mtrace.txt)
[dmesg.txt](https://github.com/thesofproject/sof/files/10161835/dmesg.txt)

### PR DESCRIPTION
**Pull request by ranj063**
Signal start/stop tests perform stream start/stop and restart without doing a hw_free. This means that the widget list associated with a stream is never freed after a stop. Change this to always free the widget list during stop so that the behaviour will be consistent with the regular PCM open/close.

Partially fixes https://github.com/thesofproject/sof/issues/6723 i.e.  the check-signal-stop-start-playback-50.sh and check-signal-stop-start-capture-50.sh cases for MTL Nocodec

### CODE REVIEW

**Comment by fredoh9** [comment]
I'm able to verify that this fixes check-signal-stop-start test for playback. looks very solid pass with this fix. tested with NOCODEC mode.

`TPLG=/lib/firmware/intel/sof-ace-tplg/sof-mtl-nocodec.tplg ~/sof-test/test-case/check-signal-stop-start.sh -c 10 -m playback`

However, same test for capture is still broken.

`TPLG=/lib/firmware/intel/sof-ace-tplg/sof-mtl-nocodec.tplg ~/sof-test/test-case/check-signal-stop-start.sh -c 10 -m capture`

**Comment by plbossart** [comment]
@ranj063 is this really a MTL problem or more general all IPC4 targets are broken for start/stop?

**Comment by ranj063** [comment]
> @ranj063 is this really a MTL problem or more general all IPC4 targets are broken for start/stop?

@plbossart TGL/ADL seem to be OK. I'm now wondering if they work only by accident

**Review by bardliao — DISMISSED** [review]
LGTM

File: sound/soc/sof/intel/hda-dai.c [hunk 1]
```diff
@@ -289,7 +289,6 @@ static int hda_dai_trigger(struct snd_pcm_substream *substream, int cmd, struct
 
 	switch (cmd) {
 	case SNDRV_PCM_TRIGGER_SUSPEND:
-	case SNDRV_PCM_TRIGGER_STOP:
 		ret = hda_link_dma_cleanup(substream, hext_stream, dai);
```
Comment (RanderWang) [inline sound/soc/sof/intel/hda-dai.c:292]: hda_link_dma_prepare is called by ASoC framework, not by widget prepare. If we don't clean up hda_link_dma, do we need to skip some hda_link_dma_prepare ?

Comment (RanderWang) [inline sound/soc/sof/intel/hda-dai.c:292]: hda_link_dma_prepare is called by ASoC framework, not by widget setup. If we don't clean up hda_link_dma, do we need to skip some hda_link_dma_prepare ?

File: sound/soc/sof/pcm.c [hunk 2]
```diff
@@ -281,7 +281,6 @@ static int sof_pcm_trigger(struct snd_soc_component *component,
 	struct snd_sof_dev *sdev = snd_soc_component_get_drvdata(component);
 	const struct sof_ipc_pcm_ops *pcm_ops = sof_ipc_get_ops(sdev, pcm);
 	struct snd_sof_pcm *spcm;
-	bool reset_hw_params = false;
```
Comment (ujfalusi) [inline sound/soc/sof/pcm.c]: The flag was added for a reason, at least the commit message was very specific on what this is suppose to handle:
04c8027764bc ("ASoC: SOF: reset DMA state in prepare")

It might lost it's purpose and relevance over time, but aren't we going to break something with this?

@kv2019i ?

Comment (ranj063) [reply sound/soc/sof/pcm.c]: @ujfalusi allot of has changed in terms of how we free the widgets with all.thenwork around ipc4. And if you think about it, platform_hw_params gets the stream tag and if with start/stop tests,.there's no setting up widgets again, we need preserve the original tag.

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (plbossart) [reply sound/soc/sof/intel/hda-dai.c:292]: not following @RanderWang 's question. Can you please elaborate?

File: sound/soc/sof/ipc3-pcm.c [hunk 3]
```diff
@@ -380,4 +380,5 @@ const struct sof_ipc_pcm_ops ipc3_pcm_ops = {
 	.hw_free = sof_ipc3_pcm_hw_free,
 	.trigger = sof_ipc3_pcm_trigger,
 	.dai_link_fixup = sof_ipc3_pcm_dai_link_fixup,
+	.reset_hw_params_during_stop = true,
```
Comment (plbossart) [inline sound/soc/sof/ipc3-pcm.c:383]: "This will ensure that the stream tag will not be given up during the
STOP trigger for IPC4."

We removed hda_link_dma_cleanup() in the previous patch, so not following why we still need to do this.

Is this needed maybe on the host side for e.g. nocodec cases?

**Review by plbossart — COMMENTED** [review]
Not following if the second patch is redundant or needed. Maybe a host- of link-dma difference between the two?

File: sound/soc/sof/ipc3-pcm.c (hunk 3 above)
Comment (ranj063) [reply sound/soc/sof/ipc3-pcm.c:383]: @plbossart why only for nocodec? we need to preserve the host DMA stream tag for all cases isnt it?

Comment (plbossart) [reply sound/soc/sof/ipc3-pcm.c:383]: What I meant is that for the link DMA, the first patch makes sure that the stream_tag is not released.

What I was asking if whether this second patch is targeting the host DMA, and you've answered to that effect in your comment above.

So my suggestion is to clarify that the second patch will only have effects on host DMAs.

Comment (ranj063) [reply sound/soc/sof/ipc3-pcm.c:383]: done

File: sound/soc/sof/intel/hda-dai.c
Comment (plbossart) [inline sound/soc/sof/intel/hda-dai.c:1]: commit message: repeated start...

**Review by plbossart — CHANGES_REQUESTED** [review]

**Review by plbossart — APPROVED** [review]
Thanks @ranj063

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (RanderWang) [reply sound/soc/sof/intel/hda-dai.c:292]: hda_link_dma_cleanup is not called by TRIGGER STOP now,  but where is hda_link_dma_prepare called ?  hda_link_dma_prepare is paired with hda_link_dma_cleanup, if we remove one hda_link_dma_cleanup, do we need to remove one hda_link_dma_prepare ? I found hda_link_dma_prepare is called by ASoC framework directly.

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c:292]: what do you mean by hda_link_dma_prepare? There is no such function? Anyway, if I can guess what you're asking, the stream tag is assigned in hda_link_hw_params() and with a repeated start, if the stream tag is not freed, prepare wouldnt really do anything, thus preserving the original stream tag for the start trigger

Comment (RanderWang) [reply sound/soc/sof/intel/hda-dai.c:292]: o, my code is out of date.  I can't find it after updating code

**Review by RanderWang — APPROVED** [review]

**Review by bardliao — APPROVED** [review]
