### PR TITLE
ASoC: SOF: Intel: hda-dai: Do not release the link DMA on STOP

### LINKED ISSUE #9695: [BUG] DSP Panic on Intel MTL
**Describe the bug**
DSP Panic seen and full freeze of the OS.

**To Reproduce**
Open pavucontrol mute/unmute microphone few times. Close pavucontrol. Wait for freeze.

**Reproduction Rate**
100%

**Expected behavior**
No DSP Panic.

**Impact**
Cannot use builtin microphone.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 6.12.1
    * SOF: sof-bin 2024.09.1
2) Name of the topology file
    * Topology: sof-hda-generic-2ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: Intel Meteor Lake Ultra 9 185H, Asus Zenbook 14 OLED UX3405M, Alpine Linux

**Screenshots or console output**
```
[  186.448058] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  186.448069] sof-audio-pci-intel-mtl 0000:00:1f.3: DSP panic!
[  186.448071] sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
[  186.448078] sof-audio-pci-intel-mtl 0000:00:1f.3: 0x50000005: module: ROM_EXT, state: FW_ENTERED, running
[  186.448083] sof-audio-pci-intel-mtl 0000:00:1f.3: Firmware state: 0x5, status/error code: 0x0
[  186.448116] sof-audio-pci-intel-mtl 0000:00:1f.3: Unknown toolchain is used
[  186.448120] sof-audio-pci-intel-mtl 0000:00:1f.3: error: DSP Firmware Oops
[  186.448121] sof-audio-pci-intel-mtl 0000:00:1f.3: error: Exception Cause: AllocaCause, MOVSP instruction, if caller’s registers are not in the register file
[  186.448123] sof-audio-pci-intel-mtl 0000:00:1f.3: EXCCAUSE 0x00000005 EXCVADDR 0x00000000 PS       0x00060d20 SAR     0x0000000c
[  186.448126] sof-audio-pci-intel-mtl 0000:00:1f.3: EPC1     0xa007626d EPC2     0x00000000 EPC3     0x00000000 EPC4    0x00000000
[  186.448128] sof-audio-pci-intel-mtl 0000:00:1f.3: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[  186.448129] sof-audio-pci-intel-mtl 0000:00:1f.3: EPS2     0x00000000 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
[  186.448131] sof-audio-pci-intel-mtl 0000:00:1f.3: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x00000000
[  186.448132] sof-audio-pci-intel-mtl 0000:00:1f.3: stack dump from 0x00000000
[  186.448134] sof-audio-pci-intel-mtl 0000:00:1f.3: AR registers:
[  186.448136] sof-audio-pci-intel-mtl 0000:00:1f.3: 0x0: a004ed15 a0111680 00000000 4015a7c0
[  186.448138] sof-audio-pci-intel-mtl 0000:00:1f.3: 0x10: a0166b00 00000018 401492b0 a0111680
[  186.448140] sof-audio-pci-intel-mtl 0000:00:1f.3: 0x20: a005fb41 a0111640 401492b0 a006506c
[  186.448142] sof-audio-pci-intel-mtl 0000:00:1f.3: 0x30: a005fb41 a0111640 401492b0 a006506c
[  186.448144] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[  186.946817] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0xe030001|0x300
[  186.946837] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[  186.946851] sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x8e030001|0x300|0x0, target: 0x1b0a0000|0x0|0x0, ctl: 0x3
[  186.946856] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[  186.946859] sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[  186.946866] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -110
[  186.946878]  HDMI2: ASoC: trigger FE cmd: 1 failed: -110
[  186.946897] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0xe010001|0x0 failed: -19
[  186.946902] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -19
[  186.946904]  HDMI2: ASoC: trigger FE cmd: 0 failed: -19
[  186.947086] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x13000003|0x1 failed: -19
[  186.947091] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to pause all pipelines
[  186.947093] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -19
[  186.947096]  DMIC Raw: ASoC: trigger FE cmd: 0 failed: -19
[  186.947198] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x46060004|0x19 failed: -19
[  186.947203] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to unbind modules module-copier.12.2:0 -> tdfb.11.1:0
[  186.947208] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x12040000|0x0 failed: -19
[  186.947212] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to free pipeline widget pipeline.12
[  186.947219] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x12050000|0x0 failed: -19
[  186.947222] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to free pipeline widget pipeline.11
[  186.947225] sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to free connected widgets
[  186.947233] sof-audio-pci-intel-mtl 0000:00:1f.3: sof_pcm_stream_free: sof_widget_list_free failed -19
[  186.947236] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
[  186.947240]  DMIC Raw: ASoC: error at __soc_pcm_prepare on DMIC Raw: -19
[  186.947243]  DMIC Raw: ASoC: error at dpcm_fe_dai_prepare on DMIC Raw: -19
[  186.947344] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc4_tx_msg_unlocked: ipc message send for 0x13020003|0x0 failed: -19
[  186.947348] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_dai_trigger on Analog CPU DAI: -19
[  186.947354]  HDA Analog: ASoC: error at dpcm_be_dai_trigger on HDA Analog: -19
[  186.947357]  HDA Analog: ASoC: trigger FE cmd: 0 failed: -19
```

Full dmesg in attachment.
[dmesg.txt](https://github.com/user-attachments/files/17959577/dmesg.txt)

### PR DESCRIPTION
**Pull request by ujfalusi**
The linkDMA should not be released on stop trigger since a stream re-start
might happen without closing of the stream. This leaves a short time for
other streams to 'steal' the linkDMA since it has been released.

This issue is not easy to reproduce under normal conditions as usually
after stop the stream is closed, or the same stream is restarted, but if
another stream got in between the stop and start, like this:
aplay -Dhw:0,3 -c2 -r48000 -fS32_LE /dev/zero -d 120
CTRL+z
aplay -Dhw:0,0 -c2 -r48000 -fS32_LE /dev/zero -d 120

then the link DMA channels will be mixed up, resulting firmware error or
crash.

Fixes: ab5593793e90 ("ASoC: SOF: Intel: hda: Always clean up link DMA during stop")
Closes: https://github.com/thesofproject/sof/issues/9695

### CODE REVIEW

File: sound/soc/sof/intel/hda-dai.c [hunk 1]
```diff
@@ -309,6 +324,18 @@ static int __maybe_unused hda_dai_trigger(struct snd_pcm_substream *substream, i
...
 			return ret;
 		}
+
+		/*
+		 * With IPC4 the pipelines (including the dai widget)) are not
+		 * freed up on stop/suspend.
+		 * If the stream is re-started after stop instead of closing it
+		 * then we need to keep the link DMA reserved.
+		 */
+		if (sdev->pdata->ipc_type == SOF_IPC_TYPE_4) {
```
Comment (ujfalusi) [inline sound/soc/sof/intel/hda-dai.c]: this likely need to be changed to:
```c
		if (cmd == SNDRV_PCM_TRIGGER_STOP &&
		    sdev->pdata->ipc_type == SOF_IPC_TYPE_4) {
```

**Review by bardliao — DISMISSED** [review]

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: @ujfalusi why not just remove the call for cleanup then? What is the idea behind cleaning up the DMA and reclaiming it?

Comment (lgirdwood) [reply sound/soc/sof/intel/hda-dai.c]: yeah - should we not just give up the link DMA ID in close() ?

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: Ahh I see the problem. Maybe we only need to clear the stream ID for stop without giving up the link DMA?

Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dai.c]: @ranj063, we need to reset the linkDMA, that is the only way to reset it's pointers and this is needed to fix the random metallic noise issue.
The firmware for IPC4 expects the linkDMA to be reset but _not_ released, the same channel must remain to be used if we have a start after the stop.
The firmware keeps it's side of the DMA channel on stop, we need to do the same on the host side.

**Comment by ujfalusi** [comment]
Changes since v1:
- only reclaim the LinkDMA channel on stop.

**Comment by ujfalusi** [comment]
The -fanalyzer gets it completely wrong: `hda_link_dma_setup()` is only called from two function and the call location is after a check for ops == NULL, in `hda_link_dma_setup()` ops cannot be NULL as the caller functions would have failed earlier.

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (lgirdwood) [reply sound/soc/sof/intel/hda-dai.c]: @ujfalusi I assume your above description about how the link DMA is handled between driver/FW is commented inline ?

File: sound/soc/sof/intel/hda-dai.c [hunk 2]
```diff
@@ -309,6 +324,19 @@ static int __maybe_unused hda_dai_trigger(struct snd_pcm_substream *substream, i
 			dev_err(sdev->dev, "%s: failed to clean up link DMA\n", __func__);
 			return ret;
 		}
+
+		/*
+		 * With IPC4 the pipelines (including the dai widget)) are not
+		 * freed up on stop/suspend.
+		 * If the stream is re-started after stop instead of closing it
+		 * then we need to keep the link DMA reserved.
+		 */
```
Comment (lgirdwood) [inline sound/soc/sof/intel/hda-dai.c]: It would be worth commenting the link DMA flow in a bit more detail since this is complex (if not already detailed in code).

**Comment by ujfalusi** [comment]
Changes since v2:
- Update comment
- Add unlikely NULL check for ops to please static analyzer

File: sound/soc/sof/intel/hda-dai.c [hunk 3]
```diff
@@ -309,6 +331,23 @@ static int __maybe_unused hda_dai_trigger(struct snd_pcm_substream *substream, i
 			dev_err(sdev->dev, "%s: failed to clean up link DMA\n", __func__);
 			return ret;
 		}
+
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda-dai.c]: I wonder @ranj063 @ujfalusi if we should modify the logic in https://github.com/thesofproject/linux/commit/ab5593793e9088abcddce30ba8e376e31b7285fd and delay the hda_link_dma_cleanup() on PCM_TRIGGER_STOP. At this point, FW pipeline is put to PAUSED state so it is still hanging on to the link DMA channel (see annotated log in https://github.com/thesofproject/linux/issues/5198#issuecomment-2388354589 ). 

This now works in the original case (same stream restarted later with a new prepare), but indeed if another stream is allocated on host side (like the bug this PR is address), the link DMA channel is allocated to other purposes and the flow won't work anymore.

So could this be delayed to either close() or new prepare() (whichever comes first). For suspend this needs to be immediate.

File: sound/soc/sof/intel/hda-dai.c [hunk 4]
```diff
@@ -309,6 +331,23 @@ static int __maybe_unused hda_dai_trigger(struct snd_pcm_substream *substream, i
...
+		 *
+		 * If the stream is closed the linkDMA is going to be cleaned up
+		 * in via hda_dai_hw_free()
+		 */
+		if (cmd == SNDRV_PCM_TRIGGER_STOP &&
+		    sdev->pdata->ipc_type == SOF_IPC_TYPE_4) {
+			hext_stream = hda_link_dma_setup(sdev, substream, dai);
+			if (IS_ERR(hext_stream))
+				return PTR_ERR(hext_stream);
+		}
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda-dai.c]: OTOH, this does seem correct and should work in all cases. It just looks a bit weird to first clean and then immediately setup again.

**Review by kv2019i — COMMENTED** [review]
A cautious +1 on this. The need to coordinate 1) host-side programming of the link DMA, with 2) IPCs sent to FW, is just complex. A few comments inline.

File: sound/soc/sof/intel/hda-dai.c (hunk 3 above)
Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dai.c]: It was delayed before ab5593793e90 and we needed to move it ahead to fix metallic noise (on restart w/o stop) and the explosion of the delay reporting.

Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dai.c]: right, you mean the hda_link_dma_cleanup() ? I think we have tried that but it was causing other issues.

File: sound/soc/sof/intel/hda-dai.c (hunk 4 above)
Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dai.c]: we could add a flag parameter for hda_link_dma_cleanup() (reclaim_channel?) and hide it there? I'm not sure if that is better or worse

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: @ujfalusi what I was asking was if it is enough if we do just 		snd_hdac_ext_bus_link_clear_stream_id(hlink, stream_tag); after clearing the RUN bit during stop?

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: @ujfalusi do you think this will work?
```
diff --git a/sound/soc/sof/intel/hda-dai.c b/sound/soc/sof/intel/hda-dai.c
index f5f2f832d117..e14647e8fd16 100644
--- a/sound/soc/sof/intel/hda-dai.c
+++ b/sound/soc/sof/intel/hda-dai.c
@@ -320,10 +320,22 @@ static int __maybe_unused hda_dai_trigger(struct snd_pcm_substream *substream, i
 
        switch (cmd) {
        case SNDRV_PCM_TRIGGER_STOP:
-               ret = hda_link_dma_cleanup(substream, hext_stream, dai);
-               if (ret < 0) {
-                       dev_err(sdev->dev, "%s: failed to clean up link DMA\n", __func__);
-                       return ret;
+               /* Clear the stream ID in the case of playback without giving up the link DMA ID */
+               if (substream->stream == SNDRV_PCM_STREAM_PLAYBACK) {
+                       struct hdac_ext_stream *hext_stream;
+                       struct hdac_ext_link *hlink;
+                       int stream_tag;
+
+                       hlink = ops->get_hlink(sdev, substream);
+                       if (!hlink)
+                               return -EINVAL;
+
+                       hext_stream = ops->get_hext_stream(sdev, dai, substream);
+                       if (!hext_stream)
+                               return -EINVAL;
+
+                       stream_tag = hdac_stream(hext_stream)->stream_tag;
+                       snd_hdac_ext_bus_link_clear_stream_id(hlink, stream_tag);
                }
                break;
        case SNDRV_PCM_TRIGGER_SUSPEND:
@@ -359,7 +371,11 @@ static int hda_dai_prepare(struct snd_pcm_substream *substream, struct snd_soc_d
        struct snd_soc_dapm_widget *w = snd_soc_dai_get_widget(dai, substream->stream);
        struct snd_sof_widget *swidget = w->dobj.private;
        struct snd_sof_dev *sdev = widget_to_sdev(w);
+       struct hdac_ext_stream *hext_stream;
+       struct hdac_stream *hstream;
+       struct hdac_ext_link *hlink;
        int stream = substream->stream;
+       int stream_tag;
        int ret;
 
        if (!ops) {
@@ -378,6 +394,17 @@ static int hda_dai_prepare(struct snd_pcm_substream *substream, struct snd_soc_d
        if (ret < 0)
                return ret;
 
+       hlink = ops->get_hlink(sdev, substream);
+       if (!hlink)
+               return -EINVAL;
+
+       hext_stream = ops->get_hext_stream(sdev, dai, substream);
+
+       hstream = &hext_stream->hstream;
+       stream_tag = hstream->stream_tag;
+       if (hext_stream->hstream.direction == SNDRV_PCM_STREAM_PLAYBACK)
+               snd_hdac_ext_bus_link_set_stream_id(hlink, stream_tag);
+
        if (ops && ops->set_up_be_pipeline)
                return ops->set_up_be_pipeline(w, substream->stream);
 

```

Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: BTW I tested this and it works for me on my HDA TGL machine

Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dai.c]: @ranj063, this does not apply and it might re-introduce the metallic noise as we need to reset the link DMA, this patch will not do that, right?

What about this one:
```diff
diff --git a/sound/soc/sof/intel/hda-dai.c b/sound/soc/sof/intel/hda-dai.c
index 2a6f821c9e14..1a6f13feef4c 100644
--- a/sound/soc/sof/intel/hda-dai.c
+++ b/sound/soc/sof/intel/hda-dai.c
@@ -103,8 +103,10 @@ hda_dai_get_ops(struct snd_pcm_substream *substream, struct snd_soc_dai *cpu_dai
 	return sdai->platform_private;
 }
 
-int hda_link_dma_cleanup(struct snd_pcm_substream *substream, struct hdac_ext_stream *hext_stream,
-			 struct snd_soc_dai *cpu_dai)
+static int
+hda_link_dma_cleanup(struct snd_pcm_substream *substream,
+		     struct hdac_ext_stream *hext_stream,
+		     struct snd_soc_dai *cpu_dai, bool release)
 {
 	const struct hda_dai_widget_dma_ops *ops = hda_dai_get_ops(substream, cpu_dai);
 	struct sof_intel_hda_stream *hda_stream;
@@ -128,6 +130,12 @@ int hda_link_dma_cleanup(struct snd_pcm_substream *substream, struct hdac_ext_st
 		snd_hdac_ext_bus_link_clear_stream_id(hlink, stream_tag);
 	}
 
+	if (!release) {
+		/* force stream reconfiguration, including LinkDMA reset */
+		hext_stream->link_prepared = 0;
+		return 0;
+	}
+
 	if (ops->release_hext_stream)
 		ops->release_hext_stream(sdev, cpu_dai, substream);
 
@@ -211,7 +219,7 @@ static int __maybe_unused hda_dai_hw_free(struct snd_pcm_substream *substream,
 	if (!hext_stream)
 		return 0;
 
-	return hda_link_dma_cleanup(substream, hext_stream, cpu_dai);
+	return hda_link_dma_cleanup(substream, hext_stream, cpu_dai, true);
 }
 
 static int __maybe_unused hda_dai_hw_params_data(struct snd_pcm_substream *substream,
@@ -304,7 +312,8 @@ static int __maybe_unused hda_dai_trigger(struct snd_pcm_substream *substream, i
 	switch (cmd) {
 	case SNDRV_PCM_TRIGGER_STOP:
 	case SNDRV_PCM_TRIGGER_SUSPEND:
-		ret = hda_link_dma_cleanup(substream, hext_stream, dai);
+		ret = hda_link_dma_cleanup(substream, hext_stream, dai,
+					   cmd == SNDRV_PCM_TRIGGER_STOP ? false : true);
 		if (ret < 0) {
 			dev_err(sdev->dev, "%s: failed to clean up link DMA\n", __func__);
 			return ret;
@@ -673,7 +682,7 @@ static int hda_dai_suspend(struct hdac_bus *bus)
 
 			ret = hda_link_dma_cleanup(hext_stream->link_substream,
 						   hext_stream,
-						   cpu_dai);
+						   cpu_dai, true);
 			if (ret < 0)
 				return ret;
 		}
diff --git a/sound/soc/sof/intel/hda.h b/sound/soc/sof/intel/hda.h
index 22bd9c3c8216..ee4ccc1a5490 100644
--- a/sound/soc/sof/intel/hda.h
+++ b/sound/soc/sof/intel/hda.h
@@ -1038,8 +1038,6 @@ const struct hda_dai_widget_dma_ops *
 hda_select_dai_widget_ops(struct snd_sof_dev *sdev, struct snd_sof_widget *swidget);
 int hda_dai_config(struct snd_soc_dapm_widget *w, unsigned int flags,
 		   struct snd_sof_dai_config_data *data);
-int hda_link_dma_cleanup(struct snd_pcm_substream *substream, struct hdac_ext_stream *hext_stream,
-			 struct snd_soc_dai *cpu_dai);
 
 static inline struct snd_sof_dev *widget_to_sdev(struct snd_soc_dapm_widget *w)
 {
```

Comment (ujfalusi) [reply sound/soc/sof/intel/hda-dai.c]: Tested on HDA (IPC3/4) and LNL SDW (IPC4) with playback and capture and suspend

**Comment by ujfalusi** [comment]
Changes since v3:
- New patch to not even release the LinkDMA channel (new flag added to hda_link_dma_cleanup() )

File: sound/soc/sof/intel/hda-dai.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-dai.c]: Sorry @ujfalusi  my patch didn't apply as it was on top of my pr. But I love this version. Thanks!

**Review by ranj063 — APPROVED** [review]

**Comment by ranj063** [comment]
@ujfalusi is the LNL HDA alsabat failure a known issue?

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
> @ujfalusi is the LNL HDA alsabat failure a known issue?

Yes, suspect atm is AC noise on a DUT. Team looking at it.

**Review by bardliao — APPROVED** [review]

**Comment by ujfalusi** [comment]
> @ujfalusi is the LNL HDA alsabat failure a known issue?

It appears to be present in all PR tests
