### PR TITLE
ASoC: Intel: sof_sdw: use generic rtd_init function for Realtek SDW DMICs

### LINKED ISSUE #4834: [REGRESSION] Dell Latitude 9520 (SKU: 0A3E) UCM regression (affecting PipeWire/PulseAudio) due to incorrect audio configuration report
The following patch caused a major regression on _all_ devices which uses non sdca rt715 codecs:
02adad081751 ("ASoC: Intel: sof_sdw: add common sdw dai link init")

On the Dell laptop the kernel reports that the device have `rt715-sdca`:
```
# amixer -c0 info
Card sysdefault:0 'sofsoundwire'/'Intel Soundwire SOF'
  Mixer name    : 'Intel Tigerlake HDMI'
  Components    : 'HDA:80862812,80860101,00100000 cfg-spk:2 cfg-amp:1 hs:rt711 spk:rt1308 mic:rt715-sdca'
  Controls      : 65
  Simple ctrls  : 39
```
while in reality it has the non sdca variant:
```
# amixer -c0 info
Card sysdefault:0 'sofsoundwire'/'Intel Soundwire SOF'
  Mixer name    : 'Intel Tigerlake HDMI'
  Components    : 'HDA:80862812,80860101,00100000 cfg-spk:2 cfg-amp:1 hs:rt711 spk:rt1308 mic:rt715'
  Controls      : 65
  Simple ctrls  : 39
```

This will make UCM to fail to initialize the card and leaves the audio unusable on the device.

Reproduction rate: 10/10

The sof_sdw_rtd_init() uses the new find_codec_info_dai() to find the codec in the codec_info_list[] :
!strcmp(codec_info_list[i].dais[j].dai_name, dai_name)
 
But we have 4 "rt715-aif2", first two is scda, second two is 'normal', if the board have 'normal' rt715 then this sof_sdw_rtd_init() will pick the first match, which is the scda and the ucm is messed up (and other things as well)

### PR DESCRIPTION
**Pull request by bardliao**
The only thing that the rt_xxx_rtd_init() functions do is to set
card->components. And we can set card->components with name_prefix
as rt712_sdca_dmic_rtd_init() does.
And sof_sdw_rtd_init() will always select the first dai with the
given dai->name from codec_info_list[]. Unfortunately, we have
different codecs with the same dai name. For example, dai name of
rt715 and rt715-sdca are both "rt715-aif2". Using a generic rtd_init
allow sof_sdw_rtd_init() run the rtd_init() callback from a similar
codec dai.

Fixes: https://github.com/thesofproject/linux/issues/4834

### CODE REVIEW

**Comment by ujfalusi** [comment]
@bardliao, you cannot change the name_prefix as UCM expects `rt714 ` for sdca variants:
```
# cat /usr/share/alsa/ucm2/codecs/rt715-sdca/init.conf
# RT715-sdca (aka RT714) specific volume control settings

BootSequence [
        cset "name='rt714 FU0A Capture Switch' 0"
        cset "name='rt714 ADC 22 Mux' 'DMIC3'"
        cset "name='rt714 ADC 23 Mux' 'DMIC4'"
        cset "name='rt714 FU02 Capture Switch' 1"
        cset "name='rt714 FU02 Capture Volume' 47"
]

FixedBootSequence [
        exec "-/sbin/modprobe snd_ctl_led"
        sysw "-/class/sound/ctl-led/mic/card${CardNumber}/attach:rt714 FU02 Capture Switch"
]
```

**Comment by bardliao** [comment]
> @bardliao, you cannot change the name_prefix as UCM expects `rt714 ` for sdca variants:
> 
> ```
> # cat /usr/share/alsa/ucm2/codecs/rt715-sdca/init.conf
> # RT715-sdca (aka RT714) specific volume control settings
> 
> BootSequence [
>         cset "name='rt714 FU0A Capture Switch' 0"
>         cset "name='rt714 ADC 22 Mux' 'DMIC3'"
>         cset "name='rt714 ADC 23 Mux' 'DMIC4'"
>         cset "name='rt714 FU02 Capture Switch' 1"
>         cset "name='rt714 FU02 Capture Volume' 47"
> ]
> 
> FixedBootSequence [
>         exec "-/sbin/modprobe snd_ctl_led"
>         sysw "-/class/sound/ctl-led/mic/card${CardNumber}/attach:rt714 FU02 Capture Switch"
> ]
> ```

Thanks @ujfalusi. I removed the changing name_prefix commit now. I think we can follow UCMs convention to use rt714 name_prefix for rt715-sdca codec.

**Comment by ujfalusi** [comment]
@bardliao, can you mark these as fixes for 8266c73126b75eabbebefe7ce489a798e9ef2662 ?
I think that is the point when things got broken.

**Comment by bardliao** [comment]
> @bardliao, can you mark these as fixes for [8266c73](https://github.com/thesofproject/linux/commit/8266c73126b75eabbebefe7ce489a798e9ef2662) ? I think that is the point when things got broken.

Done with reordering the commits. And it won't apply to https://github.com/thesofproject/linux/commit/8266c73126b75eabbebefe7ce489a798e9ef2662, but will apply to https://github.com/thesofproject/linux/commit/579d6596ebea488ad661bfa484c771c2b47eecc5 which is the next commit in the same series. I assume that is ok, right?

**Review by plbossart — DISMISSED** [review]

**Review by aiChaoSONG — APPROVED** [review]

File: sound/soc/intel/boards/sof_sdw_rt_dmic.c [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+};
+
+int rt_dmic_rtd_init(struct snd_soc_pcm_runtime *rtd)
+{
+	struct snd_soc_card *card = rtd->card;
+	struct snd_soc_component *component;
+	struct snd_soc_dai *codec_dai;
+	char *mic_name;
+
+	codec_dai = get_codec_dai_by_name(rtd, dmics, ARRAY_SIZE(dmics));
```
Comment (ujfalusi) [inline sound/soc/intel/boards/sof_sdw_rt_dmic.c:29]: I guess it is not possible to have both rt715 and rt712, or a mix if rt715 and rt715-sdca?

**Review by ujfalusi — COMMENTED** [review]
@bardliao, while this fixes the regression on the laptop I have, I think it is still leaves at least one bug:
The sof_sdw_rtd_init() will update the wrong codec_info entry if non sdca rt715 is used on the board.
We just happen to have the same rtd_init() callback set for all dmic codecs which will set the correct component name.
Not only for the rt715/rt715-sdca/rt714, but rt712-sdca-aif1 and rt712-sdca-dmic-aif1 also have duplicate entry in the struct.

Is this something we should be concerned about?

File: sound/soc/intel/boards/sof_sdw_rt_dmic.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/intel/boards/sof_sdw_rt_dmic.c:29]: > I guess it is not possible to have both rt715 and rt712, or a mix if rt715 and rt715-sdca?

No, we don't have such configuration. We have at most one SDW DMIC. But, if it really happens, `rt_dmic_rtd_init()` will be called twice, and both rt715 and rt712 will be appended to `card->components`.

Comment (bardliao) [reply sound/soc/intel/boards/sof_sdw_rt_dmic.c:29]: > > I guess it is not possible to have both rt715 and rt712, or a mix if rt715 and rt715-sdca?
> 
> No, we don't have such configuration. We have at most one SDW DMIC. But, if it really happens, `rt_dmic_rtd_init()` will be called twice, and both rt715 and rt712 will be appended to `card->components`.

Sorry, I was wrong. `rt_dmic_rtd_init()` will not be called twice since the `rtd_init_done` will be set.

**Comment by bardliao** [comment]
> @bardliao, while this fixes the regression on the laptop I have, I think it is still leaves at least one bug: The sof_sdw_rtd_init() will update the wrong codec_info entry if non sdca rt715 is used on the board. We just happen to have the same rtd_init() callback set for all dmic codecs which will set the correct component name. Not only for the rt715/rt715-sdca/rt714, but rt712-sdca-aif1 and rt712-sdca-dmic-aif1 also have duplicate entry in the struct.
> 
> Is this something we should be concerned about?

Hmm, I think it should be fine. The duplicated dai name share the same codec driver except rt715 and rt715-sdca. And rt715 and rt715-sdca can use the same rtd_init.

File: sound/soc/intel/boards/sof_sdw_rt_dmic.c [hunk 2]
```diff
@@ -15,6 +15,7 @@
 static const char * const dmics[] = {
 	"rt715",
 	"rt712-sdca-dmic",
+	"rt722-sdca",
```
Comment (plbossart) [inline sound/soc/intel/boards/sof_sdw_rt_dmic.c:19]: can you add a comment on why we don't have rt715-sdca in the list? I am a bit lost on conventions.

Comment (bardliao) [reply sound/soc/intel/boards/sof_sdw_rt_dmic.c:19]: > can you add a comment on why we don't have rt715-sdca in the list? I am a bit lost on conventions.

Because rt715-sdca codec driver uses [rt715-aif1](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/rt715-sdca.c#L936), too. I will add a comment on it. BTW, if rt715-sdca codec driver can change its dai name to `rt715-sdca-aif1` and `rt715-sdca-aif2`, it would help machine driver to distinguish rt715 and rt715-sdca DAIs. What do you think @shumingfan?

Comment (shumingfan) [reply sound/soc/intel/boards/sof_sdw_rt_dmic.c:19]: @bardliao I think the rt715-sdca codec driver could change the dai name to `rt715-sdca-aif1` and `rt715-sdca-aif2`.
The rt711-sdca codec driver did the same thing.

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
@ujfalusi can you check if this PR fixes the issue #4834

**Review by ujfalusi — APPROVED** [review]
