### PR TITLE
ASoC: SOF: free scontrol when components are unload

### LINKED ISSUE #617: topology. pipeline and it's components should be freed on any loading failure.
If any component within a pipeline fails to load then the kernel should dismantle that pipeline and remove it from internal representations to prevent it being restored at resume() i.e.
```
[    6.142444] sof-audio sof-audio: loading topology:intel/sof-apl-nocodec.tplg
[    6.149924] sof-audio sof-audio: tplg: load control type 3 name : Capture Mux 1
[    6.149929] sof-audio sof-audio: tplg: load kcontrol index 0 chans 3
[    6.149936] sof-audio sof-audio: tplg: load control type 3 name : Channel Mux 2
[    6.149938] sof-audio sof-audio: tplg: load kcontrol index 0 chans 3
[    6.149945] sof-audio sof-audio: tplg: ready widget id 0 pipe 1 type 24 name : PCM0C stream Passthrough Capture 0
[    6.149949] sof-audio sof-audio: loaded host PCM0C
[    6.149951] sof-audio sof-audio:  config: periods snk 0 src 2 fmt 0
[    6.149977] sof-audio sof-audio: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.150081] sof-audio sof-audio: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.150093] sof-audio sof-audio: tplg: ready widget id 1 pipe 1 type 2 name : MUX1.0 stream none
[    6.150096] sof-audio sof-audio: warning: widget type 2 name MUX1.0 not handled
[    6.150099] sof-audio sof-audio: tplg: ready widget id 2 pipe 1 type 31 name : BUF1.0 stream none
[    6.150102] sof-audio sof-audio: buffer BUF1.0: size 256 caps 0x71
[    6.150114] sof-audio sof-audio: ipc tx: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[    6.150370] sof-audio sof-audio: ipc tx succeeded: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[    6.150382] sof-audio sof-audio: tplg: ready widget id 3 pipe 1 type 28 name : DMIC0.IN stream NoCodec-6
[    6.150386] sof-audio sof-audio: dai DMIC0.IN: type 2 index 0
[    6.150388] sof-audio sof-audio:  config: periods snk 2 src 0 fmt 0
[    6.150404] sof-audio sof-audio: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.150539] sof-audio sof-audio: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.150548] sof-audio sof-audio: tplg: connected widget DMIC0.IN -> DAI link NoCodec-6
[    6.150557] sof-audio sof-audio: tplg: ready widget id 4 pipe 1 type 32 name : PIPELINE.1.DMIC0.IN stream DMIC0.IN
[    6.150559] sof-audio sof-audio: tplg: pipeline id 1 comp 4 scheduling comp id 3
[    6.150562] sof-audio sof-audio: pipeline PIPELINE.1.DMIC0.IN: deadline 1000 pri 0 mips 5000 core 0 frames 16
[    6.150575] sof-audio sof-audio: ipc tx: 0x30100000: GLB_TPLG_MSG: PIPE_NEW
[    6.150644] sof-audio sof-audio: ipc tx succeeded: 0x30100000: GLB_TPLG_MSG: PIPE_NEW
[    6.150652] sof-audio sof-audio: DSP core(s) enabled? 1 : core_mask 1
[    6.150661] sof-audio sof-audio: ipc tx: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[    6.150728] sof-audio sof-audio: ipc tx succeeded: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[    6.150739] sof-audio sof-audio: tplg: load control type 1 name : Detect Switch 2
[    6.150742] sof-audio sof-audio: tplg: load kcontrol index 5 chans 2
[    6.150745] sof-audio sof-audio: tplg: ready widget id 5 pipe 2 type 33 name : DETECT2.0 stream none
[    6.150747] sof-audio sof-audio: error: invalid effect type 0
[    6.150753] sof-audio sof-audio: error: effect loading failed
[    6.150756] sof-audio sof-audio: error: DSP failed to add widget id 0 type 33 name : DETECT2.0 stream none reply 0
[    6.150761] sof-audio sof-audio: ASoC: failed to load widget DETECT2.0
[    6.150763] sof-audio sof-audio: error: tplg component load failed -22
[    6.150773] sof-audio sof-audio: error: failed to load DSP topology -22
[    6.150776] sof-audio sof-audio: ASoC: failed to probe component -22
[    6.150803] sof-nocodec sof-nocodec: ASoC: failed to instantiate card -22
[    6.150847] sof-nocodec: probe of sof-nocodec failed with error -22
[    6.150859] sof-audio sof-audio: created machine sof-nocodec
[    6.150953] sof-audio sof-audio: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[    6.151025] sof-audio sof-audio: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[    6.151035] sof-audio sof-audio: FW Poll Status: reg=0x1010303 successful
[    6.152293] sof-audio sof-audio: FW Poll Status: reg=0x303 successful
[    6.152297] sof-audio sof-audio: DSP core(s) enabled? 0 : core_mask 3
[    6.152306] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[    6.152310] sof-audio sof-audio: Debug PCIW: 00000010 at  00000044
[    6.216647] random: crng init done
[    6.216652] random: 7 urandom warning(s) missed due to ratelimiting
[    6.268193] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[    6.269240] sof-audio sof-audio: loading firmware
[    6.269256] sof-audio sof-audio: Debug PCIR: 00000002 at  00000048
[    6.269259] sof-audio sof-audio: Debug PCIW: 00000000 at  00000048
[    6.269263] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[    6.269266] sof-audio sof-audio: Debug PCIW: 00000004 at  00000044
[    6.269267] sof-audio sof-audio: booting DSP firmware
[    6.269373] sof-audio sof-audio: period_bytes:0x0
[    6.269375] sof-audio sof-audio: periods:1
[    6.270697] sof-audio sof-audio: FW Poll Status: reg=0x3030303 successful
[    6.270704] sof-audio sof-audio: FW Poll Status: reg=0x3030302 successful
[    6.270707] sof-audio sof-audio: unstall/run core: core_mask = 1
[    6.270711] sof-audio sof-audio: DSP core(s) enabled? 1 : core_mask 1
[    6.272379] sof-audio sof-audio: FW Poll Status: reg=0x40000000 successful
[    6.273425] sof-audio sof-audio: FW Poll Status: reg=0x1010202 successful
[    6.307937] Adding 1942524k swap on /dev/mmcblk1p3.  Priority:-2 extents:1 across:1942524k SSFS
[    6.308157] sof-audio sof-audio: FW Poll Status: reg=0x5000001 successful
[    6.323181] sof-audio sof-audio: FW Poll Status: reg=0x5 successful
[    6.323188] sof-audio sof-audio: Firmware download successful, booting...
[    6.326014] sof-audio sof-audio: ipc rx: 0x70000000: FW_READY
[    6.326019] sof-audio sof-audio: ipc: DSP is ready 0x70000000 offset 0x81000
[    6.326021] sof-audio sof-audio: booting DSP firmware completed
[    6.326024] sof-audio sof-audio: ipc rx done: 0x70000000: FW_READY
[    6.329997] sof-audio sof-audio: firmware boot complete
[    6.330008] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[    6.330012] sof-audio sof-audio: Debug PCIW: 00000002 at  00000048
[    6.330015] sof-audio sof-audio: Debug PCIR: 00000004 at  00000044
[    6.330018] sof-audio sof-audio: Debug PCIW: 00000000 at  00000044
[    6.330038] sof-audio sof-audio: period_bytes:0x0
[    6.330040] sof-audio sof-audio: periods:1
[    6.330047] sof-audio sof-audio: stream_tag: 1
[    6.330065] sof-audio sof-audio: ipc tx: 0x90010000: GLB_TRACE_MSG
[    6.335237] sof-audio sof-audio: ipc tx succeeded: 0x90010000: GLB_TRACE_MSG
[    6.335270] sof-audio sof-audio: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.335369] sof-audio sof-audio: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.335385] sof-audio sof-audio: ipc tx: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[    6.335478] sof-audio sof-audio: ipc tx succeeded: 0x30200000: GLB_TPLG_MSG: BUFFER_NEW
[    6.335498] sof-audio sof-audio: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.338173] sof-audio sof-audio: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
[    6.338201] sof-audio sof-audio: ipc tx: 0x30100000: GLB_TPLG_MSG: PIPE_NEW
[    6.338459] sof-audio sof-audio: ipc tx succeeded: 0x30100000: GLB_TPLG_MSG: PIPE_NEW
[    6.338468] sof-audio sof-audio: DSP core(s) enabled? 1 : core_mask 1
[    6.338478] sof-audio sof-audio: ipc tx: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[    6.338624] sof-audio sof-audio: ipc tx succeeded: 0x40070000: GLB_PM_MSG: CORE_ENABLE
[    6.338631] sof-audio sof-audio: error: no config for DAI NoCodec-6
[    6.338639] sof-audio sof-audio: tplg: complete pipeline \xa0D\xb6\xfa\x9d\xff\xff\xc0\xe5\x99\xff\xff\xff\xff id 4
[    6.338648] sof-audio sof-audio: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    6.342906] sof-audio sof-audio: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[    6.342941] sof-audio sof-audio: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE
[    6.349452] sof-audio sof-audio: error: ipc error for 0x50010000 size 0x6c
[    6.349466] sof-audio sof-audio: error: failed to set control 0 values
[    6.349469] sof-audio sof-audio: error: failed kcontrol value set for widget: 5
[    6.349471] sof-audio sof-audio: error: restoring kcontrols after resume
[    6.349473] sof-audio sof-audio: error: failed to restore pipeline after resume -19
```

### PR DESCRIPTION
**Pull request by bardliao**
scontrol is allocated by sof_control_load() which will be called when
a kcontrol or a widget with kcontrol is created. We have to free it in
both sof_control_unload() and sof_widget_unload().

Signed-off-by: Bard liao <yung-chuan.liao@linux.intel.com>

Fix #617

### CODE REVIEW

File: sound/soc/sof/topology.c [hunk 1]
```diff
@@ -1959,14 +1964,32 @@ static int sof_widget_unload(struct snd_soc_component *scomp,
...
-		/* free volume table */
-		kfree(scontrol->volume_table);
+		for (i = 0; i < widget->num_kcontrols; i++) {
+			kc = &widget->kcontrol_news[i];
+			sm = (struct soc_mixer_control *)kc->private_value;
+			scontrol = sm->dobj.private;
+
+			/*
+			 * volume_table is allocated
+			 * only if num_kcontrols = 1
```
Comment (ranj063) [inline sound/soc/sof/topology.c]: @bardliao actually the more accurate reason for allocating the volume table is if sm->max > 1

File: sound/soc/sof/topology.c [hunk 2]
```diff
@@ -1959,14 +1964,32 @@ static int sof_widget_unload(struct snd_soc_component *scomp,
...
 	case snd_soc_dapm_pga:
-
-		/* get volume kcontrol */
-		kc = &widget->kcontrol_news[0];
-		sm = (struct soc_mixer_control *)kc->private_value;
-		scontrol = sm->dobj.private;
-
-		/* free volume table */
-		kfree(scontrol->volume_table);
+		for (i = 0; i < widget->num_kcontrols; i++) {
```
Comment (ranj063) [inline sound/soc/sof/topology.c]: @bardliao this needs to be done irrespective of widget type I think.
previously we only had the volume component have a mixer control. so we should just have this loop without the switch.
A widget can have only type of kcontrol today. So that can be used to check which type of kcontrol to free.

File: sound/soc/sof/topology.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/sof/topology.c]: @ranj063 But we will not call set_up_volume_table() [if (le32_to_cpu(tw->num_kcontrols) != 1)](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/topology.c#L1378)

Comment (ranj063) [reply sound/soc/sof/topology.c]: @bardliao thats for the pga widget. What about other widgets? there's no reason to have a volume control for other widgets but that doesnt prevent it. What I meant was that if there's a mixer control for a widget, we should set up a volume table only if sm->max > 1.

File: sound/soc/sof/topology.c (hunk 2 above)
Comment (bardliao) [reply sound/soc/sof/topology.c]: Thanks @ranj063 It is really a good suggestion. I will update my PR.

File: sound/soc/sof/topology.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/sof/topology.c]: @ranj063 ok I got your point. It's another topic for me. We can do it in the future and it is safe to free NULL. So, let's change the testing condition as it should be.

**Comment by bardliao** [comment]
@ranj063 The PR is updated according to your suggestion. :)

File: sound/soc/sof/topology.c [hunk 3]
```diff
@@ -1957,21 +1963,37 @@ static int sof_widget_unload(struct snd_soc_component *scomp,
...
 	default:
 		break;
 	}
+	for (i = 0; i < widget->num_kcontrols; i++) {
+		kc = &widget->kcontrol_news[i];
+		switch (dobj->widget.kcontrol_type) {
+		case SND_SOC_TPLG_TYPE_MIXER:
+			sm = (struct soc_mixer_control *)kc->private_value;
+			scontrol = sm->dobj.private;
+			if (sm->max > 1)
```
Comment (ranj063) [inline sound/soc/sof/topology.c:1976]: @bardliao Thanks. This PR looks good for what it was intended. But, in reality we never actually make sure that the volume table is set up only if sm->max is > 1. I think we should fix that.

Comment (bardliao) [reply sound/soc/sof/topology.c:1976]: @ranj063 I am thinking should we move set_up_volume_table() from sof_widget_load_pga() to sof_control_load_volume()? It seems to make more sense to me.

Comment (ranj063) [reply sound/soc/sof/topology.c:1976]: @bardliao yes, makes sense. I have no idea why I put it inside load_pga() :)

File: sound/soc/sof/topology.c [hunk 4]
```diff
@@ -1957,21 +1963,37 @@ static int sof_widget_unload(struct snd_soc_component *scomp,
...
+		case SND_SOC_TPLG_TYPE_ENUM:
+			se = (struct soc_enum *)kc->private_value;
+			scontrol = se->dobj.private;
+			break;
+		case SND_SOC_TPLG_TYPE_BYTES:
+			sbe = (struct soc_bytes_ext *)kc->private_value;
+			scontrol = sbe->dobj.private;
+			break;
+		default:
+			dev_warn(sdev->dev, "unsupported kcontrol_tupe\n");
```
Comment (ranj063) [inline sound/soc/sof/topology.c]: @bardliao typo here. kcontrol type?

Comment (bardliao) [reply sound/soc/sof/topology.c]: @ranj063 Thanks. I also update the goto label to lower case to be consistent with others.

File: sound/soc/sof/topology.c (hunk 3 above)
Comment (bardliao) [reply sound/soc/sof/topology.c:1976]: @ranj063 I may know the reason why you put it inside load_pga(). soc_tplg_create_tlv() is called after soc_tplg_init_kcontrol(), so you can't get tlv.p in sof_control_load().  I think there should be no side effect if we move soc_tplg_create_tlv() to the front of soc_tplg_init_kcontrol(). Then we can move set_up_volume_table() to sof_control_load_volume().

Comment (ranj063) [reply sound/soc/sof/topology.c:1976]: @bardliao yes, you are right. moving soc_tplg_create_tlv() ahead of soc_tplg_init_kcontrol() would fix the problem. If you look into soc-topology.c, the call to soc_tplg_create_tlv() inside soc_tplg_dapm_widget_dmixer_create() is what is of significance to us. I added the call to soc_tplg_create_tlv() after soc_tplg_init_kcontrol() to be consistent with soc_tplg_dmixer_create(). So lets change it both places.
