### PR TITLE
unload physical dai link in remove

### LINKED ISSUE #343: Can't find sof_dai in sof_link_unload()
We will see below error message if we rmmod sof_pci_dev
```
[   82.481898] sof-audio sof-audio: error: invalid DAI type 0
[   82.482352] sof-audio sof-audio: error: invalid DAI type 0
[   82.482823] sof-audio sof-audio: error: invalid DAI type 0
[   82.483266] sof-audio sof-audio: error: invalid DAI type 0
```
The reason is link->name and sof_dai->name are not matched in sof_link_unload()
for example, on up2 with pcm512x codec,
the link->name are **HDMI3, HDMI2, HDMI1, and Port5**
But the sof_dai->name are **iDisp3, iDisp2, iDisp1, SSP5-Codec**
But it was matched in sof_link_load().

### PR DESCRIPTION
**Pull request by bardliao**
soc_tplg_link_config will find the physical dai link and load the dai link
but the dai link will not be unload in snd_soc_tplg_component_remove
since it is not dynamic created by topology. Add dai link unload to
balance it. Note that the link unload will only call topology ops link_inload,
the link will still be removed by soc core.

Fix #343

### CODE REVIEW

**Comment by plbossart** [comment]
@xiulipan I don't know why the build fails, it works fine for me when I check out this PR and compile locally? It's not even based on the 4.20 code and gives the same errors with the jump thingy

File: sound/soc/soc-topology.c [hunk 1]
```diff
@@ -2577,6 +2594,9 @@ int snd_soc_tplg_component_remove(struct snd_soc_component *comp, u32 index)
 			case SND_SOC_DOBJ_DAI_LINK:
 				remove_link(comp, dobj, pass);
 				break;
+			case SND_SOC_DOBJ_NONE:
+				unload_link(comp, dobj, pass);
+				break;
```
Comment (plbossart) [inline sound/soc/soc-topology.c:2683]: I find the code complicated and confusing:
for a DAI_LINK you use remove_link() but for an DOBJ_NONE you use unload_link() (with the comment that it "unloads dai link".
in addition remove_link() calls snd_soc_remove_dai_link(comp->card, link) so you are going to lose reviewers here.

File: sound/soc/soc-topology.c [hunk 2]
```diff
@@ -2093,6 +2106,10 @@ static int soc_tplg_link_config(struct soc_tplg *tplg,
 		dev_err(tplg->dev, "ASoC: physical link loading failed\n");
 		return ret;
 	}
+	link->dobj.index = tplg->index;
+	link->dobj.ops = tplg->ops;
+	link->dobj.type = SND_SOC_DOBJ_NONE;
```
Comment (plbossart) [inline sound/soc/soc-topology.c]: is this a hack or really a type we want to use?

File: sound/soc/soc-topology.c [hunk 3]
```diff
@@ -542,6 +542,19 @@ static void remove_link(struct snd_soc_component *comp,
 	kfree(link);
 }
 
+/* unload dai link */
+static void unload_link(struct snd_soc_component *comp,
+	struct snd_soc_dobj *dobj, int pass)
+{
+	if (pass != SOC_TPLG_PASS_LINK)
+		return;
```
Comment (plbossart) [inline sound/soc/soc-topology.c:567]: unclear to me why this is different from remove_link() ?

File: sound/soc/soc-topology.c (hunk 2 above)
Comment (bardliao) [reply sound/soc/soc-topology.c]: @plbossart I think it is the best choice if we don't add a new item in [snd_soc_dobj_type](https://elixir.bootlin.com/linux/latest/source/include/sound/soc-topology.h#L38). The link which we want to unload is not a dynamic object. That's why I use SND_SOC_DOBJ_NONE. Currently,  SND_SOC_DOBJ_NONE is only used for unloading link, but we have to consider if it can be used for other functions in the future.

File: sound/soc/soc-topology.c (hunk 1 above)
Comment (bardliao) [reply sound/soc/soc-topology.c:2683]: @plbossart For DAI_LINK, which are FE links, are created in soc_tplg_fe_link_create().  So we need to remove it by remove_link(). But for DOBJ_NONE, which are BE links, are not created by topology and they will be removed by [soc_remove_dai_links](https://elixir.bootlin.com/linux/latest/source/sound/soc/soc-core.c#L1001). But It is load by ```snd_soc_tplg_component_load()->soc_tplg_load()->soc_tplg_process_headers()->soc_tplg_load_header()->soc_tplg_link_elems_load()->soc_tplg_link_config()```. So I think it is better to unload it in soc-topology.

**Comment by bardliao** [comment]
@plbossart There are two types of links. One is FE and the other is BE. The FE links are created by topology and we call remove_link() to remove it in current code. The BE links are predefined and will be removed by soc_remove_dai_links(). Topology will load the BE links in ```soc_tplg_link_config()``` without unloading it. And that is the patch trying to do. We add the link to &tplg->comp->dobj_list so we can unload it in ```snd_soc_tplg_component_remove()```

File: sound/soc/soc-topology.c (hunk 3 above)
Comment (bardliao) [reply sound/soc/soc-topology.c:567]: @plbossart The remove_link() will handle the link which is created by soc_tplg_pcm_elems_load() and its type is SOC_TPLG_PASS_PCM_DAI actually. For SOC_TPLG_PASS_LINK type, we only config it but not create it. So, only unload is needed.

File: sound/soc/soc-topology.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/soc-topology.c]: @bardliao I think we are contradicting ourselves by calling it type SND_SOC_DOBJ_NONE and then adding it to the dobj_list. 

I think the better option is to use SND_SOC_DOBJ_DAI_LINK type and re-use the remove_link to check for both passes, SOC_TPLG_PASS_PCM_DAI and SOC_TPLG_PASS_LINK.

Comment (bardliao) [reply sound/soc/soc-topology.c]: Thanks @ranj063 It's a good idea. I will update my PR and add more comment to explain it.

**Comment by plbossart** [comment]
> @plbossart There are two types of links. One is FE and the other is BE. The FE links are created by topology and we call remove_link() to remove it in current code. The BE links are predefined and will be removed by soc_remove_dai_links(). Topology will load the BE links in `soc_tplg_link_config()` without unloading it. And that is the patch trying to do. We add the link to &tplg->comp->dobj_list so we can unload it in `snd_soc_tplg_component_remove()`

Very useful explanation that's completely missing in the patch. It'd be useful to add it at least to the commit message.
Instead of doing this DOBJ_NONE hack can't we use the fact that the objects are dynamic and as Ranjani suggested free the dynamic objects in the FE parts and the rest for the BE parts?

File: sound/soc/soc-topology.c (hunk 2 above)
Comment (bardliao) [reply sound/soc/soc-topology.c]: @ranj063 There is a problem if we reuse SND_SOC_DOBJ_DAI_LINK. [soc_remove_dai_links](https://elixir.bootlin.com/linux/latest/source/sound/soc/soc-core.c#L1018) will check if the link is SND_SOC_DOBJ_DAI_LINK type. I think soc-core think all SND_SOC_DOBJ_DAI_LINK type is created by topology. So we will see "Topology forgot to remove link <link name>" warning if we reuse  SND_SOC_DOBJ_DAI_LINK type.

**Comment by xiulipan** [comment]
@plbossart 
Checked, it seems the `make SUBDIRS=sound/soc/sof C=2` is not smart enough to update all changes when such a big PR comes.
A full make fix it.

**Comment by bardliao** [comment]
@plbossart @ranj063 I updated the PR with the following changes
1. Update change log
2. Add new dobj type named SND_SOC_DOBJ_BE_DAI_LINK instead of using DOBJ_NONE
3. Add more comments in the code

File: sound/soc/soc-topology.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/soc-topology.c]: @bardliao do BE links that are defined in the machine driver get added to the card's dai_link_list?

Then maybe we need to modify the check to make sure it is a BE link before we generate the warning.

File: include/sound/soc-topology.h [hunk 4]
```diff
@@ -44,6 +44,7 @@ enum snd_soc_dobj_type {
 	SND_SOC_DOBJ_DAI_LINK,
 	SND_SOC_DOBJ_CODEC_LINK,
 	SND_SOC_DOBJ_WIDGET,
+	SND_SOC_DOBJ_BE_DAI_LINK,
```
Comment (plbossart) [inline include/sound/soc-topology.h]: Hum. If I look at include/uapi/sound/asoc.h, I see the following definitions

````c
#define SND_SOC_TPLG_TYPE_MIXER		1
#define SND_SOC_TPLG_TYPE_BYTES		2
#define SND_SOC_TPLG_TYPE_ENUM		3
#define SND_SOC_TPLG_TYPE_DAPM_GRAPH	4
#define SND_SOC_TPLG_TYPE_DAPM_WIDGET	5
#define SND_SOC_TPLG_TYPE_DAI_LINK	6
#define SND_SOC_TPLG_TYPE_PCM		7
#define SND_SOC_TPLG_TYPE_MANIFEST	8
#define SND_SOC_TPLG_TYPE_CODEC_LINK	9
#define SND_SOC_TPLG_TYPE_BACKEND_LINK	10
#define SND_SOC_TPLG_TYPE_PDATA		11
#define SND_SOC_TPLG_TYPE_DAI		12
````

It looks like there was a correlation between the two structures initially, so should we use BACKEND_LINK instead? @mengdonglin can you comment on this?

File: sound/soc/soc-topology.c [hunk 5]
```diff
@@ -542,6 +542,19 @@ static void remove_link(struct snd_soc_component *comp,
 	kfree(link);
 }
 
+/* unload dai link */
+static void unload_link(struct snd_soc_component *comp,
```
Comment (plbossart) [inline sound/soc/soc-topology.c]: unload_backend_link?

File: sound/soc/soc-topology.c [hunk 6]
```diff
@@ -2094,6 +2107,12 @@ static int soc_tplg_link_config(struct soc_tplg *tplg,
 		return ret;
 	}
 
+	/* add it to dobj_list so we can unload it in _remove */
```
Comment (plbossart) [inline sound/soc/soc-topology.c]: unload it in snd_soc_tplg_component_remove, be explicit to avoid confusions with remove_link().

File: sound/soc/soc-topology.c [hunk 7]
```diff
@@ -2577,6 +2596,13 @@ int snd_soc_tplg_component_remove(struct snd_soc_component *comp, u32 index)
 			case SND_SOC_DOBJ_DAI_LINK:
 				remove_link(comp, dobj, pass);
 				break;
+			case SND_SOC_DOBJ_BE_DAI_LINK:
+				/*
+				 * we don't free the BE link since it is not
+				 * allocated by topology
```
Comment (plbossart) [inline sound/soc/soc-topology.c]: You should describe what the unload_link does, since the link_load() only deals with initializations according to the comments. is this to free private data handled by the component driver and allocated by the link_load

**Comment by ranj063** [comment]
@plbossart @bardliao I'm starting to question the need for this now. Looking into sof_link_unload() in topology.c, it looks like the only reason we need it is for HDA dai's and even there there's a FIXME stating the following:
/*
	 * FIXME: this call to hw_free is mainly to release the link DMA ID.
	 * This is abusing the API and handling SOC internals is not
	 * recommended. This part will be reworked.
	 */

I think we should fix this before changing anything in soc-topology. We might end up not needing all this after all.

**Comment by RanderWang** [comment]
> @plbossart @bardliao I'm starting to question the need for this now. Looking into sof_link_unload() in topology.c, it looks like the only reason we need it is for HDA dai's and even there there's a FIXME stating the following:
> /*
> * FIXME: this call to hw_free is mainly to release the link DMA ID.
> * This is abusing the API and handling SOC internals is not
> * recommended. This part will be reworked.
> */
> 
> I think we should fix this before changing anything in soc-topology. We might end up not needing all this after all.

@plbossart  I want to add a interface in our sof_dsp_ops to allock & free hda resource, what is your idea? I don't want to abuse the API in Asoc

**Comment by ranj063** [comment]
> > @plbossart @bardliao I'm starting to question the need for this now. Looking into sof_link_unload() in topology.c, it looks like the only reason we need it is for HDA dai's and even there there's a FIXME stating the following:
> > /*
> > 
> > * FIXME: this call to hw_free is mainly to release the link DMA ID.
> > * This is abusing the API and handling SOC internals is not
> > * recommended. This part will be reworked.
> >   */
> > 
> > I think we should fix this before changing anything in soc-topology. We might end up not needing all this after all.
> 
> @plbossart I want to add a interface in our sof_dsp_ops to allock & free hda resource, what is your idea? I don't want to abuse the API in Asoc

@plbossart I remember you didnt want to add another ops to alloc and free hda resource but I never really understood why. could you please shed some light on that?

**Comment by bardliao** [comment]
@ranj063 Agreed. However, it is different thing for me. My point is there are link_load and link_unload in snd_soc_tplg_ops {}. The link_load ops is called by BE and FE link, but link_unload is only called by FE link. People may want to use link_unload ops for whatever purpose, but it doesn't be supported by current code. For example, people may want to config a parameter in link_load and need to reset it to default in link_unload. He/She may expect the link_unload ops will be invoked by all links, but it won't. That's why I am trying to invoke the link_unload ops if the link_load ops is invoked. What do you think? @plbossart

File: include/sound/soc-topology.h (hunk 4 above)
Comment (bardliao) [reply include/sound/soc-topology.h]: @plbossart @mengdonglin I have a question here.  We create a dobj with SND_SOC_DOBJ_DAI_LINK type for tplg type SND_SOC_TPLG_TYPE_PCM. 
[case SND_SOC_TPLG_TYPE_PCM](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/soc-topology.c#L2410)
```
soc_tplg_pcm_elems_load() -> soc_tplg_pcm_create() -> soc_tplg_fe_link_create()
```
[link->dobj.type = SND_SOC_DOBJ_DAI_LINK](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/soc-topology.c#L1792)

And config physical link on tplg type SND_SOC_TPLG_TYPE_DAI_LINK and SND_SOC_TPLG_TYPE_BACKEND_LINK.
[case SND_SOC_TPLG_TYPE_DAI_LINK:
case SND_SOC_TPLG_TYPE_BACKEND_LINK:](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/soc-topology.c#L2414)
It seems the tplg type and dobj type is mismatched already.
Should we fix it first?

File: sound/soc/soc-topology.c (hunk 7 above)
Comment (bardliao) [reply sound/soc/soc-topology.c]: @plbossart It is designed for deinitialization. I think it can also be used to free private data allocated by the link_load.

**Comment by plbossart** [comment]
> > @plbossart @bardliao I'm starting to question the need for this now. Looking into sof_link_unload() in topology.c, it looks like the only reason we need it is for HDA dai's and even there there's a FIXME stating the following:
> > /*
> > 
> > * FIXME: this call to hw_free is mainly to release the link DMA ID.
> > * This is abusing the API and handling SOC internals is not
> > * recommended. This part will be reworked.
> >   */
> > 
> > I think we should fix this before changing anything in soc-topology. We might end up not needing all this after all.
> 
> @plbossart I want to add a interface in our sof_dsp_ops to allock & free hda resource, what is your idea? I don't want to abuse the API in Asoc

how is this related to this thread?

**Comment by plbossart** [comment]
> @ranj063 Agreed. However, it is different thing for me. My point is there are link_load and link_unload in snd_soc_tplg_ops {}. The link_load ops is called by BE and FE link, but link_unload is only called by FE link. People may want to use link_unload ops for whatever purpose, but it doesn't be supported by current code. For example, people may want to config a parameter in link_load and need to reset it to default in link_unload. He/She may expect the link_unload ops will be invoked by all links, but it won't. That's why I am trying to invoke the link_unload ops if the link_load ops is invoked. What do you think? @plbossart

I agree with @bardliao. If the current topology code cannot a reset a value for the next init, or release resources as needed, then it's a limitation. The proposal looks harmless to me, and it's only use if the callback is needed by an implementation.

**Comment by ranj063** [comment]
> > > @plbossart @bardliao I'm starting to question the need for this now. Looking into sof_link_unload() in topology.c, it looks like the only reason we need it is for HDA dai's and even there there's a FIXME stating the following:
> > > /*
> > > 
> > > * FIXME: this call to hw_free is mainly to release the link DMA ID.
> > > * This is abusing the API and handling SOC internals is not
> > > * recommended. This part will be reworked.
> > >   */
> > > 
> > > I think we should fix this before changing anything in soc-topology. We might end up not needing all this after all.
> > 
> > 
> > @plbossart I want to add a interface in our sof_dsp_ops to allock & free hda resource, what is your idea? I don't want to abuse the API in Asoc
> 
> how is this related to this thread?

@plbossart It is not directly related to this thread but rather an extension to address the FIXME as above.

**Comment by ranj063** [comment]
> > @ranj063 Agreed. However, it is different thing for me. My point is there are link_load and link_unload in snd_soc_tplg_ops {}. The link_load ops is called by BE and FE link, but link_unload is only called by FE link. People may want to use link_unload ops for whatever purpose, but it doesn't be supported by current code. For example, people may want to config a parameter in link_load and need to reset it to default in link_unload. He/She may expect the link_unload ops will be invoked by all links, but it won't. That's why I am trying to invoke the link_unload ops if the link_load ops is invoked. What do you think? @plbossart
> 
> I agree with @bardliao. If the current topology code cannot a reset a value for the next init, or release resources as needed, then it's a limitation. The proposal looks harmless to me, and it's only use if the callback is needed by an implementation.

@plbossart @bardliao agreed. The changes look good.

File: include/sound/soc-topology.h (hunk 4 above)
Comment (plbossart) [reply include/sound/soc-topology.h]: sorry @bardliao i didn't understand your question, but it looks like there is a confusion that we need to solve. Care to elaborate maybe with a suggested diff?

File: sound/soc/soc-topology.c (hunk 7 above)
Comment (plbossart) [reply sound/soc/soc-topology.c]: agree, I just want this to be mentioned in the comments. no functional change

File: include/sound/soc-topology.h (hunk 4 above)
Comment (bardliao) [reply include/sound/soc-topology.h]: @plbossart If we find a SND_SOC_TPLG_TYPE_PCM type tplg when we parse a topology file, we will create a SND_SOC_DOBJ_PCM type dobj AND a SND_SOC_DOBJ_DAI_LINK type dobj. Please see the chart below. 
````
	soc_tplg_load_header()
	case SND_SOC_TPLG_TYPE_PCM:
                -> soc_tplg_pcm_elems_load ()
			-> soc_tplg_pcm_create()
				-> soc_tplg_dai_create()
						dai_drv->dobj.type = SND_SOC_DOBJ_PCM;
						list_add(&dai_drv->dobj.list, &tplg->comp->dobj_list);
				-> soc_tplg_fe_link_create()
						link->dobj.type = SND_SOC_DOBJ_DAI_LINK;
						list_add(&link->dobj.list, &tplg->comp->dobj_list);
````
So it is not one to one mapping. 
Also, SND_SOC_TPLG_TYPE_DAI_LINK and SND_SOC_TPLG_TYPE_BACKEND_LINK are both using soc_tplg_link_elems_load() in soc_tplg_load_header(). So there is no different in dealing the two tplg type. My suggestion is as below. But it is a big change, we have to check and modify the topology file as well.
````
@@ -2427,10 +2427,10 @@ static int soc_tplg_load_header(struct soc_tplg *tplg,
        case SND_SOC_TPLG_TYPE_DAPM_WIDGET:
                return soc_tplg_dapm_widget_elems_load(tplg, hdr);
        case SND_SOC_TPLG_TYPE_PCM:
+       case SND_SOC_TPLG_TYPE_DAI_LINK:
                return soc_tplg_pcm_elems_load(tplg, hdr);
        case SND_SOC_TPLG_TYPE_DAI:
                return soc_tplg_dai_elems_load(tplg, hdr);
-       case SND_SOC_TPLG_TYPE_DAI_LINK:
        case SND_SOC_TPLG_TYPE_BACKEND_LINK:
                /* physical link configurations */
                return soc_tplg_link_elems_load(tplg, hdr);
````

**Comment by bardliao** [comment]
@plbossart I add a patch which is not related to #343 to this PR. But the change is also in soc-topology.c. I guess put it in the same PR can avoid conflict. The patch is to fix a memory leak in soc_tplg_dapm_widget_create.

File: sound/soc/soc-topology.c [hunk 8]
```diff
@@ -542,6 +542,19 @@ static void remove_link(struct snd_soc_component *comp,
 	kfree(link);
 }
 
+/* unload dai link */
+static void unload_backend_link(struct snd_soc_component *comp,
```
Comment (plbossart) [inline sound/soc/soc-topology.c]: let's be consistent with the original code and call this "remove_backend_link".

File: sound/soc/soc-topology.c [hunk 9]
```diff
@@ -542,6 +542,19 @@ static void remove_link(struct snd_soc_component *comp,
...
+	struct snd_soc_dobj *dobj, int pass)
+{
+	if (pass != SOC_TPLG_PASS_LINK)
+		return;
+
+	if (dobj->ops && dobj->ops->link_unload)
+		dobj->ops->link_unload(comp, dobj);
+
```
Comment (plbossart) [inline sound/soc/soc-topology.c:571]: add a comment here on why this is different from remove_link().

File: include/sound/soc-topology.h [hunk 10]
```diff
@@ -44,6 +44,7 @@ enum snd_soc_dobj_type {
 	SND_SOC_DOBJ_DAI_LINK,
```
Comment (plbossart) [inline include/sound/soc-topology.h:45]: Fix commit message
"soc_tplg_link_config() will find the physical dai link and call soc_tplg_dai_link_load() to load the BE dai link. Currently remove_link() is only used to remove the FE dai link which is created by the topology.  The BE dai link cannot however be unloaded in snd_soc_tplg_component_remove(), which is problematic if anything needs to be released or reinitialized. 

This patch aligns the definitions of dynamic types with the existing UAPI and adds a new remove_backend_link() routine to unload the the BE dai link when snd_soc_tplg_component_remove() is invoked.
"

**Comment by bardliao** [comment]
@plbossart the PR is updated. Thanks.
