### PR TITLE
ALSA: hda: intel-dsp-config: harden I2C/I2S codec detection

### LINKED ISSUE #4934: [BUG] intel-dsp-config is using the wrong driver support for Huawei Matebook D14 NBLB-WAX9N-PCB (2020/2021)
**Description**

There are different models of Huawei Matebook D14. The newer ones come with ES8336, but older models may have different codecs. I had already access to one model with ES8336, and I own one with Realtek ALC 256.

The model with Realtek ALC 256 is reported as:
```
Manufacturer:      HUAWEI
Product Name:      NBLB-WAX9N
Product Version:   M1240
Firmware Version:  1.45
System SKU:        C100
Board Vendor:      HUAWEI
Board Name:        NBLB-WAX9N-PCB
```
And it has its latest ACPI BIOS for such model:
```
BIOS Information
        Vendor: HUAWEI
        Version: 1.45
        Release Date: 01/17/2023
```

Despite using Realtek ALC 256, its ACPI table also has entries for ES8336:
```
$ ls /sys/bus/acpi/devices/|grep ES
ESSX8336:00
```

That makes snd-intel-dspcfg to try using the SOF driver for es8336, which fails, making the device unusable.

**To Reproduce**

Boot the Kernel 6.8 on such device without any module parameter. The same problem also happens on older Kernels.

**Reproduction Rate**

It happens 100% of the time with default detection logic enabled. Adding this to /etc/modprobe.d/alsa.conf fixes the issue:
```
options snd-intel-dspcfg dsp_driver=1
```

Booting passing dsp_driver parameter makes it work properly [1]:
   https://alsa-project.org/db/?f=1a5ddeb0b151db8fe051407f5bb1c075b7dd3e4a

[1]: an additional is needed for headset microphone to work with intel_hda:
- https://lore.kernel.org/all/b92a9e49fb504eec8416bcc6882a52de89450102.1713370457.git.mchehab@kernel.org/

**Expected behavior**

A quirk at sound/hda/intel-dsp-config.c should be added to blacklist SOF detection on such device, letting it use the legacy intel HDA driver.

**Impact**

No audio.

### PR DESCRIPTION
**Pull request by plbossart**
The SOF driver is selected whenever specific I2C/I2S HIDs are reported as 'present' in the ACPI DSDT. In some cases, an HID is reported but the hardware does not actually rely on I2C/I2S.  This false positive leads to an invalid selection of the SOF driver and as a result an invalid topology is loaded.

This patch hardens the detection with a check that the NHLT table is consistent with the report of an I2S-based codec in DSDT. This table should expose at least one SSP endpoint configured for an I2S-codec connection.

Tested on Huawei Matebook D14 (NBLB-WAX9N) using an HDaudio codec with an invalid ES8336 ACPI HID reported:

[    7.858249] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
[    7.858312] snd_hda_intel 0000:00:1f.3: snd_intel_dsp_find_config: no valid SSP found for HID ESSX8336, skipped

Reported-by: Mauro Carvalho Chehab <mchehab@kernel.org>
Tested-by: Mauro Carvalho Chehab <mchehab@kernel.org>
Closes: https://github.com/thesofproject/linux/issues/4934

### CODE REVIEW

File: sound/hda/intel-dsp-config.c [hunk 1]
```diff
@@ -558,8 +558,29 @@ static const struct config_entry *snd_intel_dsp_find_config
...
-				if (acpi_dev_present(table->codec_hid->codecs[i], NULL, -1))
-					break;
+				if (acpi_dev_present(table->codec_hid->codecs[i], NULL, -1)) {
+					struct nhlt_acpi_table *nhlt;
+					bool ssp_found = false;
+
+					nhlt = intel_nhlt_init(&pci->dev);
+					if (!nhlt) {
+						dev_err(&pci->dev, "%s: NHLT table not found, skipped HID %s\n",
+						 __func__, table->codec_hid->codecs[i]);
```
Comment (bardliao) [inline sound/hda/intel-dsp-config.c:570]: Would it be better to use dev_warn like line 581? Not sure if missing NHLT table is an error or not.

Comment (plbossart) [reply sound/hda/intel-dsp-config.c:570]: I think it's an error because in that case the Windows drivers would not work at all, so that's really a broken platform. NHLT needs to be present/valid to support I2S codecs.

The dev_warn is different, essentially there's a table that's not needed because the hardware is NOT I2S based.

But if there's consensus that dev_warn is better I don't mind scaling dev_err back. It's a corner case anyways.

Comment (andy-shev) [reply sound/hda/intel-dsp-config.c:570]: `dev_err()` when showed in normal logs (first of all the log level can be adjusted) might have a different colour, hence attention by the user. I think since we use `continue;`, meaning non-fatal, `dev_warn()` less scares the end user.

Comment (plbossart) [reply sound/hda/intel-dsp-config.c:570]: dev_warn() is is then, thanks for the feedback.

File: sound/hda/intel-dsp-config.c [hunk 2]
```diff
@@ -558,8 +558,29 @@ static const struct config_entry *snd_intel_dsp_find_config
 			int i;
 
 			for (i = 0; i < table->codec_hid->num_codecs; i++)
-				if (acpi_dev_present(table->codec_hid->codecs[i], NULL, -1))
-					break;
+				if (acpi_dev_present(table->codec_hid->codecs[i], NULL, -1)) {
```
Comment (andy-shev) [inline sound/hda/intel-dsp-config.c]: Btw, you can reduce indentation level, by inverting this condition (i.e. replacing 'break' by 'continue' and inverting the conditional in the original code).

Comment (plbossart) [reply sound/hda/intel-dsp-config.c]: good, suggestion, done!

File: sound/hda/intel-dsp-config.c [hunk 3]
```diff
@@ -557,9 +557,32 @@ static const struct config_entry *snd_intel_dsp_find_config
...
-			for (i = 0; i < table->codec_hid->num_codecs; i++)
-				if (acpi_dev_present(table->codec_hid->codecs[i], NULL, -1))
+			for (i = 0; i < table->codec_hid->num_codecs; i++) {
+				struct nhlt_acpi_table *nhlt;
+				bool ssp_found = false;
+
+				if (!acpi_dev_present(table->codec_hid->codecs[i], NULL, -1))
+					continue;
+
+				nhlt = intel_nhlt_init(&pci->dev);
```
Comment (ujfalusi) [inline sound/hda/intel-dsp-config.c:567]: If num_codecs is 4 then we do 4x  intel_nhlt_init() / intel_nhlt_free() ?
Why not do that around the for loop once?
That would be even done ARRAY_SIZE(config_table) times, so move it even further?

**Review by bardliao — APPROVED** [review]

File: sound/hda/intel-dsp-config.c (hunk 3 above)
Comment (plbossart) [reply sound/hda/intel-dsp-config.c:567]: we first check that the HID is present in ACPI. Having multiple HIDs present is not really a supported configuration, we would pick the first in the table anyways.

Comment (ujfalusi) [reply sound/hda/intel-dsp-config.c:567]: OK, it is just strange to see _init() / _free() done in a loop for something which is static for the whole function.

**Review by ujfalusi — APPROVED** [review]

File: sound/hda/intel-dsp-config.c (hunk 3 above)
Comment (plbossart) [reply sound/hda/intel-dsp-config.c:567]: yeah the flow is a bit weird indeed. I just didn't want to make things too complicated.
