### PR TITLE
fixup! ASoC: SoundWire codecs: make regmap cache-only in probe

### LINKED ISSUE #4454: [BUG] Device with ID register ffffff79 is not rt5682 on Brya-SDW
**Describe the bug**
Observed this issue in CI daily test, this issue happens on ADLP Brya SDW Chromebook. This is just a warning error and does not affect functionality.  The reproduce rate is 100%. 

```
[   97.581648] kernel: rt5682 sdw:0:025d:5682:00: Device with ID register ffffff79 is not rt5682
[   97.581712] kernel: rt5682 sdw:0:025d:5682:00: Update Slave status failed:-19
```

**To Reproduce**
Check the dmesg after boot.

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[34b7f81747f8](https://github.com/thesofproject/linux/commit/34b7f81747f8)}
    * SOF: {stable-v2.2/[b6c174c8f9a8](https://github.com/thesofproject/sof/commit/b6c174c8f9a8)}
2) Name of the topology file
    * Topology: {sof-tplg/sof-adl-sdw-max98373-rt5682.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {ADLP_BRYA_SDW}

[dmesg.txt](https://github.com/thesofproject/linux/files/11953307/dmesg.txt)

### PR DESCRIPTION
**Pull request by bardliao**
There are two regmap in rt5682_priv struct, one is sdw_regmap which is for IO transfer, and the other is used for registers control. We call regcache_cache_only(rt5682->sdw_regmap, true); in rt5682_sdw_init which is correct to avoid sdw access before rt5682 is attached. But regcache_cache_only(rt5682->regmap, false); is called in rt5682_io_init which needs to be fixed.

Fixes: #4454

### CODE REVIEW

File: sound/soc/codecs/rt5682-sdw.c [hunk 1]
```diff
@@ -372,7 +372,7 @@ static int rt5682_io_init(struct device *dev, struct sdw_slave *slave)
 	if (rt5682->hw_init)
 		return 0;
 
-	regcache_cache_only(rt5682->regmap, false);
+	regcache_cache_only(rt5682->sdw_regmap, false);
```
Comment (plbossart) [inline sound/soc/codecs/rt5682-sdw.c:376]: @bardliao in the suspend routine we do this:

	regcache_cache_only(rt5682->regmap, true);

Should we also do this for sdw_regmap? I am not sure I follow the flows...

Comment (bardliao) [reply sound/soc/codecs/rt5682-sdw.c:376]: > @bardliao in the suspend routine we do this:
> 
> ```
> regcache_cache_only(rt5682->regmap, true);
> ```
> 
> Should we also do this for sdw_regmap? I am not sure I follow the flows...

Thanks @plbossart. On the second thought, I think we should set both rt5682->sdw_regmap and rt5682->regmap cache only. Because 1. rt5682_clock_config uses rt5682->sdw_regmap directly. 2. If we set rt5682->sdw_regmap only, rt5682_sdw_read and rt5682_sdw_write won't get/set the right value through rt5682->sdw_regmap.

File: sound/soc/codecs/rt5682-sdw.c [hunk 2]
```diff
@@ -770,6 +773,7 @@ static int __maybe_unused rt5682_dev_resume(struct device *dev)
 
 regmap_sync:
 	slave->unattach_request = 0;
+	regcache_cache_only(rt5682->sdw_regmap, false);
```
Comment (plbossart) [inline sound/soc/codecs/rt5682-sdw.c:776]: should we do a regcache_sync(rt5682->sdw_regmap); as well?

**Comment by shumingfan** [comment]
@bardliao @plbossart 
Could we do the modification like below?
```
@@ -625,8 +625,8 @@ static int rt5682_clock_config(struct device *dev)
                return -EINVAL;
        }

-       regmap_write(rt5682->sdw_regmap, 0xe0, value);
-       regmap_write(rt5682->sdw_regmap, 0xf0, value);
+       sdw_write_no_pm(rt5682->slave, 0xe0, value);
+       sdw_write_no_pm(rt5682->slave, 0xf0, value);
```

After this modification, the read/write operations only use the rt5682->regmap. 
We could take care of the cache state of rt5682->regmap only.

**Comment by plbossart** [comment]
> After this modification, the read/write operations only use the rt5682->regmap

Not following @shumingfan, the routines rt5682_sdw_read() and rt5682_sdw_write() still use the sdw_regmap?

That said, I don't think there's a need for a regmap here, the information is one-way and never cached, is it?

**Comment by bardliao** [comment]
> > After this modification, the read/write operations only use the rt5682->regmap
> 
> Not following @shumingfan, the routines rt5682_sdw_read() and rt5682_sdw_write() still use the sdw_regmap?
> 
> That said, I don't think there's a need for a regmap here, the information is one-way and never cached, is it?

@plbossart  Do you mean we can get rid of rt5682->sdw_regmap and use sdw_write_no_pm directly? As far as I remember, using regmap_read/write with rt5682->sdw_regmap is to prevent using the IO routing directly in codec driver. That was an ask from community. I don't know if the rule is still there because I do see sdw_write/read_no_pm is used in some codec drivers.

**Comment by plbossart** [comment]
@bardliao Look at the code for rt5682_sdw_read() and rt5682_sdw_write() , it makes no sense for regmap. it's an indirection so there's no benefits that I can see. It's just added complexity for a couple of registers that are used in 'one-way' commands.

**Comment by shumingfan** [comment]
The rt5682->regmap uses 16 register bits and 16 value bits.
This regmap could be easy to map the registers to the datasheet.
The rt5682->sdw_regmap uses 32 register bits and 8 value bits for SdW registers.
I think it is necessary to use the separate two regmap to handle.
The rt711 non-SDCA codec driver uses the same way.

I just want the sdw_regmap to be used in the .reg_read/.reg_write callback only.
All read/write operations in the codec driver except mipi-defined registers (0xe0/0xf0) will use the rt5682->regmap only.
If the codec driver set the rt5682->regmap as the cache_only state, the R/W operation will not touch the sdw_regmap.

**Comment by plbossart** [comment]
> The rt5682->regmap uses 16 register bits and 16 value bits. This regmap could be easy to map the registers to the datasheet. The rt5682->sdw_regmap uses 32 register bits and 8 value bits for SdW registers. I think it is necessary to use the separate two regmap to handle. The rt711 non-SDCA codec driver uses the same way.
> 
> I just want the sdw_regmap to be used in the .reg_read/.reg_write callback only. All read/write operations in the codec driver except mipi-defined registers (0xe0/0xf0) will use the rt5682->regmap only. If the codec driver set the rt5682->regmap as the cache_only state, the R/W operation will not touch the sdw_regmap.

Sorry @shumingfan , not following the explanations. Maybe it's best if you send a PR, that will more clearly show the intent?

**Comment by plbossart** [comment]
@bardliao @shumingfan Can you guys chat and suggest a solution for RT5682 handling? 
There's this PR https://github.com/thesofproject/linux/pull/4469 and and alternate one https://github.com/thesofproject/linux/pull/4473

I have no value in the conversation, just want the pm_runtime fixes to be sent upstream in this kernel cycle

**Comment by bardliao** [comment]
> @bardliao @shumingfan Can you guys chat and suggest a solution for RT5682 handling? There's this PR #4469 and and alternate one #4473
> 
> I have no value in the conversation, just want the pm_runtime fixes to be sent upstream in this kernel cycle

@plbossart, @shumingfan agree to go with this PR. We think it will be less discussion in upstream and easier to be applied.

**Review by shumingfan — APPROVED** [review]

File: sound/soc/codecs/rt5682-sdw.c (hunk 2 above)
Comment (plbossart) [reply sound/soc/codecs/rt5682-sdw.c:776]: @bardliao if we treat both regmaps at the same time, then we're missing a regcache_sync(rt5682->sdw_regmap) below, no?

Comment (bardliao) [reply sound/soc/codecs/rt5682-sdw.c:776]: > @bardliao if we treat both regmaps at the same time, then we're missing a regcache_sync(rt5682->sdw_regmap) below, no?

@plbossart No, we don't do regcache_sync(rt5682->sdw_regmap);. The cache type of sdw_regmap is REGCACHE_NONE.

**Review by plbossart — APPROVED** [review]
