### PR TITLE
ASoC: SOF: Intel: mtl: fix page fault with dspless mode

### LINKED ISSUE #4279: [MTL] DSPless mode cause page fault
I'm using latest topic/sof-dev, b64d8f76d5d639c8346eef96eb334a115d6edda2
Tested with TGL and MTL. Only MTL has the problem.

set sof_debug for dspless
`options snd-sof sof_debug=0x8001`

Kernel detect the bit and switching to DSPless mode
```
[    8.620021] sof-audio-pci-intel-mtl 0000:00:1f.3: sof_debug value: 0x8001
[    8.620024] sof-audio-pci-intel-mtl 0000:00:1f.3: Switching to DSPless mode
```

It ends up with page fault
```
[   70.390393] BUG: unable to handle page fault for address: 0000000000001108
[   70.390401] #PF: supervisor read access in kernel mode
[   70.390405] #PF: error_code(0x0000) - not-present page
[   70.390410] PGD 0 P4D 0
[   70.390416] Oops: 0000 [#1] PREEMPT SMP NOPTI
[   70.390413] snd_sof_intel_hda:hda_codec_probe: sof-audio-pci-intel-mtl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0245
[   70.390423] CPU: 1 PID: 1661 Comm: irq/150-AudioDS Tainted: G        W          6.3.0-rc2-daily-default-20230404-0-gb64d8f76d5d6 #dev
[   70.390430] Hardware name: Intel Corporation Meteor Lake Client Platform/MTL-P DDR5 SODIMM SBS RVP, BIOS MTLPFWI1.R00.3064.D81.2302110734 02/11/2023
[   70.390434] RIP: 0010:mtl_dsp_check_ipc_irq+0x108/0x120 [snd_sof_intel_hda_common]
[   70.390486] Code: 74 0e 48 8b 78 08 89 da 48 89 ee e8 d2 00 ff ff 65 ff 0d 83 73 64 3f 75 85 e8 14 cc 05 f0 e9 7b ff ff ff 8b 1e e9 72 ff ff ff <8b> 06 e9 31 ff ff ff e8 fc cb 05 f0 eb 90 66 2e 0f 1f 84 00 00 00
[   70.390494] RSP: 0018:ffffb2d04383fe50 EFLAGS: 00010246
[   70.390500] RAX: 0000000000000000 RBX: ffffa092c743b768 RCX: 0000000000000000
[   70.390505] RDX: 0000000000000000 RSI: 0000000000001108 RDI: ffffa092c8a01828
[   70.390509] RBP: ffffa092c8a01828 R08: 0000000000000000 R09: 0000000000000000
[   70.390514] R10: 0000000000000001 R11: 0000000000000003 R12: ffffffffc0baa540
[   70.390518] R13: 0000000000000096 R14: ffffa092c8aff028 R15: ffffffffb0d191b0
[   70.390523] FS:  0000000000000000(0000) GS:ffffa0964dc00000(0000) knlGS:0000000000000000
[   70.390529] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   70.390534] CR2: 0000000000001108 CR3: 000000010b9ec003 CR4: 0000000000f70ee0
[   70.390539] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   70.390543] DR3: 0000000000000000 DR6: 00000000ffff07f0 DR7: 0000000000000400
[   70.390548] PKRU: 55555554
[   70.390551] Call Trace:
[   70.390557]  <TASK>
[   70.390562]  hda_dsp_interrupt_thread+0x5d/0x440 [snd_sof_intel_hda_common]
[   70.390605]  irq_thread_fn+0x21/0x60
[   70.390619]  ? irq_thread+0xb9/0x200
[   70.390629]  irq_thread+0x107/0x200
[   70.390638]  ? __kthread_parkme+0x1e/0xa0
[   70.390645]  ? __pfx_irq_thread+0x10/0x10
[   70.390654]  ? __pfx_irq_thread_dtor+0x10/0x10
[   70.390664]  ? __pfx_irq_thread+0x10/0x10
[   70.390673]  kthread+0xe5/0x110
[   70.390680]  ? __pfx_kthread+0x10/0x10
[   70.390689]  ret_from_fork+0x29/0x50
```

### PR DESCRIPTION
**Pull request by fredoh9**
Nothing to do in dsp irq in DSPless mode.

fixes: https://github.com/thesofproject/linux/issues/4279

### CODE REVIEW

File: sound/soc/sof/intel/mtl.c [hunk 1]
```diff
@@ -60,6 +60,9 @@ bool mtl_dsp_check_ipc_irq(struct snd_sof_dev *sdev)
 	u32 irq_status;
 	u32 hfintipptr;
 
+	if(sdev->dspless_mode_selected)
```
Comment (ranj063) [inline sound/soc/sof/intel/mtl.c]: need a space after if in both paces

**Review by ranj063 — DISMISSED** [review]

**Review by ujfalusi — DISMISSED** [review]
This should be sent as a fix upstream (the support is in linux-next now).

I thought it had been tested on MTL, that's why I sent it without much hesitation.

Nice find!

File: sound/soc/sof/intel/mtl.c [hunk 2]
```diff
@@ -581,6 +584,9 @@ static void mtl_ipc_dump(struct snd_sof_dev *sdev)
 
 static int mtl_dsp_disable_interrupts(struct snd_sof_dev *sdev)
 {
+	if (sdev->dspless_mode_selected)
+		return 0;
+
```
Comment (plbossart) [inline sound/soc/sof/intel/mtl.c]: we should have this test inside mtl_disable_ipc_interrupts() for consistency with the existing code in hda-dsp.c

Alternate proposal:

````diff
diff --git a/sound/soc/sof/intel/mtl.c b/sound/soc/sof/intel/mtl.c
index fe9b6671a194..7f72502e86cc 100644
--- a/sound/soc/sof/intel/mtl.c
+++ b/sound/soc/sof/intel/mtl.c
@@ -60,6 +60,9 @@ bool mtl_dsp_check_ipc_irq(struct snd_sof_dev *sdev)
        u32 irq_status;
        u32 hfintipptr;
 
+       if (sdev->dspless_mode_selected)
+               return false;
+
        /* read Interrupt IP Pointer */
        hfintipptr = snd_sof_dsp_read(sdev, HDA_DSP_BAR, MTL_HFINTIPPTR) & MTL_HFINTIPPTR_PTR_MASK;
        irq_status = snd_sof_dsp_read(sdev, HDA_DSP_BAR, hfintipptr + MTL_DSP_IRQSTS);
@@ -120,6 +123,9 @@ void mtl_enable_ipc_interrupts(struct snd_sof_dev *sdev)
        struct sof_intel_hda_dev *hda = sdev->pdata->hw_pdata;
        const struct sof_intel_dsp_desc *chip = hda->desc;
 
+       if (sdev->dspless_mode_selected)
+               return;
+
        /* enable IPC DONE and BUSY interrupts */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR, chip->ipc_ctl,
                                MTL_DSP_REG_HFIPCXCTL_BUSY | MTL_DSP_REG_HFIPCXCTL_DONE,
@@ -131,6 +137,9 @@ void mtl_disable_ipc_interrupts(struct snd_sof_dev *sdev)
        struct sof_intel_hda_dev *hda = sdev->pdata->hw_pdata;
        const struct sof_intel_dsp_desc *chip = hda->desc;
 
+       if (sdev->dspless_mode_selected)
+               return;
+
        /* disable IPC DONE and BUSY interrupts */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR, chip->ipc_ctl,

````
[mtl.diff.txt](https://github.com/thesofproject/linux/files/11159326/mtl.diff.txt)

**Review by plbossart — COMMENTED** [review]
Nice catch @fredoh9 but see alternate proposal below - minor change on where we test the dspless mode.

File: sound/soc/sof/intel/mtl.c (hunk 2 above)
Comment (fredoh9) [reply sound/soc/sof/intel/mtl.c]: @plbossart I'm still having page fault with this call stack. I need to handle same thing in mtl_enable_sdw_irq()

```
[   72.947570] Call Trace:
[   72.947576]  <TASK>
[   72.947582]  snd_sof_dsp_update_bits+0x4d/0x80 [snd_sof]
[   72.947614]  mtl_enable_sdw_irq+0x35/0x190 [snd_sof_intel_hda_common]
[   72.947645]  mtl_dsp_disable_interrupts+0x14/0x60 [snd_sof_intel_hda_common]
[   72.947670]  hda_suspend+0x4c/0x150 [snd_sof_intel_hda_common]
[   72.947696]  ? __lock_acquire.constprop.0+0x117/0x690
[   72.947707]  hda_dsp_runtime_suspend+0x4c/0xe0 [snd_sof_intel_hda_common]
[   72.947729]  sof_suspend.isra.0+0xd8/0x2d0 [snd_sof]
[   72.947749]  pci_pm_runtime_suspend+0x5f/0x1b0
[   72.947757]  ? __pfx_pci_pm_runtime_suspend+0x10/0x10
```

Comment (fredoh9) [reply sound/soc/sof/intel/mtl.c]: mtl_enable_interrupts() needs that too, i will push my update soon

```
[   73.348878] RIP: 0010:mtl_enable_interrupts+0x291/0x360 [snd_sof_intel_hda_common]
[   73.348921] Code: e8 d4 d3 0a e7 e9 cf fe ff ff 48 8b 33 45 89 e0 b9 40 11 00 00 48 c7 c2 90 8e ba c0 48 c7 c7 28 5e bb c0 e8 b1 d3 0a e7 eb a1 <44> 8b 26 e9 b5 fd ff ff 44 8b 2e e9 9a fe ff ff 44 8b 26 eb 8a 48
...
[   73.348954] Call Trace:
[   73.348959]  <TASK>
[   73.348964]  hda_suspend+0x4c/0x150 [snd_sof_intel_hda_common]
[   73.348984]  ? __lock_acquire.constprop.0+0x117/0x690
[   73.348992]  hda_dsp_runtime_suspend+0x4c/0xe0 [snd_sof_intel_hda_common]
[   73.349011]  sof_suspend.isra.0+0xd8/0x2d0 [snd_sof]
[   73.349047]  pci_pm_runtime_suspend+0x5f/0x1b0
[   73.349055]  ? __pfx_pci_pm_runtime_suspend+0x10/0x10
```

Comment (plbossart) [reply sound/soc/sof/intel/mtl.c]: thanks @fredoh9 

I think it's because we we HDA_DSP_BAR in mtl_enable_sdw_irq(). That's not initialized in dspless mode, only HDA_DSP_HDA_BAR is.

It's the same problem in mtl_enable_interrupts().

But I don't think there's any reason why this is required, IIRC the SoundWire bits are shadowed in the host and DSP BAR, so we could very well use the host one.

let me look into this, this could be a mistake in the code.

Comment (plbossart) [reply sound/soc/sof/intel/mtl.c]: Actually no, I don't see those registers in the host BAR. 

What looks required is this

````diff
diff --git a/sound/soc/sof/intel/mtl.c b/sound/soc/sof/intel/mtl.c
index fe9b6671a194..908aac928d8d 100644
--- a/sound/soc/sof/intel/mtl.c
+++ b/sound/soc/sof/intel/mtl.c
@@ -60,6 +60,9 @@ bool mtl_dsp_check_ipc_irq(struct snd_sof_dev *sdev)
        u32 irq_status;
        u32 hfintipptr;
 
+       if (sdev->dspless_mode_selected)
+               return false;
+
        /* read Interrupt IP Pointer */
        hfintipptr = snd_sof_dsp_read(sdev, HDA_DSP_BAR, MTL_HFINTIPPTR) & MTL_HFINTIPPTR_PTR_MASK;
        irq_status = snd_sof_dsp_read(sdev, HDA_DSP_BAR, hfintipptr + MTL_DSP_IRQSTS);
@@ -120,6 +123,9 @@ void mtl_enable_ipc_interrupts(struct snd_sof_dev *sdev)
        struct sof_intel_hda_dev *hda = sdev->pdata->hw_pdata;
        const struct sof_intel_dsp_desc *chip = hda->desc;
 
+       if (sdev->dspless_mode_selected)
+               return;
+
        /* enable IPC DONE and BUSY interrupts */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR, chip->ipc_ctl,
                                MTL_DSP_REG_HFIPCXCTL_BUSY | MTL_DSP_REG_HFIPCXCTL_DONE,
@@ -131,6 +137,9 @@ void mtl_disable_ipc_interrupts(struct snd_sof_dev *sdev)
        struct sof_intel_hda_dev *hda = sdev->pdata->hw_pdata;
        const struct sof_intel_dsp_desc *chip = hda->desc;
 
+       if (sdev->dspless_mode_selected)
+               return;
+
        /* disable IPC DONE and BUSY interrupts */
        snd_sof_dsp_update_bits(sdev, HDA_DSP_BAR, chip->ipc_ctl,
                                MTL_DSP_REG_HFIPCXCTL_BUSY | MTL_DSP_REG_HFIPCXCTL_DONE, 0);
@@ -143,6 +152,9 @@ static void mtl_enable_sdw_irq(struct snd_sof_dev *sdev, bool enable)
        u32 val;
        int ret;
 
+       if (sdev->dspless_mode_selected)
+               return;
+
        /* Enable/Disable SoundWire interrupt */
        mask = MTL_DSP_REG_HfSNDWIE_IE_MASK;
        if (enable)
@@ -170,6 +182,9 @@ int mtl_enable_interrupts(struct snd_sof_dev *sdev, bool enable)
        u32 val;
        int ret;
 
+       if (sdev->dspless_mode_selected)
+               return;
+
        /* read Interrupt IP Pointer */
        hfintipptr = snd_sof_dsp_read(sdev, HDA_DSP_BAR, MTL_HFINTIPPTR) & MTL_HFINTIPPTR_PTR_MASK;
 
````

[mtl.diff.txt](https://github.com/thesofproject/linux/files/11162588/mtl.diff.txt)

The benefit of checking all functions is that this will also work for LNL, where we reuse MTL functions.

**Comment by greg-intel** [comment]
SOFCI TEST

Trying to temporarily bypass the issue that's been causing the sofkernel failures.

File: sound/soc/sof/intel/mtl.c (hunk 2 above)
Comment (fredoh9) [reply sound/soc/sof/intel/mtl.c]: @plbossart your suggestion is same as my last update, can you double check and approve this?

**Comment by greg-intel** [comment]
SOFCI TEST

**Review by ranj063 — APPROVED** [review]

**Review by plbossart — APPROVED** [review]
