### PR TITLE
soundwire: mipi_disco: add MIPI-specific property_read_bool() helpers

### LINKED ISSUE #5129: [SoundWire] RT712 VA jack detection is broken
Not sure what happened, but jack detection no longer works with topic/sof-dev 

dc9dd7b28159 ("ASoC: SOF: Intel: hda: refactoring topology name fixup for SDW mach")

SKU Number: 0CC7

@bardliao @ujfalusi FYI

### PR DESCRIPTION
**Pull request by plbossart**
The existing device/fwnode_property_read_bool() helpers only check if the property is present.

The MIPI DisCo for SoundWire specification allows properties to be exposed with a value of 'false'. Using the standard helpers to retrieve the MIPI-defined properties causes all kinds of logical inversions - such as jack detection broken when the device properties are read in Realtek codec drivers.

This patch adds new MIPI/SoundWire helpers which first check if the property is present, and then return the actual value extracted from platform firmware.

Modifying the default property handling was considered as a possible solution, but it could lead to other types of logical inversions breaking 'working' setups. The path of least resistance was chosen, with MIPI-specific helpers which can be tested and with no side effects outside of the SoundWire subsystem.

Closes: https://github.com/thesofproject/linux/issues/5129

### CODE REVIEW

**Comment by plbossart** [comment]
@andy-shev FYI

File: drivers/soundwire/mipi_disco.c [hunk 1]
```diff
@@ -23,6 +23,26 @@
...
 
+static bool mipi_fwnode_property_read_bool(const struct fwnode_handle *fwnode,
+					   const char *propname)
+{
+	int ret;
+	u8 val;
+
+	if (!fwnode_property_present(fwnode, propname))
+		return false;
+	ret = fwnode_property_read_u8_array(fwnode, propname, &val, 1);
```
Comment (andy-shev) [inline drivers/soundwire/mipi_disco.c:34]: Hmm… we should be careful with endianness here. DT keeps values in BE32 format, and if this code ever be run on OF based system, it might be problematic. But despite that, it’s always better to be in a robust side. Up to you , though, how to improve this, if necessary at all.

Comment (plbossart) [reply drivers/soundwire/mipi_disco.c:34]: so far all MIPI DisCo definitions rely on ACPI, there's no support for DeviceTree at all. The main reason is that no one on the committee knew anything about DeviceTree, all we had was ACPI tools. Maybe in a future revision this will change, but that depends on participation in a standard so will take time.

**Review by bardliao — APPROVED** [review]

File: drivers/soundwire/mipi_disco.c (hunk 1 above)
Comment (plbossart) [reply drivers/soundwire/mipi_disco.c:34]: I will add a note though to mention the endianess and make sure this is documented.

That's also another reason why it makes sense to keep those helpers MIPI/DisCo specific, I am not sure how we could change the common helper.

Comment (plbossart) [reply drivers/soundwire/mipi_disco.c:34]: commit message modified to add note on endianness, thanks @andy-shev for the feeedback.
