### PR TITLE
Fix Pause/Release Xrun for HDMI pipelines

### LINKED ISSUE #1160: [BUG][playback] Underrun after pause-release on HDA Link pipelines
There is a random underrun after pause-release sequence done on HDA Link pipelines. Repro rate is under 5%. It shows up during CI tests. It looks like Link DMA doesn't copy anything after release, so DSP has no free space for copying data from buffer.
There are two possibilities that we could check:
1. See if the right Link DMA is started by kernel after release. I remember that we've already had such problem before.
2. Fix sequence of pausing/stopping the pipelines. Kernel should first send pause/stop ipc to the FW and only then deassert stream RUN bit. Doing it other way around can potentially lead to incrementing Gateway FPI by the DSP, when RUN bit is already 0 and such behavior can have undefined consequences.

### PR DESCRIPTION
**Pull request by ranj063**
Currently, SND_SOC_DPCM_TRIGGER_PRE/POST determines the order in which FE DAI and BE DAI are triggered. In the case of SND_SOC_DPCM_TRIGGER_PRE, the FE DAI is triggered before
the BE DAI and in the case of SND_SOC_DPCM_TRIGGER_POST, the BE DAI is triggered before the FE DAI.

With the SOF driver, during playback, the FW expects the BE DAI to be triggered before the FE DAI during the START trigger. This can be addressed by setting the trigger order for the FE dai
link to SND_SOC_DPCM_TRIGGER_POST. But during the STOP trigger, retaining the same order of triggering the BE DAI before the FE DAI results in a DSP panic.

The issue can be fixed by mirroring the trigger order of FE and BE DAI's during the START and STOP trigger. So, with the trigger order set to SND_SOC_DPCM_TRIGGER_PRE, the FE DAI will be
trigger first during START and the BE DAI will be triggered first during STOP. Conversely, with the trigger order set to SND_SOC_DPCM_TRIGGER_POST, the BE DAI will be triggered first during START and the FE DAI will be triggered first during the STOP command.

Fixes #1160

### CODE REVIEW

**Comment by tlauda** [comment]
@ranj063 Fixed the panic in case some weird sequence will happen in the future: https://github.com/thesofproject/sof/pull/1902.

**Comment by ranj063** [comment]
> @ranj063 Fixed the panic in case some weird sequence will happen in the future: [thesofproject/sof#1902](https://github.com/thesofproject/sof/pull/1902).

@tlauda thanks!

File: sound/soc/soc-pcm.c [hunk 1]
```diff
@@ -2282,42 +2282,91 @@ int dpcm_be_dai_trigger(struct snd_soc_pcm_runtime *fe, int stream,
 }
 EXPORT_SYMBOL_GPL(dpcm_be_dai_trigger);
 
+static int dpcm_fe_dai_trigger_fe_first(struct snd_pcm_substream *substream,
```
Comment (kv2019i) [inline sound/soc/soc-pcm.c]: @ranj063 phew, this makes my head burn! :) I mean "fe_trigger_fe_first" is a bit hard to understand. If we have a function to trigger "fe", one would expect this to trigger "fe" and not something else.

Anyways, the commit message does makes sense. I guess the big question are existing ok with change the the release ordering, or should DSP/machien drivers to have ability to specify PRE-versus-POST for each direction separately. I think you need to send to alsa-devel for this.

File: sound/soc/sof/topology.c [hunk 2]
```diff
@@ -2853,6 +2853,10 @@ static int sof_link_load(struct snd_soc_component *scomp, int index,
 	if (!link->no_pcm) {
 		link->nonatomic = true;
 
+		/* set trigger order */
+		link->trigger[0] = SND_SOC_DPCM_TRIGGER_POST;
```
Comment (kv2019i) [inline sound/soc/sof/topology.c:2936]: Shouldn't this be set in machin drivers, or at least in Intel DSP specific code (as this is a Intel DSP limitation)? I see most drivers setting this in machine drivers.

File: sound/soc/soc-pcm.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/soc-pcm.c]: @kv2019i unfortunately when a PCM is triggered it is always done through the FE. So the function to trigger FE takes care of triggering the corresponding BE's too. Now the ordering for PRE and POST work just fine for most cases. So I am a bit nervous about this change affecting other drivers. My first thought was to use the BESPOKE trigger but if you look at soc_pcm_bespoke_trigger(), it doesnt really have to do anything to do with the ordering of the FE/BE DAI's at all. In fact it just invokes the bespoke_triggers implemented by the dai drivers. 
And AFAICT, there are no drivers using this.

Anyway I will add some more context to the commit message and send this to alsa-devel

File: sound/soc/sof/topology.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/sof/topology.c:2936]: @kv2019i SOF does not define the FE DAI links in the machine driver. They are created when the pcm elems in topology are parsed.

**Comment by ranj063** [comment]
send to alsa-devl too

**Comment by tlauda** [comment]
@ranj063 Is there a chance to get it merged soon taking into an account, that it fixes one of the CI issues.

**Comment by plbossart** [comment]
> @ranj063 Is there a chance to get it merged soon taking into an account, that it fixes one of the CI issues.

I was planning to have this merged with the weekly upstream stuff, but since @ranj063 sent the code as RFC it was not picked up.

@ranj063 do you want to provide an update here and send an update to alsa-devel?

**Comment by RanderWang** [comment]
@ranj063   I understood your work. Now SND_SOC_DPCM_TRIGGER_POST is processed dynamically for start and stop case. The usage is different with original design, which is not perfect. 

I have an idea to discuss with you, like adding flags 
SND_SOC_DPCM_TRIGGER_START_POST,
SND_SOC_DPCM_TRIGGER_START_PRE,
SND_SOC_DPCM_TRIGGER_STOP_POST,
SND_SOC_DPCM_TRIGGER_STOP_PRE.

then trigger = SND_SOC_DPCM_TRIGGER_START_POST | SND_SOC_DPCM_TRIGGER_STOP_PRE 
...

A problem is: there are so many status.

**Comment by ranj063** [comment]
> @ranj063 Is there a chance to get it merged soon taking into an account, that it fixes one of the CI issues.

@tlauda sure. I will update the patch based on suggestions today and send an updated version to alsa-devel. 

@plbossart the reason I was delaying sending the update is because I havent done any testing on legacy drivers. I dont have any devices to try that and I'm wondering if @mengdonglin can help with that.

**Comment by plbossart** [comment]
> > @ranj063 Is there a chance to get it merged soon taking into an account, that it fixes one of the CI issues.
> 
> @tlauda sure. I will update the patch based on suggestions today and send an updated version to alsa-devel.
> 
> @plbossart the reason I was delaying sending the update is because I havent done any testing on legacy drivers. I dont have any devices to try that and I'm wondering if @mengdonglin can help with that.

well, if you are changing the behavior and adding PM support on devices you don't have access to, it's not going to go well... You do need to have access to BYT/CHT devices, it's really a prerequisite.

**Comment by wenqingfu** [comment]
SOFCI TEST

**Comment by ranj063** [comment]
> well, if you are changing the behavior and adding PM support on devices you don't have access to, it's not going to go well... You do need to have access to BYT/CHT devices, it's really a prerequisite.

@plbossart BYT/CHT device PM support is being tested with @cujomalainey 's help. So there are no issues there. I dont have access to ASUS T100 and I doubt we have enough lying around to get access to one for me.

For this particular issue, I am working on getting it tested on KBL/GLK devices for now.

**Comment by wenqingfu** [comment]
The latest CI testing (as of  "2019-10-11 16:42:37.339213 UTC")  seems not bad.

There is a nasty bug on CI result processing, which ends up random number of platforms shown as "not tested" from time to time. In fact, they have been tested. In such case, please re-trigger the CI testing with 'SOFCI TEST'. 

@xiulipan @fredoh9

**Comment by ranj063** [comment]
@plbossart I have updated this based on your suggestions on alsa-devel. 

I have also tested it so far on my KBL based XPS13 with no regressions. More tests are underway and I will update soon.

**Comment by ranj063** [comment]
> @ranj063 I understood your work. Now SND_SOC_DPCM_TRIGGER_POST is processed dynamically for start and stop case. The usage is different with original design, which is not perfect.
> 
> I have an idea to discuss with you, like adding flags
> SND_SOC_DPCM_TRIGGER_START_POST,
> SND_SOC_DPCM_TRIGGER_START_PRE,
> SND_SOC_DPCM_TRIGGER_STOP_POST,
> SND_SOC_DPCM_TRIGGER_STOP_PRE.
> 
> then trigger = SND_SOC_DPCM_TRIGGER_START_POST | SND_SOC_DPCM_TRIGGER_STOP_PRE
> ...
> 
> A problem is: there are so many status.

@RanderWang this would confuse people more with so many POST/PRE's. I am getting this tested with legacy drivers right now. If there are no regressions I think the proposed change should be good to go.

**Comment by plbossart** [comment]
>     well, if you are changing the behavior and adding PM support on
>     devices you don't have access to, it's not going to go well... You
>     do need to have access to BYT/CHT devices, it's really a prerequisite.
> 
> @plbossart <https://github.com/plbossart> BYT/CHT device PM support is 
> being tested with @cujomalainey <https://github.com/cujomalainey> 's 
> help. So there are no issues there. I dont have access to ASUS T100 and 
> I doubt we have enough lying around to get access to one for me.

Well I've asked that our team acquires or steals devices from other 
teams, and now we're stuck. Gah. If we don't have legacy test devices we 
should stop pretending we support those legacy devices...We've never 
going to deprecate legacy drivers with this level of testing (or lack 
thereof).

**Comment by cujomalainey** [comment]
@plbossart should we look into seeing if we can get some byt/cht devices to you guys? We still very much support them here so the upstream support would definitely be appreciated.

**Comment by plbossart** [comment]
On 10/11/19 1:17 PM, Curtis Malainey wrote:
> @plbossart <https://github.com/plbossart> should we look into seeing if 
> we can get some byt/cht devices to you guys? We still very much support 
> them here so the upstream support would definitely be appreciated.

That would help, but what I was referring to is getting access to 
non-Chromebook devices. There are fundamental differences between 
CoreBoot and EFI bios, and if we don't test both we'll have recurring 
issues for suspend-resume.

The devices I have that still work are
BYT Chromebook: Lenovo 100s
CHT Chromebook: Acer Cyan

BYT ASUS100 TA
BYT ASUS100 TAN (BYT-CR)
CHT ASUS100 HAN
CHT Dell Venue 8350

So I am covered, but I can test everything myself, others need to have 
similar setups.

**Comment by cujomalainey** [comment]
I'll add this to the list of things I plan on discussing with @lgirdwood when we meet in a couple weeks with @dgreid.

**Comment by RanderWang** [comment]
> > @ranj063 I understood your work. Now SND_SOC_DPCM_TRIGGER_POST is processed dynamically for start and stop case. The usage is different with original design, which is not perfect.
> > I have an idea to discuss with you, like adding flags
> > SND_SOC_DPCM_TRIGGER_START_POST,
> > SND_SOC_DPCM_TRIGGER_START_PRE,
> > SND_SOC_DPCM_TRIGGER_STOP_POST,
> > SND_SOC_DPCM_TRIGGER_STOP_PRE.
> > then trigger = SND_SOC_DPCM_TRIGGER_START_POST | SND_SOC_DPCM_TRIGGER_STOP_PRE
> > ...
> > A problem is: there are so many status.
> 
> @RanderWang this would confuse people more with so many POST/PRE's. I am getting this tested with legacy drivers right now. If there are no regressions I think the proposed change should be good to go.

Yes,  I agree with you. I just shared you my idea. Please go ahead with your patch.

**Comment by wenqingfu** [comment]
SOFCI TEST

**Comment by YvonneYang2** [comment]
PR #1277 can fix https://github.com/thesofproject/linux/issues/1329 and partly optimize https://github.com/thesofproject/sof/issues/1925. And no side effect found.

Only below steps can reproduce https://github.com/thesofproject/sof/issues/1925 :
Aplay 0,0 +Arecord 0,1 --> background and foreground on arecord 0,1 --> I/O error

**Comment by ranj063** [comment]
@plbossart could we possibly merge this PR to sof-dev to unblock CI while the tests with legacy driver is ongoing?
