### PR TITLE
ASoC: SOF: Intel: hda: enable DMI L1 for d0i3-compatible streams

### LINKED ISSUE #2678: TGL: Active System State:  DUT is not able to go below PC2 and causing Power regression
DUT:  TGL Chrome System
SOF fw: V11-release
Kernel:  Google kernel 5.4 

Test Step:
1) Boot DUT -> System is in S0 (i.e. Active state)
2) arecord -Dhw:0,100 -M -N -c 2 -f S24_LE -r 16000 --buffer-size=96000 tmp.wav -d 10
3) Check : "/sys/kernel/debug/pmc_core/package_cstate_show"
  Only "Package C2" is increasing. Not able to go below PC2.
4) Also, Power team checked: it is causing a very high power addition (app: ~800mW).

Note:
a) 
Without "wov capture ON",   DUT is able to go to "Package C6 /C8"

b) This power impact is there for all System scenarios 
   e.g.
   Idle + WoV-ON
   Playback + WoV-ON
   Meet Call + WoV-ON

### PR DESCRIPTION
**Pull request by ranj063**
DMI L1 entry is currently disabled whenever any capture stream is
opened to prevent xruns during pause/resume scenarios. But, in
order to maximise power savings for the wake-on-voice usecase,
DMI L1 entry should be enabled. Therefore, exclude the
D0i3-compatible capture streams from disabling DMI L1 entry
when they are opened.

Fixes #2678

### CODE REVIEW

File: sound/soc/sof/intel/hda.h [hunk 1]
```diff
@@ -562,8 +562,9 @@ bool hda_dsp_check_ipc_irq(struct snd_sof_dev *sdev);
 bool hda_dsp_check_stream_irq(struct snd_sof_dev *sdev);
 
 struct hdac_ext_stream *
-	hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction);
-int hda_dsp_stream_put(struct snd_sof_dev *sdev, int direction, int stream_tag);
+	hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction, bool d0i3_compatible);
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda.h]: Could be one line?

File: sound/soc/sof/intel/hda-stream.c [hunk 2]
```diff
@@ -223,14 +224,14 @@ int hda_dsp_stream_put(struct snd_sof_dev *sdev, int direction, int stream_tag)
 		if (s->direction == direction && s->stream_tag == stream_tag) {
 			s->opened = false;
 			found = true;
-		} else if (s->direction == SNDRV_PCM_STREAM_CAPTURE) {
+		} else if (s->direction == SNDRV_PCM_STREAM_CAPTURE && !d0i3_compatible) {
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda-stream.c]: I think we need to store information on whether stream is d0i3_compatible to "struct sof_intel_hda_stream" in stream_get(), and then in stream_put, use this information.

Now above you are going through all remaining open streams, but you don't know whether other streams are d0i3_compatible or not, so this won't quite work. For s->direction the logic works as we have stored the direction information for all stream. I think we need to do same for d0i3_compatible.

**Review by kv2019i — CHANGES_REQUESTED** [review]
A very good find! Having the DMI L1 logic inside current get/put starts to be a bit problematic, but I think this is still ok and this seems the cleanest option.

I did find one problem that needs to be addressed in put() logic.

File: sound/soc/sof/intel/hda-stream.c (hunk 2 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-stream.c]: nice catch @kv2019i . fixed now.

File: sound/soc/sof/intel/hda.h (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda.h]: nope, doesnt fit.

File: sound/soc/sof/intel/hda-pcm.c [hunk 3]
```diff
@@ -240,10 +249,19 @@ int hda_dsp_pcm_open(struct snd_sof_dev *sdev,
...
+	struct snd_sof_pcm *spcm;
 	int direction = substream->stream;
 	int ret;
 
+	spcm = snd_sof_find_spcm_dai(scomp, rtd);
+	if (!spcm) {
+		dev_err(sdev->dev, "error: can't find PCM with DAI ID %d\n", rtd->dai_link->id);
+		return -EINVAL;
+	}
+
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda-pcm.c]: spcm is not used in close(), so this can be dropped, right?

**Review by kv2019i — CHANGES_REQUESTED** [review]
One minor thing more...

File: sound/soc/sof/intel/hda-compress.c [hunk 4]
```diff
@@ -25,7 +25,7 @@ int hda_probe_compr_assign(struct snd_sof_dev *sdev,
 {
 	struct hdac_ext_stream *stream;
 
-	stream = hda_dsp_stream_get(sdev, cstream->direction);
+	stream = hda_dsp_stream_get(sdev, cstream->direction, false);
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-compress.c]: comment on commit message: 'exclude... from disabling'. can we reword as 'enable'?

File: sound/soc/sof/intel/hda-stream.c [hunk 5]
```diff
@@ -189,16 +189,18 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
 			"playback" : "capture");
 
 	/*
-	 * Disable DMI Link L1 entry when capture stream is opened.
+	 * Disable DMI Link L1 entry when non-d0i3-compatible capture stream is opened.
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-stream.c]: Prevent DMI Link L1 entry when non-d0i3-compatible capture stream is opened.

File: sound/soc/sof/intel/hda-stream.c [hunk 6]
```diff
@@ -224,13 +226,18 @@ int hda_dsp_stream_put(struct snd_sof_dev *sdev, int direction, int stream_tag)
...
+			hda_stream = container_of(stream, struct sof_intel_hda_stream, hda_stream);
+			if (!hda_stream->d0i3_compatible)
+				active_capture_stream = true;
 		}
 	}
 
 	spin_unlock_irq(&bus->reg_lock);
 
-	/* Enable DMI L1 entry if there are no capture streams open */
+	/* Enable DMI L1 entry if there are no non-d0i3-compatible capture streams open */
```
Comment (plbossart) [inline sound/soc/sof/intel/hda-stream.c]: Enter DMA L1 ...

File: sound/soc/sof/intel/hda-compress.c (hunk 4 above)
Comment (plbossart) [reply sound/soc/sof/intel/hda-compress.c]: I also find the 'entry disabled' wording odd, it's really the mode that is disabled so there is no transition.

**Review by plbossart — CHANGES_REQUESTED** [review]
Minor comments below

I keep wondering if the real solution is to enable S0/D0i3... if we care about power in S0, that would give us the best results.

**Comment by ranj063** [comment]
> I keep wondering if the real solution is to enable S0/D0i3... if we care about power in S0, that would give us the best results.

@plbossart we already have S0/D0i3 enabled by default. The problem we have would manifest even if the DSP werent in D0i3, for example: headset playback + wov. we should enable DMI L1 in this case even though the DSP is not in D0i3.

File: sound/soc/sof/intel/hda-stream.c (hunk 6 above)
Comment (kv2019i) [reply sound/soc/sof/intel/hda-stream.c]: How about "Allow DMI L1 entry if there are"? 

Writing to L1SEN doesn't cause DMI L1 entry, but allows controller to opportunistically enter L1 if DMAs are idle.

**Review by kv2019i — DISMISSED** [review]
Thanks, code is now ok. If the commit msg can be clarified, even better.

File: sound/soc/sof/intel/hda-stream.c [hunk 7]
```diff
@@ -224,13 +226,18 @@ int hda_dsp_stream_put(struct snd_sof_dev *sdev, int direction, int stream_tag)
...
+			hda_stream = container_of(stream, struct sof_intel_hda_stream, hda_stream);
+			if (!hda_stream->d0i3_compatible)
+				active_capture_stream = true;
 		}
 	}
 
 	spin_unlock_irq(&bus->reg_lock);
 
-	/* Enable DMI L1 entry if there are no capture streams open */
+	/* Enter DMI L1 if there are no non-d0i3-compatible capture streams open */
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda-stream.c]: "no non-d0i3-compatile" is bit of a mouthful, but I'm ok if you are :) 

If you make an additional spin, my proposal:
"Allow DMI L1 if all remaining streams support it */

**Review by kv2019i — DISMISSED** [review]
I'm good with this.

File: sound/soc/sof/intel/hda-stream.c (hunk 7 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-stream.c]: ack. done

**Comment by plbossart** [comment]
> > I keep wondering if the real solution is to enable S0/D0i3... if we care about power in S0, that would give us the best results.
> 
> @plbossart we already have S0/D0i3 enabled by default. The problem we have would manifest even if the DSP werent in D0i3, for example: headset playback + wov. we should enable DMI L1 in this case even though the DSP is not in D0i3.

We enter D0i3 on 'S0 suspend' which really means S0ix. Do we have any other way of entering D0i3 while *remaining* in S0 (no suspend)?

**Comment by ranj063** [comment]
> > > I keep wondering if the real solution is to enable S0/D0i3... if we care about power in S0, that would give us the best results.
> > 
> > 
> > @plbossart we already have S0/D0i3 enabled by default. The problem we have would manifest even if the DSP werent in D0i3, for example: headset playback + wov. we should enable DMI L1 in this case even though the DSP is not in D0i3.
> 
> We enter D0i3 on 'S0 suspend' which really means S0ix. Do we have any other way of entering D0i3 while _remaining_ in S0 (no suspend)?

@plbossart no we enter D0i3 in S0. After 5 seconds of sending an IPC, if there are only D0i3-compatible streams active, we always put the DSP in D0i3.

**Comment by kv2019i** [comment]
@plbossart I think the cost of disabling L1 is higher than expected for playback streams. We can't go to D0i3 as DSP is needed for playback but we want to enter DMI L1 between DMA bursts.

**Review by kv2019i — APPROVED** [review]

**Comment by plbossart** [comment]
> > We enter D0i3 on 'S0 suspend' which really means S0ix. Do we have any other way of entering D0i3 while _remaining_ in S0 (no suspend)?
> 
> @plbossart no we enter D0i3 in S0. After 5 seconds of sending an IPC, if there are only D0i3-compatible streams active, we always put the DSP in D0i3.

Ah right, I forgot that.

So just to be clear, has anyone verified that the use of L1 on capture/D0i3-compatible stream has no effect on power consumption in actual S0i1 cases?

**Comment by ranj063** [comment]
> > > We enter D0i3 on 'S0 suspend' which really means S0ix. Do we have any other way of entering D0i3 while _remaining_ in S0 (no suspend)?
> > 
> > 
> > @plbossart no we enter D0i3 in S0. After 5 seconds of sending an IPC, if there are only D0i3-compatible streams active, we always put the DSP in D0i3.
> 
> Ah right, I forgot that.
> 
> So just to be clear, has anyone verified that the use of L1 on capture/D0i3-compatible stream has no effect on power consumption in actual S0i1 cases?

@plbossart tests are on-going both system validation and PnP tests. @sathya-nujella can confirm the resutls once they're done

**Comment by plbossart** [comment]
> > So just to be clear, has anyone verified that the use of L1 on capture/D0i3-compatible stream has no effect on power consumption in actual S0i1 cases?
> 
> @plbossart tests are on-going both system validation and PnP tests. @sathya-nujella can confirm the resutls once they're done

Ack, let's merge when the results are in.

**Review by plbossart — DISMISSED** [review]
thanks for bearing with my questions @ranj063

**Comment by jairaj-arava** [comment]
> > > > We enter D0i3 on 'S0 suspend' which really means S0ix. Do we have any other way of entering D0i3 while _remaining_ in S0 (no suspend)?
> > > 
> > > 
> > > @plbossart no we enter D0i3 in S0. After 5 seconds of sending an IPC, if there are only D0i3-compatible streams active, we always put the DSP in D0i3.
> > 
> > 
> > Ah right, I forgot that.
> > So just to be clear, has anyone verified that the use of L1 on capture/D0i3-compatible stream has no effect on power consumption in actual S0i1 cases?
> 
> @plbossart tests are on-going both system validation and PnP tests. @sathya-nujella can confirm the resutls once they're done

@ranj063 I have verified the Google Hot word functionality in S0 and WOV in S0IX and they are working good and system enters into PC8 in S0. Even headset playback seems to be good.

We requested our power team to give the power data too, will update here once we have them.

**Comment by keyonjie** [comment]
@ranj063 thanks for the fix. Actually at my end I am using different change which verified also works. It looks simpler, just move the DMI L1 stuff from the suspend/resume helpers to the hda_dsp_set_D0_state(): D0I0->D0I3, enable DMI L1, D0I3->D0I0, disable DMI L1. The logic here is that if you want to enter low power D0I3, I will enable DMI L1 for you to save power, no matter what stream are active (those only D0i3-compatible streams active logic is hidden and controlled by the D0I0<->D0I3 switching logic).

Just for your reference.

```
diff --git a/sound/soc/sof/intel/hda-dsp.c b/sound/soc/sof/intel/hda-dsp.c
index 18ff1c2f5376e..3152ef4ebbfa1 100644
--- a/sound/soc/sof/intel/hda-dsp.c
+++ b/sound/soc/sof/intel/hda-dsp.c
@@ -393,6 +393,7 @@ static int hda_dsp_update_d0i3c_register(struct snd_sof_dev *sdev, u8 value)
 static int hda_dsp_set_D0_state(struct snd_sof_dev *sdev,
                                const struct sof_dsp_power_state *target_state)
 {
+       struct sof_intel_hda_dev *hda = sdev->pdata->hw_pdata;
        u32 flags = 0;
        int ret;
        u8 value = 0;
@@ -431,9 +432,22 @@ static int hda_dsp_set_D0_state(struct snd_sof_dev *sdev,
                    !hda_enable_trace_D0I3_S0 ||
                    sdev->system_suspend_target != SOF_SUSPEND_NONE)
                        flags = HDA_PM_NO_DMA_TRACE;
+
+               /* enable L1SEN to make sure the system can enter S0Ix */
+               hda->l1_support_changed =
+                       snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
+                                               HDA_VS_INTEL_EM2,
+                                               HDA_VS_INTEL_EM2_L1SEN,
+                                               HDA_VS_INTEL_EM2_L1SEN);
        } else {
                /* prevent power gating in D0I0 */
                flags = HDA_PM_PPG;
+
+               /* restore L1SEN bit */
+               if (hda->l1_support_changed)
+                       snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
+                                               HDA_VS_INTEL_EM2,
+                                               HDA_VS_INTEL_EM2_L1SEN, 0);
        }
 
        /* update D0I3C register */
@@ -706,7 +720,6 @@ static int hda_resume(struct snd_sof_dev *sdev, bool runtime_resume)
 
 int hda_dsp_resume(struct snd_sof_dev *sdev)
 {
-       struct sof_intel_hda_dev *hda = sdev->pdata->hw_pdata;
        struct pci_dev *pci = to_pci_dev(sdev->dev);
        const struct sof_dsp_power_state target_state = {
                .state = SOF_DSP_PM_D0,
@@ -749,12 +762,6 @@ int hda_dsp_resume(struct snd_sof_dev *sdev)
                        return ret;
                }
 
-               /* restore L1SEN bit */
-               if (hda->l1_support_changed)
-                       snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
-                                               HDA_VS_INTEL_EM2,
-                                               HDA_VS_INTEL_EM2_L1SEN, 0);
-
                /* restore and disable the system wakeup */
                pci_restore_state(pci);
                disable_irq_wake(pci->irq);
@@ -840,13 +847,6 @@ int hda_dsp_suspend(struct snd_sof_dev *sdev, u32 target_state)
                        return ret;
                }
 
-               /* enable L1SEN to make sure the system can enter S0Ix */
-               hda->l1_support_changed =
-                       snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
-                                               HDA_VS_INTEL_EM2,
-                                               HDA_VS_INTEL_EM2_L1SEN,
-                                               HDA_VS_INTEL_EM2_L1SEN);
-
 #if IS_ENABLED(CONFIG_SND_SOC_SOF_HDA)
                /* stop the CORB/RIRB DMA if it is On */
                if (bus->cmd_dma_state)
```

**Comment by ranj063** [comment]
> @ranj063 thanks for the fix. Actually at my end I am using different change which verified also works. It looks simpler, just move the DMI L1 stuff from the suspend/resume helpers to the hda_dsp_set_D0_state(): D0I0->D0I3, enable DMI L1, D0I3->D0I0, disable DMI L1. The logic here is that if you want to enter low power D0I3, I will enable DMI L1 for you to save power, no matter what stream are active (those only D0i3-compatible streams active logic is hidden and controlled by the D0I0<->D0I3 switching logic).

@keyonjie this is not enough. This will only fix the idle display ON case. What about headset playback+ wov?

**Comment by keyonjie** [comment]
> > @ranj063 thanks for the fix. Actually at my end I am using different change which verified also works. It looks simpler, just move the DMI L1 stuff from the suspend/resume helpers to the hda_dsp_set_D0_state(): D0I0->D0I3, enable DMI L1, D0I3->D0I0, disable DMI L1. The logic here is that if you want to enter low power D0I3, I will enable DMI L1 for you to save power, no matter what stream are active (those only D0i3-compatible streams active logic is hidden and controlled by the D0I0<->D0I3 switching logic).
> 
> @keyonjie this is not enough. This will only fix the idle display ON case. What about headset playback+ wov?

Oh, so do you mean we need to achieve low power consumption (via enabling DMI L1) for headset playback case also?

**Comment by ranj063** [comment]
> > > @ranj063 thanks for the fix. Actually at my end I am using different change which verified also works. It looks simpler, just move the DMI L1 stuff from the suspend/resume helpers to the hda_dsp_set_D0_state(): D0I0->D0I3, enable DMI L1, D0I3->D0I0, disable DMI L1. The logic here is that if you want to enter low power D0I3, I will enable DMI L1 for you to save power, no matter what stream are active (those only D0i3-compatible streams active logic is hidden and controlled by the D0I0<->D0I3 switching logic).
> > 
> > 
> > @keyonjie this is not enough. This will only fix the idle display ON case. What about headset playback+ wov?
> 
> Oh, so do you mean we need to achieve low power consumption (via enabling DMI L1) for headset playback case also?

Yes, we need to enable DMI L1 for any combination of playback and wov streams

File: sound/soc/sof/intel/hda.h [hunk 8]
```diff
@@ -471,6 +471,7 @@ struct sof_intel_hda_stream {
 	struct hdac_ext_stream hda_stream;
 	struct sof_intel_stream stream;
 	int host_reserved; /* reserve host DMA channel */
+	bool d0i3_compatible;
```
Comment (keyonjie) [inline sound/soc/sof/intel/hda.h]: how about name this to sth like dmi_l1_capable and then we set it true for DMA trace stream also?

**Comment by keyonjie** [comment]
> Yes, we need to enable DMI L1 for any combination of playback and wov streams

OK, then makes sense.

File: sound/soc/sof/intel/hda.h (hunk 8 above)
Comment (kv2019i) [reply sound/soc/sof/intel/hda.h]: @ranj063 Hmm, Keyon has a point. To describe DMA stream properties, capability or compatibility with opportunistic DMI L1 entry seems more fitting than the more abstract "D0i3x-compatibility" which is more a property of the whole logical stream (all resources needed for the stream need to fit to the low-power memory/hw).

So here dmi_l1_capable (or "dmi_l1_compatible") would fit better. As this is Intel specific, upper layers should not use this term, so only in hda.h/hda-stream.c/hda-pcm.c.

Comment (plbossart) [reply sound/soc/sof/intel/hda.h]: it's more 'dmi_l1_required', no? we can enable L1 on all streams, be they D0i3 compatible or not. We chose not to do so in most cases, but that WoV capture is an exception coming from a hardware requirement.

Comment (ranj063) [reply sound/soc/sof/intel/hda.h]: @plbossart I think dmi_l1_compatible is a better choice. "required" would need to be backed up with a confirmation that it was honored.

Comment (plbossart) [reply sound/soc/sof/intel/hda.h]: ok, let's leave it as is then.

Comment (ranj063) [reply sound/soc/sof/intel/hda.h]: @kv2019i @plbossart @keyonjie now updated to include trace DMA as well.

File: sound/soc/sof/intel/hda-stream.c [hunk 9]
```diff
@@ -189,50 +189,62 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
...
-	bool active_capture_stream = false;
+	bool dmi_l1_enable = true;
 	bool found = false;
 
 	spin_lock_irq(&bus->reg_lock);
 
 	/*
 	 * close stream matching the stream tag
-	 * and check if there are any open capture streams.
+	 * and check if there any capture streams open that are DMI L1 incompatible.
```
Comment (lyakh) [inline sound/soc/sof/intel/hda-stream.c]: I think the first "are" is still also needed there

File: sound/soc/sof/intel/hda-stream.c [hunk 10]
```diff
@@ -189,50 +189,62 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
...
 		if (!s->opened)
 			continue;
 
 		if (s->direction == direction && s->stream_tag == stream_tag) {
 			s->opened = false;
 			found = true;
-		} else if (s->direction == SNDRV_PCM_STREAM_CAPTURE) {
-			active_capture_stream = true;
+		} else {
+			if (!hda_stream->dmi_l1_compatible)
```
Comment (lyakh) [inline sound/soc/sof/intel/hda-stream.c]: this could still have been an `else if`

File: sound/soc/sof/intel/hda-stream.c [hunk 11]
```diff
@@ -189,50 +189,62 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
...
 		}
 	}
 
 	spin_unlock_irq(&bus->reg_lock);
 
-	/* Enable DMI L1 entry if there are no capture streams open */
+	/* Enter DMI L1 if permitted */
 	if (!IS_ENABLED(CONFIG_SND_SOC_SOF_HDA_ALWAYS_ENABLE_DMI_L1))
-		if (!active_capture_stream)
+		if (dmi_l1_enable)
```
Comment (lyakh) [inline sound/soc/sof/intel/hda-stream.c]: could be `if (!IS_ENABLED(...) && dmi_...)` to reduce indentation depth

**Review by lyakh — APPROVED** [review]
looks good and the logic seems correct

File: sound/soc/sof/intel/hda-stream.c [hunk 12]
```diff
@@ -206,37 +214,39 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
...
-	bool active_capture_stream = false;
+	bool dmi_l1_enable = true;
 	bool found = false;
 
 	spin_lock_irq(&bus->reg_lock);
 
 	/*
 	 * close stream matching the stream tag
-	 * and check if there are any open capture streams.
+	 * and check if there are any capture streams open that are DMI L1 incompatible.
```
Comment (keyonjie) [inline sound/soc/sof/intel/hda-stream.c]: "any capture streams" -> "any streams" to be consistent with the code, we don't check if it is capture stream here.

File: sound/soc/sof/intel/hda-stream.c [hunk 13]
```diff
@@ -183,18 +183,26 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
...
+
+	/* all playback streams are DMI L1 compatible by default */
+	if (direction == SNDRV_PCM_STREAM_PLAYBACK)
+		hda_stream->dmi_l1_compatible = true;
+	else
+		hda_stream->dmi_l1_compatible = dmi_l1_compatible;
 
 	/*
-	 * Disable DMI Link L1 entry when capture stream is opened.
+	 * Prevent DMI Link L1 entry for capture streams that don't support it.
```
Comment (keyonjie) [inline sound/soc/sof/intel/hda-stream.c]: Ditto, "capture streams" -> "streams" .

File: sound/soc/sof/intel/hda.h [hunk 14]
```diff
@@ -471,6 +471,7 @@ struct sof_intel_hda_stream {
 	struct hdac_ext_stream hda_stream;
 	struct sof_intel_stream stream;
 	int host_reserved; /* reserve host DMA channel */
+	bool dmi_l1_compatible;
```
Comment (keyonjie) [inline sound/soc/sof/intel/hda.h]: Shall we add some comments to guide the user to set this for what kind of stream? e.g. "/* set false for capture stream support pause/release */" ?

**Review by keyonjie — COMMENTED** [review]
only minor comments related, please take my approval once they are addressed.

File: sound/soc/sof/intel/hda-loader.c [hunk 15]
```diff
@@ -35,7 +35,7 @@ static struct hdac_ext_stream *cl_stream_prepare(struct snd_sof_dev *sdev, unsig
 	struct pci_dev *pci = to_pci_dev(sdev->dev);
 	int ret;
 
-	dsp_stream = hda_dsp_stream_get(sdev, direction);
+	dsp_stream = hda_dsp_stream_get(sdev, direction, false);
```
Comment (xiulipan) [inline sound/soc/sof/intel/hda-loader.c]: Would some predefined macro here to replace the `false` to improve the code readability.
```suggestion
	dsp_stream = hda_dsp_stream_get(sdev, direction, DMI_L1_NOT_COMPATIBLE);
```

**Review by xiulipan — COMMENTED** [review]
some suggestion for code readability

**Review by lyakh — DISMISSED** [review]

File: sound/soc/sof/intel/hda-loader.c (hunk 15 above)
Comment (kv2019i) [reply sound/soc/sof/intel/hda-loader.c]: Hmm, I do like this. We have many calls to stream_get() and this version is much more readable. The definition side is a bit akward, but maybe something like:
```
#define DMI_L1_NOT_COMPATIBLE false
#define DM_L1_COMPATIBLE true
```

Not pretty, but helps readability of the functions for sure.

File: sound/soc/sof/intel/hda-stream.c [hunk 16]
```diff
@@ -206,37 +214,39 @@ hda_dsp_stream_get(struct snd_sof_dev *sdev, int direction)
...
 	spin_unlock_irq(&bus->reg_lock);
 
-	/* Enable DMI L1 entry if there are no capture streams open */
-	if (!IS_ENABLED(CONFIG_SND_SOC_SOF_HDA_ALWAYS_ENABLE_DMI_L1))
-		if (!active_capture_stream)
-			snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
-						HDA_VS_INTEL_EM2,
-						HDA_VS_INTEL_EM2_L1SEN,
-						HDA_VS_INTEL_EM2_L1SEN);
+	/* Enter DMI L1 if permitted */
```
Comment (kv2019i) [inline sound/soc/sof/intel/hda-stream.c]: How did we get back to "Enter" again. Writing L1SEN=1 does not mean DMI L1 is entered. The "SEN" in register name is literally from "Support Enable". L1 may be entered, but this is upto hw state machine to decide.

File: sound/soc/sof/intel/hda.h (hunk 14 above)
Comment (kv2019i) [reply sound/soc/sof/intel/hda.h]: I'd leave this out. The logic when to set it might change later or vary from hw to another, so better to have it in implementation side only.

**Review by kv2019i — COMMENTED** [review]
It seems we have a consensus on the logic, but still some comments on readibility aspects. I added a few comments as well.

File: sound/soc/sof/intel/hda-loader.c (hunk 15 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda-loader.c]: I personally dont like this macro suggestion. Maybe the true/false dont tell you what they are for but it takes one glance at the function signature to deduce that. But, I will do it if everyone feels the need for this. @plbossart @lyakh thoughts?

Comment (plbossart) [reply sound/soc/sof/intel/hda-loader.c]: I like the define not really because of the readability but the extensibility. If later on you want to add a flag in some cases, it'd be easier. But we've need a prefix to avoid conflicts.

Comment (ranj063) [reply sound/soc/sof/intel/hda-loader.c]: Thanks @plbossart. thats definitely a lot better. changed now

**Comment by ranj063** [comment]
@keyonjie @kv2019i @plbossart @lyakh can you please help review?

**Review by kv2019i — DISMISSED** [review]
Thanks @ranj063 , looks good now!

**Comment by sathya-nujella** [comment]
Hi,

With 'Wake On Voice' capture path ON and when system is in idle:


without this PR patch,
cat /sys/kernel/debug/pmc_core/package_cstate_show
	only "Package C2" count increased.

with this PR2681 patch, I see:
cat /sys/kernel/debug/pmc_core/package_cstate_show
	only "Package C8"/ "package C6" count increased.

File: sound/soc/sof/intel/hda.h [hunk 17]
```diff
@@ -471,6 +474,7 @@ struct sof_intel_hda_stream {
...
```
Comment (plbossart) [inline sound/soc/sof/intel/hda.h]: would it make sense to add a generic 'u32 flags' here and keep the value provided to hda_dsp_stream_get()?
That way you just test for the L1 compatible property when you need it, and we will never need another extension to the stream structure if we expand the flags.

**Review by plbossart — COMMENTED** [review]
looks good, but see minor improvement suggested below.

File: sound/soc/sof/intel/hda.h (hunk 17 above)
Comment (ranj063) [reply sound/soc/sof/intel/hda.h]: ack. done!

**Comment by plbossart** [comment]
@ranj063 build fail?

**Comment by ranj063** [comment]
> @ranj063 build fail?

sorry about that. Should be fixed now!

**Review by kv2019i — APPROVED** [review]

**Comment by ranj063** [comment]
@plbossart I've split  trace DMA DMI L1 enabling into a separate patch now.

**Review by plbossart — APPROVED** [review]

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
Looks good now, thanks @ranj063 !
