### PR TITLE
ASoC: SOF: ipc4-control: Use local copy of IPC message for sending

### LINKED ISSUE #5734: FW reported error: 9 - Specified resource not found
Sometimes got below error while creating pipelines.
```
2026-04-15T17:16:32.857212+08:00: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-ptl 0000:00:1f.3: ipc tx      : 0x44001012|0x30000000: MOD_LARGE_CONFIG_SET
2026-04-15T17:16:32.857213+08:00: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-ptl 0000:00:1f.3: Create pipeline pipeline.1 (pipe 1) - instance 1, core 0
2026-04-15T17:16:32.858145+08:00: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-ptl 0000:00:1f.3: ipc tx reply: 0x64000009|0x30000000: MOD_LARGE_CONFIG_SET
2026-04-15T17:16:32.858149+08:00: sof-audio-pci-intel-ptl 0000:00:1f.3: FW reported error: 9 - Specified resource not found
2026-04-15T17:16:32.858150+08:00: sof-audio-pci-intel-ptl 0000:00:1f.3: ipc error for msg 0x44001012|0x30000000
2026-04-15T17:16:32.858151+08:00: sof-audio-pci-intel-ptl 0000:00:1f.3: sof_ipc4_set_get_data: large config set failed at offset 0: -22
2026-04-15T17:16:32.858152+08:00: sof-audio-pci-intel-ptl 0000:00:1f.3: Failed to set volume update for Pre Mixer Jack Out Playback Volume
```

Platform: PTL
SOF firmware version: v2.14.1 from sof-bin
Kernel commit: a3650a4c72bf soundwire: intel: Move suspend tracking from trigger to pm suspend

Reproduce rate: about 50%

The kernel log with the error:
[kern_error_ipc_payload.log](https://github.com/user-attachments/files/26744181/kern_error_ipc_payload.log)
The kernel log without the error:
[kern_no_error_ipc_payload.log](https://github.com/user-attachments/files/26744182/kern_no_error_ipc_payload.log)

### PR DESCRIPTION
**Pull request by ujfalusi**
If a kcontrol update comes to a control right at the same time when the PCM containing the control is started up then there is a small window when a race can happen:
while the widget is set up the swidget->setup_mutex is taken in topology level and if the control update comes at this point, it will be stopped within sof_ipc4_set_get_kcontrol_data() with the mutex and it will be blocked until the swidget setup is done, which will clear the control's IPC message payload.

To avoid such race, use local copy of the template IPC message instead of the template directly. This will ensure data integrity in case of concurrent updates during initialization.

Link: https://github.com/thesofproject/linux/issues/5734

### CODE REVIEW

**Comment by ujfalusi** [comment]
Changes since v1:
- use local copy of the template IPC message instead of directly using the template itself.

File: sound/soc/sof/ipc4-control.c [hunk 1]
```diff
@@ -107,6 +106,7 @@ sof_ipc4_set_volume_data(struct snd_sof_dev *sdev, struct snd_sof_widget *swidge
 	 * notify DSP with a single IPC message if all channel values are equal. Otherwise send
 	 * a separate IPC for each channel.
 	 */
+	memcpy(&msg, &cdata->msg, sizeof(msg));
```
Comment (bardliao) [inline sound/soc/sof/ipc4-control.c:109]: Do we need to protect the data->msg when we are copying the msg?

Comment (ujfalusi) [reply sound/soc/sof/ipc4-control.c:109]: no, it is a template, but I think there is one catch here. If the topology have no payload for a bytes control (DAX) then the extension's param_id will be 0 and if it would send notification then we would not be able to find the control/swidget since the match is not present.
But this is no different than what we have atm, if the tplg have no bytes data, the param_id is 0 and if the firmware sends a change notification we will be not able to identify the source of it anyways.
(but if the user sets once the same bytes control then we would have modified the template and from that point we would have the param_id carved into the template)

I would argue that this is a topology error, if the change notification is expected from a bytes control, then tplg must have initial data at least to describe the control as we cannot trust that user will set the bytes.

**Review by kv2019i — APPROVED** [review]
Thanks, looks good.

**Review by bardliao — APPROVED** [review]
