### PR TITLE
fix unregister device twice on ASoC driver

### LINKED ISSUE #837: [CML][HDA] Kernel panic when tried to remove sof module (sof_pci_dev)
**Summary**
Kernel panic when tried to remove sof module.

**To reproduce**
1. sudo rmmod sof_pci_dev

**Actual result**
Kernel Panic

**Test recipe**
Kernel: 2de29fae6 [thesofproject/linux: topic/sof-dev] +[RanderWang/linux: cml-validation-20190415] d04ccf494 + bfb0729dd + 8a2b13a81 + 63ceb8f68 + db89510d0 
Firmware: https://github.com/bardliao/sof/commit/00bbb113d0a99c56958f5eadb498424b8bef8c67 + https://github.com/bardliao/sof/commit/57380037a8326e4c8904e5607184b8a269786f47
Topology: sof-hda-generic.tplg

**dmesg log**
```
[ 1569.663137] ------------[ cut here ]------------
[ 1569.663138] sysfs group 'power' not found for kobject 'ehdaudio0D0'
[ 1569.663145] WARNING: CPU: 4 PID: 3004 at fs/sysfs/group.c:256 sysfs_remove_group+0x71/0x80
[ 1569.663145] Modules linked in: snd_soc_skl_hda_dsp snd_soc_hdac_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_soc_dmic sof_pci_dev(-) snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof_xtensa_dsp snd_sof iwlmvm snd_soc_acpi_intel_match snd_soc_acpi snd_hda_ext_core ax88179_178a snd_soc_core usbnet snd_hda_codec snd_hwdep snd_hda_core intel_lpss_pci intel_lpss iwlwifi snd_pcm x86_pkg_temp_thermal mfd_core efivarfs xhci_pci xhci_hcd
[ 1569.663156] CPU: 4 PID: 3004 Comm: rmmod Not tainted 5.0.0-cml-validation-20190415-4-hda-sof-db89510 #5.0.0
[ 1569.663156] Hardware name: Dell Inc. Inspiron 5590/, BIOS 86.1.4 04/08/2019
[ 1569.663158] RIP: 0010:sysfs_remove_group+0x71/0x80
[ 1569.663159] Code: 48 89 df 5b 5d 41 5c e9 6d c0 ff ff 48 89 df e8 c5 bc ff ff eb cb 49 8b 14 24 48 8b 75 00 48 c7 c7 90 1a 22 a0 e8 cf 82 e2 ff <0f> 0b 5b 5d 41 5c c3 0f 1f 84 00 00 00 00 00 48 85 f6 74 31 41 54
[ 1569.663159] RSP: 0018:ffffa11f04c23ac8 EFLAGS: 00010286
[ 1569.663160] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000006
[ 1569.663161] RDX: 0000000000000007 RSI: 0000000000000092 RDI: ffff993458315410
[ 1569.663161] RBP: ffffffffa00bac80 R08: 0000000000000048 R09: 0000000000000004
[ 1569.663162] R10: ffff993451649ac0 R11: 0000000000000001 R12: ffff9934525a7010
[ 1569.663162] R13: ffff993452b8b000 R14: 0000000000000000 R15: ffffffffa020ee2b
[ 1569.663163] FS:  00007f9d0f55a540(0000) GS:ffff993458300000(0000) knlGS:0000000000000000
[ 1569.663164] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1569.663164] CR2: 00005653dcf4e430 CR3: 00000004fd464004 CR4: 00000000003606e0
[ 1569.663165] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 1569.663165] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 1569.663166] Call Trace:
[ 1569.663170]  device_del+0x51/0x350
[ 1569.663173]  snd_hdac_device_unregister+0x19/0x30 [snd_hda_core]
[ 1569.663177]  snd_hda_codec_dev_free+0x14/0x40 [snd_hda_codec]
[ 1569.663180]  __snd_device_free+0x43/0x70
[ 1569.663181]  snd_device_free_all+0x36/0x80
[ 1569.663183]  release_card_device+0x14/0x60
[ 1569.663184]  device_release+0x2b/0x80
[ 1569.663187]  kobject_put+0x84/0x1b0
[ 1569.663188]  snd_card_free+0x60/0x90
[ 1569.663191]  soc_cleanup_card_resources+0x22/0x390 [snd_soc_core]
[ 1569.663194]  snd_soc_unbind_card.part.59+0xa8/0xf0 [snd_soc_core]
[ 1569.663197]  snd_soc_unregister_component+0x8f/0xd0 [snd_soc_core]
[ 1569.663199]  release_nodes+0x121/0x220
[ 1569.663201]  device_release_driver_internal+0x190/0x240
[ 1569.663202]  bus_remove_device+0xe0/0x150
[ 1569.663203]  device_del+0x133/0x350
[ 1569.663205]  snd_hdac_device_unregister+0x19/0x30 [snd_hda_core]
[ 1569.663208]  snd_hdac_ext_bus_device_remove+0x2a/0x60 [snd_hda_ext_core]
[ 1569.663214]  hda_dsp_remove+0x26/0x110 [snd_sof_intel_hda_common]
[ 1569.663217]  snd_sof_device_remove+0x5c/0x90 [snd_sof]
[ 1569.663219]  sof_pci_remove+0x10/0x20 [sof_pci_dev]
[ 1569.663221]  pci_device_remove+0x36/0xb0
[ 1569.663222]  device_release_driver_internal+0x180/0x240
[ 1569.663224]  driver_detach+0x48/0x80
[ 1569.663225]  bus_remove_driver+0x4c/0xc0
[ 1569.663226]  pci_unregister_driver+0x1d/0x90
[ 1569.663228]  __x64_sys_delete_module+0x155/0x240
[ 1569.663230]  do_syscall_64+0x43/0xf0
[ 1569.663232]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[ 1569.663233] RIP: 0033:0x7f9d0f0781b7
[ 1569.663235] Code: 73 01 c3 48 8b 0d d1 8c 2c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 b8 b0 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d a1 8c 2c 00 f7 d8 64 89 01 48
[ 1569.663236] RSP: 002b:00007ffcbccabe68 EFLAGS: 00000206 ORIG_RAX: 00000000000000b0
[ 1569.663236] RAX: ffffffffffffffda RBX: 00007ffcbccabec8 RCX: 00007f9d0f0781b7
[ 1569.663237] RDX: 000000000000000a RSI: 0000000000000800 RDI: 000055f65674f7b8
[ 1569.663238] RBP: 000055f65674f750 R08: 00007ffcbccaade1 R09: 0000000000000000
[ 1569.663238] R10: 00007f9d0f0f4cc0 R11: 0000000000000206 R12: 00007ffcbccac090
[ 1569.663239] R13: 00007ffcbccac7d5 R14: 000055f65674e260 R15: 000055f65674f750
[ 1569.663240] ---[ end trace f504933eaff4071b ]---
```

[reload_failed.log](https://github.com/thesofproject/linux/files/3079641/reload_failed.log)

### PR DESCRIPTION
**Pull request by bardliao**
snd_hda_codec_device_new() is used by both legacy HDA and ASoC driver. However, we will call snd_hdac_device_unregister() in snd_hdac_ext_bus_device_remove() for ASoC device. The first patch uses
the type flag in hdac_device struct to determine is it a ASoC device or legacy HDA device and call snd_hdac_device_unregister() in snd_hda_codec_dev_free() only if it is a legacy HDA device.
And the second patch overwrite the hdev->type flag to identify that is a ASoC device.

fix #837

### CODE REVIEW

**Comment by ranj063** [comment]
@bardliao Im a bit confused by this piece of code in the SOF driver in hda-codec.c
 /* use legacy bus only for HDA codecs, idisp uses ext bus */
        if ((resp & 0xFFFF0000) != IDISP_VID_INTEL) {
                hdev->type = HDA_DEV_LEGACY;
                hda_codec_load_module(&hda_priv->codec);
        }

Why do we set it to HDA_DEV_LEGACY here explicitly only to be overwritten later?

**Comment by bardliao** [comment]
> @bardliao Im a bit confused by this piece of code in the SOF driver in hda-codec.c
> /* use legacy bus only for HDA codecs, idisp uses ext bus */
> if ((resp & 0xFFFF0000) != IDISP_VID_INTEL) {
> hdev->type = HDA_DEV_LEGACY;
> hda_codec_load_module(&hda_priv->codec);
> }
> 
> Why do we set it to HDA_DEV_LEGACY here explicitly only to be overwritten later?

@ranj063 Good question. That was also my question when I made the PR. The reason of the piece of code is that we set  [.api_version = HDA_DEV_LEGACY](https://github.com/thesofproject/linux/blob/topic/sof-dev/include/sound/hda_codec.h#L94) for hda codecs and [.api_version = HDA_DEV_ASOC](https://github.com/thesofproject/linux/blob/topic/sof-dev/include/sound/hdaudio_ext.h#L20) for hdmi only. So we must set hdev->type = HDA_DEV_LEGACY to load driver for hda codecs. And the type flag will never be used after that. That's why it can be overwrite and used for legacy HDA/ASoC mode checking.

see also [snd_hda_id_realtek[]](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/pci/hda/patch_realtek.c#L8672) and [hdmi_list[]](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/codecs/hdac_hdmi.c#L2154) for reference

**Comment by RanderWang** [comment]
Sorry, I also have a question:  sof invokes snd_hdac_ext_bus_device_remove to remove all the codec devices, but codec devices are not directly created by sof and it is created by hdac_hda driver. So why sof needs to release these codecs? let hdac_hda do it.

**Comment by bardliao** [comment]
@RanderWang In fact, sof will call [snd_hdac_ext_bus_device_init()](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/intel/hda-codec.c#L73) to invoke [snd_hdac_device_register()](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/hda/ext/hdac_ext_bus.c#L157). So I think it is even to call [snd_hdac_device_unregister()](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/hda/ext/hdac_ext_bus.c#L192) in ``snd_hdac_ext_bus_device_remove()``

**Comment by RanderWang** [comment]
In legacy hda,  snd_hdac_device_register() is invoked by hda codec probe, and snd_hdac_device_unregister() is invoked by hda codec remove. Now in sof, snd_hdac_ext_bus_device_init is used to probe the hda codec, so it is correct to invoke snd_hdac_device_register() in snd_hdac_ext_bus_device_init. But now we keep the snd_hdac_device_unregister in hda codec remove and add it in another function snd_hdac_ext_bus_device_remove.  My idea is deleting snd_hdac_ext_bus_device_remove in sof.

**Comment by bardliao** [comment]
@RanderWang 
>  snd_hdac_device_unregister() is invoked by hda codec remove

No, actually, it is done when hda codec is unbind. 

> My idea is deleting snd_hdac_ext_bus_device_remove in sof.

That is the other direction. But note that we don't have a similar unregister function on hdac_hdmi codec driver. i.e. Currently,  snd_hdac_ext_bus_device_remove is required for hdac_hdmi codec driver. Also, I think it is even to call ```hda_codec_probe() -> snd_hdac_ext_bus_device_init() -> snd_hdac_device_register()``` and ```hda_dsp_remove() -> snd_hdac_ext_bus_device_remove() -> snd_hdac_device_unregister()```  in sof. I don't see a reason to call ```snd_hdac_device_register()``` in sof but ```snd_hdac_device_unregister()``` in another place.

**Comment by RanderWang** [comment]
> @RanderWang
> 
> > snd_hdac_device_unregister() is invoked by hda codec remove
> 
> No, actually, it is done when hda codec is unbind.
> 
> > My idea is deleting snd_hdac_ext_bus_device_remove in sof.
> 
> That is the other direction. But note that we don't have a similar unregister function on hdac_hdmi codec driver. i.e. Currently, snd_hdac_ext_bus_device_remove is required for hdac_hdmi codec driver. 

ok, I get it. The flow is complex for me to make it clear in short time.

File: sound/soc/codecs/hdac_hda.c [hunk 1]
```diff
@@ -328,6 +328,12 @@ static int hdac_hda_codec_probe(struct snd_soc_component *component)
 		dev_err(&hdev->dev, "failed to create hda codec %d\n", ret);
 		goto error_no_pm;
 	}
+	/*
+	 * Overwrite type to HDA_DEV_ASOC since it is a ASoC driver
+	 * hda_codec.c will check this flag to determine if unregister
+	 * device is needed.
+	 */
+	hdev->type = HDA_DEV_ASOC;
```
Comment (plbossart) [inline sound/soc/codecs/hdac_hda.c:336]: it's really a bit ugly to do this. You first use HDA_DEV_LEGACY to load the codec, and have to use HDA_DEV_ASOC to prevent it being released twice.
Is this the best we can do?

**Comment by ranj063** [comment]
@bardliao I think my suggestion https://github.com/thesofproject/linux/issues/837#issuecomment-484171806 might be a better solution. CONFIG_SND_SOC_SOF_HDA_AUDIO_CODEC is only enabled when there are HDA codecs, so we dont need to call snd_hdac_ext_bus_device_remove in SOF. 

In the case of HDMI only as in APL, this will get called because we dont enable this right?

**Comment by bardliao** [comment]
@ranj063 I tried it, but the result is not good. rmmod can't finish if I don't call snd_hdac_ext_bus_device_remove in SOF or snd_hdac_device_unregister in snd_hdac_ext_bus_device_remove. So we need to do more if we decide to go on this direction. Actually, I don't know if it is the right direction. My question is **why we have to call snd_hdac_device_register in SOF, but snd_hdac_device_unregister in somewhere else?**

@plbossart Yes, I agree that the code is ugly :).  However, the problem is that we set [hdev->type = HDA_DEV_ASOC;](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/hda/ext/hdac_ext_bus.c#L154)  in [snd_hdac_ext_bus_device_init](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/intel/hda-codec.c#L73) at first , but overwrite it to  [hdev->type = HDA_DEV_LEGACY](https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/sof/intel/hda-codec.c#L79) latter. So, in my opinion, set hdev->type = HDA_DEV_ASOC in hda_hdac.c is to correct hdev->type to as what it should be.

**Comment by plbossart** [comment]
@bardliao I'll have to look at this next week when I have a bigger screen and can look at the code in details. Thanks for your patience.

**Comment by wenqingfu** [comment]
this can go to alsa-dev for more brains to look into @bardliao

**Comment by bardliao** [comment]
@wenqingfu  Sure, I will do it.

**Comment by bardliao** [comment]
@plbossart Seems I am a little bit too late. I just cherry-pick -x from Takashi's git and force update the PR after you merged it :)
