### PR TITLE
Soundwire: register intel sdw master driver with driver_register()

### LINKED ISSUE #1595: [BUG][SDW]" IPC timed out for 0x60050000 size 12" occured when arecord0,4(RT715) after s3 and terminating arecord0,1(RT711)
**Describe the bug**
Firstly disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001.
When wake up from s3 with headset playback/capture(RT711), terminate it and start to arecord0,4(RT715), it will occur "IPC timed out for 0x60050000 size 12". Need reboot to recover.

Note: enable master and sof runtime PM status, issue cannot be reproduced.

**To Reproduce**
1.Disable master and sof runtime PM status via add sof-pci-debug=1 and sdw_md_flags=0x01000001, then reboot to make it work.
2.Arecord0,1 via "arecord -Dhw:0,1 -r 48000 -c2 -fs16_le 1.wav -vvv -i"
3.Enter s3 via "sudo rtcwake -m mem -s 10"
4.Terminate arecord after waking up from s3, then start to arecord0,4(RT715)

**Reproduce rate**
5/5

**Expected result**
Arecord0,4 normally, no error occured.

**Actual result**
 "IPC timed out for 0x60050000 size 12" occured when arecord0,4(RT715) after s3 and terminating arecord0,1(RT711)

<details>
 <summary>dmesg error log</summary>

````
[  190.985434] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3501 <= 0003
[  190.985438] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3501 <= 0000
[  190.985457] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3607 <= 0010
[  190.985463] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3627 <= 0010
[  190.985489]  SDW3-Capture: ASoC: BE SDW3-Capture event 1 dir 1
[  190.985683]  SDW3-Capture: ASoC: trigger BE SDW3-Capture cmd 1
[  190.985685] intel-sdw sdw-master-3: intel_trigger: SDW3 Pin2: start
[  190.985705] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 00e0 <= 0001
[  190.985708] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 00f0 <= 0001
[  190.985710] sdw_enable_stream: SDW3 Pin2-Capture: done
[  190.985712] intel-sdw sdw-master-3: intel_trigger: SDW3 Pin2: done
[  190.985715]  DMIC: ASoC: post trigger FE DMIC cmd 1
[  190.985717] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 1 cmd 1
[  190.986231] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x2024001e successful
[  190.986233] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  190.986449] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  191.489674]  DMIC: ASoC: pre trigger FE DMIC cmd 0
[  191.489682] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 4 dir 1 cmd 0
[  191.489688] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  191.553489]  Headphone: ASoC: pre trigger FE Headphone cmd 0
[  191.553495] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  191.993433] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60050000 size 12
[  191.993440] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[  191.993450] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[  191.993601] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[  191.993615] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000083 rirb 00
[  191.993618] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  191.993638] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x000000                      03
[  191.993641] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[  191.993706] sof-audio-pci 0000:00:1f.3: error: trace IO error
[  191.993724] sof-audio-pci 0000:00:1f.3: error: trace IO error
[  191.993727] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[  191.994226] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20240000 successful
[  191.994234]  DMIC: ASoC: trigger FE cmd: 0 failed: -110
[  191.994252]  DMIC: ASoC: hw_free FE DMIC
[  191.994258] sof-audio-pci 0000:00:1f.3: pcm: free stream 4 dir 1
[  192.497425] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60050000 size 12
[  192.497431] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[  192.497437] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[  192.497583] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[  192.497595] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000081 rirb 00
[  192.497599] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  192.497608] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x000000                      03
[  192.497611] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[  192.497668] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  192.498185] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[  192.498192]  Headphone: ASoC: trigger FE cmd: 0 failed: -110
[  193.001443] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60030000 size 12
[  193.001450] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[  193.001456] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[  193.001602] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[  193.001616] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[  193.001619] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  193.001628] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x000000                      03
[  193.001631] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[  193.001681] intel-sdw sdw-master-3: intel_hw_free: SDW3 Pin2: start
[  193.001685] sdw_deprepare_stream: SDW3 Pin2-Capture: inconsistent state state 3
[  193.001688] sdw_deprepare_stream: SDW3 Pin2-Capture: done
[  193.001691] intel-sdw sdw-master-3: sdw_deprepare_stream: failed -22
[  193.001694]  SDW3-Capture: ASoC: close BE SDW3-Capture
[  193.001697] intel-sdw sdw-master-3: intel_shutdown: SDW3 Pin2: start
[  193.001701] intel-sdw sdw-master-3: intel_shutdown: SDW3 Pin2: done
[  193.001738]  DMIC: ASoC: close FE DMIC
[  193.001742] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 1
[  193.001878] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3607 <= 0000
[  193.001884] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3627 <= 0000
[  193.001950] rt715 sdw:3:25d:715:0: [rt715_sdw_write] 3501 <= 0003
[  193.002011]  SDW3-Capture: ASoC: BE SDW3-Capture event 2 dir 1
[  193.002044]  DMIC: ASoC: BE capture disconnect check for SDW3-Capture
[  193.002046]  DMIC: freed DSP capture path DMIC <- SDW3-Capture
[  193.002112]  Headphone: ASoC: hw_free FE Headphone
[  193.002120] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 0
[  193.002125] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[  193.505433] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60030000 size 12
[  193.505440] sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
[  193.505448] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[  193.505600] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[  193.505614] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[  193.505617] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  193.505634] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x000000                      03
[  193.505637] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[  193.505702] intel-sdw sdw-master-0: intel_hw_free: SDW0 Pin2: start
[  193.505706] sdw_deprepare_stream: SDW0 Pin2-Playback: inconsistent state state 3
[  193.505709] sdw_deprepare_stream: SDW0 Pin2-Playback: done
[  193.505712] intel-sdw sdw-master-0: sdw_deprepare_stream: failed -22
[  193.505716]  SDW0-Playback: ASoC: close BE SDW0-Playback
[  193.505719] intel-sdw sdw-master-0: intel_shutdown: SDW0 Pin2: start
[  193.505723] intel-sdw sdw-master-0: intel_shutdown: SDW0 Pin2: done
[  193.505761]  Headphone: ASoC: close FE Headphone
[  193.505766] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 0
[  193.505774]  SDW0-Playback: ASoC: BE SDW0-Playback event 2 dir 0
[  193.506170] sdw_cdns_irq: 129 callbacks suppressed
[  193.506174] intel-sdw sdw-master-3: Parity error
[  193.506180] sdw_cdns_irq: 129 callbacks suppressed
[  193.506182] intel-sdw sdw-master-3: Bus clash for control word
[  193.506184] sdw_cdns_irq: 129 callbacks suppressed
[  193.506186] intel-sdw sdw-master-3: Bus clash for data word
[  193.506240] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7321 83a1 <= b080

````
</details>

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: add887e+PR #1589
FW: https://github.com/thesofproject/sof/commits/master commit: 65de27d
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode。

[sof_trace.log](https://github.com/thesofproject/linux/files/3926002/sof_trace.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3926004/dmesg.log)

### PR DESCRIPTION
**Pull request by bardliao**
dev->power.no_pm_callbacks flag is used to check if there is pm ops
for the device. Pm callback function will not be invoked if there is
no pm ops. Currently the flag is true for sdw-master devices which
is incorrect since we do have pm ops in intel_sdw_driver. As a result,
intel_suspend() which is the suspend callback function of intel-sdw
driver may not be invoked in system suspend.
With driver_register() and setting md->dev.driver before
device_register(), dev->power.no_pm_callbacks flag will be set to the
correct value (false) by device_pm_check_callbacks() which will be
triggered by device_register().

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

Fixes #1595 #1614

### CODE REVIEW

File: drivers/soundwire/intel_init.c [hunk 1]
```diff
@@ -395,6 +404,7 @@ EXPORT_SYMBOL(sdw_intel_startup);
 void sdw_intel_exit(struct sdw_intel_ctx *ctx)
 {
 	sdw_intel_cleanup(ctx);
+	driver_register(&intel_sdw_driver.driver);
```
Comment (plbossart) [inline drivers/soundwire/intel_init.c]: driver_unregister() ?

File: drivers/soundwire/master.c [hunk 2]
```diff
@@ -58,6 +58,12 @@ struct sdw_master_device *sdw_md_add(struct sdw_md_driver *driver,
 	}
 
 	md->dev.driver = &driver->driver;
+	ret = device_bind_driver(&md->dev);
```
Comment (plbossart) [inline drivers/soundwire/master.c]: don't we need a matching device_release_driver() ?

Comment (ranj063) [reply drivers/soundwire/master.c]: @bardliao typically device_add should take care of binding the driver isnt it? I may be wrong. But is the problem simply that we should set md->dev.driver before we call device_resgiter() in sdw_md_add?

**Comment by plbossart** [comment]
@bardliao can you also clarify what issue you are chasing? Last week it was a problem with issue https://github.com/thesofproject/linux/issues/1595 but I can't reproduce the error with the existing integration/soundwire-latest.

File: drivers/soundwire/intel_init.c (hunk 1 above)
Comment (bardliao) [reply drivers/soundwire/intel_init.c]: Thanks. Fix it now.

File: drivers/soundwire/master.c (hunk 2 above)
Comment (bardliao) [reply drivers/soundwire/master.c]: > @bardliao typically device_add should take care of binding the driver isnt it? I may be wrong. But is the problem simply that we should set md->dev.driver before we call device_resgiter() in sdw_md_add?

@ranj063 You are right. Actually, I tried it before. But we didn't call driver_register() at that time so it result in system crash. Now moving md->dev.driver before device_resgiter() work fine.

**Comment by bardliao** [comment]
> @bardliao can you also clarify what issue you are chasing? Last week it was a problem with issue #1595 but I can't reproduce the error with the existing integration/soundwire-latest.

@plbossart What I want to fix is to make sure intel_suspend() will be triggered for all links. I will update my commit message then.

**Comment by plbossart** [comment]
@bardliao see trace attached

[dmesg_arecord1_rtcwake_arecord4.log](https://github.com/thesofproject/linux/files/3942686/dmesg_arecord1_rtcwake_arecord4.log)

````
[   23.582884] intel-sdw sdw-master-2: intel_suspend_runtime start
[   23.583131] intel-sdw sdw-master-2: intel_suspend_runtime done
[   29.393476] intel-sdw sdw-master-1: intel_suspend_runtime start
[   29.393894] intel-sdw sdw-master-1: intel_suspend_runtime done
[   29.847667] intel-sdw sdw-master-3: intel_suspend_runtime start
[   29.847979] intel-sdw sdw-master-3: intel_suspend_runtime done
[   38.462559] intel-sdw sdw-master-3: intel_suspend start
[   38.462562] intel-sdw sdw-master-3: intel_suspend: pm_runtime status: suspended
[   38.462567] intel-sdw sdw-master-2: intel_suspend start
[   38.462569] intel-sdw sdw-master-2: intel_suspend: pm_runtime status: suspended
[   38.462574] intel-sdw sdw-master-1: intel_suspend start
[   38.462577] intel-sdw sdw-master-1: intel_suspend: pm_runtime status: suspended
[   38.462587] intel-sdw sdw-master-0: intel_suspend start
[   38.462599] intel-sdw sdw-master-0: intel_suspend done
[   46.313061] intel-sdw sdw-master-2: intel_suspend_runtime start
[   46.313090] intel-sdw sdw-master-3: intel_suspend_runtime start
[   46.313109] intel-sdw sdw-master-1: intel_suspend_runtime start
[   46.313581] intel-sdw sdw-master-1: intel_suspend_runtime done
[   46.313605] intel-sdw sdw-master-3: intel_suspend_runtime done
[   48.321434] intel-sdw sdw-master-2: intel_suspend_runtime done
[   54.025043] intel-sdw sdw-master-0: intel_suspend_runtime start
[   54.025669] intel-sdw sdw-master-0: intel_suspend_runtime done
````

and yes I have the standard rt700 on all links

````
/sys/kernel/debug/soundwire# ls master-*
master-0:
intel-sdw  sdw:0:25d:700:0  sdw:0:25d:711:0

master-1:
intel-sdw  sdw:1:25d:1308:0  sdw:1:25d:700:0

master-2:
intel-sdw  sdw:2:25d:700:0  sdw:2:25d:701:0

master-3:
intel-sdw  sdw:3:25d:700:0  sdw:3:25d:715:0
````

but I haven't updated the BIOS since the original release with the SOF key

**Comment by plbossart** [comment]
@bardliao I am using only the clock_quirks 0x8, no other pm_runtime filter or link mask btw

**Comment by bardliao** [comment]
@plbossart So the reasons you don't see #1595 is 
1. The issue can only be seen when runtime pm is disabled.
2. The rt700 codecs are the "ghost". Can you try removing rt700 driver from the kernel?

**Comment by plbossart** [comment]
> @plbossart So the reasons you don't see #1595 is
> 
> 1. The issue can only be seen when runtime pm is disabled.
> 2. The rt700 codecs are the "ghost". Can you try removing rt700 driver from the kernel?

ok, but can you file a bug that has all the information? it's impossible to guess or reproduce otherwise. thanks!
