### PR TITLE
ASoC: SOF: Intel: lnl: add core get and set support for dsp core

### LINKED ISSUE #8478: [BUG] LNL has FW reported error: 116 Invalid target code ID provided
**Describe the bug**
LNLM_RVP_NOCODEC has new firmware error 116, Invalid target code ID provided.

```
[  245.761516] kernel: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-lnl 0000:00:1f.3: pipeline: 5 memory pages: 5
[  245.761520] kernel: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-lnl 0000:00:1f.3: Create widget pipeline.5 instance 0 - pipe 5 - core 2
[  245.761524] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc tx      : 0x11000005|0x200000: GLB_CREATE_PIPELINE
[  245.761788] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc tx reply: 0x31000074|0x200000: GLB_CREATE_PIPELINE
[  245.761792] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: FW reported error: 116 - Invalid target code ID provided
[  245.764783] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: ipc error for msg 0x11000005|0x200000
[  245.768322] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: failed to create module pipeline.5
[  245.772154] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: Failed to set up connected widgets
[  245.776196] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: error: failed widget list set up for pcm 2 dir 0
[  245.780925] kernel: sof-audio-pci-intel-lnl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
[  245.786529] kernel: snd_sof:sof_pcm_hw_free: sof-audio-pci-intel-lnl 0000:00:1f.3: pcm: free stream 2 dir 0
[  245.786806] kernel: snd_sof:sof_pcm_close: sof-audio-pci-intel-lnl 0000:00:1f.3: pcm: close stream 2 dir 0
```

**To Reproduce**
Can be reproducible with simple playback
TPLG=/lib/firmware/intel/development/sof-lnl-nocodec.tplg MODEL=LNLM_RVP_NOCODEC SOF_TEST_INTERVAL=5 ~/sof-test/test-case/check-playback.sh -d 3 -l 1 -r 1 -F

**Reproduction Rate**
100%

**Environment**

- Linux Branch: [topic/sof-dev](https://github.com/thesofproject/linux/tree/topic/sof-dev)
- Linux Commit: [453fdbbb8fce](https://github.com/thesofproject/linux/commit/453fdbbb8fced8d547e7fac1583eb485a5e0cf42)
- SOF Branch: [main](https://github.com/thesofproject/sof/tree/main)
- SOF Commit: [9eae757947d4](https://github.com/thesofproject/sof/commit/9eae757947d4c3a7cd127112d5d70ddcc514acda)
- TPLG: development/sof-lnl-nocodec.tpl

Similar issue is https://github.com/thesofproject/sof/issues/8275

### PR DESCRIPTION
**Pull request by RanderWang**
Driver uses get and set ops to change the power state of dsp core.

Fix https://github.com/thesofproject/sof/issues/8478 (multi-core issue)

### CODE REVIEW

**Comment by RanderWang** [comment]
Validated by @keqiaozhang. please check issue: https://github.com/thesofproject/sof/issues/8478

File: sound/soc/sof/intel/lnl.c [hunk 1]
```diff
@@ -130,6 +130,10 @@ int sof_lnl_ops_init(struct snd_sof_dev *sdev)
 
 	sof_lnl_ops.get_stream_position = mtl_dsp_get_stream_hda_link_position;
 
+	/* dsp core get/put */
+	sof_lnl_ops.core_get = mtl_dsp_core_get;
+	sof_lnl_ops.core_put = mtl_dsp_core_put;
+
```
Comment (plbossart) [inline sound/soc/sof/intel/lnl.c:136]: Commit message, missing

Closes: https://github.com/thesofproject/sof/issues/8478

**Review by plbossart — APPROVED** [review]

File: sound/soc/sof/intel/lnl.c (hunk 1 above)
Comment (RanderWang) [reply sound/soc/sof/intel/lnl.c:136]: Thanks, updated

**Comment by RanderWang** [comment]
update commit message with fixed issue

**Review by softwarecki — APPROVED** [review]

**Comment by plbossart** [comment]
SOFCI TEST
