### PR TITLE
fixup! ASoC: SOF: IPC4: extend dai_data with node_id

### LINKED ISSUE #8875: [BUG] FW reported error: 7 - Unsupported operation requested on TGL-UP-HDA
**Describe the bug**
Observed this issue in CI daily test, this issue happens when testing multiple-pipeline-all or multiple-pause-resume, the error occurs at second round. 

**dmesg**
```
[  196.041448] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x13010004|0x0: GLB_SET_PIPELINE_STATE
[  196.042249] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x33000007|0x0: GLB_SET_PIPELINE_STATE
[  196.042254] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 7 - Unsupported operation requested
[  196.042398] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc error for msg 0x13010004|0x0
[  196.042407] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at soc_dai_trigger on Analog CPU DAI: -22
[  196.042413] kernel:  HDA Analog: ASoC: trigger FE cmd: 1 failed: -22
[  196.042413] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x11020005|0x1: GLB_CREATE_PIPELINE
[  196.042420] kernel: snd_sof:sof_pcm_trigger: sof-audio-pci-intel-tgl 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[  196.042424] kernel: snd_sof:sof_ipc4_trigger_pipelines: sof-audio-pci-intel-tgl 0000:00:1f.3: trigger cmd: 0 state: 3
```

**mtrace**
```
[  196.045958] <inf> ipc: buffer_new: buffer new size 0x300 id 2.65536 flags 0x0
[  196.045988] <inf> pipe: pipeline_connect: comp:2 0x10002 connect buffer 65536 as sink
[  196.046006] <inf> pipe: pipeline_connect: comp:1 0x3 connect buffer 65536 as source
[  196.048575] <inf> ipc: ipc_cmd: rx	: 0x13010004|0x0
[  196.048733] <inf> copier: copier_prepare: comp:1 0x10004 copier_prepare()
[  196.048750] <err> dai_comp: dai_common_config_prepare: comp:1 0x10004 dai_common_config_prepare(): dma_request_channel() failed
[  196.048765] <err> module_adapter: module_prepare: comp:1 0x10004 module_prepare() error -5: module specific prepare failed, comp_id 65540
[  196.048780] <err> module_adapter: module_adapter_prepare: comp:1 0x10004 module_adapter_prepare() error fffffffb: module prepare failed
[  196.048815] <err> pipe: pipeline_prepare: pipe:1 0x0 pipeline_prepare(): ret = -5, dev->comp.id = 3
[  196.048826] <err> ipc: ipc4_pcm_params: ipc: pipe 1 comp 0 prepare failed -5
[  196.048958] <inf> component: comp_set_state: comp:1 0x10004 comp_set_state(), state already set to 1
[  196.048971] <err> ipc: ipc_cmd: ipc4: FW_GEN_MSG failed with err 7
[  196.086513] <inf> ipc: ipc_cmd: rx	: 0x11030004|0x0
[  196.086540] <inf> pipe: pipeline_new: pipeline new pipe_id 3 priority 0
[  196.086916] <inf> ipc: ipc_cmd: rx	: 0x40030004|0x30015
[  196.087035] <inf> dma: dma_get: dma_get() ID 0 sref = 1 busy channels 0
[  196.087050] <inf> ipc: dai_config: comp:3 0x30004 dai_config() dai type = 3 index = 0 dd 0x9e0c4a00
```

**To Reproduce**
~/sof-test/test-case/multiple-pipeline.sh -f a -c 20 -l 50

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[fe385b69f8c8](https://github.com/thesofproject/linux/commit/fe385b69f8c86adbd43f533005a219f6215ec230)}
    * SOF: {[3681e099de45](https://github.com/thesofproject/sof/commit/3681e099de45953455dd8dc83a5fe80256a820bd)}
2) Name of the topology file
    * Topology: {sof-hda-generic-cavs25-4ch.tplg }
3) Name of the platform(s) on which the bug is observed.
    * Platform: {TGLU_UP_HDA-ipc4}

[dmesg.txt](https://github.com/thesofproject/sof/files/14353084/dmesg.txt)
[mtrace.txt](https://github.com/thesofproject/sof/files/14353101/mtrace.txt)

### PR DESCRIPTION
**Pull request by RanderWang**
Commit da53ad5bc48e177 ("ASoC: SOF: IPC4: extend dai_data with node_id") uses the node_id value specifically for ALH but the code is also used by HDA. Now reserve the old logic for HDA case.

fix https://github.com/thesofproject/sof/issues/8875

### CODE REVIEW

File: sound/soc/sof/ipc4-topology.c [hunk 1]
```diff
@@ -2838,7 +2838,11 @@ static int sof_ipc4_dai_config(struct snd_sof_dev *sdev, struct snd_sof_widget *
 	case SOF_DAI_INTEL_HDA:
 		gtw_attr = ipc4_copier->gtw_attr;
 		gtw_attr->lp_buffer_alloc = pipeline->lp_mode;
-		fallthrough;
+		if (flags & SOF_DAI_CONFIG_FLAGS_HW_PARAMS) {
+			copier_data->gtw_cfg.node_id &= ~SOF_IPC4_NODE_INDEX_MASK;
+			copier_data->gtw_cfg.node_id |= SOF_IPC4_NODE_INDEX(data->dai_data);
+		}
+		break;
```
Comment (ranj063) [inline sound/soc/sof/ipc4-topology.c:2845]: Is this really necessary @RanderWang ? What issue does this fix?

Comment (ranj063) [reply sound/soc/sof/ipc4-topology.c:2845]: ahh just saw the linked issue.

**Review by ranj063 — APPROVED** [review]

**Review by bardliao — APPROVED** [review]
