### PR TITLE
fixup! ASoC: SOF: Introduce struct snd_sof_pipeline

### LINKED ISSUE #3983: [BUG][ADL][TGL] playback failed at the second run with ipc tx error for 0x60010000 GLB_STREAM_MSG: PCM_PARAMS
**Describe the bug**
In today's CI tests, we found that playback failed with IPC tx error at the second run on almost all our platforms.

```
[   41.385988] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   41.386111] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx error for 0x60010000 (msg/reply size: 108/20): -22
[   41.386221] sof-audio-pci-intel-tgl 0000:00:1f.3: HW params ipc failed for stream 1
[   41.386222] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:1f.3: -22
[   41.386240]  Jack Out: ASoC: error at __soc_pcm_hw_params on Jack Out: -22
[   41.386244] sdw_deprepare_stream: subdevice #0-Playback: inconsistent state state 1
[   41.386247] snd_sof:ipc3_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   41.386569]  Jack Out: ASoC: error at dpcm_fe_dai_hw_params on Jack Out: -22
```
This is a kernel regression and caused by https://github.com/thesofproject/linux/commit/6e2cdc2e08685be62713ecdc0d7188cd64ef08de.
```
ASoC: SOF: Introduce struct snd_sof_pipeline
Introduce struct snd_sof_pipeline to save the information about
pipelines including the pipeline widget, their status wrt how many PCM's
are using them and whether they are complete or not.

In struct snd_sof_widget, replace pipe_widget with spipe and remove
complete. In struct snd_sof_pcm_stream_pipeline_list, replace
pipe_widgets with pipelines.

Update all users accordingly.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
 [topic/sof-dev](https://github.com/thesofproject/linux) ([#3957](https://github.com/thesofproject/linux/pull/3957))
```

**To Reproduce**
run `aplay   -Dhw:0,0 -r 48000 -c 2 -f S16_LE -d 3 /dev/zero -v -q` twice.

**Reproduction Rate**
100%

[dmesg.txt](https://github.com/thesofproject/linux/files/9915175/dmesg.txt)

### PR DESCRIPTION
**Pull request by ranj063**
Clear the complete flag for pipelines when the scheduler widget is freed.

Fixes https://github.com/thesofproject/linux/issues/3983

### CODE REVIEW

**Review by bardliao — APPROVED** [review]

**Comment by keqiaozhang** [comment]
Verified that this PR can fix https://github.com/thesofproject/linux/issues/3983.

**Review by plbossart — APPROVED** [review]

**Comment by plbossart** [comment]
I don't know what to make of the results @ranj063 @keqiaozhang TGLU_UP_HDA_IPC4ZPH is a fail on multiple tests.

**Comment by ujfalusi** [comment]
> I don't know what to make of the results @ranj063 @keqiaozhang TGLU_UP_HDA_IPC4ZPH is a fail on multiple tests.

I think what happened is that `multiple-pipeline-playback.sh` failed - firmware crash - (if it is because of this PR or not is a question) since we prevent powering down the DSP to preserve the DSP state. Consecutive tests fail since the DSP is kept powered  in crashed state. With IPC4/Zephyr we don't have panic interrupt/message so we can not force a DSP power cycle.

Let me check it locally, it should be easy to hit.

File: sound/soc/sof/sof-audio.c [hunk 1]
```diff
@@ -75,6 +75,10 @@ int sof_widget_free(struct snd_sof_dev *sdev, struct snd_sof_widget *swidget)
 			err = ret;
 	}
 
+	/* clear pipeline complete */
+	if (swidget->id == snd_soc_dapm_scheduler)
+		swidget->spipe->complete = 0;
```
Comment (ujfalusi) [inline sound/soc/sof/sof-audio.c:80]: Can a pipeline belong to different paths?

**Comment by ujfalusi** [comment]
> Let me check it locally, it should be easy to hit.

No crash so far after 46 iteration.

**Comment by ranj063** [comment]
> I don't know what to make of the results @ranj063 @keqiaozhang TGLU_UP_HDA_IPC4ZPH is a fail on multiple tests.

@plbossart IPC4 failures are due toe the chaind DAM SOF PR which shouldnt have been merged. There's a revert for that as well

File: sound/soc/sof/sof-audio.c (hunk 1 above)
Comment (ranj063) [reply sound/soc/sof/sof-audio.c:80]: @ujfalusi yes it can and the scheduler widget will be freed only when the last of all the users lets it go

**Comment by ranj063** [comment]
> > I don't know what to make of the results @ranj063 @keqiaozhang TGLU_UP_HDA_IPC4ZPH is a fail on multiple tests.
> 
> I think what happened is that `multiple-pipeline-playback.sh` failed - firmware crash - (if it is because of this PR or not is a question) since we prevent powering down the DSP to preserve the DSP state. Consecutive tests fail since the DSP is kept powered in crashed state. With IPC4/Zephyr we don't have panic interrupt/message so we can not force a DSP power cycle.
> 
> Let me check it locally, it should be easy to hit.

it is because of the SOF PR for chained DMA that was merged a bit too early

**Comment by plbossart** [comment]
@ujfalusi any objections here? this needs to go in before 2pm PDT to fix daily tests
